// AN1: native professional annotation workflows on the AF1 command boundary.
(() => {
  const prompt=(name,instruction)=>Object.freeze({commandName:name,instruction,text:`${name}: ${instruction}`})
  const point=value=>Object.freeze({x:value.x,y:value.y})
  const planner=Object.freeze({plan:value=>Object.freeze({status:"planned",value})})
  function publish(recordGateway,record,name){const outcome=recordGateway.createAll([record]);return outcome.status==="committed"?Object.freeze({status:"command-completed",command:name,outcome,recordIds:Object.freeze([record.id])}):Object.freeze({status:"invalid-input",command:name,reason:outcome.status,message:"Unable to create annotation; input is preserved.",outcome})}
  function chainSession({name,reader,recordGateway,selection,resolveTypedPoint,requestRender,clearSnap,activation,continued=false}){
    const selected=selection.orderedIds().map(id=>reader.records().find(record=>record.id===id)).find(record=>record?.type==="dimension-linear")
    let datum=selected?(continued?point(selected.secondPoint):point(selected.firstPoint)):null,previous=selected?point(selected.secondPoint):null,candidate=null,count=0,presentation=prompt(name,datum?"Specify next extension point":"Specify datum point")
    const update=text=>{presentation=prompt(name,text);activation.setPrompt?.(presentation.text,presentation)}
    function geometry(next){const first=continued?(previous||datum):datum,dx=next.x-first.x,dy=next.y-first.y,mode=Math.abs(dx)>=Math.abs(dy)?"horizontal":"vertical",distance=5*(count+1),dimensionLinePoint=mode==="horizontal"?{x:next.x,y:Math.max(first.y,next.y)+distance}:{x:Math.max(first.x,next.x)+distance,y:next.y};return{type:"dimension-linear",mode,firstPoint:first,secondPoint:next,dimensionLinePoint,textOverride:null,dimensionStyleId:reader.currentDimensionStyleId()}}
    function accept(value){const next=point(value);if(!datum){datum=next;previous=next;update("Specify next extension point");requestRender();return Object.freeze({status:"input-accepted",command:name,point:next})}const first=continued?(previous||datum):datum;if(first.x===next.x&&first.y===next.y)return Object.freeze({status:"invalid-input",command:name,reason:"degenerate-points",message:"Extension points must differ."});const record=recordGateway.createLinearDimension(geometry(next)),outcome=recordGateway.createAll([record]);if(outcome.status!=="committed")return Object.freeze({status:"invalid-input",command:name,reason:outcome.status,message:"Unable to create dimension; chain is preserved."});previous=next;count++;candidate=null;update("Specify next extension point; Enter to finish");requestRender();return Object.freeze({status:"input-accepted",command:name,kind:"dimension-committed",recordId:record.id,outcome})}
    function finish(){clearSnap();requestRender();return count||selected?Object.freeze({status:"command-completed",command:name,count}):Object.freeze({status:"invalid-input",command:name,reason:"dimension-required",message:"Specify at least two points."})}
    function cancel(){candidate=null;clearSnap();requestRender();return Object.freeze({status:"command-cancelled",command:name,count})}
    function input(value){const parsed=resolveTypedPoint(value,continued?(previous||datum):datum);return parsed.status==="point-resolved"?accept(parsed):Object.freeze({status:"invalid-input",command:name,reason:parsed.reason,message:"Enter a point as x,y."})}
    requestRender();return Object.freeze({name,handlePointerDown:accept,handlePointerMove:value=>{candidate=point(value);requestRender()},handlePointerLeave:()=>{candidate=null;clearSnap();requestRender()},handleInput:input,finish,cancel,getDimensionPreview:()=>datum&&candidate&&((continued?(previous||datum):datum).x!==candidate.x||(continued?(previous||datum):datum).y!==candidate.y)?geometry(candidate):null,getOrthoReference:()=>continued?(previous||datum):datum,hasPointerPreview:()=>true,get prompt(){return presentation.text},get promptPresentation(){return presentation}})
  }
  function ordinateSession({reader,recordGateway,requestRender,clearSnap,activation}){let axis="x",points=[],candidate=null,presentation=prompt("Ordinate","Specify datum point");const update=text=>{presentation=prompt("Ordinate",text);activation.setPrompt?.(presentation.text,presentation)};const geometry=value=>({type:"dimension-ordinate",axis,datumPoint:points[0],featurePoint:points[1],leaderPoint:value,textOverride:null,dimensionStyleId:reader.currentDimensionStyleId()});function accept(value){const p=point(value);if(points.length<2){points.push(p);update(points.length===1?"Specify feature point":"Specify leader location");requestRender();return Object.freeze({status:"input-accepted",command:"Ordinate",point:p})}return publish(recordGateway,recordGateway.createOrdinateDimension(geometry(p)),"Ordinate")}function option(id){if(!["x","y"].includes(id))return Object.freeze({status:"option-unavailable",command:"Ordinate",optionId:id});axis=id;requestRender();return Object.freeze({status:"option-updated",command:"Ordinate",optionId:id,value:id})}function cancel(){clearSnap();requestRender();return Object.freeze({status:"command-cancelled",command:"Ordinate"})}return Object.freeze({name:"Ordinate",handlePointerDown:accept,handlePointerMove:p=>{candidate=point(p);requestRender()},handlePointerLeave:()=>{candidate=null;clearSnap();requestRender()},handleOption:option,finish:cancel,cancel,getDimensionPreview:()=>points.length===2&&candidate?geometry(candidate):null,getOrthoReference:()=>points.at(-1)||null,hasPointerPreview:()=>true,get options(){return Object.freeze([{id:"x",label:"X",enabled:axis!=="x"},{id:"y",label:"Y",enabled:axis!=="y"}])},get prompt(){return presentation.text},get promptPresentation(){return presentation}})}
  function arcLengthSession({reader,recordGateway,hitTestEditableDirectTarget,requestRender,clearSnap,activation}){let source=null,candidate=null,presentation=prompt("ArcLength","Select an Arc");function down(value,context={}){if(!source){source=hitTestEditableDirectTarget(context.rawPoint||value,["arc"]);if(!source)return Object.freeze({status:"invalid-input",command:"ArcLength",reason:"arc-required",message:"Select a valid Arc."});presentation=prompt("ArcLength","Specify dimension arc location");activation.setPrompt?.(presentation.text,presentation);requestRender();return Object.freeze({status:"input-accepted",command:"ArcLength",recordId:source.id})}const geometry=preview(value),record=recordGateway.createArcLengthDimension(geometry);return publish(recordGateway,record,"ArcLength")}function preview(value=candidate){return source&&value?{type:"dimension-arc-length",centerPoint:source.center,startPoint:source.start,endPoint:source.end,dimensionArcPoint:point(value),sweep:source.sweep,sourceRecordId:source.id,textOverride:null,dimensionStyleId:reader.currentDimensionStyleId()}:null}function cancel(){clearSnap();requestRender();return Object.freeze({status:"command-cancelled",command:"ArcLength"})}return Object.freeze({name:"ArcLength",handlePointerDown:down,handlePointerMove:p=>{if(source)candidate=point(p);requestRender()},handlePointerLeave:()=>{candidate=null;clearSnap();requestRender()},finish:cancel,cancel,getDimensionPreview:preview,hasPointerPreview:()=>Boolean(source),get usesResolvedPoint(){return Boolean(source)},get prompt(){return presentation.text},get promptPresentation(){return presentation}})}
  function centerMarkSession({reader,recordGateway,hitTestEditableDirectTarget,requestRender,clearSnap}){const presentation=prompt("CenterMark","Select a Circle or Arc");function down(value,context={}){const source=hitTestEditableDirectTarget(context.rawPoint||value,["circle","arc"]);if(!source)return Object.freeze({status:"invalid-input",command:"CenterMark",reason:"circular-source-required",message:"Select a Circle or Arc."});const size=Math.min(source.radius,reader.resolveDimensionStyle({dimensionStyleId:reader.currentDimensionStyleId()}).arrowSize*1.5),record=recordGateway.createCenterMark({centerPoint:source.center,sizePoint:{x:source.center.x+size,y:source.center.y},sourceRecordId:source.id,dimensionStyleId:reader.currentDimensionStyleId()});return publish(recordGateway,record,"CenterMark")}function cancel(){clearSnap();requestRender();return Object.freeze({status:"command-cancelled",command:"CenterMark"})}return Object.freeze({name:"CenterMark",handlePointerDown:down,finish:cancel,cancel,get isSelectionPhase(){return true},get prompt(){return presentation.text},get promptPresentation(){return presentation}})}
  function centerLineSession({reader,recordGateway,hitTestEditableDirectTarget,requestRender,clearSnap,activation}){let first=null,presentation=prompt("CenterLine","Select first parallel Line");function down(value,context={}){const line=hitTestEditableDirectTarget(context.rawPoint||value,["line"]);if(!line)return Object.freeze({status:"invalid-input",command:"CenterLine",reason:"line-required",message:"Select a Line."});if(!first){first=line;presentation=prompt("CenterLine","Select second parallel Line");activation.setPrompt?.(presentation.text,presentation);requestRender();return Object.freeze({status:"input-accepted",command:"CenterLine",recordId:line.id})}const ax=first.end.x-first.start.x,ay=first.end.y-first.start.y,bx=line.end.x-line.start.x,by=line.end.y-line.start.y;if(Math.abs(ax*by-ay*bx)>1e-9*Math.max(1,Math.hypot(ax,ay)*Math.hypot(bx,by)))return Object.freeze({status:"invalid-input",command:"CenterLine",reason:"nonparallel-lines",message:"Selected Lines must be parallel."});const midpoint=r=>({x:(r.start.x+r.end.x)/2,y:(r.start.y+r.end.y)/2}),record=recordGateway.createCenterLine({firstPoint:midpoint(first),secondPoint:midpoint(line),extension:reader.resolveDimensionStyle({dimensionStyleId:reader.currentDimensionStyleId()}).extensionBeyond,sourceRecordIds:[first.id,line.id],dimensionStyleId:reader.currentDimensionStyleId()});return publish(recordGateway,record,"CenterLine")}function cancel(){clearSnap();requestRender();return Object.freeze({status:"command-cancelled",command:"CenterLine"})}return Object.freeze({name:"CenterLine",handlePointerDown:down,finish:cancel,cancel,get isSelectionPhase(){return true},get prompt(){return presentation.text},get promptPresentation(){return presentation}})}
  const registrations=Object.freeze([
    Object.freeze({name:"DimBaseline",aliases:Object.freeze(["DBA"]),planner,createSession:s=>chainSession({...s,name:"DimBaseline"})}),
    Object.freeze({name:"DimContinue",aliases:Object.freeze(["DCO"]),planner,createSession:s=>chainSession({...s,name:"DimContinue",continued:true})}),
    Object.freeze({name:"Ordinate",aliases:Object.freeze(["DIMORDINATE","DOR"]),planner,createSession:ordinateSession}),
    Object.freeze({name:"ArcLength",aliases:Object.freeze(["DIMARCLENGTH","DAR"]),planner,createSession:arcLengthSession}),
    Object.freeze({name:"CenterMark",aliases:Object.freeze([]),planner,createSession:centerMarkSession}),
    Object.freeze({name:"CenterLine",aliases:Object.freeze([]),planner,createSession:centerLineSession}),
  ])
  window.CaderactAnnotationCommands=Object.freeze({registrations})
})()
