// DC3 AF1 command sessions. Array math remains in ArrayPlanner.
(() => {
  const prompt = (commandName, instruction) => Object.freeze({ commandName, instruction, text: `${commandName}: ${instruction}` })
  const messages = Object.freeze({ "empty-selection":"Select at least one editable object.","selection-not-editable":"Selection contains hidden, locked, grouped, or unavailable objects.","invalid-count":"Count must be a whole number of at least 1 (2 for total items).","invalid-spacing":"Spacing must be a finite non-zero value.","zero-spacing":"Spacing for repeated rows or columns cannot be zero.","invalid-angle":"Fill angle must be non-zero and no greater than 360 degrees.","copy-limit":"The array exceeds the 500-record safety limit.","no-copies":"Increase rows or columns to create at least one copy.","invalid-path":"Select an editable Line or open Polyline path.","path-too-short":"The requested count and spacing exceed the path length." })
  const failure = (command, plan) => Object.freeze({ status:"invalid-input", reason:plan.reason, command, message:messages[plan.reason] || "The array parameters are invalid.", plan })
  function createSession({ kind, name, planner, reader, recordGateway, selection, resolveTypedPoint, hitTestEditableArrayPath, requestRender, clearSnap, activation }) {
    let phase = selection.selectedIds().length ? (kind === "polar" ? "center" : kind === "path" ? "base" : "parameters") : "selection"
    let selectedIds = phase === "selection" ? Object.freeze([]) : selection.selectedIds(), center = null, basePoint = null, pathRecord = null, pending = null
    let rows=2, columns=2, rowSpacing=10, columnSpacing=10, itemCount=4, fillAngleDegrees=360, spacing=10
    let presentation = prompt(name, phase === "selection" ? "Select objects, then press Enter" : phase === "center" ? "Specify array center" : phase === "base" ? "Specify source base point" : "Adjust parameters, then press Enter")
    const update = instruction => { presentation=prompt(name,instruction);activation.setPrompt?.(presentation.text,presentation);requestRender() }
    function records(){const ids=new Set(selectedIds);return reader.editableRecords().filter(record=>ids.has(record.id))}
    function validateSelection(){const ids=selection.orderedIds(), editable=new Map(reader.editableRecords().map(record=>[record.id,record]));if(!ids.length)return failure(name,{reason:"empty-selection"});if(ids.some(id=>!editable.has(id)||reader.groupForRecord(id)))return failure(name,{reason:"selection-not-editable"});selectedIds=Object.freeze([...ids]);return null}
    function plan(){const source=records();if(kind==="rectangular")return planner.plan({records:source,rows,columns,rowSpacing,columnSpacing});if(kind==="polar")return planner.plan({records:source,center,itemCount,fillAngleDegrees});return planner.plan({records:source,path:pathRecord,basePoint,itemCount,spacing})}
    function transformed(planResult, fresh){const byId=new Map(records().map(record=>[record.id,record]));return planResult.transforms.map(transform=>{const source=byId.get(transform.recordId);let output=transform.kind==="rotate"?window.CaderactGeometryTransform.rotateRecord(source,transform.center,transform.angle):window.CaderactGeometryTransform.translateRecord(source,transform.dx,transform.dy);return fresh?recordGateway.copyWithFreshIdentity(output):Object.freeze({...output,id:null})})}
    function getMovePreview(){if(!["parameters","ready"].includes(phase))return null;const result=plan();if(result.status!=="planned")return null;return Object.freeze({mode:`array-${kind}`,preserveSourceVisible:true,recordIds:Object.freeze([]),sourceRecords:Object.freeze([]),records:Object.freeze(transformed(result,false))})}
    function commit(){const selectionError=validateSelection();if(selectionError)return selectionError;const result=plan();if(result.status!=="planned")return failure(name,result);let copies;try{copies=transformed(result,true)}catch(error){return Object.freeze({status:"invalid-input",reason:"unsupported-geometry",command:name,message:error.message})}const outcome=recordGateway.createAll(copies);if(outcome.status!=="committed")return Object.freeze({status:"invalid-input",reason:outcome.status,command:name,message:"Unable to publish array; preview preserved.",outcome});selection.applyRecordIds(copies.map(record=>record.id));clearSnap();requestRender();return Object.freeze({status:"command-completed",command:name,outcome,recordIds:Object.freeze(copies.map(record=>record.id)),plan:result})}
    function finish(){if(phase==="selection"){const error=validateSelection();if(error)return error;phase=kind==="polar"?"center":kind==="path"?"base":"parameters";update(phase==="center"?"Specify array center":phase==="base"?"Specify source base point":"Adjust parameters, then press Enter");return Object.freeze({status:"input-accepted",command:name,kind:"selection",recordIds:selectedIds})}if(phase==="parameters"||phase==="ready")return commit();return Object.freeze({status:"invalid-input",reason:"point-required",command:name,message:phase==="center"?"Specify array center.":phase==="base"?"Specify source base point.":"Select a path."})}
    function acceptPoint(point,context={}){if(phase==="center"){center=Object.freeze({x:point.x,y:point.y});phase="parameters";update("Adjust count/angle, then press Enter");return Object.freeze({status:"input-accepted",command:name,kind:"center",point:center})}if(phase==="base"){basePoint=Object.freeze({x:point.x,y:point.y});phase="path";update("Select a Line or open Polyline path");return Object.freeze({status:"input-accepted",command:name,kind:"base-point",point:basePoint})}if(phase==="path"){pathRecord=hitTestEditableArrayPath(context.rawPoint||point);if(!pathRecord)return failure(name,{reason:"invalid-path"});const vertices=pathRecord.type==="line"?[pathRecord.start,pathRecord.end]:pathRecord.vertices;const length=vertices.slice(1).reduce((sum,end,index)=>sum+Math.hypot(end.x-vertices[index].x,end.y-vertices[index].y),0);spacing=length/(itemCount-1);phase="ready";update("Adjust count/spacing, then press Enter");return Object.freeze({status:"input-accepted",command:name,kind:"path",recordId:pathRecord.id})}return Object.freeze({status:"invalid-input",reason:"point-unavailable",command:name})}
    function setPending(id){pending=id;update(`Enter ${id.replace(/([A-Z])/g," $1").toLowerCase()}`);return Object.freeze({status:"option-updated",command:name,optionId:id})}
    function handleOption(id){const allowed=kind==="rectangular"?["rows","columns","rowSpacing","columnSpacing"]:kind==="polar"?["count","angle"]:["count","spacing"];return allowed.includes(id)?setPending(id):Object.freeze({status:"option-unavailable",reason:"unknown-option",command:name,optionId:id})}
    function handleInput(input){if(pending){const value=Number(String(input).trim());const whole=pending==="rows"||pending==="columns"||pending==="count";if(!Number.isFinite(value)||(whole&&(!Number.isInteger(value)||value<(pending==="count"?2:1))))return Object.freeze({status:"invalid-input",reason:whole?"invalid-count":"invalid-value",command:name,message:messages[whole?"invalid-count":"invalid-spacing"]});if(pending==="rows")rows=value;else if(pending==="columns")columns=value;else if(pending==="rowSpacing")rowSpacing=value;else if(pending==="columnSpacing")columnSpacing=value;else if(pending==="count")itemCount=value;else if(pending==="angle")fillAngleDegrees=value;else spacing=value;const id=pending;pending=null;update("Adjust parameters, then press Enter");return Object.freeze({status:"input-accepted",command:name,kind:"parameter",parameter:id,value})}if(phase==="center"||phase==="base"){const parsed=resolveTypedPoint(input);if(parsed.status!=="point-resolved")return Object.freeze({status:"invalid-input",reason:parsed.reason,command:name,message:"Enter a point as x,y."});return acceptPoint(parsed)}return Object.freeze({status:"invalid-input",reason:"option-required",command:name,message:"Choose a parameter option first."})}
    function options(){if(!["parameters","ready"].includes(phase))return Object.freeze([]);const entries=kind==="rectangular"?[["rows","Rows",rows],["columns","Columns",columns],["rowSpacing","Row spacing",rowSpacing],["columnSpacing","Column spacing",columnSpacing]]:kind==="polar"?[["count","Count",itemCount],["angle","Fill angle",fillAngleDegrees]]:[["count","Count",itemCount],["spacing","Spacing",spacing]];return Object.freeze(entries.map(([id,label,value])=>Object.freeze({id,label,value:String(value),enabled:true})))}
    function cancel(){clearSnap();requestRender();return Object.freeze({status:"command-cancelled",command:name})}
    requestRender();return Object.freeze({name,finish,cancel,handlePointerDown:acceptPoint,handleInput,handleOption,getMovePreview,handlePointerLeave:()=>{clearSnap();requestRender()},get usesResolvedPoint(){return phase==="center"||phase==="base"},hasPointerPreview:()=>false,get isSelectionPhase(){return phase==="selection"},get phase(){return phase},get options(){return options()},get prompt(){return presentation.text},get promptPresentation(){return presentation}})
  }
  const registrations=Object.freeze([
    Object.freeze({name:"RectangularArray",aliases:Object.freeze(["ARRAYRECT","AR"]),planner:Object.freeze({plan:window.CaderactArrayPlanner.rectangular}),createSession:services=>createSession({...services,kind:"rectangular",name:"RectangularArray"})}),
    Object.freeze({name:"PolarArray",aliases:Object.freeze(["ARRAYPOLAR"]),planner:Object.freeze({plan:window.CaderactArrayPlanner.polar}),createSession:services=>createSession({...services,kind:"polar",name:"PolarArray"})}),
    Object.freeze({name:"PathArray",aliases:Object.freeze(["ARRAYPATH"]),planner:Object.freeze({plan:window.CaderactArrayPlanner.path}),createSession:services=>createSession({...services,kind:"path",name:"PathArray"})}),
  ])
  window.CaderactArrayCommands=Object.freeze({registrations})
})()
