// GBUX2: compact management surface over native Block Definitions and commands.
(() => {
  const list=document.querySelector("#blocks-list"),createButton=document.querySelector("#block-create"),purgeButton=document.querySelector("#block-purge")
  if(!list||!createButton||!purgeButton||!window.caderactDocumentSession||!window.caderactSelection)return
  const session=window.caderactDocumentSession,selection=window.caderactSelection,router=window.caderactCommandRouter,popup=document.createElement("div")
  popup.classList.add("block-actions-menu");popup.setAttribute("role","menu");popup.hidden=true;(document.body||document).appendChild(popup);window.caderactBlockActionsMenu=popup
  let editingDefinitionId=null,inspectedDefinitionId=null,openMenuDefinitionId=null,menuAnchor=null,unsubscribeHistory=null
  const result=(status,details={})=>Object.freeze({status,...details})
  const messages={"invalid-name":"Block name cannot be empty.","duplicate-name":"A Block Definition with that name already exists.","missing-definition":"The Block Definition no longer exists.","definition-in-use":"Referenced Block Definitions cannot be deleted.","commit-failed":"The Block Definition could not be changed."}
  function feedback(outcome){const message=messages[outcome.status];if(message)window.caderactFeedback?.showTemporary(message,"error")}
  function blocked(){return Boolean(router?.isActive)}
  function modelInstances(definitionId){return session.reader.records().filter(record=>record.type==="block-instance"&&record.definitionId===definitionId)}
  function isReferenced(definitionId){return modelInstances(definitionId).length>0||session.reader.blockDefinitions().some(definition=>Object.values(definition.records).some(record=>record.type==="block-instance"&&record.definitionId===definitionId))}
  function closeMenu(){menuAnchor?.setAttribute?.("aria-expanded","false");openMenuDefinitionId=null;menuAnchor=null;popup.hidden=true;popup.replaceChildren()}
  function cancelRename({renderNow=true}={}){if(!editingDefinitionId)return false;editingDefinitionId=null;if(renderNow)render();return true}
  function run(action){if(blocked())return result("block-action-blocked-active-command");const outcome=action();feedback(outcome);return outcome}
  function create(){if(blocked())return result("block-action-blocked-active-command");return router.execute("Block")}
  function insert(definitionId){if(blocked())return result("block-action-blocked-active-command");const definition=session.reader.blockDefinition(definitionId);if(!definition)return result("missing-definition",{definitionId});const started=router.execute("Insert");return started.status==="command-started"?router.submitActiveInput(definition.name):started}
  function edit(definitionId){if(blocked())return result("block-action-blocked-active-command");const definition=session.reader.blockDefinition(definitionId);if(!definition)return result("missing-definition",{definitionId});const started=router.execute("BlockEdit");return started.status==="command-started"?router.submitActiveInput(definition.name):started}
  function rename(definitionId,name){return run(()=>session.blockDefinitionGateway.rename(definitionId,name))}
  function remove(definitionId){return run(()=>session.blockDefinitionGateway.remove(definitionId))}
  function purge(){const outcome=run(()=>session.blockDefinitionGateway.purgeUnused());if(outcome.status==="committed")window.caderactFeedback?.showTemporary(`Purged ${outcome.definitionIds.length} unused Block Definition${outcome.definitionIds.length===1?"":"s"}.`);else if(outcome.status==="no-op")window.caderactFeedback?.showTemporary("No unused Block Definitions.");return outcome}
  function selectInstances(definitionId){const definition=session.reader.blockDefinition(definitionId);if(!definition)return result("missing-definition",{definitionId});return selection.applyRecordIds(modelInstances(definitionId).map(record=>record.id))}
  function inspect(definitionId){if(!session.reader.blockDefinition(definitionId))return result("missing-definition",{definitionId});inspectedDefinitionId=definitionId;render();return result("definition-inspected",{definitionId})}
  function beginRename(definitionId){if(blocked())return result("block-action-blocked-active-command");if(!session.reader.blockDefinition(definitionId))return result("missing-definition",{definitionId});closeMenu();editingDefinitionId=definitionId;inspectedDefinitionId=definitionId;render();return result("rename-started",{definitionId})}
  function icon(name){const svg=document.createElementNS?.("http://www.w3.org/2000/svg","svg")||document.createElement("svg"),use=document.createElementNS?.("http://www.w3.org/2000/svg","use")||document.createElement("use");svg.setAttribute("aria-hidden","true");use.setAttribute("href",`#dock-${name}`);svg.appendChild(use);return svg}
  function button(className,label,iconName,handler){const value=document.createElement("button");value.type="button";value.classList.add(className);value.setAttribute("aria-label",label);value.title=label;if(iconName)value.appendChild(icon(iconName));value.addEventListener("click",event=>{event.stopPropagation?.();handler(event)});return value}
  function menuAction(label,iconName,handler,{disabled=false}={}){const value=button("block-menu-action",label,iconName,()=>{closeMenu();handler()});value.disabled=blocked()||disabled;const text=document.createElement("span");text.textContent=label;value.appendChild(text);popup.appendChild(value)}
  function placeMenu(){if(!menuAnchor||popup.hidden)return;const anchor=menuAnchor.getBoundingClientRect?.()||{left:8,right:32,top:8,bottom:32},width=popup.offsetWidth||204,height=popup.offsetHeight||172,vw=window.innerWidth||1024,vh=window.innerHeight||768,margin=8,left=Math.max(margin,Math.min(vw-width-margin,anchor.right-width)),candidate=anchor.bottom+4+height<=vh-margin?anchor.bottom+4:Math.max(margin,anchor.top-height-4),top=Math.max(margin,Math.min(vh-height-margin,candidate));popup.style.left=`${left}px`;popup.style.top=`${top}px`;popup.dataset.placement=candidate<anchor.top?"above":"below"}
  function openMenu(definition,anchor){cancelRename({renderNow:false});openMenuDefinitionId=definition.id;menuAnchor=anchor;anchor.setAttribute("aria-expanded","true");popup.replaceChildren();const count=modelInstances(definition.id).length;menuAction("Edit Definition","block",()=>edit(definition.id));menuAction("Insert Block","add",()=>insert(definition.id));menuAction("Select Instances","select",()=>selectInstances(definition.id),{disabled:count===0});menuAction("Definition Info","block",()=>inspect(definition.id));menuAction("Rename","rename",()=>beginRename(definition.id));menuAction("Delete Definition","delete",()=>remove(definition.id),{disabled:isReferenced(definition.id)});popup.hidden=false;placeMenu()}
  function render(){
    const definitions=session.reader.blockDefinitions(),selectedIds=selection.selectedIds(),eligible=selectedIds.length>0&&selectedIds.every(id=>session.reader.isRecordEditable(id)&&!session.reader.groupForRecord(id));createButton.disabled=blocked()||!eligible;purgeButton.disabled=blocked()||!definitions.length;let editInput=null;const nodes=[]
    for(const definition of definitions){const row=document.createElement("div");row.classList.add("block-row");row.setAttribute("role","listitem");row.dataset.definitionId=definition.id;if(inspectedDefinitionId===definition.id)row.classList.add("is-inspected");const mark=document.createElement("span");mark.classList.add("block-icon");mark.appendChild(icon("block"))
      let name;if(editingDefinitionId===definition.id){name=document.createElement("input");name.type="text";name.value=definition.name;name.maxLength=128;name.classList.add("block-name-input");name.setAttribute("aria-label",`Rename ${definition.name}`);name.addEventListener("keydown",event=>{if(event.key==="Escape"){event.preventDefault();cancelRename()}else if(event.key==="Enter"){event.preventDefault();const outcome=rename(definition.id,name.value);if(outcome.status==="committed"||outcome.status==="no-op"){editingDefinitionId=null;render()}}});name.addEventListener("blur",()=>{if(editingDefinitionId===definition.id)cancelRename()});editInput=name}else{name=button("block-select",`Inspect ${definition.name}`,null,()=>inspect(definition.id));name.textContent=definition.name;name.title=definition.name;name.addEventListener("dblclick",event=>{event.preventDefault();beginRename(definition.id)})}
      const count=modelInstances(definition.id).length,countNode=document.createElement("span");countNode.classList.add("block-instance-count");countNode.textContent=String(count);countNode.title=`${count} model-space instance${count===1?"":"s"}`;const more=button("block-actions",`Actions for ${definition.name}`,"more",event=>openMenuDefinitionId===definition.id?closeMenu():openMenu(definition,event.currentTarget||more));more.setAttribute("aria-expanded",String(openMenuDefinitionId===definition.id));for(const node of [mark,name,countNode,more])row.appendChild(node);nodes.push(row)
      if(inspectedDefinitionId===definition.id){const info=document.createElement("div");info.classList.add("block-definition-info");info.textContent=`Definition · ${definition.recordOrder.length} member${definition.recordOrder.length===1?"":"s"} · Base ${definition.basePoint.x}, ${definition.basePoint.y}`;nodes.push(info)}
    }
    if(!nodes.length){const empty=document.createElement("p");empty.classList.add("blocks-empty");empty.textContent="No Block Definitions in this drawing.";list.replaceChildren(empty)}else list.replaceChildren(...nodes)
    if(openMenuDefinitionId){menuAnchor=nodes.find(node=>node.dataset?.definitionId===openMenuDefinitionId)?.children[3]||menuAnchor;placeMenu()}if(editInput){editInput.focus();editInput.select?.()}
  }
  function bindDocument(){unsubscribeHistory?.();unsubscribeHistory=session.controller.subscribeHistory(render);cancelRename({renderNow:false});closeMenu();inspectedDefinitionId=null;render()}
  createButton.addEventListener("click",()=>{cancelRename({renderNow:false});create()});purgeButton.addEventListener("click",()=>{cancelRename({renderNow:false});purge()});list.addEventListener("scroll",()=>{cancelRename();if(openMenuDefinitionId)placeMenu()});document.addEventListener("pointerdown",event=>{if(editingDefinitionId&&!event.target?.classList?.contains("block-name-input"))cancelRename();if(openMenuDefinitionId&&!popup.contains(event.target)&&event.target!==menuAnchor)closeMenu()});document.addEventListener("keydown",event=>{if(event.key==="Escape"&&openMenuDefinitionId){event.preventDefault();closeMenu()}});window.addEventListener("resize",placeMenu);selection.subscribe(render);session.subscribe(bindDocument);router.subscribe(render);bindDocument()
  window.caderactBlocks=Object.freeze({create,insert,edit,rename,remove,purge,selectInstances,inspect,beginRename,cancelRename,refresh:render,getState:()=>Object.freeze({editingDefinitionId,inspectedDefinitionId,openMenuDefinitionId})})
})()
