// UX9C-R: staged, renderer-independent CAD color picker.
(() => {
const PALETTE=["#202830","#65717d","#aab4be","#d7dee5","#f4f6f8","#b9363e","#b96026","#a77913","#28764c","#087b83","#2368b5","#6954a3","#9b4380","#e65c61","#df914b","#d6bb49","#68a878","#5ab0b4","#72a3db","#a395ca","#c98ab0","#8a684f","#6c808a","#e8edf4"],validHex=value=>/^#[0-9a-f]{6}$/i.test(value),clamp=(value,min,max)=>Math.max(min,Math.min(max,value)),rgbFromHex=value=>[1,3,5].map(index=>parseInt(value.slice(index,index+2),16)),hexFromRgb=values=>`#${values.map(value=>Math.round(value).toString(16).padStart(2,"0")).join("")}`
function rgbToHsv([r,g,b]){r/=255;g/=255;b/=255;const max=Math.max(r,g,b),min=Math.min(r,g,b),d=max-min;let h=0;if(d){if(max===r)h=60*(((g-b)/d)%6);else if(max===g)h=60*((b-r)/d+2);else h=60*((r-g)/d+4)}if(h<0)h+=360;return[h,max?d/max:0,max]}
function hsvToRgb([h,s,v]){const c=v*s,x=c*(1-Math.abs((h/60)%2-1)),m=v-c,rgb=h<60?[c,x,0]:h<120?[x,c,0]:h<180?[0,c,x]:h<240?[0,x,c]:h<300?[x,0,c]:[c,0,x];return rgb.map(value=>(value+m)*255)}
function element(tag,className,text){const node=document.createElement(tag);if(className)node.classList.add(className);if(text!==undefined)node.textContent=text;return node}
function create({host=document.body||document}={}){
 const root=element("section","color-popover");root.hidden=true;root.setAttribute("role","dialog");root.setAttribute("aria-modal","true")
 const header=element("header","color-popover-header"),heading=element("strong","color-popover-title","Color"),original=element("span","color-preview"),pending=element("span","color-preview");original.setAttribute("aria-label","Current color");pending.setAttribute("aria-label","New color");for(const node of [heading,original,pending])header.appendChild(node)
 const mode=element("select","color-mode");mode.setAttribute("aria-label","Color mode");for(const [value,label] of [["custom","Custom"],["by-layer","ByLayer"]]){const option=element("option",null,label);option.value=value;mode.appendChild(option)}
 const surface=element("div","color-custom-surface"),sv=element("div","color-sv"),svWhite=element("span","color-sv-white"),svBlack=element("span","color-sv-black"),svIndicator=element("span","color-sv-indicator"),hue=element("div","color-hue"),hueIndicator=element("span","color-hue-indicator");sv.tabIndex=hue.tabIndex=0;sv.setAttribute("role","slider");sv.setAttribute("aria-label","Saturation and brightness");hue.setAttribute("role","slider");hue.setAttribute("aria-label","Hue");for(const node of [svWhite,svBlack,svIndicator])sv.appendChild(node);hue.appendChild(hueIndicator);surface.appendChild(sv);surface.appendChild(hue)
 const palette=element("div","color-palette");palette.setAttribute("aria-label","CAD color palette");for(const color of PALETTE){const button=element("button","color-palette-swatch");button.type="button";button.dataset.color=color;button.style.setProperty?.("--swatch-color",color);button.setAttribute("aria-label",`Use ${color.toUpperCase()}`);button.title=color.toUpperCase();palette.appendChild(button)}
 const hexLabel=element("label","color-field-label","Hex"),hex=element("input","color-hex");hex.type="text";hex.maxLength=7;hex.spellcheck=false;hexLabel.appendChild(hex)
 const rgb=element("div","color-rgb"),channels=["R","G","B"].map(name=>{const label=element("label","color-field-label",name),input=element("input","color-channel");input.type="number";input.min="0";input.max="255";input.step="1";label.appendChild(input);rgb.appendChild(label);return input})
 const error=element("p","color-popover-error");error.setAttribute("role","alert");const footer=element("footer","color-popover-actions"),cancel=element("button","color-cancel","Cancel"),apply=element("button","color-apply","Apply");cancel.type=apply.type="button";apply.setAttribute("aria-label","Apply color");footer.appendChild(cancel);footer.appendChild(apply);for(const node of [header,mode,surface,palette,hexLabel,rgb,error,footer])root.appendChild(node);host.appendChild(root)
 let state=null,drag=null
 function updateIndicators(){if(!state)return;const[h,s,v]=state.hsv;sv.style.setProperty?.("--hue-color",hexFromRgb(hsvToRgb([h,1,1])));svIndicator.style.left=`${s*100}%`;svIndicator.style.top=`${(1-v)*100}%`;hueIndicator.style.top=`${h/360*100}%`;hue.setAttribute("aria-valuenow",String(Math.round(h)));sv.setAttribute("aria-valuetext",`${Math.round(s*100)}% saturation, ${Math.round(v*100)}% brightness`)}
 function setColor(value){state.value=value.toLowerCase();state.hsv=rgbToHsv(rgbFromHex(state.value));hex.value=state.value.toUpperCase();rgbFromHex(state.value).forEach((item,index)=>channels[index].value=String(item));pending.style.backgroundColor=state.value;error.textContent="";apply.disabled=false;updateIndicators()}
 function setHsv(h,s,v){state.hsv=[(h+360)%360,clamp(s,0,1),clamp(v,0,1)];state.value=hexFromRgb(hsvToRgb(state.hsv));hex.value=state.value.toUpperCase();rgbFromHex(state.value).forEach((item,index)=>channels[index].value=String(item));pending.style.backgroundColor=state.value;error.textContent="";apply.disabled=false;updateIndicators()}
 function validate(){if(!state)return false;if(mode.value==="by-layer"){error.textContent="";apply.disabled=false;return true}const value=hex.value.startsWith("#")?hex.value:`#${hex.value}`,values=channels.map(input=>Number(input.value));if(!validHex(value)){error.textContent="Enter six hexadecimal digits.";apply.disabled=true;return false}if(values.some((value,index)=>!Number.isInteger(value)||value<0||value>255||String(value)!==String(channels[index].value).trim())){error.textContent="Use whole numbers from 0 to 255.";apply.disabled=true;return false}setColor(value);return true}
 function syncDisabled(){const inherited=mode.value==="by-layer";hex.disabled=inherited;channels.forEach(input=>input.disabled=inherited);surface.classList.toggle("is-disabled",inherited);palette.classList.toggle("is-disabled",inherited);if(inherited){pending.style.backgroundColor=state.resolvedColor||state.value;apply.disabled=false}else setColor(state.value)}
 function position(){const bounds=state.anchor.getBoundingClientRect?.()||{left:8,top:8,bottom:32,right:32},width=root.offsetWidth||292,height=root.offsetHeight||430,vw=window.innerWidth||1024,vh=window.innerHeight||768;root.style.left=`${clamp(bounds.right-width,8,vw-width-8)}px`;root.style.top=`${clamp(bounds.bottom+6+height<=vh-8?bounds.bottom+6:bounds.top-height-6,8,vh-height-8)}px`}
 function close({restore=true}={}){if(!state)return;const anchor=state.anchor;state=null;drag=null;root.hidden=true;if(restore)anchor.focus?.()}
 function commit(){if(!state||!validate())return;const next=mode.value==="by-layer"?null:state.value,callback=state.onApply;close();callback(next)}
 function open({anchor,value,allowByLayer=false,isByLayer=false,resolvedColor=null,label="Color",onApply}={}){if(!anchor||typeof onApply!=="function")throw new Error("Color popover requires an anchor and Apply callback");state={anchor,value:validHex(value)?value.toLowerCase():"#e8edf4",resolvedColor,onApply,hsv:[0,0,0]};heading.textContent=label;root.setAttribute("aria-label",label);mode.hidden=!allowByLayer;mode.value=isByLayer?"by-layer":"custom";original.style.backgroundColor=resolvedColor||state.value;setColor(state.value);syncDisabled();root.hidden=false;position();(isByLayer?mode:sv).focus();return snapshot()}
 function snapshot(){return Object.freeze({open:Boolean(state),value:state?.value||null,hsv:state?Object.freeze([...state.hsv]):null,mode:mode.value,valid:!apply.disabled})}
 function relative(event,node){const bounds=node.getBoundingClientRect?.()||{left:0,top:0,width:1,height:1};return{x:clamp((event.clientX-bounds.left)/(bounds.width||1),0,1),y:clamp((event.clientY-bounds.top)/(bounds.height||1),0,1)}}
 function updateDrag(event){if(!state||mode.value==="by-layer"||!drag)return;if(drag==="sv"){const point=relative(event,sv);setHsv(state.hsv[0],point.x,1-point.y)}else{const point=relative(event,hue);setHsv(point.y*360,state.hsv[1],state.hsv[2])}}
 for(const [node,type] of [[sv,"sv"],[hue,"hue"]]){node.addEventListener("pointerdown",event=>{if(mode.value==="by-layer")return;drag=type;node.setPointerCapture?.(event.pointerId);updateDrag(event);event.preventDefault?.()});node.addEventListener("pointermove",updateDrag);node.addEventListener("pointerup",()=>drag=null);node.addEventListener("pointercancel",()=>drag=null)}
 palette.addEventListener("click",event=>{const button=event.target.closest?.(".color-palette-swatch")||event.target;if(state&&button.dataset?.color&&mode.value!=="by-layer")setColor(button.dataset.color)})
 hex.addEventListener("input",()=>{if(!state)return;const value=hex.value.startsWith("#")?hex.value:`#${hex.value}`;if(validHex(value))setColor(value);else validate()});for(const input of channels)input.addEventListener("input",()=>{if(!state)return;const values=channels.map(channel=>Number(channel.value));if(values.every((value,index)=>Number.isInteger(value)&&value>=0&&value<=255&&String(value)===String(channels[index].value).trim()))setColor(hexFromRgb(values));else validate()})
 mode.addEventListener("change",syncDisabled);cancel.addEventListener("click",()=>close());apply.addEventListener("click",commit);document.addEventListener("pointerdown",event=>{if(state&&!root.contains(event.target)&&event.target!==state.anchor)close()});document.addEventListener("keydown",event=>{if(!state)return;if(event.key==="Escape"){event.preventDefault();event.stopImmediatePropagation?.();close()}else if(event.key==="Enter"&&event.target!==cancel){event.preventDefault();event.stopImmediatePropagation?.();commit()}},true);window.addEventListener("resize",()=>{if(state)position()})
 return Object.freeze({open,close,getState:snapshot,root,hex,channels,mode,apply,cancel,sv,hue,palette})
}
window.CaderactColorPopover=Object.freeze({PALETTE,validHex,rgbFromHex,hexFromRgb,rgbToHsv,hsvToRgb,create});window.caderactColorPopover=create()
})()
