// C2: thin semantic adapters for canvas and layer-row contexts.
(() => {
  const element=document.querySelector("#editor-context-menu"),canvas=document.querySelector("canvas"),layers=document.querySelector("#layers-list")
  if(!element||!canvas||!layers||!window.CaderactContextMenu)return
  const controller=window.CaderactContextMenu.create({element})
  const router=window.caderactCommandRouter,selection=window.caderactSelection,session=window.caderactDocumentSession
  const commandAction=name=>({id:name.toLowerCase(),label:name,enabled:selection.selectedIds().length>0,execute:()=>router.execute(name)})
  function selectionActions(){const current=session.reader.layer(session.reader.snapshot().currentLayerId),canAssign=selection.selectedIds().length>0&&current?.visible&&!current?.locked;return [commandAction("Move"),commandAction("Copy"),commandAction("Rotate"),commandAction("Scale"),commandAction("Mirror"),{id:"properties",label:"Properties",separatorBefore:true,enabled:true,execute:()=>window.caderactPropertiesPanel.open()},{id:"assign-current",label:"Assign to Current Layer",enabled:canAssign,execute:()=>window.caderactLayers.assign()},{id:"delete",label:"Delete",separatorBefore:true,enabled:selection.selectedIds().length>0,execute:()=>router.execute("Delete")}]}
  function canvasActions(){const actions=[];if(router.lastRepeatableCommand)actions.push({id:"repeat",label:`Repeat ${router.lastRepeatableCommand}`,enabled:true,execute:()=>router.repeatLastCommand()});actions.push({id:"select-all",label:"Select All",separatorBefore:actions.length>0,enabled:session.reader.editableRecords().length>0,execute:()=>window.caderactViewport.selectAllCommittedGeometry()});return actions}
  function layerActions(layerId){const layer=session.reader.layer(layerId),documentState=session.reader.snapshot(),selected=selection.selectedIds(),inUse=session.reader.records().some(record=>record.layerId===layerId);return [{id:"set-current",label:"Set Current",enabled:layer.visible&&!layer.locked&&documentState.currentLayerId!==layerId,execute:()=>window.caderactLayers.setCurrent(layerId)},{id:"assign-layer",label:"Assign Selection",enabled:selected.length>0&&layer.visible&&!layer.locked,execute:()=>window.caderactLayers.assign(layerId)},{id:"rename",label:"Rename",separatorBefore:true,enabled:true,execute:()=>window.caderactLayers.beginRename(layerId)},{id:"delete-layer",label:"Delete",enabled:layerId!==documentState.defaultLayerId&&!inUse,execute:()=>window.caderactLayers.remove(layerId)},{id:"visibility",label:layer.visible?"Hide":"Show",separatorBefore:true,enabled:!(documentState.currentLayerId===layerId&&!session.reader.layers().some(other=>other.id!==layerId&&other.visible&&!other.locked)),execute:()=>window.caderactLayers.setVisibility(layerId,!layer.visible)},{id:"locking",label:layer.locked?"Unlock":"Lock",enabled:!(!layer.locked&&documentState.currentLayerId===layerId&&!session.reader.layers().some(other=>other.id!==layerId&&other.visible&&!other.locked)),execute:()=>window.caderactLayers.setLocked(layerId,!layer.locked)}]}
  canvas.addEventListener("contextmenu",event=>{if(event.target?.matches?.("input,textarea,select,[contenteditable=true]")||window.caderactViewport.isLayerAssignmentBusy())return;const bounds=canvas.getBoundingClientRect(),point={x:event.clientX-bounds.left,y:event.clientY-bounds.top},context=window.caderactViewport.prepareContextSelection(point);if(context.type==="suppressed")return;event.preventDefault();controller.open({context,actions:context.type==="selection"?selectionActions():canvasActions(),x:event.clientX,y:event.clientY,focusTarget:canvas})})
  layers.addEventListener("contextmenu",event=>{const row=event.target?.closest?.(".layer-row");if(!row||event.target?.matches?.("input,textarea,select,[contenteditable=true]")||window.caderactViewport.isLayerAssignmentBusy())return;event.preventDefault();controller.open({context:{type:"layer",layerId:row.dataset.layerId},actions:layerActions(row.dataset.layerId),x:event.clientX,y:event.clientY,focusTarget:event.target})})
  router.subscribe(()=>controller.close({restoreFocus:false}));session.subscribe(()=>controller.close({restoreFocus:false}))
  window.caderactContextMenu=Object.freeze({open:controller.open,close:controller.close,getState:controller.getState})
})()
