// DC4 AF1 sessions. Planning is pure; publication remains document-owned.
(() => {
  const prompt=(commandName,instruction)=>Object.freeze({commandName,instruction,text:`${commandName}: ${instruction}`})
  const message=reason=>({"empty-selection":"Select at least one editable object.","empty-capture":"Pick one or more endpoints/vertices to stretch.","whole-record-capture":"Stretch requires a partial feature capture, not the whole object.","unsupported-geometry":"That geometry is not supported by this command.","non-positive-length":"Resulting length must be greater than zero.","invalid-arc-length":"Arc length must remain between zero and one full circle.","degenerate-point-pair":"Source and destination point pairs must each be distinct."}[reason]||"The requested edit is invalid.")
  const fail=(name,plan)=>Object.freeze({status:"invalid-input",reason:plan.reason,command:name,message:message(plan.reason),plan})
  const find=(reader,id)=>reader.records().find(record=>record.id===id)||null
  function alignedRecord(record,transform){let result=record;if(transform.factor!==1)result=window.CaderactGeometryTransform.scaleRecord(result,transform.source,transform.factor);if(transform.angle!==0)result=window.CaderactGeometryTransform.rotateRecord(result,transform.source,transform.angle);return window.CaderactGeometryTransform.translateRecord(result,transform.destination.x-transform.source.x,transform.destination.y-transform.source.y)}
  function createStretch({planner,reader,recordGateway,selection,resolveTypedPoint,hitTestStretchFeatures,requestRender,clearSnap,activation}){
    let phase=selection.selectedIds().length?"capture":"selection",selectedIds=phase==="capture"?selection.selectedIds():Object.freeze([]),captures=null,base=null,candidate=null,presentation=prompt("Stretch",phase==="selection"?"Select Lines/open Polylines, then press Enter":"Pick endpoints or vertices to stretch")
    const update=text=>{presentation=prompt("Stretch",text);activation.setPrompt?.(presentation.text,presentation);requestRender()};const records=()=>{const ids=new Set(selectedIds);return reader.editableRecords().filter(record=>ids.has(record.id))}
    function confirm(){const ids=selection.orderedIds(),source=new Map(reader.editableRecords().map(r=>[r.id,r]));if(!ids.length)return fail("Stretch",{reason:"empty-selection"});if(ids.some(id=>!source.has(id)||reader.groupForRecord(id)||!(source.get(id).type==="line"||source.get(id).type==="polyline"&&!source.get(id).closed)))return fail("Stretch",{reason:"unsupported-geometry"});selectedIds=Object.freeze([...ids]);phase="capture";update("Pick endpoints or vertices to stretch");return Object.freeze({status:"input-accepted",command:"Stretch",kind:"selection"})}
    function plan(){return planner.plan({records:records(),captures,dx:candidate.x-base.x,dy:candidate.y-base.y})}
    function accept(point,context={}){if(phase==="capture"){captures=hitTestStretchFeatures(context.rawPoint||point,selectedIds);if(!captures?.length)return fail("Stretch",{reason:"empty-capture"});phase="base";update("Specify base point");return Object.freeze({status:"input-accepted",command:"Stretch",kind:"capture"})}if(phase==="base"){base=Object.freeze({x:point.x,y:point.y});phase="target";update("Specify second point");return Object.freeze({status:"input-accepted",command:"Stretch",kind:"base",point:base})}candidate=Object.freeze({x:point.x,y:point.y});const result=plan();if(result.status!=="planned")return fail("Stretch",result);const outcome=recordGateway.replaceAll(result.replacements);if(outcome.status!=="committed")return Object.freeze({status:"invalid-input",reason:outcome.status,command:"Stretch",message:"Unable to publish; preview preserved."});clearSnap();requestRender();return Object.freeze({status:"command-completed",command:"Stretch",outcome,plan:result})}
    function input(value){if(phase!=="base"&&phase!=="target")return fail("Stretch",{reason:"point-required"});const parsed=resolveTypedPoint(value,phase==="target"?base:null);if(parsed.status!=="point-resolved")return Object.freeze({status:"invalid-input",reason:parsed.reason,command:"Stretch",message:"Enter a point as x,y."});return accept(parsed)}
    function preview(){if(phase!=="target"||!candidate)return null;const result=plan();return result.status==="planned"?Object.freeze({mode:"stretch",preserveSourceVisible:false,recordIds:selectedIds,sourceRecords:Object.freeze([]),records:result.replacements}):null}
    function finish(){return phase==="selection"?confirm():Object.freeze({status:"invalid-input",reason:"point-required",command:"Stretch",message:"Complete the current point step."})}function cancel(){clearSnap();requestRender();return Object.freeze({status:"command-cancelled",command:"Stretch"})}
    requestRender();return Object.freeze({name:"Stretch",finish,cancel,handlePointerDown:accept,handlePointerMove:point=>{if(phase==="target")candidate=Object.freeze({x:point.x,y:point.y});requestRender()},handlePointerLeave:()=>{candidate=null;clearSnap();requestRender()},handleInput:input,getMovePreview:preview,getOrthoReference:()=>phase==="target"?base:null,get usesResolvedPoint(){return phase==="base"||phase==="target"},hasPointerPreview:()=>phase==="target",get isSelectionPhase(){return phase==="selection"},get phase(){return phase},get prompt(){return presentation.text},get promptPresentation(){return presentation}})
  }
  function createLengthen({planner,reader,recordGateway,hitTestEditableDirectTarget,requestRender,clearSnap,activation}){
    let phase="target",target=null,pick=null,mode="delta",value=null,presentation=prompt("Lengthen","Select a Line or Arc near the endpoint to modify")
    const update=text=>{presentation=prompt("Lengthen",text);activation.setPrompt?.(presentation.text,presentation);requestRender()};const plan=()=>planner.plan({record:target,pickPoint:pick,mode,value})
    function commit(){const result=plan();if(result.status!=="planned")return fail("Lengthen",result);const outcome=recordGateway.replace(target.id,result.replacement);if(outcome.status!=="committed")return Object.freeze({status:"invalid-input",reason:outcome.status,command:"Lengthen",message:"Unable to publish; preview preserved."});clearSnap();requestRender();return Object.freeze({status:"command-completed",command:"Lengthen",outcome,plan:result})}
    function down(point,context={}){if(phase!=="target")return Object.freeze({status:"invalid-input",reason:"value-required",command:"Lengthen"});pick=Object.freeze({x:(context.rawPoint||point).x,y:(context.rawPoint||point).y});target=hitTestEditableDirectTarget(pick,["line","arc"]);if(!target)return fail("Lengthen",{reason:"invalid-target"});phase="value";update(`Enter ${mode} length`);return Object.freeze({status:"input-accepted",command:"Lengthen",kind:"target",recordId:target.id})}
    function input(text){if(phase!=="value")return Object.freeze({status:"invalid-input",reason:"target-required",command:"Lengthen",message:"Select an object first."});const parsed=Number(String(text).trim());if(!Number.isFinite(parsed))return Object.freeze({status:"invalid-input",reason:"invalid-value",command:"Lengthen",message:"Enter a finite length."});value=parsed;return commit()}
    function option(id){if(id!=="delta"&&id!=="total")return Object.freeze({status:"option-unavailable",reason:"unknown-option",command:"Lengthen",optionId:id});mode=id;update(target?`Enter ${mode} length`:"Select a Line or Arc near the endpoint to modify");return Object.freeze({status:"option-updated",command:"Lengthen",optionId:id})}
    function preview(){if(!target||value===null)return null;const result=plan();return result.status==="planned"?Object.freeze({mode:"lengthen",preserveSourceVisible:false,recordIds:Object.freeze([target.id]),sourceRecords:Object.freeze([]),records:Object.freeze([result.replacement])}):null}
    function cancel(){clearSnap();requestRender();return Object.freeze({status:"command-cancelled",command:"Lengthen"})}requestRender();return Object.freeze({name:"Lengthen",finish:()=>Object.freeze({status:"invalid-input",reason:phase==="target"?"target-required":"value-required",command:"Lengthen"}),cancel,handlePointerDown:down,handleInput:input,handleOption:option,getMovePreview:preview,usesResolvedPoint:false,hasPointerPreview:()=>false,get options(){return Object.freeze([{id:"delta",label:"Delta",value:mode==="delta"?"Active":"",enabled:true},{id:"total",label:"Total",value:mode==="total"?"Active":"",enabled:true}])},get phase(){return phase},get prompt(){return presentation.text},get promptPresentation(){return presentation}})
  }
  function createAlign({planner,reader,recordGateway,selection,resolveTypedPoint,requestRender,clearSnap,activation}){
    let phase=selection.selectedIds().length?"source1":"selection",ids=phase==="selection"?Object.freeze([]):selection.selectedIds(),points={},candidate=null,scale=false,presentation=prompt("Align",phase==="selection"?"Select objects, then press Enter":"Specify first source point")
    const instructions={source1:"Specify first source point",destination1:"Specify first destination point",source2:"Specify second source point",destination2:"Specify second destination point"};const update=text=>{presentation=prompt("Align",text);activation.setPrompt?.(presentation.text,presentation);requestRender()};const records=()=>{const set=new Set(ids);return reader.editableRecords().filter(r=>set.has(r.id))}
    function validate(){const selected=selection.orderedIds(),editable=new Map(reader.editableRecords().map(r=>[r.id,r]));if(!selected.length)return fail("Align",{reason:"empty-selection"});if(selected.some(id=>!editable.has(id)||reader.groupForRecord(id)))return fail("Align",{reason:"unsupported-geometry"});ids=Object.freeze([...selected]);return null}
    function plan(final=candidate){return planner.plan({records:records(),source1:points.source1,destination1:points.destination1,source2:points.source2,destination2:final,scale})}
    function transformed(result){return records().map(record=>alignedRecord(record,result.transform))}
    function accept(point){if(phase==="selection")return fail("Align",{reason:"empty-selection"});const accepted=Object.freeze({x:point.x,y:point.y});if(phase==="destination2"){candidate=accepted;const selectionError=validate();if(selectionError)return selectionError;const result=plan();if(result.status!=="planned")return fail("Align",result);const replacements=transformed(result),outcome=recordGateway.replaceAll(replacements);if(outcome.status!=="committed")return Object.freeze({status:"invalid-input",reason:outcome.status,command:"Align",message:"Unable to publish; preview preserved."});clearSnap();requestRender();return Object.freeze({status:"command-completed",command:"Align",outcome,plan:result})}points[phase]=accepted;phase=phase==="source1"?"destination1":phase==="destination1"?"source2":"destination2";update(instructions[phase]);return Object.freeze({status:"input-accepted",command:"Align",kind:phase,point:accepted})}
    function input(value){const parsed=resolveTypedPoint(value);if(parsed.status!=="point-resolved")return Object.freeze({status:"invalid-input",reason:parsed.reason,command:"Align",message:"Enter a point as x,y."});return accept(parsed)}
    function finish(){if(phase!=="selection")return Object.freeze({status:"invalid-input",reason:"point-required",command:"Align"});const error=validate();if(error)return error;phase="source1";update(instructions.source1);return Object.freeze({status:"input-accepted",command:"Align",kind:"selection"})}
    function option(id){if(id!=="scale")return Object.freeze({status:"option-unavailable",reason:"unknown-option",command:"Align",optionId:id});scale=!scale;requestRender();return Object.freeze({status:"option-updated",command:"Align",optionId:id,value:scale?"Yes":"No"})}
    function preview(){if(phase!=="destination2"||!candidate)return null;const result=plan();return result.status==="planned"?Object.freeze({mode:"align",preserveSourceVisible:false,recordIds:ids,sourceRecords:Object.freeze([]),records:Object.freeze(transformed(result))}):null}
    function cancel(){clearSnap();requestRender();return Object.freeze({status:"command-cancelled",command:"Align"})}requestRender();return Object.freeze({name:"Align",finish,cancel,handlePointerDown:accept,handlePointerMove:point=>{if(phase==="destination2")candidate=Object.freeze({x:point.x,y:point.y});requestRender()},handlePointerLeave:()=>{candidate=null;clearSnap();requestRender()},handleInput:input,handleOption:option,getMovePreview:preview,hasPointerPreview:()=>phase!=="selection",get isSelectionPhase(){return phase==="selection"},get phase(){return phase},get options(){return Object.freeze([{id:"scale",label:"Scale",value:scale?"Yes":"No",enabled:true}])},get prompt(){return presentation.text},get promptPresentation(){return presentation}})
  }
  window.CaderactDirectEditingCommands=Object.freeze({registrations:Object.freeze([
    Object.freeze({name:"Stretch",aliases:Object.freeze(["S"]),planner:Object.freeze({plan:window.CaderactDirectEditingPlanner.stretch}),createSession:createStretch}),
    Object.freeze({name:"Lengthen",aliases:Object.freeze(["LENG"]),planner:Object.freeze({plan:window.CaderactDirectEditingPlanner.lengthen}),createSession:createLengthen}),
    Object.freeze({name:"Align",aliases:Object.freeze(["AL"]),planner:Object.freeze({plan:window.CaderactDirectEditingPlanner.align}),createSession:createAlign}),
  ])})
})()
