// GBUX1: compact management surface over the native Group gateway.
(() => {
  const list=document.querySelector("#groups-list"),createButton=document.querySelector("#group-create")
  if(!list||!createButton||!window.caderactDocumentSession||!window.caderactSelection)return
  const session=window.caderactDocumentSession,selection=window.caderactSelection,popup=document.createElement("div")
  popup.classList.add("group-actions-menu");popup.setAttribute("role","menu");popup.hidden=true;(document.body||document).appendChild(popup)
  window.caderactGroupActionsMenu=popup
  let editingGroupId=null,openMenuGroupId=null,menuAnchor=null,unsubscribeHistory=null
  const result=(status,details={})=>Object.freeze({status,...details})
  const messages={"insufficient-members":"Select at least two ungrouped objects.","missing-member":"The selection contains an unavailable object.","already-grouped":"An object can belong to only one group.","invalid-name":"Group name cannot be empty.","duplicate-name":"A group with that name already exists.","member-limit":"This group has reached its member limit.","missing-group":"The group no longer exists."}
  function feedback(outcome){const message=messages[outcome.status];if(message)window.caderactFeedback?.showTemporary(message,"error")}
  function blocked(){return Boolean(window.caderactCommandRouter?.isActive)}
  function selectedIds(){const records=new Set(session.reader.records().map(record=>record.id));return selection.selectedIds().filter(id=>records.has(id))}
  function closeMenu(){menuAnchor?.setAttribute?.("aria-expanded","false");openMenuGroupId=null;menuAnchor=null;popup.hidden=true;popup.replaceChildren()}
  function cancelRename({renderNow=true}={}){if(!editingGroupId)return false;editingGroupId=null;if(renderNow)render();return true}
  function run(action){if(blocked())return result("group-action-blocked-active-command");const outcome=action();feedback(outcome);return outcome}
  function create(){const outcome=run(()=>session.groupGateway.createGroup(selectedIds()));if(outcome.group)window.caderactFeedback?.showTemporary(`${outcome.group.name} created.`);return outcome}
  function rename(groupId,name){return run(()=>session.groupGateway.rename(groupId,name))}
  function addSelection(groupId){return run(()=>session.groupGateway.addMembers(groupId,selectedIds()))}
  function removeSelection(groupId){return run(()=>session.groupGateway.removeMembers(groupId,selectedIds()))}
  function dissolve(groupId){return run(()=>session.groupGateway.ungroup(groupId))}
  function selectGroup(groupId){const group=session.reader.group(groupId);if(!group)return result("missing-group",{groupId});return selection.applyRecordIds(group.memberIds)}
  function beginRename(groupId){if(blocked())return result("group-action-blocked-active-command");if(!session.reader.group(groupId))return result("missing-group",{groupId});closeMenu();editingGroupId=groupId;render();return result("rename-started",{groupId})}
  function icon(name){const svg=document.createElementNS?.("http://www.w3.org/2000/svg","svg")||document.createElement("svg"),use=document.createElementNS?.("http://www.w3.org/2000/svg","use")||document.createElement("use");svg.setAttribute("aria-hidden","true");use.setAttribute("href",`#dock-${name}`);svg.appendChild(use);return svg}
  function button(className,label,iconName,handler){const value=document.createElement("button");value.type="button";value.classList.add(className);value.setAttribute("aria-label",label);value.title=label;if(iconName)value.appendChild(icon(iconName));value.addEventListener("click",event=>{event.stopPropagation?.();handler(event)});return value}
  function menuAction(label,iconName,handler,{disabled=false}={}){const value=button("group-menu-action",label,iconName,()=>{closeMenu();handler()});value.disabled=blocked()||disabled;const text=document.createElement("span");text.textContent=label;value.appendChild(text);popup.appendChild(value)}
  function placeMenu(){if(!menuAnchor||popup.hidden)return;const anchor=menuAnchor.getBoundingClientRect?.()||{left:8,right:32,top:8,bottom:32},width=popup.offsetWidth||196,height=popup.offsetHeight||144,vw=window.innerWidth||1024,vh=window.innerHeight||768,margin=8,left=Math.max(margin,Math.min(vw-width-margin,anchor.right-width)),candidate=anchor.bottom+4+height<=vh-margin?anchor.bottom+4:Math.max(margin,anchor.top-height-4),top=Math.max(margin,Math.min(vh-height-margin,candidate));popup.style.left=`${left}px`;popup.style.top=`${top}px`;popup.dataset.placement=candidate<anchor.top?"above":"below"}
  function openMenu(group,anchor){cancelRename({renderNow:false});openMenuGroupId=group.id;menuAnchor=anchor;anchor.setAttribute("aria-expanded","true");popup.replaceChildren();const ids=selectedIds(),owners=ids.map(id=>session.reader.groupForRecord(id)),canAdd=ids.some(id=>!group.memberIds.includes(id))&&owners.every(owner=>!owner||owner.id===group.id),canRemove=ids.some(id=>group.memberIds.includes(id));menuAction("Select Group","select",()=>selectGroup(group.id));menuAction("Rename","rename",()=>beginRename(group.id));menuAction("Add Selection","add",()=>addSelection(group.id),{disabled:!canAdd});menuAction("Remove Selection","move-layer",()=>removeSelection(group.id),{disabled:!canRemove});menuAction("Dissolve Group","delete",()=>dissolve(group.id));popup.hidden=false;placeMenu()}
  function render(){
    const selected=selectedIds(),groups=session.reader.groups();createButton.disabled=blocked()||selected.length<2||selected.some(id=>session.reader.groupForRecord(id));let editInput=null
    const rows=groups.map(group=>{const row=document.createElement("div");row.classList.add("group-row");row.setAttribute("role","listitem");row.dataset.groupId=group.id
      let name;if(editingGroupId===group.id){name=document.createElement("input");name.type="text";name.value=group.name;name.maxLength=128;name.classList.add("group-name-input");name.setAttribute("aria-label",`Rename ${group.name}`);name.addEventListener("keydown",event=>{if(event.key==="Escape"){event.preventDefault();cancelRename()}else if(event.key==="Enter"){event.preventDefault();const outcome=rename(group.id,name.value);if(outcome.status==="committed"||outcome.status==="no-op"){editingGroupId=null;render()}}});name.addEventListener("blur",()=>{if(editingGroupId===group.id)cancelRename()});editInput=name}else{name=button("group-select",`Select ${group.name}`,null,()=>selectGroup(group.id));name.textContent=group.name;name.title=group.name;name.addEventListener("dblclick",event=>{event.preventDefault();beginRename(group.id)})}
      const count=document.createElement("span");count.classList.add("group-member-count");count.textContent=String(group.memberIds.length);count.title=`${group.memberIds.length} member${group.memberIds.length===1?"":"s"}`
      const more=button("group-actions",`Actions for ${group.name}`,"more",event=>openMenuGroupId===group.id?closeMenu():openMenu(group,event.currentTarget||more));more.setAttribute("aria-expanded",String(openMenuGroupId===group.id));row.appendChild(name);row.appendChild(count);row.appendChild(more);return row})
    if(!rows.length){const empty=document.createElement("p");empty.classList.add("groups-empty");empty.textContent="No groups in this drawing.";list.replaceChildren(empty)}else list.replaceChildren(...rows)
    if(openMenuGroupId){menuAnchor=rows.find(row=>row.dataset.groupId===openMenuGroupId)?.children[2]||menuAnchor;placeMenu()}if(editInput){editInput.focus();editInput.select?.()}
  }
  function bindDocument(){unsubscribeHistory?.();unsubscribeHistory=session.controller.subscribeHistory(render);cancelRename({renderNow:false});closeMenu();render()}
  createButton.addEventListener("click",()=>{cancelRename({renderNow:false});create()});list.addEventListener("scroll",()=>{cancelRename();if(openMenuGroupId)placeMenu()});document.addEventListener("pointerdown",event=>{if(editingGroupId&&!event.target?.classList?.contains("group-name-input"))cancelRename();if(openMenuGroupId&&!popup.contains(event.target)&&event.target!==menuAnchor)closeMenu()});document.addEventListener("keydown",event=>{if(event.key==="Escape"&&openMenuGroupId){event.preventDefault();closeMenu()}});window.addEventListener("resize",placeMenu);selection.subscribe(render);session.subscribe(bindDocument);window.caderactCommandRouter?.subscribe(render);bindDocument()
  window.caderactGroups=Object.freeze({create,rename,addSelection,removeSelection,dissolve,selectGroup,beginRename,cancelRename,refresh:render,getState:()=>Object.freeze({editingGroupId,openMenuGroupId})})
})()
