// PS1 compact Model/Layout navigation and Layout document operations.
(() => {
  const strip=document.querySelector(".model-strip"),tabs=document.querySelector("#layout-tabs"),add=document.querySelector("#layout-add")
  const session=window.caderactDocumentSession,context=window.caderactLayoutContext
  if(!strip||!tabs||!add||!session||!context)return
  let dragged=null,unsubscribeHistory=null,selectedViewportId=null
  const viewportTools=document.querySelector("#layout-viewport-tools"),viewportCreate=document.querySelector("#layout-viewport-create"),viewportScale=document.querySelector("#layout-viewport-scale"),viewportLock=document.querySelector("#layout-viewport-lock")
  const setupDialog=document.createElement("dialog");setupDialog.classList.add("page-setup-dialog");setupDialog.setAttribute("aria-labelledby","page-setup-title");(document.body||document).appendChild(setupDialog)
  function field(label,control){const row=document.createElement("label");row.classList.add("page-setup-row");const text=document.createElement("span");text.textContent=label;row.appendChild(text);row.appendChild(control);return row}
  const title=document.createElement("h2");title.id="page-setup-title";title.textContent="Page Setup";const size=document.createElement("select"),orientation=document.createElement("select");for(const value of ["A4","A3","Letter","Legal","Custom"]){const option=document.createElement("option");option.value=value;option.textContent=value;size.appendChild(option)}for(const value of ["portrait","landscape"]){const option=document.createElement("option");option.value=value;option.textContent=value[0].toUpperCase()+value.slice(1);orientation.appendChild(option)}const width=document.createElement("input"),height=document.createElement("input");width.type=height.type="number";width.min=height.min="0.01";width.step=height.step="0.1";const margins={};for(const key of ["top","right","bottom","left"]){margins[key]=document.createElement("input");margins[key].type="number";margins[key].min="0";margins[key].step="0.1"}const actions=document.createElement("div");actions.classList.add("page-setup-actions");const cancel=document.createElement("button"),apply=document.createElement("button");cancel.type=apply.type="button";cancel.textContent="Cancel";apply.textContent="Apply";apply.classList.add("is-primary");actions.appendChild(cancel);actions.appendChild(apply);setupDialog.appendChild(title);setupDialog.appendChild(field("Paper size",size));setupDialog.appendChild(field("Orientation",orientation));setupDialog.appendChild(field("Width (mm)",width));setupDialog.appendChild(field("Height (mm)",height));for(const key of ["top","right","bottom","left"])setupDialog.appendChild(field(`${key[0].toUpperCase()+key.slice(1)} margin (mm)`,margins[key]));setupDialog.appendChild(actions)
  let setupLayoutId=null
  function syncDimensions(){const preset=window.CaderactPaperSpace.SIZES[size.value];if(!preset)return;const portrait=orientation.value==="portrait";width.value=String(portrait?preset.width:preset.height);height.value=String(portrait?preset.height:preset.width)}
  size.addEventListener("change",syncDimensions);orientation.addEventListener("change",syncDimensions);cancel.addEventListener("click",()=>setupDialog.close?.())
  apply.addEventListener("click",()=>{const outcome=session.layoutGateway.setPageSetup(setupLayoutId,{size:size.value,orientation:orientation.value,width:Number(width.value),height:Number(height.value),units:"mm",margins:Object.fromEntries(Object.entries(margins).map(([key,input])=>[key,Number(input.value)]))});if(outcome.status==="committed"||outcome.status==="no-op")setupDialog.close?.();else setupDialog.setAttribute("data-error",outcome.status)})
  function openPageSetup(layoutId){const layout=session.reader.layout(layoutId);if(!layout)return Object.freeze({status:"unknown-layout"});setupLayoutId=layoutId;const paper=layout.paper;size.value=paper.size;orientation.value=paper.orientation;width.value=String(paper.width);height.value=String(paper.height);for(const key of Object.keys(margins))margins[key].value=String(paper.margins[key]);setupDialog.removeAttribute?.("data-error");setupDialog.showModal?.();return Object.freeze({status:"page-setup-opened",layoutId})}
  const activate=id=>{const outcome=id==="model"?context.switchToModel():context.switchToLayout(id);if(outcome.status==="context-switched"){window.caderactSelection?.clear?.();window.caderactViewport?.refreshDocumentView?.()}return outcome}
  function tab(label,id){const button=document.createElement("button");button.type="button";button.classList.add("layout-tab");button.textContent=label;button.dataset.layoutId=id;button.setAttribute("role","tab");button.setAttribute("aria-selected","false");button.draggable=id!=="model";button.addEventListener("click",()=>activate(id));if(id!=="model"){button.title="Double-click to rename; right-click for Page Setup; Delete key removes";button.addEventListener("dblclick",()=>{const name=window.prompt?.("Rename Layout",label);if(name!==null&&name!==undefined)session.layoutGateway.rename(id,name)});button.addEventListener("contextmenu",event=>{event.preventDefault();openPageSetup(id)});button.addEventListener("keydown",event=>{if(event.key==="Delete"&&window.confirm?.(`Delete ${label}?`)!==false)session.layoutGateway.remove(id)});button.addEventListener("dragstart",()=>{dragged=id});button.addEventListener("dragover",event=>event.preventDefault());button.addEventListener("drop",event=>{event.preventDefault();const target=session.reader.layouts().findIndex(layout=>layout.id===id);if(dragged)session.layoutGateway.reorder(dragged,target);dragged=null})}return button}
  function selectedViewport(){const current=context.snapshot(),layout=current.kind==="layout"?session.reader.layout(current.layoutId):null;return layout?.viewports?.[selectedViewportId]||null}
  function render(){const current=context.snapshot();tabs.replaceChildren(tab("Model","model"),...session.reader.layouts().map(layout=>tab(layout.name,layout.id)));for(const button of tabs.children){const active=current.kind==="model"?button.dataset.layoutId==="model":button.dataset.layoutId===current.layoutId;button.classList.toggle("is-active",active);button.setAttribute("aria-selected",String(active));if(active)button.setAttribute("aria-current","page");else button.removeAttribute("aria-current")}if(viewportTools)viewportTools.hidden=current.kind!=="layout";const viewport=selectedViewport();if(viewportScale){viewportScale.disabled=!viewport;viewportScale.value=String(viewport?.scale||1)}if(viewportLock){viewportLock.disabled=!viewport;viewportLock.textContent=viewport?.locked?"Unlock":"Lock";viewportLock.setAttribute("aria-pressed",String(Boolean(viewport?.locked)))}}
  function bind(){unsubscribeHistory?.();unsubscribeHistory=session.controller.subscribeHistory(render);render()}
  add.addEventListener("click",()=>{const outcome=session.layoutGateway.create();if(outcome.layout)activate(outcome.layout.id)})
  viewportCreate?.addEventListener("click",()=>{const current=context.snapshot();if(current.kind!=="layout")return;const layout=session.reader.layout(current.layoutId),outcome=session.layoutGateway.createViewport(layout.id,{frame:{x:layout.paper.margins.left+10,y:layout.paper.margins.bottom+10,width:Math.min(120,layout.paper.width-40),height:Math.min(90,layout.paper.height-40)},viewCenter:{x:0,y:0},scale:1,locked:false});if(outcome.viewport)selectedViewportId=outcome.viewport.id;render();window.caderactViewport?.refreshDocumentView?.()})
  viewportScale?.addEventListener("change",()=>{const current=context.snapshot(),viewport=selectedViewport();if(current.kind==="layout"&&viewport)session.layoutGateway.updateViewport(current.layoutId,viewport.id,{scale:Number(viewportScale.value)},{viewChange:true})})
  viewportLock?.addEventListener("click",()=>{const current=context.snapshot(),viewport=selectedViewport();if(current.kind==="layout"&&viewport)session.layoutGateway.updateViewport(current.layoutId,viewport.id,{locked:!viewport.locked})})
  context.subscribe(render);session.subscribe(bind);bind()
  window.caderactLayouts=Object.freeze({create:name=>session.layoutGateway.create(name),rename:(id,name)=>session.layoutGateway.rename(id,name),remove:id=>session.layoutGateway.remove(id),reorder:(id,index)=>session.layoutGateway.reorder(id,index),setPageSetup:(id,setup)=>session.layoutGateway.setPageSetup(id,setup),createViewport:(id,options)=>session.layoutGateway.createViewport(id,options),updateViewport:(layoutId,id,patch,options)=>session.layoutGateway.updateViewport(layoutId,id,patch,options),removeViewport:(layoutId,id)=>session.layoutGateway.removeViewport(layoutId,id),selectViewport(id){selectedViewportId=id;render();window.caderactPropertiesPanel?.refresh?.();window.caderactViewport?.refreshDocumentView?.();return Object.freeze({status:selectedViewport()?"viewport-selected":"unknown-viewport",viewportId:id})},get selectedViewportId(){return selectedViewportId},openPageSetup,activate,get context(){return context.snapshot()}})
})()
