// AN2: semantic Leader and Multileader command sessions on AF1.
(() => {
  const prompt=(name,instruction)=>Object.freeze({commandName:name,instruction,text:`${name}: ${instruction}`})
  const point=value=>Object.freeze({x:value.x,y:value.y})
  const planner=Object.freeze({plan:value=>Object.freeze({status:"planned",value})})
  function session({name,multi,reader,recordGateway,resolveTypedPoint,requestRender,clearSnap,activation}){
    let branches=[[]],phase="points",candidate=null,presentation=prompt(name,"Specify arrow point")
    const update=instruction=>{presentation=prompt(name,instruction);activation.setPrompt?.(presentation.text,presentation)}
    const current=()=>branches.at(-1)
    const completeBranches=()=>branches.filter(branch=>branch.length>=2)
    function accept(value){if(phase!=="points")return Object.freeze({status:"invalid-input",command:name,reason:"text-required",message:"Enter annotation text."});const p=point(value),branch=current();if(branch.length&&branch.at(-1).x===p.x&&branch.at(-1).y===p.y)return Object.freeze({status:"invalid-input",command:name,reason:"duplicate-vertex",message:"Leader vertices must differ."});branch.push(p);update(branch.length===1?"Specify leader vertex":"Specify another vertex or press Enter for text");requestRender();return Object.freeze({status:"input-accepted",command:name,point:p})}
    function textPhase(){if(current().length<2)return Object.freeze({status:"invalid-input",command:name,reason:"leader-incomplete",message:"Specify an arrow point and leader vertex."});phase="text";candidate=null;update("Enter annotation text");requestRender();return Object.freeze({status:"input-accepted",command:name,kind:"text-phase"})}
    function commit(value){const content=String(value??"").replace(/\\n/g,"\n");if(!content.trim())return Object.freeze({status:"invalid-input",command:name,reason:"empty-text",message:"Annotation text cannot be empty."});const style=reader.dimensionStyle(),source=completeBranches(),last=source[0].at(-1),direction=source[0][0].x<=last.x?1:-1,textPosition={x:last.x+direction*(style.textGap+style.extensionBeyond),y:last.y},geometry={branches:source.map(vertices=>({vertices})),vertices:source[0],textPosition,landingLength:style.extensionBeyond,textOverride:content,dimensionStyleId:reader.currentDimensionStyleId()},record=multi?recordGateway.createMultileader(geometry):recordGateway.createLeader(geometry),outcome=recordGateway.createAll([record]);if(outcome.status!=="committed")return Object.freeze({status:"invalid-input",command:name,reason:outcome.status,message:"Unable to create annotation; draft is preserved.",outcome});clearSnap();requestRender();return Object.freeze({status:"command-completed",command:name,outcome,recordIds:Object.freeze([record.id])})}
    function input(value){if(phase==="text")return commit(value);const parsed=resolveTypedPoint(value,current().at(-1)||null);return parsed.status==="point-resolved"?accept(parsed):Object.freeze({status:"invalid-input",command:name,reason:parsed.reason,message:"Enter a point as x,y."})}
    function option(id){if(id==="text")return textPhase();if(multi&&id==="add"){if(current().length<2)return Object.freeze({status:"invalid-input",command:name,reason:"leader-incomplete",message:"Complete the current branch first."});branches.push([]);phase="points";update("Specify added branch arrow point");requestRender();return Object.freeze({status:"option-updated",command:name,optionId:id})}if(multi&&id==="remove"){if(branches.length<=1)return Object.freeze({status:"invalid-input",command:name,reason:"last-branch",message:"A Multileader needs at least one branch."});branches.pop();update("Specify another vertex or press Enter for text");requestRender();return Object.freeze({status:"option-updated",command:name,optionId:id})}return Object.freeze({status:"option-unavailable",command:name,optionId:id})}
    function preview(){const source=completeBranches();if(!source.length)return null;const withCandidate=phase==="points"&&candidate&&current().length?branches.map((branch,index)=>index===branches.length-1?[...branch,candidate]:branch):branches,last=source[0].at(-1),style=reader.dimensionStyle(),textPosition={x:last.x+(source[0][0].x<=last.x?1:-1)*(style.textGap+style.extensionBeyond),y:last.y};return{type:multi?"dimension-multileader":"dimension-leader",branches:withCandidate.filter(branch=>branch.length>=2).map(vertices=>({vertices})),vertices:withCandidate[0],textPosition,landingLength:style.extensionBeyond,textOverride:"",dimensionStyleId:reader.currentDimensionStyleId()}}
    function cancel(){branches=[[]];candidate=null;clearSnap();requestRender();return Object.freeze({status:"command-cancelled",command:name})}
    requestRender();return Object.freeze({name,handlePointerDown:accept,handlePointerMove:value=>{candidate=point(value);requestRender()},handlePointerLeave:()=>{candidate=null;clearSnap();requestRender()},handleInput:input,handleOption:option,finish:textPhase,cancel,getDimensionPreview:preview,getDraftPoints:()=>Object.freeze(branches.flat().map(point)),getSnapCandidates:()=>Object.freeze(branches.flat().map((value,index)=>Object.freeze({kind:"draft-point",point:value,stableKey:`${name}:${index}`,reference:Object.freeze({kind:"draft-point",index})}))),getOrthoReference:()=>current().at(-1)||null,hasPointerPreview:()=>phase==="points",get options(){return Object.freeze([...(multi?[{id:"add",label:"Add Leader",enabled:current().length>=2},{id:"remove",label:"Remove Leader",enabled:branches.length>1}]:[]),{id:"text",label:"Text",enabled:current().length>=2}])},get phase(){return phase},get prompt(){return presentation.text},get promptPresentation(){return presentation}})
  }
  const registrations=Object.freeze([
    Object.freeze({name:"Leader",aliases:Object.freeze(["LE"]),planner,createSession:services=>session({...services,name:"Leader",multi:false})}),
    Object.freeze({name:"MLeader",aliases:Object.freeze(["MLD"]),planner,createSession:services=>session({...services,name:"MLeader",multi:true})}),
  ])
  window.CaderactLeaderCommands=Object.freeze({registrations})
})()
