// PDF2: Layout-only export UX. Native save/file state is deliberately untouched.
(() => {
  const trigger=document.querySelector("#layout-export-pdf"),session=window.caderactDocumentSession,context=window.caderactLayoutContext,serializer=window.CaderactPdfSerializer
  if(!trigger||!session||!context||!serializer)return
  const dialog=document.createElement("dialog");dialog.classList.add("pdf-export-dialog","caderact-dialog");dialog.setAttribute("aria-labelledby","pdf-export-title");const title=document.createElement("h2"),summary=document.createElement("p"),label=document.createElement("label"),input=document.createElement("input"),actions=document.createElement("div"),cancel=document.createElement("button"),submit=document.createElement("button");title.id="pdf-export-title";title.classList.add("caderact-dialog-title");title.textContent="Export PDF";summary.classList.add("pdf-export-summary");label.textContent="Filename";input.type="text";input.setAttribute("aria-label","PDF filename");cancel.type=submit.type="button";cancel.textContent="Cancel";submit.textContent="Export";submit.classList.add("is-primary");label.appendChild(input);actions.classList.add("pdf-export-actions","caderact-dialog-actions");actions.append(cancel,submit);dialog.append(title,summary,label,actions);(document.body||document).appendChild(dialog)
  const safePart=value=>String(value||"").trim().replace(/[<>:"/\\|?*\u0000-\u001f]/g,"-").replace(/[. ]+$/g,"").slice(0,96)||"Untitled"
  const filename=(documentName,layoutName)=>`${safePart(documentName.replace(/\.caderact$/i,""))}-${safePart(layoutName)}.pdf`
  const normalizeFilename=value=>`${safePart(String(value||"").replace(/\.pdf$/i,""))}.pdf`
  function prepare(){const built=window.caderactPlotPreview?.buildScene?.();if(!built||built.status!=="ready")return Object.freeze({status:built?.status||"plot-preview-unavailable"});try{return Object.freeze({status:"ready",layout:built.layout,scene:built.scene,pdf:serializer.serialize(built.scene)})}catch(error){return Object.freeze({status:"serialization-failed",error})}}
  const notify=(message,severity="status")=>{const inLayout=context.snapshot().kind==="layout";return window.caderactApplicationFeedback?.notify(message,{severity,source:"layout-export-pdf",anchor:inLayout?trigger:null,placementTarget:inLayout?trigger.parentElement:null})||window.caderactFeedback?.showTemporary(message,severity)}
  function open(){const prepared=prepare();if(prepared.status!=="ready"){notify(context.snapshot().kind!=="layout"?"Switch to a Layout to export PDF.":"PDF export could not be prepared.","error");return prepared}const documentName=session.reader.snapshot().name||"Untitled";input.value=filename(documentName,prepared.layout.name);summary.textContent=`${prepared.layout.paper.size} · ${prepared.layout.paper.orientation} · ${prepared.layout.paper.plot.colorMode}`;dialog.showModal?.();input.focus();input.select?.();return Object.freeze({status:"opened",filename:input.value})}
  function close(){dialog.close?.();trigger.focus()}
  function download(bytes,name){const blob=new Blob([bytes],{type:"application/pdf"}),url=URL.createObjectURL(blob);try{const anchor=document.createElement("a");anchor.href=url;anchor.download=name;anchor.click()}finally{URL.revokeObjectURL(url)}return Object.freeze({status:"initiated"})}
  function exportPdf({output=download}={}){const prepared=prepare();if(prepared.status!=="ready")return prepared;const name=normalizeFilename(input.value);let result;try{result=output(prepared.pdf.bytes,name,prepared.pdf)}catch(error){result=Object.freeze({status:"download-failed",error})}if(result?.status==="initiated"){close();notify(`PDF download initiated: ${name}`,"success")}else notify("PDF download could not be initiated.","error");return Object.freeze({...result,filename:name,pdf:prepared.pdf,scene:prepared.scene})}
  trigger.addEventListener("click",open);cancel.addEventListener("click",close);submit.addEventListener("click",()=>exportPdf());dialog.addEventListener("cancel",event=>{event.preventDefault();close()})
  window.caderactPdfExport=Object.freeze({open,close,prepare,export:exportPdf,normalizeFilename,getState:()=>Object.freeze({open:Boolean(dialog.open),filename:input.value,summary:summary.textContent})})
})()
