// PDF2: Layout-only export UX. Native save/file state is deliberately untouched.
(() => {
  const trigger=document.querySelector("#layout-export-pdf"),session=window.caderactDocumentSession,context=window.caderactLayoutContext,serializer=window.CaderactPdfSerializer,plotOutput=window.CaderactPlotOutput
  if(!trigger||!session||!context||!serializer||!plotOutput)return
  const dialog=document.createElement("dialog");dialog.classList.add("pdf-export-dialog","caderact-dialog");dialog.setAttribute("aria-labelledby","pdf-export-title");const header=document.createElement("header"),titleWrap=document.createElement("div"),title=document.createElement("h2"),subtitle=document.createElement("span"),closeButton=document.createElement("button"),body=document.createElement("div"),summary=document.createElement("p"),label=document.createElement("label"),input=document.createElement("input"),actions=document.createElement("footer"),cancel=document.createElement("button"),submit=document.createElement("button");header.classList.add("caderact-dialog-header","pdf-export-header");title.id="pdf-export-title";title.textContent="Export PDF";subtitle.textContent="Active Layout vector output";titleWrap.append(title,subtitle);closeButton.type="button";closeButton.classList.add("caderact-dialog-close");closeButton.setAttribute("aria-label","Close Export PDF");closeButton.textContent="×";header.append(titleWrap,closeButton);body.classList.add("caderact-dialog-body","pdf-export-body");summary.classList.add("pdf-export-summary");label.textContent="Filename";input.type="text";input.setAttribute("aria-label","PDF filename");cancel.type=submit.type="button";cancel.textContent="Cancel";submit.textContent="Export";submit.classList.add("is-primary");label.appendChild(input);body.append(summary,label);actions.classList.add("pdf-export-actions","caderact-dialog-actions");actions.append(cancel,submit);dialog.append(header,body,actions);(document.body||document).appendChild(dialog)
  const floating=window.CaderactFloatingDialog.bind(dialog,header)
  let returnFocus=trigger,currentJob=window.CaderactPlotJob.defaults(),currentBatch=null
  const safePart=value=>String(value||"").trim().replace(/[<>:"/\\|?*\u0000-\u001f]/g,"-").replace(/[. ]+$/g,"").slice(0,96)||"Untitled"
  const filename=(documentName,layoutName)=>`${safePart(documentName.replace(/\.caderact$/i,""))}-${safePart(layoutName)}.pdf`
  const normalizeFilename=value=>`${safePart(String(value||"").replace(/\.pdf$/i,""))}.pdf`
  function uniqueNames(documentName,pages){return window.CaderactPlotBatch.filenames(documentName,pages.map(page=>page.layout))}
  function prepare(job=currentJob,batchInput=currentBatch){if(batchInput){const built=plotOutput.prepareBatch(batchInput,job);if(!built||built.status!=="ready")return Object.freeze({status:built?.status||"plot-output-unavailable"});try{const pdfs=built.batch.outputMode==="separate"?built.pages.map(page=>serializer.serialize(page.scene)):null,pdf=built.batch.outputMode==="multi-page"?serializer.serializePages(built.pages.map(page=>page.scene)):null;return Object.freeze({status:"ready",batch:built.batch,pages:built.pages,pdf,pdfs})}catch(error){return Object.freeze({status:"serialization-failed",error})}}const built=plotOutput.prepare(job);if(!built||built.status!=="ready")return Object.freeze({status:built?.status||"plot-output-unavailable"});try{return Object.freeze({status:"ready",layout:built.layout,job:built.job,scene:built.scene,pdf:serializer.serialize(built.scene)})}catch(error){return Object.freeze({status:"serialization-failed",error})}}
  const notify=(message,severity="status")=>{const inLayout=context.snapshot().kind==="layout";return window.caderactApplicationFeedback?.notify(message,{severity,source:"layout-export-pdf",anchor:inLayout?trigger:null,placementTarget:inLayout?trigger.parentElement:null})||window.caderactFeedback?.showTemporary(message,severity)}
  function open(options={}){const normalized=window.CaderactPlotJob.normalize(options.job||window.CaderactPlotJob.defaults());currentJob=normalized.status==="ready"?normalized.job:window.CaderactPlotJob.defaults();currentBatch=options.batch||null;const prepared=prepare(currentJob,currentBatch);if(prepared.status!=="ready"){notify(context.snapshot().kind!=="layout"&&!currentBatch?"Switch to a Layout to export PDF.":"PDF export could not be prepared.","error");return prepared}returnFocus=options.returnFocus||document.activeElement||trigger;const documentName=session.reader.snapshot().name||"Untitled";input.value=prepared.batch?`${safePart(documentName.replace(/\.caderact$/i,""))}-Layouts.pdf`:filename(documentName,prepared.layout.name);summary.textContent=prepared.batch?`${prepared.pages.length} Layouts · ${prepared.batch.outputMode==="multi-page"?"Single multi-page PDF":"Separate PDFs"}`:`${prepared.layout.paper.size} · ${prepared.layout.paper.orientation} · ${prepared.job.colorMode}`;dialog.showModal?.();floating.center();input.focus();input.select?.();return Object.freeze({status:"opened",filename:input.value,job:currentJob,batch:prepared.batch||null})}
  function close(){if(dialog.open)dialog.close?.();returnFocus?.focus?.()}
  function download(bytes,name){const blob=new Blob([bytes],{type:"application/pdf"}),url=URL.createObjectURL(blob);try{const anchor=document.createElement("a");anchor.href=url;anchor.download=name;anchor.click()}finally{URL.revokeObjectURL(url)}return Object.freeze({status:"initiated"})}
  function exportPdf({output=download}={}){const prepared=prepare();if(prepared.status!=="ready")return prepared;const name=normalizeFilename(input.value);let result;try{if(prepared.batch?.outputMode==="separate"){const names=uniqueNames(session.reader.snapshot().name,prepared.pages),outputs=prepared.pdfs.map((pdf,index)=>output(pdf.bytes,names[index],pdf));result=outputs.every(value=>value?.status==="initiated")?Object.freeze({status:"initiated",filenames:names,outputs:Object.freeze(outputs)}):Object.freeze({status:"download-failed",outputs:Object.freeze(outputs)})}else result=output(prepared.pdf.bytes,name,prepared.pdf)}catch(error){result=Object.freeze({status:"download-failed",error})}if(result?.status==="initiated"){close();notify(prepared.batch?`PDF download initiated for ${prepared.pages.length} Layouts.`:`PDF download initiated: ${name}`,"success")}else notify("PDF download could not be initiated.","error");return Object.freeze({...result,filename:name,pdf:prepared.pdf||null,pdfs:prepared.pdfs||null,scene:prepared.scene||null,pages:prepared.pages||null})}
  trigger.addEventListener("click",()=>open({returnFocus:trigger}));cancel.addEventListener("click",close);closeButton.addEventListener("click",close);submit.addEventListener("click",()=>exportPdf());input.addEventListener("keydown",event=>{if(event.key==="Enter"&&input.value.trim()){event.preventDefault();exportPdf()}});dialog.addEventListener("cancel",event=>{event.preventDefault();close()})
  window.caderactPdfExport=Object.freeze({open,close,prepare,export:exportPdf,normalizeFilename,uniqueNames,getState:()=>Object.freeze({open:Boolean(dialog.open),filename:input.value,summary:summary.textContent,batch:currentBatch})})
})()
