// PDF1: ephemeral preview of the authoritative renderer-neutral plot scene.
(() => {
  const trigger=document.querySelector("#layout-plot-preview"),session=window.caderactDocumentSession,context=window.caderactLayoutContext
  if(!trigger||!session||!context||!window.CaderactPlotScene)return
  const dialog=document.createElement("dialog");dialog.classList.add("plot-preview-dialog","caderact-dialog");dialog.setAttribute("aria-labelledby","plot-preview-title")
  const header=document.createElement("header"),title=document.createElement("h2"),meta=document.createElement("span"),controls=document.createElement("div"),pageSetup=document.createElement("button"),fit=document.createElement("button"),minus=document.createElement("button"),plus=document.createElement("button"),exportPdf=document.createElement("button"),close=document.createElement("button"),surface=document.createElement("div"),canvas=document.createElement("canvas"),message=document.createElement("p")
  header.classList.add("caderact-dialog-header","plot-preview-header");title.id="plot-preview-title";title.textContent="Plot Preview";meta.classList.add("plot-preview-meta");controls.classList.add("plot-preview-controls");pageSetup.textContent="Page Setup";fit.textContent="Fit Page";minus.textContent="−";minus.setAttribute("aria-label","Zoom out");plus.textContent="+";plus.setAttribute("aria-label","Zoom in");exportPdf.textContent="Export PDF";exportPdf.classList.add("is-primary");close.textContent="×";close.classList.add("caderact-dialog-close");close.setAttribute("aria-label","Close Plot");surface.classList.add("plot-preview-surface","caderact-dialog-body");canvas.setAttribute("aria-label","Layout plot preview");message.classList.add("plot-preview-message");message.hidden=true;controls.append(pageSetup,fit,minus,plus,exportPdf,close);header.append(title,meta,controls);surface.append(canvas,message);dialog.append(header,surface);(document.body||document).appendChild(dialog)
  const floating=window.CaderactFloatingDialog.bind(dialog,header)
  let zoom=1,scene=null,unsubscribeHistory=null,returnFocus=trigger,mode="preview"
  function styles(){return Object.fromEntries(session.reader.dimensionStyles().map(style=>[style.id,style]))}
  function buildScene(){const current=context.snapshot();if(current.kind!=="layout")return Object.freeze({status:"no-active-layout"});const layout=session.reader.layout(current.layoutId);if(!layout)return Object.freeze({status:"invalid-layout"});try{return Object.freeze({status:"ready",layout,scene:window.CaderactPlotScene.create({layout,records:session.reader.visibleRecords(),layers:session.reader.layers(),documentUnit:session.reader.units().length,dimensionStyles:styles()})})}catch(error){return Object.freeze({status:"plot-scene-unavailable",error})}}
  function render(){const built=buildScene();if(built.status!=="ready"){scene=null;canvas.hidden=true;message.hidden=false;message.textContent=built.status==="no-active-layout"?"Plot Preview is available from a Layout.":"The current Layout cannot be previewed.";return built}scene=built.scene;canvas.hidden=false;message.hidden=true;const ratio=scene.page.width/scene.page.height,availableWidth=Math.max(320,surface.clientWidth||900),availableHeight=Math.max(240,surface.clientHeight||620),fitScale=Math.min((availableWidth-48)/scene.page.width,(availableHeight-48)/scene.page.height),scale=fitScale*zoom,dpr=window.devicePixelRatio||1,width=Math.max(1,Math.round(scene.page.width*scale)),height=Math.max(1,Math.round(scene.page.height*scale));canvas.style.width=`${width}px`;canvas.style.height=`${height}px`;canvas.width=Math.round(width*dpr);canvas.height=Math.round(height*dpr);canvas.dataset.aspectRatio=String(ratio);const ctx=canvas.getContext("2d");if(!ctx)return Object.freeze({status:"preview-context-unavailable"});ctx.setTransform(dpr,0,0,dpr,0,0);ctx.clearRect(0,0,width,height);ctx.fillStyle="#ffffff";ctx.fillRect(0,0,width,height);const point=value=>({x:value.x*scale,y:height-value.y*scale});const a=point({x:scene.printable.x,y:scene.printable.y}),b=point({x:scene.printable.x+scene.printable.width,y:scene.printable.y+scene.printable.height});ctx.save();ctx.strokeStyle="#a8adb3";ctx.lineWidth=1;ctx.setLineDash([4,3]);ctx.strokeRect(a.x,b.y,b.x-a.x,a.y-b.y);ctx.restore();for(const line of scene.segments){const start=point(line.start),end=point(line.end);ctx.beginPath();ctx.strokeStyle=line.color;ctx.lineWidth=1;ctx.setLineDash([]);ctx.moveTo(start.x,start.y);ctx.lineTo(end.x,end.y);ctx.stroke()}for(const text of scene.texts){const anchor=point(text.point);ctx.save();ctx.fillStyle=text.color;ctx.font=`${Math.max(1,text.height*scale)}px sans-serif`;ctx.textAlign=text.alignment==="right"?"right":text.alignment==="center"?"center":"left";ctx.translate(anchor.x,anchor.y);ctx.rotate(-text.rotation);ctx.fillText(text.value,0,0);ctx.restore()}meta.textContent=`${built.layout.paper.size} · ${built.layout.paper.orientation} · ${built.layout.paper.plot.colorMode}`;return Object.freeze({status:"rendered",scene,width,height,zoom})}
  function open(options={}){const result=buildScene();if(result.status!=="ready"){const inLayout=context.snapshot().kind==="layout",feedback=result.status==="no-active-layout"?"Switch to a Layout to plot.":"Plot is unavailable for the current Layout.";window.caderactApplicationFeedback?.notify(feedback,{severity:"error",source:"layout-plot-preview",anchor:inLayout?trigger:null,placementTarget:inLayout?trigger.parentElement:null})||window.caderactFeedback?.showTemporary(feedback,"error");return result}mode=options.mode==="plot"?"plot":"preview";returnFocus=options.returnFocus||document.activeElement||trigger;title.textContent=mode==="plot"?"Plot":"Plot Preview";zoom=1;dialog.showModal?.();floating.center();render();close.focus();return Object.freeze({status:"opened",mode})}
  function closePreview(){if(dialog.open)dialog.close?.();returnFocus?.focus?.();return Object.freeze({status:"closed"})}
  function setZoom(value){zoom=Math.max(.25,Math.min(4,value));if(dialog.open)render();return zoom}
  trigger.addEventListener("click",()=>open({mode:"preview",returnFocus:trigger}));close.addEventListener("click",closePreview);fit.addEventListener("click",()=>{zoom=1;render()});minus.addEventListener("click",()=>setZoom(zoom/1.25));plus.addEventListener("click",()=>setZoom(zoom*1.25));pageSetup.addEventListener("click",()=>{const current=context.snapshot();if(current.kind==="layout")window.caderactLayouts?.openPageSetup?.(current.layoutId,pageSetup)});exportPdf.addEventListener("click",()=>window.caderactPdfExport?.open?.({returnFocus:exportPdf}));dialog.addEventListener("cancel",event=>{event.preventDefault();closePreview()});context.subscribe(()=>{if(dialog.open)render()});unsubscribeHistory=session.controller.subscribeHistory(()=>{if(dialog.open)render()});session.subscribe(()=>{unsubscribeHistory?.();unsubscribeHistory=session.controller.subscribeHistory(()=>{if(dialog.open)render()});if(dialog.open)render()})
  window.caderactPlotPreview=Object.freeze({open,openPlot:returnTarget=>open({mode:"plot",returnFocus:returnTarget}),close:closePreview,fit:()=>{zoom=1;return render()},zoomBy:factor=>setZoom(zoom*factor),refresh:render,buildScene,getState:()=>Object.freeze({open:Boolean(dialog.open),mode,zoom,layoutId:scene?.layoutId||null,scene})})
})()
