// SEL1: pure screen-space Fence/WP/CP geometry and semantic selection queries.
(() => {
  const EPSILON=1e-5
  const point=(x,y)=>Object.freeze({x,y})
  const segment=(a,b)=>Object.freeze({a,b})
  function orientation(a,b,c){const value=(b.x-a.x)*(c.y-a.y)-(b.y-a.y)*(c.x-a.x);return Math.abs(value)<=EPSILON?0:Math.sign(value)}
  function onSegment(a,p,b){return orientation(a,p,b)===0&&p.x>=Math.min(a.x,b.x)-EPSILON&&p.x<=Math.max(a.x,b.x)+EPSILON&&p.y>=Math.min(a.y,b.y)-EPSILON&&p.y<=Math.max(a.y,b.y)+EPSILON}
  function segmentsIntersect(a,b,c,d){const abC=orientation(a,b,c),abD=orientation(a,b,d),cdA=orientation(c,d,a),cdB=orientation(c,d,b);return abC!==abD&&cdA!==cdB||abC===0&&onSegment(a,c,b)||abD===0&&onSegment(a,d,b)||cdA===0&&onSegment(c,a,d)||cdB===0&&onSegment(c,b,d)}
  function pointInPolygon(value,polygon){let inside=false;for(let index=0,prior=polygon.length-1;index<polygon.length;prior=index++){const a=polygon[index],b=polygon[prior];if(onSegment(a,value,b))return true;if((a.y>value.y)!==(b.y>value.y)&&value.x<(b.x-a.x)*(value.y-a.y)/(b.y-a.y)+a.x)inside=!inside}return inside}
  function polygonEdges(polygon){return polygon.map((value,index)=>segment(value,polygon[(index+1)%polygon.length]))}
  function flatSegments(values){const output=[];for(let index=0;index<values.length;index+=4)output.push(segment(point(values[index],values[index+1]),point(values[index+2],values[index+3])));return output}
  function projectedArc(record,worldToScreen){const center=worldToScreen(record.center.x,record.center.y),start=worldToScreen(record.start.x,record.start.y);return {center,radius:Math.hypot(start.x-center.x,start.y-center.y),startAngle:Math.atan2(start.y-center.y,start.x-center.x),sweep:-record.sweep}}
  function projectedEllipse(record,worldToScreen){const center=worldToScreen(record.center.x,record.center.y),axis=worldToScreen(record.center.x+record.majorAxis.x,record.center.y+record.majorAxis.y),major=Math.hypot(record.majorAxis.x,record.majorAxis.y);return {center,radiusX:Math.hypot(axis.x-center.x,axis.y-center.y),radiusY:record.minorRadius*Math.hypot(axis.x-center.x,axis.y-center.y)/major,rotation:Math.atan2(axis.y-center.y,axis.x-center.x)}}
  function recordSegments(record,worldToScreen){
    if(record?.type==="line")return [segment(worldToScreen(record.start.x,record.start.y),worldToScreen(record.end.x,record.end.y))]
    if(record?.type==="polyline"){const vertices=record.vertices.map(value=>worldToScreen(value.x,value.y)),count=record.closed?vertices.length:vertices.length-1;return Array.from({length:count},(_,index)=>segment(vertices[index],vertices[(index+1)%vertices.length]))}
    if(record?.type==="circle"){const center=worldToScreen(record.center.x,record.center.y),edge=worldToScreen(record.center.x+record.radius,record.center.y),radius=Math.hypot(edge.x-center.x,edge.y-center.y);return flatSegments(window.CaderactCircleTessellation.createSegments({center,radius}))}
    if(record?.type==="arc")return flatSegments(window.CaderactCircleTessellation.createArcSegments(projectedArc(record,worldToScreen)))
    if(record?.type==="ellipse")return flatSegments(window.CaderactEllipseTessellation.createSegments(projectedEllipse(record,worldToScreen),.25))
    if(record?.type==="text"){const corners=window.CaderactAnnotationGeometry.projectedCorners(record,worldToScreen);return corners.map((value,index)=>segment(value,corners[(index+1)%corners.length]))}
    if(record?.type==="region"||record?.type==="hatch"){const output=[];for(const loop of record.loops)for(const edge of loop.edges){const points=window.CaderactRegionGeometry.sampleEdge(edge).map(value=>worldToScreen(value.x,value.y));for(let index=1;index<points.length;index++)output.push(segment(points[index-1],points[index]))}return output}
    if(record?.type?.startsWith("dimension-")){const presentation=window.CaderactDimensionGeometry.derive(record,window.caderactDocumentSession?.reader.resolveDimensionStyle(record)||window.CaderactDocument.DEFAULT_DIMENSION_STYLE,window.caderactDocumentSession?.reader.units()||{length:"mm"});if(!presentation.supported)return [];const output=presentation.lines.map(([a,b])=>segment(worldToScreen(a.x,a.y),worldToScreen(b.x,b.y)));for(const arc of presentation.arcs||[])output.push(...flatSegments(window.CaderactCircleTessellation.createArcSegments(projectedArc(arc,worldToScreen))));for(const triangle of presentation.triangles)for(let index=0;index<3;index++)output.push(segment(worldToScreen(triangle[index].x,triangle[index].y),worldToScreen(triangle[(index+1)%3].x,triangle[(index+1)%3].y)));return output}
    return []
  }
  function matchesFence(record,fence,worldToScreen){const geometry=recordSegments(record,worldToScreen);for(let index=1;index<fence.length;index++)for(const edge of geometry)if(segmentsIntersect(fence[index-1],fence[index],edge.a,edge.b))return true;return false}
  function matchesPolygon(record,polygon,mode,worldToScreen){const geometry=recordSegments(record,worldToScreen);if(!geometry.length)return false;const contained=geometry.every(edge=>pointInPolygon(edge.a,polygon)&&pointInPolygon(edge.b,polygon));if(mode==="window-polygon"||contained)return contained;const edges=polygonEdges(polygon);return geometry.some(value=>pointInPolygon(value.a,polygon)||pointInPolygon(value.b,polygon)||edges.some(edge=>segmentsIntersect(value.a,value.b,edge.a,edge.b)))}
  function queryGeometry({mode,points,records=[],worldToScreen}){if(!["fence","window-polygon","crossing-polygon"].includes(mode)||points.length<(mode==="fence"?2:3))return Object.freeze([]);const grouped=new Map();for(const record of records){const match=mode==="fence"?matchesFence(record,points,worldToScreen):matchesPolygon(record,points,mode,worldToScreen),state=grouped.get(record.id)||{all:true,any:false};state.all&&=match;state.any||=match;grouped.set(record.id,state)}return Object.freeze(Array.from(grouped).filter(([,state])=>mode==="window-polygon"?state.all:state.any).map(([id])=>id).sort())}
  function queryRecords({records=[],type=null,layerId=null}){return Object.freeze(Array.from(records).filter(record=>(type===null||record.type===type)&&(layerId===null||record.layerId===layerId)).map(record=>record.id).sort())}
  function similar(records,seeds){const signatures=new Set(seeds.map(record=>`${record.type}\u0000${record.layerId}`));return Object.freeze(records.filter(record=>signatures.has(`${record.type}\u0000${record.layerId}`)).map(record=>record.id).sort())}
  window.CaderactProfessionalSelection=Object.freeze({segmentsIntersect,pointInPolygon,recordSegments,queryGeometry,queryRecords,similar})
})()
