// L6: selection-driven right-sidebar Properties surface.
(() => {
  const layersTab=document.querySelector("#sidebar-layers-tab"),propertiesTab=document.querySelector("#sidebar-properties-tab")
  const layersView=document.querySelector("#layers-panel-view"),propertiesView=document.querySelector("#properties-panel-view"),content=document.querySelector("#properties-content")
  if(!layersTab||!propertiesTab||!layersView||!propertiesView||!content||!window.caderactDocumentSession)return
  const session=window.caderactDocumentSession,selection=window.caderactSelection,properties=window.CaderactObjectProperties
  let activePanel="layers",unsubscribeHistory=null
  const title=value=>value.charAt(0).toUpperCase()+value.slice(1)
  const number=value=>Number(value.toFixed(3)).toString()
  const isDimension=record=>record?.type?.startsWith("dimension-")
  function recordTypeLabel(record){if(record.type==="dimension-linear")return record.mode==="aligned"?"Aligned Dimension":"Linear Dimension";if(record.type==="dimension-angular")return"Angular Dimension";if(record.type==="dimension-radial")return record.mode==="diameter"?"Diameter Dimension":"Radius Dimension";return title(record.type)}
  function setPanel(name,{focus=false}={}){activePanel=name;const showProperties=name==="properties";layersView.hidden=showProperties;propertiesView.hidden=!showProperties;layersTab.setAttribute("aria-selected",String(!showProperties));propertiesTab.setAttribute("aria-selected",String(showProperties));if(focus)(showProperties?propertiesTab:layersTab).focus();if(showProperties)render()}
  function tabKeydown(event){if(!["ArrowLeft","ArrowRight","Home","End"].includes(event.key))return;event.preventDefault();const propertiesTarget=event.key==="ArrowRight"||event.key==="End";setPanel(propertiesTarget?"properties":"layers",{focus:true})}
  function option(select,value,label,{selected=false,disabled=false}={}){const item=document.createElement("option");item.value=String(value);item.textContent=label;item.selected=selected;item.disabled=disabled;if(selected)select.value=String(value);select.appendChild(item);return item}
  function section(label){const node=document.createElement("section");node.classList.add("property-section");const heading=document.createElement("h3");heading.textContent=label;node.appendChild(heading);return node}
  function valueRow(label,value){const row=document.createElement("div");row.classList.add("property-row");const left=document.createElement("span");left.classList.add("property-label");left.textContent=label;const right=document.createElement("span");right.classList.add("property-value");right.textContent=value;row.appendChild(left);row.appendChild(right);return row}
  function controlRow(labelText,control){const row=document.createElement("div");row.classList.add("property-row");const label=document.createElement("label");label.textContent=labelText;const id=`property-${labelText.toLowerCase().replace(/\W+/g,"-")}`;control.id=id;label.setAttribute("for",id);row.appendChild(label);row.appendChild(control);return row}
  function selectedRecords(){const byId=new Map(session.reader.records().map(record=>[record.id,record]));return selection.selectedIds().map(id=>byId.get(id)).filter(Boolean)}
  function edit(ids,patch){const outcome=session.recordGateway.setProperties(ids,patch);if(outcome.status!=="committed"&&outcome.status!=="no-op")window.caderactFeedback?.showTemporary("Properties could not be changed.","error");render();return outcome}
  function layerControl(records,disabled){const select=document.createElement("select"),ids=records.map(record=>record.id),first=records[0].layerId,mixed=!records.every(record=>record.layerId===first);if(mixed)option(select,"","Mixed",{selected:true,disabled:true});for(const layer of session.reader.layers().filter(layer=>layer.visible&&!layer.locked))option(select,layer.id,layer.name,{selected:!mixed&&layer.id===first});select.disabled=disabled;select.addEventListener("change",()=>{window.caderactLayers.assign(select.value);render()});return select}
  function effectiveValue(records,key){const resolver=key==="linetype"?properties.effectiveLinetype:key==="lineweight"?properties.effectiveLineweight:properties.effectiveColor,values=records.map(record=>resolver(record,session.reader.layer(record.layerId)));return values.every(value=>Object.is(value,values[0]))?values[0]:properties.MIXED}
  function inheritedReadout(value,key){const output=document.createElement("span");output.classList.add("property-inherited-value");output.textContent=value===properties.MIXED?"→ Mixed":`→ ${key==="lineweight"?`${value} mm`:key==="linetype"?title(value):value}`;output.title="Effective inherited appearance";return output}
  function simplePropertyControl(key,value,records,disabled){const wrap=document.createElement("div");wrap.classList.add("property-select-control");const select=document.createElement("select");select.setAttribute("aria-label",title(key));if(value===properties.MIXED)option(select,"mixed","Mixed",{selected:true,disabled:true});option(select,"by-layer","ByLayer",{selected:value===null});const values=key==="linetype"?properties.LINETYPES:properties.LINEWEIGHTS;for(const candidate of values)option(select,candidate,key==="linetype"?title(candidate):`${candidate} mm`,{selected:Object.is(value,candidate)});select.disabled=disabled;select.addEventListener("change",()=>edit(selection.selectedIds(),{[key]:select.value==="by-layer"?null:key==="lineweight"?Number(select.value):select.value}));wrap.appendChild(select);if(value===null)wrap.appendChild(inheritedReadout(effectiveValue(records,key),key));return wrap}
  function colorControl(value,records,disabled){const wrap=document.createElement("div");wrap.classList.add("property-color-control");const mode=document.createElement("select"),swatch=document.createElement("input");mode.setAttribute("aria-label","Color property state");swatch.type="color";swatch.setAttribute("aria-label","Explicit color");const mixed=value===properties.MIXED,effective=effectiveValue(records,"color");option(mode,"mixed","Mixed",{selected:mixed,disabled:true});option(mode,"by-layer","ByLayer",{selected:value===null});option(mode,"explicit","Explicit",{selected:typeof value==="string"});const fallback=effective===properties.MIXED?"#e8edf4":effective;swatch.value=typeof value==="string"?value:fallback;swatch.disabled=disabled||mixed||value===null;mode.disabled=disabled;mode.addEventListener("change",()=>edit(selection.selectedIds(),{color:mode.value==="by-layer"?null:swatch.value}));swatch.addEventListener("change",()=>edit(selection.selectedIds(),{color:swatch.value}));wrap.appendChild(mode);if(value===null&&effective===properties.MIXED)wrap.appendChild(inheritedReadout(effective,"color"));else wrap.appendChild(swatch);return wrap}
  function geometryRows(record){if(isDimension(record)){const presentation=window.CaderactDimensionGeometry.derive(record,session.reader.dimensionStyle(),session.reader.units());if(!presentation.supported)return[];const rows=[["Measurement",presentation.text.value],["Style","Default"]];for(const key of ["firstPoint","secondPoint","dimensionLinePoint","firstRayPoint","vertex","secondRayPoint","dimensionArcPoint","centerPoint","dimensionPoint","leaderPoint"]){const point=record[key];if(point)rows.push([key.replace(/([A-Z])/g," $1").replace(/^./,value=>value.toUpperCase()),`${number(point.x)}, ${number(point.y)}`])}return rows}const measured=window.CaderactMeasurement.measureRecord(record);if(!measured)return[];if(record.type==="line")return[["Length",number(measured.length)]];if(record.type==="circle")return[["Radius",number(measured.radius)],["Diameter",number(measured.diameter)],["Circumference",number(measured.circumference)],["Area",number(measured.area)]];if(record.type==="arc")return[["Radius",number(measured.radius)],["Diameter",number(measured.diameter)],["Sweep",`${number(Math.abs(measured.sweepDegrees))}°`],["Arc Length",number(measured.arcLength)]];if(record.type==="ellipse")return[["Major Radius",number(measured.majorRadius)],["Minor Radius",number(measured.minorRadius)],["Major Diameter",number(measured.majorDiameter)],["Minor Diameter",number(measured.minorDiameter)],["Area",number(measured.area)]];if(record.type==="polyline"){const rows=[["Length",number(measured.length)]];if(measured.closed)rows.push(["Perimeter",number(measured.perimeter)]);if(Number.isFinite(measured.area))rows.push(["Area",number(measured.area)]);rows.push(["Vertex Count",String(measured.vertexCount)],["Open/Closed",measured.closed?"Closed":"Open"]);return rows}return[]}
  function dimensionTextControl(record,disabled){const input=document.createElement("input");input.type="text";input.value=record.textOverride??"";input.maxLength=window.CaderactDocument.MAX_DIMENSION_TEXT_OVERRIDE_LENGTH;input.disabled=disabled;input.placeholder="Use measured value";input.addEventListener("change",()=>{const value=input.value===""?null:input.value;if(typeof value==="string"&&/[\u0000-\u001f\u007f]/.test(value)){window.caderactFeedback?.showTemporary("Dimension text contains unsupported control characters.","error");render();return}const outcome=session.recordGateway.replace(record.id,{...record,textOverride:value});if(outcome.status!=="committed"&&outcome.status!=="no-op")window.caderactFeedback?.showTemporary("Dimension text could not be changed.","error");render()});return input}
  function render(){
    const records=selectedRecords();if(!records.length){const empty=document.createElement("p");empty.classList.add("properties-empty");empty.textContent="Select drawing objects to view and edit their properties.";content.replaceChildren(empty);return}
    const ids=records.map(record=>record.id),blocked=window.caderactCommandRouter.isActive||records.some(record=>!session.reader.isRecordEditable(record.id)),sameType=records.every(record=>record.type===records[0].type),aggregate=session.reader.aggregateRecordProperties(ids),nodes=[]
    const summary=section("Selection"),typeLabel=sameType?`${recordTypeLabel(records[0])}${records.length>1?` (${records.length})`:""}`:`Multiple (${records.length})`;summary.appendChild(valueRow("Type",typeLabel));summary.appendChild(valueRow("Count",String(records.length)));nodes.push(summary)
    if(blocked){const note=document.createElement("p");note.classList.add("properties-disabled-note");note.textContent=window.caderactCommandRouter.isActive?"Finish or cancel the active command to edit properties.":"The selection contains locked or hidden objects.";nodes.push(note)}
    const general=section("General");general.appendChild(controlRow("Layer",layerControl(records,blocked)));nodes.push(general)
    const appearance=section("Appearance");appearance.appendChild(controlRow("Color",colorControl(aggregate.color,records,blocked)));appearance.appendChild(controlRow("Linetype",simplePropertyControl("linetype",aggregate.linetype,records,blocked)));appearance.appendChild(controlRow("Lineweight",simplePropertyControl("lineweight",aggregate.lineweight,records,blocked)));nodes.push(appearance)
    if(records.length===1){const record=records[0];if(isDimension(record)){const dimension=section("Dimension");dimension.appendChild(controlRow("Text Override",dimensionTextControl(record,blocked)));nodes.push(dimension)}const rows=geometryRows(record);if(rows.length){const geometry=section("Geometry");for(const [label,value] of rows)geometry.appendChild(valueRow(label,value));nodes.push(geometry)}}
    content.replaceChildren(...nodes)
  }
  function bindDocument(){unsubscribeHistory?.();unsubscribeHistory=session.controller.subscribeHistory(render);render()}
  layersTab.addEventListener("click",()=>setPanel("layers"));propertiesTab.addEventListener("click",()=>setPanel("properties"));layersTab.addEventListener("keydown",tabKeydown);propertiesTab.addEventListener("keydown",tabKeydown);selection.subscribe(render);session.subscribe(bindDocument);window.caderactCommandRouter.subscribe(render);bindDocument()
  window.caderactPropertiesPanel=Object.freeze({open:()=>setPanel("properties",{focus:true}),showLayers:()=>setPanel("layers",{focus:true}),refresh:render,getState:()=>Object.freeze({activePanel,selectedCount:selectedRecords().length})})
})()
