// L6: selection-driven right-sidebar Properties surface.
(() => {
  const layersTab=document.querySelector("#sidebar-layers-tab"),propertiesTab=document.querySelector("#sidebar-properties-tab")
  const layersView=document.querySelector("#layers-panel-view"),propertiesView=document.querySelector("#properties-panel-view"),content=document.querySelector("#properties-content")
  if(!layersTab||!propertiesTab||!layersView||!propertiesView||!content||!window.caderactDocumentSession)return
  const session=window.caderactDocumentSession,selection=window.caderactSelection,properties=window.CaderactObjectProperties
  let activePanel="layers",unsubscribeHistory=null
  const title=value=>value.charAt(0).toUpperCase()+value.slice(1)
  const number=value=>Number(value.toFixed(3)).toString()
  function setPanel(name,{focus=false}={}){activePanel=name;const showProperties=name==="properties";layersView.hidden=showProperties;propertiesView.hidden=!showProperties;layersTab.setAttribute("aria-selected",String(!showProperties));propertiesTab.setAttribute("aria-selected",String(showProperties));if(focus)(showProperties?propertiesTab:layersTab).focus();if(showProperties)render()}
  function option(select,value,label,{selected=false,disabled=false}={}){const item=document.createElement("option");item.value=String(value);item.textContent=label;item.selected=selected;item.disabled=disabled;if(selected)select.value=String(value);select.appendChild(item);return item}
  function section(label){const node=document.createElement("section");node.classList.add("property-section");const heading=document.createElement("h3");heading.textContent=label;node.appendChild(heading);return node}
  function valueRow(label,value){const row=document.createElement("div");row.classList.add("property-row");const left=document.createElement("span");left.classList.add("property-label");left.textContent=label;const right=document.createElement("span");right.classList.add("property-value");right.textContent=value;row.appendChild(left);row.appendChild(right);return row}
  function controlRow(labelText,control){const row=document.createElement("div");row.classList.add("property-row");const label=document.createElement("label");label.textContent=labelText;const id=`property-${labelText.toLowerCase().replace(/\W+/g,"-")}`;control.id=id;label.setAttribute("for",id);row.appendChild(label);row.appendChild(control);return row}
  function selectedRecords(){const byId=new Map(session.reader.records().map(record=>[record.id,record]));return selection.selectedIds().map(id=>byId.get(id)).filter(Boolean)}
  function edit(ids,patch){const outcome=session.recordGateway.setProperties(ids,patch);if(outcome.status!=="committed"&&outcome.status!=="no-op")window.caderactFeedback?.showTemporary("Properties could not be changed.","error");render();return outcome}
  function layerControl(records,disabled){const select=document.createElement("select"),ids=records.map(record=>record.id),first=records[0].layerId,mixed=!records.every(record=>record.layerId===first);if(mixed)option(select,"","Mixed",{selected:true,disabled:true});for(const layer of session.reader.layers().filter(layer=>layer.visible&&!layer.locked))option(select,layer.id,layer.name,{selected:!mixed&&layer.id===first});select.disabled=disabled;select.addEventListener("change",()=>{window.caderactLayers.assign(select.value);render()});return select}
  function simplePropertyControl(key,value,disabled){const select=document.createElement("select");if(value===properties.MIXED)option(select,"mixed","Mixed",{selected:true,disabled:true});option(select,"by-layer","ByLayer",{selected:value===null});const values=key==="linetype"?properties.LINETYPES:properties.LINEWEIGHTS;for(const candidate of values)option(select,candidate,key==="linetype"?title(candidate):`${candidate} mm`,{selected:Object.is(value,candidate)});select.disabled=disabled;select.addEventListener("change",()=>edit(selection.selectedIds(),{[key]:select.value==="by-layer"?null:key==="lineweight"?Number(select.value):select.value}));return select}
  function colorControl(value,records,disabled){const wrap=document.createElement("div");wrap.classList.add("property-color-control");const mode=document.createElement("select"),swatch=document.createElement("input");swatch.type="color";const mixed=value===properties.MIXED;option(mode,"mixed","Mixed",{selected:mixed,disabled:true});option(mode,"by-layer","ByLayer",{selected:value===null});option(mode,"explicit","Explicit",{selected:typeof value==="string"});const fallback=records.length?properties.effectiveColor(records[0],session.reader.layer(records[0].layerId)):"#e8edf4";swatch.value=typeof value==="string"?value:fallback;swatch.disabled=disabled||mixed||value===null;mode.disabled=disabled;mode.addEventListener("change",()=>edit(selection.selectedIds(),{color:mode.value==="by-layer"?null:swatch.value}));swatch.addEventListener("change",()=>edit(selection.selectedIds(),{color:swatch.value}));wrap.appendChild(mode);wrap.appendChild(swatch);return wrap}
  function geometryRows(record){if(record.type==="line")return [["Length",number(Math.hypot(record.end.x-record.start.x,record.end.y-record.start.y))]];if(record.type==="circle")return [["Radius",number(record.radius)],["Diameter",number(record.radius*2)]];if(record.type==="arc")return [["Radius",number(record.radius)],["Sweep",`${number(Math.abs(record.sweep)*180/Math.PI)}°`],["Length",number(Math.abs(record.sweep)*record.radius)]];if(record.type==="ellipse")return [["Major radius",number(Math.hypot(record.majorAxis.x,record.majorAxis.y))],["Minor radius",number(record.minorRadius)]];if(record.type==="polyline")return [["Vertices",String(record.vertices.length)],["Status",record.closed?"Closed":"Open"]];return []}
  function render(){
    const records=selectedRecords();if(!records.length){const empty=document.createElement("p");empty.classList.add("properties-empty");empty.textContent="Select drawing objects to view and edit their properties.";content.replaceChildren(empty);return}
    const ids=records.map(record=>record.id),blocked=window.caderactCommandRouter.isActive||records.some(record=>!session.reader.isRecordEditable(record.id)),sameType=records.every(record=>record.type===records[0].type),aggregate=session.reader.aggregateRecordProperties(ids),nodes=[]
    const summary=section("Selection"),typeLabel=sameType?`${title(records[0].type)}${records.length>1?` (${records.length})`:""}`:`Multiple (${records.length})`;summary.appendChild(valueRow("Type",typeLabel));summary.appendChild(valueRow("Count",String(records.length)));nodes.push(summary)
    if(blocked){const note=document.createElement("p");note.classList.add("properties-disabled-note");note.textContent=window.caderactCommandRouter.isActive?"Finish or cancel the active command to edit properties.":"The selection contains locked or hidden objects.";nodes.push(note)}
    const general=section("General");general.appendChild(controlRow("Layer",layerControl(records,blocked)));nodes.push(general)
    const appearance=section("Appearance");appearance.appendChild(controlRow("Color",colorControl(aggregate.color,records,blocked)));appearance.appendChild(controlRow("Linetype",simplePropertyControl("linetype",aggregate.linetype,blocked)));appearance.appendChild(controlRow("Lineweight",simplePropertyControl("lineweight",aggregate.lineweight,blocked)));nodes.push(appearance)
    if(records.length===1){const rows=geometryRows(records[0]);if(rows.length){const geometry=section("Geometry");for(const [label,value] of rows)geometry.appendChild(valueRow(label,value));nodes.push(geometry)}}
    content.replaceChildren(...nodes)
  }
  function bindDocument(){unsubscribeHistory?.();unsubscribeHistory=session.controller.subscribeHistory(render);render()}
  layersTab.addEventListener("click",()=>setPanel("layers"));propertiesTab.addEventListener("click",()=>setPanel("properties"));selection.subscribe(render);session.subscribe(bindDocument);window.caderactCommandRouter.subscribe(render);bindDocument()
  window.caderactPropertiesPanel=Object.freeze({open:()=>setPanel("properties",{focus:true}),showLayers:()=>setPanel("layers",{focus:true}),refresh:render,getState:()=>Object.freeze({activePanel,selectedCount:selectedRecords().length})})
})()
