// SEL1: AF1 command adapters over the shared viewport/SelectionManager authority.
(() => {
  const planner=Object.freeze({plan:()=>Object.freeze({status:"planned"})})
  function geometrySession({name,mode,beginProfessionalSelection,finishProfessionalSelection,cancelProfessionalSelection}){const started=beginProfessionalSelection(mode,{commandOwned:true});return Object.freeze({name,activationOutcome:started.status==="selection-mode-started"?undefined:Object.freeze({status:"invalid-input",command:name,reason:started.status}),finish(){const outcome=finishProfessionalSelection();return outcome.status==="selection-mode-completed"?Object.freeze({status:"command-completed",command:name,recordIds:outcome.selectedIds}):Object.freeze({status:"invalid-input",command:name,reason:outcome.reason||outcome.status,message:"Add more selection points."})},cancel(){cancelProfessionalSelection();return Object.freeze({status:"command-cancelled",command:name})},handlePointerLeave(){},get isSelectionPhase(){return true},get prompt(){return "Specify selection points; Enter to finish"}})}
  function immediateSession(name,outcome){return Object.freeze({name,activationOutcome:Object.freeze({status:"command-completed",command:name,outcome,recordIds:outcome.selectedIds||Object.freeze([])}),finish(){return this.activationOutcome},cancel(){return Object.freeze({status:"command-cancelled",command:name})},get prompt(){return name}})}
  function querySession({name,query}){return Object.freeze({name,finish:()=>Object.freeze({status:"invalid-input",command:name,reason:"query-required",message:`Enter ${name==="SelectByType"?"an entity type":"a layer name"}.`}),cancel:()=>Object.freeze({status:"command-cancelled",command:name}),handleInput(value){const outcome=query(value);return outcome.status==="invalid-selection-query"?Object.freeze({status:"invalid-input",command:name,reason:outcome.reason,message:"No matching layer."}):Object.freeze({status:"command-completed",command:name,outcome,recordIds:outcome.selectedIds})},get isSelectionPhase(){return true},get prompt(){return name==="SelectByType"?"Enter entity type":"Enter layer name"}})}
  function selectionSetSession(services){return Object.freeze({name:"SelectionSet",finish:()=>Object.freeze({status:"invalid-input",command:"SelectionSet",reason:"operation-required",message:"Enter Save, Update, Delete, or Select followed by a set name."}),cancel:()=>Object.freeze({status:"command-cancelled",command:"SelectionSet"}),handleInput(value){const match=String(value||"").trim().match(/^(SAVE|UPDATE|DELETE|SELECT)\s+(.+)$/i);if(!match)return Object.freeze({status:"invalid-input",command:"SelectionSet",reason:"invalid-operation",message:"Use Save, Update, Delete, or Select followed by a set name."});const operation=match[1].toUpperCase(),name=match[2],outcome=operation==="SAVE"?services.saveSelectionSet(name):operation==="UPDATE"?services.saveSelectionSet(name,{update:true}):operation==="DELETE"?services.deleteSelectionSet(name):services.selectSelectionSet(name);if(["invalid-selection-set-name","selection-set-exists","selection-set-missing","empty-selection-set"].includes(outcome.status))return Object.freeze({status:"invalid-input",command:"SelectionSet",reason:outcome.status,message:outcome.status.replaceAll("-"," ")});return Object.freeze({status:"command-completed",command:"SelectionSet",outcome,recordIds:outcome.selectedIds||outcome.recordIds||Object.freeze([])})},get isSelectionPhase(){return true},get prompt(){return "Enter Save, Update, Delete, or Select and a set name"}})}
  function filterSession(services){return Object.freeze({name:"SelectFilter",finish:()=>Object.freeze({status:"invalid-input",command:"SelectFilter",reason:"filter-required",message:"Enter one or more Type, Layer, Color, or Block filters."}),cancel:()=>Object.freeze({status:"command-cancelled",command:"SelectFilter"}),handleInput(value){const criteria={};for(const match of String(value||"").matchAll(/(TYPE|LAYER|COLOR|BLOCK)\s*=\s*("[^"]+"|'[^']+'|[^,;]+?)(?=\s+(?:TYPE|LAYER|COLOR|BLOCK)\s*=|[,;]|$)/gi))criteria[match[1].toLowerCase()]=match[2].trim().replace(/^("|')|("|')$/g,"");if(!Object.keys(criteria).length)return Object.freeze({status:"invalid-input",command:"SelectFilter",reason:"invalid-filter",message:"Use Type=, Layer=, Color=, or Block=."});const outcome=services.selectByFilter(criteria);if(outcome.status==="invalid-selection-query")return Object.freeze({status:"invalid-input",command:"SelectFilter",reason:outcome.reason,message:"Filter value was not found or is invalid."});return Object.freeze({status:"command-completed",command:"SelectFilter",outcome,recordIds:outcome.selectedIds})},get isSelectionPhase(){return true},get prompt(){return "Enter Type=, Layer=, Color=, or Block= filters"}})}
  const registrations=Object.freeze([
    Object.freeze({name:"Fence",aliases:Object.freeze([]),planner,createSession:services=>geometrySession({...services,name:"Fence",mode:"fence"})}),
    Object.freeze({name:"WindowPolygon",aliases:Object.freeze(["WP"]),planner,createSession:services=>geometrySession({...services,name:"WindowPolygon",mode:"window-polygon"})}),
    Object.freeze({name:"CrossingPolygon",aliases:Object.freeze(["CPOLY"]),planner,createSession:services=>geometrySession({...services,name:"CrossingPolygon",mode:"crossing-polygon"})}),
    Object.freeze({name:"SelectSimilar",aliases:Object.freeze([]),planner,createSession:services=>immediateSession("SelectSimilar",services.selectSimilar())}),
    Object.freeze({name:"SelectByType",aliases:Object.freeze(["SELTYPE"]),planner,createSession:services=>querySession({name:"SelectByType",query:services.selectByType})}),
    Object.freeze({name:"SelectByLayer",aliases:Object.freeze(["SELLAYER"]),planner,createSession:services=>querySession({name:"SelectByLayer",query:services.selectByLayer})}),
    Object.freeze({name:"PreviousSelection",aliases:Object.freeze(["PSELECT"]),planner,createSession:services=>immediateSession("PreviousSelection",services.selectPreviousSelection())}),
    Object.freeze({name:"SelectLast",aliases:Object.freeze(["SELLAST"]),planner,createSession:services=>immediateSession("SelectLast",services.selectLastCreated())}),
    Object.freeze({name:"InvertSelection",aliases:Object.freeze(["SELINVERT"]),planner,createSession:services=>immediateSession("InvertSelection",services.invertSelection())}),
    Object.freeze({name:"SelectionSet",aliases:Object.freeze(["SELSET"]),planner,createSession:selectionSetSession}),
    Object.freeze({name:"SelectFilter",aliases:Object.freeze(["SELFILTER"]),planner,createSession:filterSession}),
  ])
  window.CaderactSelectionCommands=Object.freeze({registrations})
})()
