// DUX2: one immediate-apply Drafting Settings surface over UserPreferences/Viewport.
(() => {
  const $=selector=>document.querySelector(selector),all=selector=>Array.from(document.querySelectorAll(selector))
  const panel=$("#settings-panel"),close=$("#settings-close"),reset=$("#settings-reset"),title=$("#settings-title"),subtitle=$("#settings-subtitle"),preferencesTabs=$("#preferences-tabs"),draftingTabs=$("#drafting-settings-tabs"),draftingFooter=$("#drafting-settings-footer"),triggers=[$("#settings-trigger"),$("#preferences-trigger"),$("#drafting-settings-trigger"),...all("[data-open-drafting-settings]")].filter(Boolean)
  const tabs=all("[data-settings-tab]"),pages=all("[data-settings-page]"),preferences=window.caderactUserPreferences,workspacePreferences=window.caderactWorkspacePreferences,viewport=window.caderactViewport
  const controls={uiTheme:$("#settings-ui-theme"),canvasTheme:$("#settings-canvas-theme"),grid:$("#settings-grid-visible"),gridSnap:$("#settings-grid-snap"),color:$("#settings-grid-color"),opacity:$("#settings-grid-opacity"),opacityValue:$("#settings-grid-opacity-value"),majorColor:$("#settings-major-grid-color"),majorOpacity:$("#settings-major-grid-opacity"),majorOpacityValue:$("#settings-major-grid-opacity-value"),interval:$("#settings-major-grid-interval"),xColor:$("#settings-x-axis-color"),xOpacity:$("#settings-x-axis-opacity"),xOpacityValue:$("#settings-x-axis-opacity-value"),yColor:$("#settings-y-axis-color"),yOpacity:$("#settings-y-axis-opacity"),yOpacityValue:$("#settings-y-axis-opacity-value"),polar:$("#settings-polar-enabled"),polarIncrement:$("#settings-polar-increment"),osnap:$("#settings-osnap-enabled"),track:$("#settings-track-enabled"),extension:$("#settings-extension-enabled"),dynamic:$("#settings-dynamic-enabled")}
  const snapModes=all("[data-settings-snap-mode]"),selectAll=$("#settings-osnap-select-all"),clearAll=$("#settings-osnap-clear-all")
  const customSection=$("#settings-custom-canvas"),template=$("#settings-canvas-template"),templateReset=$("#settings-canvas-reset"),contrast=$("#settings-canvas-contrast"),canvasColors=all("[data-canvas-color]")
  const appearanceReset=$("#settings-appearance-reset"),workspaceReset=$("#settings-workspace-reset"),activeCollection=$("#settings-active-collection"),workspacePanels=all("[data-workspace-panel]")
  if(!panel||!close||!reset||!title||!subtitle||!preferencesTabs||!draftingTabs||!draftingFooter||!preferences||!workspacePreferences||!viewport||!triggers.length||!customSection||!template||!templateReset||!contrast||!appearanceReset||!workspaceReset||!activeCollection||Object.values(controls).some(value=>!value))return
  let previousFocus=null,activeSection="appearance",mode="preferences"
  const snapPreference=mode=>`${mode}SnapEnabled`
  const sectionMode=name=>["appearance","workspace","command","cursor"].includes(name)?"preferences":"drafting"
  const modeTabs=()=>tabs.filter(tab=>tab.dataset.settingsGroup===mode)
  function selectSection(name,{focus=false}={}){const available=modeTabs();if(!available.some(tab=>tab.dataset.settingsTab===name))name=mode==="preferences"?"appearance":"grid";activeSection=name;for(const tab of tabs){const selected=tab.dataset.settingsGroup===mode&&tab.dataset.settingsTab===name;tab.setAttribute("aria-selected",String(selected));tab.tabIndex=selected?0:-1;if(selected&&focus)tab.focus()}for(const page of pages)page.hidden=page.dataset.settingsGroup!==mode||page.dataset.settingsPage!==name}
  function render(value=preferences.value){const workspace=workspacePreferences.value;controls.uiTheme.value=workspace.uiTheme;controls.canvasTheme.value=workspace.canvasTheme;customSection.hidden=workspace.canvasTheme!=="custom";template.value=workspace.customCanvasTemplate;for(const input of canvasColors)input.value=workspace.customCanvasColors[input.dataset.canvasColor];contrast.textContent=window.caderactThemes?.contrastWarning(workspace.customCanvasColors)||"";for(const input of workspacePanels){const key=`rightDock${input.dataset.workspacePanel[0].toUpperCase()+input.dataset.workspacePanel.slice(1)}Visible`;input.checked=workspace[key]}activeCollection.value=workspace.activeToolCollection;controls.grid.checked=value.gridVisible;controls.gridSnap.checked=value.gridSnapEnabled;controls.color.value=value.gridColor;controls.opacity.value=Math.round(value.gridOpacity*100);controls.opacityValue.value=`${controls.opacity.value}%`;controls.majorColor.value=value.majorGridColor;controls.majorOpacity.value=Math.round(value.majorGridOpacity*100);controls.majorOpacityValue.value=`${controls.majorOpacity.value}%`;controls.interval.value=String(value.majorGridInterval);controls.xColor.value=value.xAxisColor;controls.xOpacity.value=Math.round(value.xAxisOpacity*100);controls.xOpacityValue.value=`${controls.xOpacity.value}%`;controls.yColor.value=value.yAxisColor;controls.yOpacity.value=Math.round(value.yAxisOpacity*100);controls.yOpacityValue.value=`${controls.yOpacity.value}%`;controls.polar.checked=value.polarEnabled;controls.polarIncrement.value=String(value.polarIncrementDegrees);controls.osnap.checked=value.objectSnapEnabled;controls.track.checked=value.objectSnapTrackingEnabled;controls.extension.checked=value.extensionTrackingEnabled;controls.dynamic.checked=value.dynamicInputEnabled;for(const option of snapModes)option.checked=Boolean(value[snapPreference(option.dataset.settingsSnapMode)])}
  function open(section="appearance",source=document.activeElement){previousFocus=source;mode=sectionMode(section);preferencesTabs.hidden=mode!=="preferences";draftingTabs.hidden=mode!=="drafting";draftingFooter.hidden=mode!=="drafting";title.textContent=mode==="preferences"?"Preferences":"Drafting Settings";subtitle.textContent=mode==="preferences"?"Application and workspace":"Drafting behavior";close.setAttribute("aria-label",`Close ${title.textContent}`);for(const menu of all(".drafting-menu, #snap-menu"))menu.hidden=true;for(const trigger of all(".drafting-flyout-trigger"))trigger.setAttribute("aria-expanded","false");panel.hidden=false;selectSection(section);render();modeTabs().find(tab=>tab.dataset.settingsTab===activeSection)?.focus()}
  function dismiss(){panel.hidden=true;previousFocus?.focus?.()}
  function hiddenByParent(element){for(let node=element;node&&node!==panel;node=node.parentElement)if(node.hidden)return true;return false}
  function focusable(){return all("#settings-panel button, #settings-panel input, #settings-panel select, #settings-panel textarea, #settings-panel [href], #settings-panel [tabindex]").filter(element=>!element.disabled&&!hiddenByParent(element)&&element.tabIndex>=0)}
  for(const trigger of triggers)trigger.addEventListener("click",()=>open(trigger.dataset.openDraftingSettings||"appearance",trigger))
  close.addEventListener("click",dismiss)
  for(const tab of tabs){tab.addEventListener("click",()=>selectSection(tab.dataset.settingsTab));tab.addEventListener("keydown",event=>{if(!["ArrowLeft","ArrowRight","Home","End"].includes(event.key))return;event.preventDefault();const available=modeTabs(),index=available.indexOf(tab),next=event.key==="Home"?0:event.key==="End"?available.length-1:event.key==="ArrowLeft"?(index+available.length-1)%available.length:(index+1)%available.length;selectSection(available[next].dataset.settingsTab,{focus:true})})}
  document.addEventListener("keydown",event=>{if(panel.hidden)return;if(event.key==="Escape"){event.preventDefault();dismiss();return}if(event.key!=="Tab")return;const available=focusable();if(!available.length)return;const first=available[0],last=available.at(-1);if(event.shiftKey&&document.activeElement===first){event.preventDefault();last.focus()}else if(!event.shiftKey&&document.activeElement===last){event.preventDefault();first.focus()}})
  controls.uiTheme.addEventListener("change",()=>workspacePreferences.set({uiTheme:controls.uiTheme.value}))
  controls.canvasTheme.addEventListener("change",()=>workspacePreferences.set({canvasTheme:controls.canvasTheme.value}))
  function applyTemplate(){const name=template.value,colors=window.CaderactWorkspacePreferences.CANVAS_TEMPLATES[name];if(colors)workspacePreferences.set({canvasTheme:"custom",customCanvasTemplate:name,customCanvasColors:colors})}
  template.addEventListener("change",applyTemplate);templateReset.addEventListener("click",applyTemplate)
  for(const input of canvasColors)input.addEventListener("input",()=>workspacePreferences.set({customCanvasColors:{...workspacePreferences.value.customCanvasColors,[input.dataset.canvasColor]:input.value}}))
  appearanceReset.addEventListener("click",()=>{const defaults=window.CaderactWorkspacePreferences.defaults;workspacePreferences.set({uiTheme:defaults.uiTheme,canvasTheme:defaults.canvasTheme,customCanvasTemplate:defaults.customCanvasTemplate,customCanvasColors:defaults.customCanvasColors})})
  for(const input of workspacePanels)input.addEventListener("change",()=>window.caderactPropertiesPanel?.setPanelVisible(input.dataset.workspacePanel,input.checked))
  activeCollection.addEventListener("change",()=>window.caderactApplicationShell?.showCategory?.(activeCollection.value)||workspacePreferences.set({activeToolCollection:activeCollection.value}))
  workspaceReset.addEventListener("click",()=>{const defaults=window.CaderactWorkspacePreferences.defaults;workspacePreferences.set({rightDockWidth:defaults.rightDockWidth,rightDockLayersVisible:defaults.rightDockLayersVisible,rightDockGroupsVisible:defaults.rightDockGroupsVisible,rightDockBlocksVisible:defaults.rightDockBlocksVisible,rightDockPropertiesVisible:defaults.rightDockPropertiesVisible,activeDockPanel:defaults.activeDockPanel,activeToolCollection:defaults.activeToolCollection});window.caderactRightDock?.apply(defaults.rightDockWidth,{persist:false});window.caderactPropertiesPanel?.showLayers?.({focus:false});window.caderactApplicationShell?.showCategory?.(defaults.activeToolCollection)})
  controls.grid.addEventListener("change",()=>preferences.set({gridVisible:controls.grid.checked}))
  controls.gridSnap.addEventListener("change",()=>viewport.setGridSnapEnabled(controls.gridSnap.checked))
  controls.color.addEventListener("change",()=>preferences.set({gridColor:controls.color.value}))
  controls.opacity.addEventListener("input",()=>preferences.set({gridOpacity:Number(controls.opacity.value)/100}))
  controls.majorColor.addEventListener("change",()=>preferences.set({majorGridColor:controls.majorColor.value}))
  controls.majorOpacity.addEventListener("input",()=>preferences.set({majorGridOpacity:Number(controls.majorOpacity.value)/100}))
  controls.interval.addEventListener("change",()=>preferences.set({majorGridInterval:Number(controls.interval.value)}))
  controls.xColor.addEventListener("change",()=>preferences.set({xAxisColor:controls.xColor.value}));controls.xOpacity.addEventListener("input",()=>preferences.set({xAxisOpacity:Number(controls.xOpacity.value)/100}));controls.yColor.addEventListener("change",()=>preferences.set({yAxisColor:controls.yColor.value}));controls.yOpacity.addEventListener("input",()=>preferences.set({yAxisOpacity:Number(controls.yOpacity.value)/100}))
  controls.polar.addEventListener("change",()=>viewport.setPolarEnabled(controls.polar.checked));controls.polarIncrement.addEventListener("change",()=>viewport.setPolarIncrementDegrees(Number(controls.polarIncrement.value)))
  controls.osnap.addEventListener("change",()=>viewport.setObjectSnapMode("object",controls.osnap.checked));for(const option of snapModes)option.addEventListener("change",()=>viewport.setObjectSnapMode(option.dataset.settingsSnapMode,option.checked))
  function setAllSnaps(enabled){for(const option of snapModes)viewport.setObjectSnapMode(option.dataset.settingsSnapMode,enabled)}
  selectAll.addEventListener("click",()=>setAllSnaps(true));clearAll.addEventListener("click",()=>setAllSnaps(false))
  controls.track.addEventListener("change",()=>viewport.setObjectSnapTrackingEnabled(controls.track.checked));controls.extension.addEventListener("change",()=>viewport.setExtensionTrackingEnabled(controls.extension.checked));controls.dynamic.addEventListener("change",()=>viewport.setDynamicInputEnabled(controls.dynamic.checked))
  reset.addEventListener("click",()=>{const value=preferences.reset();viewport.setGridSnapEnabled(value.gridSnapEnabled);viewport.setOrthoEnabled(value.orthoEnabled);viewport.setPolarEnabled(value.polarEnabled);viewport.setPolarIncrementDegrees(value.polarIncrementDegrees);viewport.setObjectSnapTrackingEnabled(value.objectSnapTrackingEnabled);viewport.setExtensionTrackingEnabled(value.extensionTrackingEnabled);viewport.setDynamicInputEnabled(value.dynamicInputEnabled);viewport.setObjectSnapMode("object",value.objectSnapEnabled);for(const option of snapModes)viewport.setObjectSnapMode(option.dataset.settingsSnapMode,value[snapPreference(option.dataset.settingsSnapMode)]);render(value)})
  preferences.subscribe(render);workspacePreferences.subscribe(()=>render());selectSection("appearance")
  window.caderactDraftingSettings=Object.freeze({open,dismiss,selectSection,getState:()=>Object.freeze({open:!panel.hidden,activeSection})})
})()
