// DUX2: one immediate-apply Drafting Settings surface over UserPreferences/Viewport.
(() => {
  const $=selector=>document.querySelector(selector),all=selector=>Array.from(document.querySelectorAll(selector))
  const panel=$("#settings-panel"),close=$("#settings-close"),reset=$("#settings-reset"),triggers=[$("#settings-trigger"),$("#preferences-trigger"),$("#drafting-settings-trigger"),...all("[data-open-drafting-settings]")].filter(Boolean)
  const tabs=all("[data-settings-tab]"),pages=all("[data-settings-page]"),preferences=window.caderactUserPreferences,workspacePreferences=window.caderactWorkspacePreferences,viewport=window.caderactViewport
  const controls={uiTheme:$("#settings-ui-theme"),canvasTheme:$("#settings-canvas-theme"),grid:$("#settings-grid-visible"),gridSnap:$("#settings-grid-snap"),color:$("#settings-grid-color"),opacity:$("#settings-grid-opacity"),opacityValue:$("#settings-grid-opacity-value"),majorColor:$("#settings-major-grid-color"),majorOpacity:$("#settings-major-grid-opacity"),majorOpacityValue:$("#settings-major-grid-opacity-value"),interval:$("#settings-major-grid-interval"),xColor:$("#settings-x-axis-color"),xOpacity:$("#settings-x-axis-opacity"),xOpacityValue:$("#settings-x-axis-opacity-value"),yColor:$("#settings-y-axis-color"),yOpacity:$("#settings-y-axis-opacity"),yOpacityValue:$("#settings-y-axis-opacity-value"),polar:$("#settings-polar-enabled"),polarIncrement:$("#settings-polar-increment"),osnap:$("#settings-osnap-enabled"),track:$("#settings-track-enabled"),extension:$("#settings-extension-enabled"),dynamic:$("#settings-dynamic-enabled")}
  const snapModes=all("[data-settings-snap-mode]"),selectAll=$("#settings-osnap-select-all"),clearAll=$("#settings-osnap-clear-all")
  if(!panel||!close||!reset||!preferences||!workspacePreferences||!viewport||!triggers.length||Object.values(controls).some(value=>!value))return
  let previousFocus=null,activeSection="appearance"
  const snapPreference=mode=>`${mode}SnapEnabled`
  function selectSection(name,{focus=false}={}){if(!tabs.some(tab=>tab.dataset.settingsTab===name))name="appearance";activeSection=name;for(const tab of tabs){const selected=tab.dataset.settingsTab===name;tab.setAttribute("aria-selected",String(selected));tab.tabIndex=selected?0:-1;if(selected&&focus)tab.focus()}for(const page of pages)page.hidden=page.dataset.settingsPage!==name}
  function render(value=preferences.value){controls.uiTheme.value=workspacePreferences.value.uiTheme;controls.canvasTheme.value=workspacePreferences.value.canvasTheme;controls.grid.checked=value.gridVisible;controls.gridSnap.checked=value.gridSnapEnabled;controls.color.value=value.gridColor;controls.opacity.value=Math.round(value.gridOpacity*100);controls.opacityValue.value=`${controls.opacity.value}%`;controls.majorColor.value=value.majorGridColor;controls.majorOpacity.value=Math.round(value.majorGridOpacity*100);controls.majorOpacityValue.value=`${controls.majorOpacity.value}%`;controls.interval.value=String(value.majorGridInterval);controls.xColor.value=value.xAxisColor;controls.xOpacity.value=Math.round(value.xAxisOpacity*100);controls.xOpacityValue.value=`${controls.xOpacity.value}%`;controls.yColor.value=value.yAxisColor;controls.yOpacity.value=Math.round(value.yAxisOpacity*100);controls.yOpacityValue.value=`${controls.yOpacity.value}%`;controls.polar.checked=value.polarEnabled;controls.polarIncrement.value=String(value.polarIncrementDegrees);controls.osnap.checked=value.objectSnapEnabled;controls.track.checked=value.objectSnapTrackingEnabled;controls.extension.checked=value.extensionTrackingEnabled;controls.dynamic.checked=value.dynamicInputEnabled;for(const option of snapModes)option.checked=Boolean(value[snapPreference(option.dataset.settingsSnapMode)])}
  function open(section="appearance",source=document.activeElement){previousFocus=source;for(const menu of all(".drafting-menu, #snap-menu"))menu.hidden=true;for(const trigger of all(".drafting-flyout-trigger"))trigger.setAttribute("aria-expanded","false");panel.hidden=false;selectSection(section);render();tabs.find(tab=>tab.dataset.settingsTab===activeSection)?.focus()}
  function dismiss(){panel.hidden=true;previousFocus?.focus?.()}
  for(const trigger of triggers)trigger.addEventListener("click",()=>open(trigger.dataset.openDraftingSettings||"appearance",trigger))
  close.addEventListener("click",dismiss)
  for(const tab of tabs){tab.addEventListener("click",()=>selectSection(tab.dataset.settingsTab));tab.addEventListener("keydown",event=>{if(!["ArrowLeft","ArrowRight","Home","End"].includes(event.key))return;event.preventDefault();const index=tabs.indexOf(tab),next=event.key==="Home"?0:event.key==="End"?tabs.length-1:event.key==="ArrowLeft"?(index+tabs.length-1)%tabs.length:(index+1)%tabs.length;selectSection(tabs[next].dataset.settingsTab,{focus:true})})}
  document.addEventListener("keydown",event=>{if(event.key==="Escape"&&!panel.hidden){event.preventDefault();dismiss()}})
  controls.uiTheme.addEventListener("change",()=>workspacePreferences.set({uiTheme:controls.uiTheme.value}))
  controls.canvasTheme.addEventListener("change",()=>workspacePreferences.set({canvasTheme:controls.canvasTheme.value}))
  controls.grid.addEventListener("change",()=>preferences.set({gridVisible:controls.grid.checked}))
  controls.gridSnap.addEventListener("change",()=>viewport.setGridSnapEnabled(controls.gridSnap.checked))
  controls.color.addEventListener("change",()=>preferences.set({gridColor:controls.color.value}))
  controls.opacity.addEventListener("input",()=>preferences.set({gridOpacity:Number(controls.opacity.value)/100}))
  controls.majorColor.addEventListener("change",()=>preferences.set({majorGridColor:controls.majorColor.value}))
  controls.majorOpacity.addEventListener("input",()=>preferences.set({majorGridOpacity:Number(controls.majorOpacity.value)/100}))
  controls.interval.addEventListener("change",()=>preferences.set({majorGridInterval:Number(controls.interval.value)}))
  controls.xColor.addEventListener("change",()=>preferences.set({xAxisColor:controls.xColor.value}));controls.xOpacity.addEventListener("input",()=>preferences.set({xAxisOpacity:Number(controls.xOpacity.value)/100}));controls.yColor.addEventListener("change",()=>preferences.set({yAxisColor:controls.yColor.value}));controls.yOpacity.addEventListener("input",()=>preferences.set({yAxisOpacity:Number(controls.yOpacity.value)/100}))
  controls.polar.addEventListener("change",()=>viewport.setPolarEnabled(controls.polar.checked));controls.polarIncrement.addEventListener("change",()=>viewport.setPolarIncrementDegrees(Number(controls.polarIncrement.value)))
  controls.osnap.addEventListener("change",()=>viewport.setObjectSnapMode("object",controls.osnap.checked));for(const option of snapModes)option.addEventListener("change",()=>viewport.setObjectSnapMode(option.dataset.settingsSnapMode,option.checked))
  function setAllSnaps(enabled){for(const option of snapModes)viewport.setObjectSnapMode(option.dataset.settingsSnapMode,enabled)}
  selectAll.addEventListener("click",()=>setAllSnaps(true));clearAll.addEventListener("click",()=>setAllSnaps(false))
  controls.track.addEventListener("change",()=>viewport.setObjectSnapTrackingEnabled(controls.track.checked));controls.extension.addEventListener("change",()=>viewport.setExtensionTrackingEnabled(controls.extension.checked));controls.dynamic.addEventListener("change",()=>viewport.setDynamicInputEnabled(controls.dynamic.checked))
  reset.addEventListener("click",()=>{const value=preferences.reset();viewport.setGridSnapEnabled(value.gridSnapEnabled);viewport.setOrthoEnabled(value.orthoEnabled);viewport.setPolarEnabled(value.polarEnabled);viewport.setPolarIncrementDegrees(value.polarIncrementDegrees);viewport.setObjectSnapTrackingEnabled(value.objectSnapTrackingEnabled);viewport.setExtensionTrackingEnabled(value.extensionTrackingEnabled);viewport.setDynamicInputEnabled(value.dynamicInputEnabled);viewport.setObjectSnapMode("object",value.objectSnapEnabled);for(const option of snapModes)viewport.setObjectSnapMode(option.dataset.settingsSnapMode,value[snapPreference(option.dataset.settingsSnapMode)]);render(value)})
  preferences.subscribe(render);workspacePreferences.subscribe(()=>render());selectSection("appearance")
  window.caderactDraftingSettings=Object.freeze({open,dismiss,selectSection,getState:()=>Object.freeze({open:!panel.hidden,activeSection})})
})()
