// WS3: persistent application-workspace layout state, separate from drawings and drafting preferences.
(() => {
  const KEY="caderact:workspace-preferences",VERSION=1,LEGACY_KEY="caderact:user-preferences"
  const PANELS=Object.freeze(["layers","groups","blocks","properties"]),COLLECTIONS=Object.freeze(["Draw","Modify","Annotate","Layers","Blocks","Measure","Drafting","Custom"])
  const CANVAS_TEMPLATES=Object.freeze({
    "classic-dark":Object.freeze({background:"#182633",gridMinor:"#a7afbb",gridMajor:"#a7afbb",axisX:"#984b51",axisY:"#3b7658",geometry:"#e8edf4",selection:"#63b7e6",grip:"#e8edf4",gripHover:"#f2cf72",osnap:"#f2cf72",tracking:"#6fbed2",crosshair:"#e8edf4",dynamicSurface:"#10202e",dynamicText:"#dce5ee"}),
    "technical-light":Object.freeze({background:"#f4f6f7",gridMinor:"#9aa6b2",gridMajor:"#697887",axisX:"#a2474e",axisY:"#32704f",geometry:"#263442",selection:"#0878bb",grip:"#263442",gripHover:"#9a5c00",osnap:"#9a5c00",tracking:"#007e99",crosshair:"#263442",dynamicSurface:"#f8fafc",dynamicText:"#24313e"}),
    blueprint:Object.freeze({background:"#12395a",gridMinor:"#315b78",gridMajor:"#5d87a2",axisX:"#ef8b8f",axisY:"#77c89e",geometry:"#f1f5f7",selection:"#61d5ff",grip:"#f1f5f7",gripHover:"#ffd166",osnap:"#ffd166",tracking:"#7de3ec",crosshair:"#f1f5f7",dynamicSurface:"#0c2d49",dynamicText:"#f1f5f7"}),
    "high-contrast":Object.freeze({background:"#000000",gridMinor:"#303030",gridMajor:"#666666",axisX:"#ff5555",axisY:"#55ff88",geometry:"#ffffff",selection:"#00c8ff",grip:"#ffffff",gripHover:"#ffff00",osnap:"#ffff00",tracking:"#ff66ff",crosshair:"#ffffff",dynamicSurface:"#000000",dynamicText:"#ffffff"}),
  })
  const COLOR_KEYS=Object.freeze(Object.keys(CANVAS_TEMPLATES["classic-dark"]))
  const defaults=Object.freeze({rightDockWidth:288,rightDockLayersVisible:true,rightDockGroupsVisible:true,rightDockBlocksVisible:true,rightDockPropertiesVisible:true,activeDockPanel:"layers",activeToolCollection:"Draw",uiTheme:"dark",canvasTheme:"dark",customCanvasTemplate:"classic-dark",customCanvasColors:CANVAS_TEMPLATES["classic-dark"],customCanvasPresentation:null})
  const visibilityKeys=Object.freeze(["rightDockLayersVisible","rightDockGroupsVisible","rightDockBlocksVisible","rightDockPropertiesVisible"])
  function normalizeColors(input,fallback){const source=input&&typeof input==="object"?input:{};return Object.freeze(Object.fromEntries(COLOR_KEYS.map(key=>[key,/^#[0-9a-f]{6}$/i.test(source[key])?source[key].toLowerCase():fallback[key]])))}
  function normalize(input={}){const next={...defaults};for(const key of Object.keys(defaults))if(key in input)next[key]=input[key];next.rightDockWidth=Number.isFinite(next.rightDockWidth)?Math.max(230,Math.min(960,Math.round(next.rightDockWidth))):defaults.rightDockWidth;for(const key of visibilityKeys)if(typeof next[key]!=="boolean")next[key]=defaults[key];if(!PANELS.includes(next.activeDockPanel))next.activeDockPanel=defaults.activeDockPanel;if(!COLLECTIONS.includes(next.activeToolCollection))next.activeToolCollection=defaults.activeToolCollection;if(!["light","dark"].includes(next.uiTheme))next.uiTheme=defaults.uiTheme;if(!["light","dark","custom"].includes(next.canvasTheme))next.canvasTheme=defaults.canvasTheme;if(!Object.hasOwn(CANVAS_TEMPLATES,next.customCanvasTemplate))next.customCanvasTemplate=defaults.customCanvasTemplate;next.customCanvasColors=normalizeColors(next.customCanvasColors,CANVAS_TEMPLATES[next.customCanvasTemplate]);next.customCanvasPresentation=window.CaderactCanvasAppearance.normalize(next.customCanvasPresentation);return Object.freeze(next)}
  function legacyPreferences(storage){try{const raw=storage?.getItem(LEGACY_KEY);if(!raw)return null;const payload=JSON.parse(raw),source=payload?.preferences;if(!source||typeof source!=="object")return null;return Object.fromEntries(Object.keys(defaults).filter(key=>key in source).map(key=>[key,source[key]]))}catch{return null}}
  function sameValue(a,b){return Object.keys(defaults).every(key=>key==="customCanvasPresentation"?JSON.stringify(a[key])===JSON.stringify(b[key]):key==="customCanvasColors"?COLOR_KEYS.every(color=>a[key][color]===b[key][color]):Object.is(a[key],b[key]))}
  function create({storage=window.localStorage}={}){let value=normalize(),loaded=false,migrated=false;const listeners=new Set();try{const raw=storage?.getItem(KEY);if(raw){const payload=JSON.parse(raw);if(payload?.version===VERSION){value=normalize(payload.preferences);loaded=true}}}catch{}if(!loaded){const legacy=legacyPreferences(storage);if(legacy){value=normalize(legacy);migrated=true}}function save(){try{storage?.setItem(KEY,JSON.stringify({version:VERSION,preferences:value}))}catch{}}if(migrated)save();function set(patch){const next=normalize({...value,...patch});if(sameValue(next,value))return value;value=next;save();for(const listener of listeners)listener(value);return value}return Object.freeze({defaults,get value(){return value},set,reset:()=>set(defaults),subscribe(listener){listeners.add(listener);listener(value);return()=>listeners.delete(listener)}})}
  window.CaderactWorkspacePreferences=Object.freeze({KEY,VERSION,PANELS,COLLECTIONS,CANVAS_TEMPLATES,COLOR_KEYS,defaults,normalize,create})
  window.caderactWorkspacePreferences=create()
})()
