// WS3: persistent application-workspace layout state, separate from drawings and drafting preferences.
(() => {
  const KEY="caderact:workspace-preferences",VERSION=1,LEGACY_KEY="caderact:user-preferences"
  const PANELS=Object.freeze(["layers","groups","blocks","properties"]),COLLECTIONS=Object.freeze(["Draw","Modify","Annotate","Layers","Blocks","Measure","Drafting","Custom"])
  const defaults=Object.freeze({rightDockWidth:288,rightDockLayersVisible:true,rightDockGroupsVisible:true,rightDockBlocksVisible:true,rightDockPropertiesVisible:true,activeDockPanel:"layers",activeToolCollection:"Draw",uiTheme:"light",canvasTheme:"dark"})
  const visibilityKeys=Object.freeze(["rightDockLayersVisible","rightDockGroupsVisible","rightDockBlocksVisible","rightDockPropertiesVisible"])
  function normalize(input={}){const next={...defaults};for(const key of Object.keys(defaults))if(key in input)next[key]=input[key];next.rightDockWidth=Number.isFinite(next.rightDockWidth)?Math.max(230,Math.min(960,Math.round(next.rightDockWidth))):defaults.rightDockWidth;for(const key of visibilityKeys)if(typeof next[key]!=="boolean")next[key]=defaults[key];if(!PANELS.includes(next.activeDockPanel))next.activeDockPanel=defaults.activeDockPanel;if(!COLLECTIONS.includes(next.activeToolCollection))next.activeToolCollection=defaults.activeToolCollection;for(const key of ["uiTheme","canvasTheme"])if(!["light","dark"].includes(next[key]))next[key]=defaults[key];return Object.freeze(next)}
  function legacyPreferences(storage){try{const raw=storage?.getItem(LEGACY_KEY);if(!raw)return null;const payload=JSON.parse(raw),source=payload?.preferences;if(!source||typeof source!=="object")return null;return Object.fromEntries(Object.keys(defaults).filter(key=>key in source).map(key=>[key,source[key]]))}catch{return null}}
  function create({storage=window.localStorage}={}){let value=normalize(),loaded=false,migrated=false;const listeners=new Set();try{const raw=storage?.getItem(KEY);if(raw){const payload=JSON.parse(raw);if(payload?.version===VERSION){value=normalize(payload.preferences);loaded=true}}}catch{}if(!loaded){const legacy=legacyPreferences(storage);if(legacy){value=normalize(legacy);migrated=true}}function save(){try{storage?.setItem(KEY,JSON.stringify({version:VERSION,preferences:value}))}catch{}}if(migrated)save();function set(patch){const next=normalize({...value,...patch});if(Object.keys(defaults).every(key=>Object.is(next[key],value[key])))return value;value=next;save();for(const listener of listeners)listener(value);return value}return Object.freeze({defaults,get value(){return value},set,reset:()=>set(defaults),subscribe(listener){listeners.add(listener);listener(value);return()=>listeners.delete(listener)}})}
  window.CaderactWorkspacePreferences=Object.freeze({KEY,VERSION,PANELS,COLLECTIONS,defaults,normalize,create})
  window.caderactWorkspacePreferences=create()
})()
