const test=require('node:test'),assert=require('node:assert/strict'),{browser}=require('../helpers/browser.cjs')

const ids=b=>b.read('window.caderactSelection.selectedIds()')
function seed(b){b.run(`window.__a=recordGateway.createLine({x:0,y:0},{x:1,y:0});window.__b=recordGateway.createCircle({x:4,y:0},1);window.__c=recordGateway.createLine({x:0,y:3},{x:1,y:3});recordGateway.createAll([window.__a,window.__b,window.__c])`)}

test('SEL2 Previous restores the prior meaningful selection without document mutation',async()=>{const b=await browser();seed(b);const before=b.read('({revision:documentController.currentRevision,history:documentController.historyInfo,dirty:documentController.isDirty})');b.run('window.caderactSelection.selectOnly(window.__a.id);window.caderactSelection.selectOnly(window.__b.id)');assert.deepEqual(ids(b),b.read('[window.__b.id]'));assert.equal(b.read('window.caderactViewport.selectPreviousSelection().status'),'previous-selection-restored');assert.deepEqual(ids(b),b.read('[window.__a.id]'));assert.deepEqual(b.read('({revision:documentController.currentRevision,history:documentController.historyInfo,dirty:documentController.isDirty})'),before)})

test('SEL2 Previous survives command cancellation and respects current selectable records',async()=>{const b=await browser();seed(b);b.run('window.caderactSelection.selectOnly(window.__a.id);window.caderactSelection.clear()');b.launch('Line');b.key('Escape');assert.equal(b.read('window.caderactViewport.selectPreviousSelection().status'),'previous-selection-restored');assert.deepEqual(ids(b),b.read('[window.__a.id]'));b.run(`layerGateway.create('Locked');window.__locked=modelReader.layers().find(x=>x.name==='Locked');recordGateway.assignLayer([window.__a.id],window.__locked.id);layerGateway.setLocked(window.__locked.id,true);window.caderactSelection.clear()`);assert.equal(b.read('window.caderactViewport.selectPreviousSelection().status'),'previous-selection-unavailable')})

test('SEL2 Last follows creation Undo Redo and deletion deterministically',async()=>{const b=await browser();b.run(`window.__a=recordGateway.createLine({x:0,y:0},{x:1,y:0});recordGateway.createAll([window.__a]);window.__b=recordGateway.createCircle({x:4,y:0},1);recordGateway.createAll([window.__b])`);b.run('window.caderactViewport.selectLastCreated()');assert.deepEqual(ids(b),b.read('[window.__b.id]'));b.run('documentController.undo();window.caderactViewport.selectLastCreated()');assert.deepEqual(ids(b),b.read('[window.__a.id]'));b.run('documentController.redo();window.caderactViewport.selectLastCreated()');assert.deepEqual(ids(b),b.read('[window.__b.id]'));b.run('recordGateway.removeAll([window.__b.id]);window.caderactViewport.selectLastCreated()');assert.deepEqual(ids(b),b.read('[window.__a.id]'))})

test('SEL2 Invert respects hidden locked isolation Groups and Block Instances',async()=>{const b=await browser();b.run(`layerGateway.create('A');layerGateway.create('Hidden');layerGateway.create('Locked');window.__la=modelReader.layers().find(x=>x.name==='A');window.__lh=modelReader.layers().find(x=>x.name==='Hidden');window.__ll=modelReader.layers().find(x=>x.name==='Locked');window.__a=recordGateway.createLine({x:0,y:0},{x:1,y:0});window.__b=recordGateway.createLine({x:0,y:1},{x:1,y:1});window.__hidden=recordGateway.createCircle({x:4,y:0},1);window.__locked=recordGateway.createCircle({x:8,y:0},1);recordGateway.createAll([window.__a,window.__b,window.__hidden,window.__locked]);recordGateway.assignLayer([window.__a.id,window.__b.id],window.__la.id);recordGateway.assignLayer([window.__hidden.id],window.__lh.id);recordGateway.assignLayer([window.__locked.id],window.__ll.id);layerGateway.setVisibility(window.__lh.id,false);layerGateway.setLocked(window.__ll.id,true);window.__group=groupGateway.createGroup([window.__a.id,window.__b.id]);window.__member=recordGateway.createLine({x:0,y:0},{x:2,y:0});window.__definition=blockDefinitionGateway.create({name:'Part',records:[window.__member]}).definition;window.__instance=recordGateway.createBlockInstance({definitionId:window.__definition.id,insertionPoint:{x:10,y:0}});recordGateway.createAll([window.__instance]);window.caderactSelection.selectOnly(window.__a.id);window.caderactViewport.invertSelection()`);assert.deepEqual(ids(b),b.read('[window.__instance.id]'));b.run('window.caderactViewport.setLayerIsolation(window.__la.id);window.caderactViewport.invertSelection()');assert.deepEqual(ids(b).sort(),b.read('[window.__a.id,window.__b.id].sort()'))})

test('SEL2 named Selection Sets are session-owned, updateable, and tolerate missing members',async()=>{const b=await browser();seed(b);const before=b.read('({revision:documentController.currentRevision,history:documentController.historyInfo,dirty:documentController.isDirty})');b.run(`window.caderactSelection.applyRecordIds([window.__a.id,window.__b.id]);window.__created=window.caderactViewport.saveSelectionSet('Primary')`);assert.equal(b.read('window.__created.status'),'selection-set-created');b.run('window.caderactSelection.selectOnly(window.__c.id);window.caderactViewport.saveSelectionSet("Primary",{update:true});window.caderactSelection.clear();window.caderactViewport.selectSelectionSet("Primary")');assert.deepEqual(ids(b),b.read('[window.__c.id]'));assert.deepEqual(b.read('({revision:documentController.currentRevision,history:documentController.historyInfo,dirty:documentController.isDirty})'),before);b.run('recordGateway.removeAll([window.__c.id]);window.caderactSelection.clear()');assert.equal(b.read('window.caderactViewport.selectSelectionSet("Primary").status'),'selection-set-empty');assert.equal(b.read('window.caderactViewport.deleteSelectionSet("Primary").status'),'selection-set-deleted');assert.deepEqual(b.read('window.caderactViewport.listSelectionSets()'),[]);b.run('window.caderactSelection.selectOnly(window.__a.id);window.caderactViewport.saveSelectionSet("Transient")');b.run('window.caderactDocumentSession.replaceStore(window.CaderactDocument.createStore())');assert.deepEqual(b.read('window.caderactViewport.listSelectionSets()'),[])})

test('SEL2 combined filters support Type Layer color semantics and Block definition',async()=>{const b=await browser();b.run(`layerGateway.create('A');window.__layer=modelReader.layers().find(x=>x.name==='A');window.__red=recordGateway.createLine({x:0,y:0},{x:1,y:0});window.__by=recordGateway.createLine({x:0,y:1},{x:1,y:1});window.__circle=recordGateway.createCircle({x:4,y:0},1);recordGateway.createAll([{...window.__red,color:'#ff0000'},window.__by,window.__circle]);recordGateway.assignLayer([window.__red.id,window.__by.id],window.__layer.id);window.__member=recordGateway.createLine({x:0,y:0},{x:1,y:0});window.__door=blockDefinitionGateway.create({name:'Door',records:[window.__member]}).definition;window.__instance=recordGateway.createBlockInstance({definitionId:window.__door.id,insertionPoint:{x:10,y:0}});recordGateway.createAll([window.__instance])`);b.run(`window.caderactViewport.selectByFilter({type:'line',layer:'A',color:'#ff0000'})`);assert.deepEqual(ids(b),b.read('[window.__red.id]'));b.run(`window.caderactViewport.selectByFilter({type:'line',layer:'A',color:'ByLayer'})`);assert.deepEqual(ids(b),b.read('[window.__by.id]'));b.run(`window.caderactViewport.selectByFilter({block:'Door'})`);assert.deepEqual(ids(b),b.read('[window.__instance.id]'))})

test('SEL2 command surface and cycling labels expose truthful context',async()=>{const b=await browser();seed(b);assert.deepEqual(b.read(`['PreviousSelection','SelectLast','InvertSelection','SelectionSet','SelectFilter'].map(name=>window.caderactCommandRegistry.resolve(name)?.name)`),['PreviousSelection','SelectLast','InvertSelection','SelectionSet','SelectFilter']);b.run('window.caderactSelection.selectOnly(window.__a.id);window.caderactSelection.clear()');b.launch('PreviousSelection');assert.deepEqual(ids(b),b.read('[window.__a.id]'));b.resize(800,600);b.run(`window.__overlap=recordGateway.createLine({x:0,y:0},{x:1,y:0});recordGateway.createAll([window.__overlap]);window.caderactSelection.clear()`);b.point(402,300);const state=b.read('window.caderactViewport.getSelectionCycleState()');assert.match(state.activeLabel,/Line/);assert.match(state.activeLabel,/Default/);assert.equal(state.candidates.length,2)})

test('SEL2 large Invert remains one linear editor-state operation',async()=>{const b=await browser();b.run(`const records=[];for(let i=0;i<5000;i++)records.push(recordGateway.createLine({x:i,y:0},{x:i,y:1}));recordGateway.createAll(records);documentController.markStateSaved(documentController.captureStateToken());window.__before={revision:documentController.currentRevision,history:documentController.historyInfo,dirty:documentController.isDirty};window.__out=window.caderactViewport.invertSelection()`);assert.equal(b.read('window.__out.selectedIds.length'),5000);assert.deepEqual(b.read('({revision:documentController.currentRevision,history:documentController.historyInfo,dirty:documentController.isDirty})'),b.read('window.__before'))})
