'use strict';
const {test}=require('node:test');const assert=require('node:assert/strict');const {browser}=require('../helpers/browser.cjs');
function seed(b){b.run(`window.__line=recordGateway.createLine({x:0,y:0},{x:10,y:0});window.__circle=recordGateway.createCircle({x:5,y:5},2);window.__definition=blockDefinitionGateway.create({name:'Interactive',records:[window.__line,window.__circle]}).definition;window.__instance=recordGateway.createBlockInstance({definitionId:window.__definition.id,insertionPoint:{x:20,y:10},rotation:0,scale:1,mirrored:false});recordGateway.createAll([window.__instance])`);return b.read('window.__instance')}

test('GB8 outer Block selection and insertion grip preserve model identity',async()=>{const b=await browser(),instance=seed(b);b.point(500,250);assert.deepEqual(b.read('window.caderactSelection.selectedIds()'),[instance.id]);const grips=b.read('window.caderactGrips.grips()');assert.deepEqual(grips.map(g=>g.kind),['insertionPoint']);assert.equal(grips[0].featureId,instance.insertionPoint.featureId);b.run(`window.__replacement=window.CaderactGrips.blockAdapter.replacement(window.__instance,window.caderactGrips.grips()[0],{x:30,y:15})`);assert.equal(b.read('window.__replacement.id'),instance.id);assert.equal(b.read('window.__replacement.insertionPoint.featureId'),instance.insertionPoint.featureId);assert.equal(b.read('window.__replacement.definitionId'),instance.definitionId)});

test('GB8 Block members contribute path-qualified native snaps and intersections',async()=>{const b=await browser(),instance=seed(b);b.run(`recordGateway.createAll([recordGateway.createLine({x:20,y:5},{x:20,y:15})])`);b.launch('Line');b.point(500,250,'pointermove');const snap=b.read('activeSnapResult');assert.equal(snap.kind,'endpoint');assert.deepEqual(snap.point,{x:20,y:10});assert.ok((snap.reference?.recordId||snap.sourceReference?.recordId).includes(instance.id));b.point(525,250,'pointermove');assert.ok(['midpoint','nearest','intersection'].includes(b.read('activeSnapResult.kind')))});

test('GB8 repeated instances have independent runtime identities and no persistence leakage',async()=>{const b=await browser();seed(b);b.run(`window.__copy=recordGateway.copyWithFreshIdentity(window.CaderactGeometryTransform.translateRecord(window.__instance,40,0));recordGateway.createAll([window.__copy])`);b.launch('Line');b.point(500,250,'pointermove');const first=b.read('activeSnapResult.reference?.recordId||activeSnapResult.sourceReference?.recordId');b.point(700,250,'pointermove');const second=b.read('activeSnapResult.reference?.recordId||activeSnapResult.sourceReference?.recordId');assert.notEqual(first,second);assert.equal(b.run('window.CaderactPersistence.serializeDocument(modelReader.snapshot()).includes("runtimeReference")'),false)});

test('GB8 SelectionBox aggregates expanded members for Window and Crossing',async()=>{const b=await browser();seed(b);const world=(x,y)=>b.read(`window.caderactViewport.getRendererState&&null`)||{x,y};b.run(`window.__proxy=[{id:'outer',type:'line',start:{x:0,y:0},end:{x:1,y:0}},{id:'outer',type:'line',start:{x:10,y:0},end:{x:11,y:0}}];window.__identity=(x,y)=>({x,y})`);assert.deepEqual(b.read(`window.CaderactSelectionBox.query({start:{x:-1,y:-1},current:{x:2,y:1},records:window.__proxy,worldToScreen:window.__identity}).recordIds`),[]);assert.deepEqual(b.read(`window.CaderactSelectionBox.query({start:{x:2,y:1},current:{x:-1,y:-1},records:window.__proxy,worldToScreen:window.__identity}).recordIds`),['outer'])});


