'use strict';
const test=require('node:test');const assert=require('node:assert/strict');const {browser}=require('../helpers/browser.cjs');
const typed=(b,value)=>{b.input.value=value;b.emit(b.input,'input');b.key('Enter',b.input)};
function beginParallel(b,y){b.launch('Line');typed(b,`-20,${y}`);typed(b,`-10,${y}`);b.point(700,300-y*5,'pointermove');b.flush();assert.equal(b.read('activeSnapResult.kind'),'tracking');assert.deepEqual(b.read('activeSnapResult.relationships'),['tracking','parallel'])}
function snapState(b){return b.read(`({kind:activeSnapResult.kind,kinds:activeSnapResult.kinds,point:activeSnapResult.point,relationships:activeSnapResult.relationships,hud:window.caderactViewport.getDynamicInputState().tags})`)}

test('Mid and End immediately replace active Parallel tracking, including marker HUD and click',async()=>{const b=await browser();b.resize(800,600);b.flush();b.run(`window.caderactViewport.setGridSnapEnabled(false);window.caderactViewport.setObjectSnapMode('nearest',true);recordGateway.createAll([recordGateway.createLine({x:0,y:0},{x:10,y:0})])`);beginParallel(b,0);b.point(425,300,'pointermove');b.flush();assert.deepEqual(snapState(b),{kind:'midpoint',kinds:['midpoint'],point:{x:5,y:0},relationships:[],hud:['Mid']});assert.ok(b.renders.at(-1).snapOverlay);b.point(425,300);assert.ok(b.read(`modelReader.records().some(record=>record.type==='line'&&record.end.x===5&&record.end.y===0)`));b.launch('Line');b.point(450,300,'pointermove');assert.equal(b.read('activeSnapResult.kind'),'endpoint')});

test('Cen beats Near and tracking while the custom cursor remains raw',async()=>{const b=await browser();b.resize(800,600);b.flush();b.run(`window.caderactViewport.setGridSnapEnabled(false);window.caderactViewport.setObjectSnapMode('nearest',true);recordGateway.createAll([recordGateway.createCircle({x:20,y:20},5)])`);beginParallel(b,20);b.point(501,200,'pointermove');b.flush();const state=snapState(b);assert.equal(state.kind,'center');assert.deepEqual(state.point,{x:20,y:20});assert.deepEqual(state.relationships,[]);assert.deepEqual(state.hud,['Cen']);assert.deepEqual(b.read('(({x,y})=>({x,y}))(window.caderactViewport.getInteractionVisualState())'),{x:511,y:210})});

test('Int beats Near and Parallel tracking at exact committed intersection',async()=>{const b=await browser();b.resize(800,600);b.flush();b.run(`window.caderactViewport.setGridSnapEnabled(false);window.caderactViewport.setObjectSnapMode('nearest',true);recordGateway.createAll([recordGateway.createLine({x:0,y:10},{x:10,y:10}),recordGateway.createLine({x:5,y:5},{x:5,y:15})])`);beginParallel(b,10);b.point(425,250,'pointermove');b.flush();const state=snapState(b);assert.equal(state.kind,'intersection');assert.deepEqual(state.point,{x:5,y:10});assert.ok(state.kinds.includes('intersection'));assert.deepEqual(state.relationships,[]);assert.deepEqual(state.hud,['Int, Mid'])});

test('Near remains a direct snap and beats active Track/Parallel when no higher feature is acquired',async()=>{const b=await browser();b.resize(800,600);b.flush();b.run(`window.caderactViewport.setGridSnapEnabled(false);window.caderactViewport.setObjectSnapMode('nearest',true);recordGateway.createAll([recordGateway.createLine({x:0,y:30},{x:20,y:30})])`);beginParallel(b,30);b.point(427,148,'pointermove');b.flush();const state=snapState(b);assert.equal(state.kind,'nearest');assert.deepEqual(state.point,{x:5.4,y:30});assert.deepEqual(state.relationships,[]);assert.deepEqual(state.hud,['Near'])});

test('Osnap off clears semantics while Track off leaves direct semantic acquisition unchanged',async()=>{const b=await browser();b.resize(800,600);b.flush();b.run(`window.caderactViewport.setGridSnapEnabled(false);recordGateway.createAll([recordGateway.createLine({x:0,y:0},{x:10,y:0})]);window.caderactViewport.setObjectSnapTrackingEnabled(false)`);b.launch('Line');b.point(425,300,'pointermove');assert.equal(b.read('activeSnapResult.kind'),'midpoint');b.run(`window.caderactViewport.setObjectSnapMode('object',false)`);b.point(425,300,'pointermove');assert.equal(b.read('activeSnapResult.snapped'),false);assert.deepEqual(b.read('window.caderactViewport.getObjectSnapTrackingState().acquiredPoints'),[])});

