'use strict';
const {test}=require('node:test');const assert=require('node:assert/strict');const {browser}=require('../helpers/browser.cjs');
function typeHud(b,text){for(const character of text)b.key(character)}
function typed(b,value){b.input.value=value;b.emit(b.input,'input');b.key('Enter',b.input)}

test('P6B typing owns Line Distance, preserves text through movement, and submits through P5',async()=>{const b=await browser();b.launch('Line');b.point(400,300);b.point(450,250,'pointermove');typeHud(b,'100');let state=b.read('window.caderactViewport.getDynamicInputState()');assert.equal(state.editing,true);assert.equal(state.activeFieldId,'distance');assert.equal(state.fields.find(field=>field.active).text,'100');assert.equal(b.input.value,'');b.point(470,260,'pointermove');state=b.read('window.caderactViewport.getDynamicInputState()');assert.equal(state.fields.find(field=>field.active).text,'100');b.key('Enter');const point=b.read('window.caderactCommandRouter.activeSession.draft.acceptedPoints()[1]');assert.ok(Math.abs(Math.hypot(point.x,point.y)-100)<1e-12);assert.ok(Math.abs(point.y/point.x-8/14)<1e-12);assert.equal(b.read('window.caderactViewport.getDynamicInputState().editing'),false)});

test('P6B invalid input remains editable and first Escape cancels only the edit',async()=>{const b=await browser();b.launch('Line');b.point(400,300);b.point(450,300,'pointermove');typeHud(b,'-');b.key('Enter');assert.equal(b.read('window.caderactViewport.getDynamicInputState().editing'),true);assert.equal(b.read('window.caderactViewport.getDynamicInputState().invalid'),true);assert.equal(b.read('window.caderactCommandRouter.activeCommand'),'Line');b.key('Escape');assert.equal(b.read('window.caderactViewport.getDynamicInputState().editing'),false);assert.equal(b.read('window.caderactCommandRouter.activeCommand'),'Line');b.key('Escape');assert.equal(b.read('window.caderactCommandRouter.activeCommand'),null)});

test('P6B command bar focus keeps HUD display-only with no duplicate ownership',async()=>{const b=await browser();b.launch('Line');b.point(400,300);b.point(450,300,'pointermove');b.input.focus();b.emit(b.input,'focus');b.input.value='25';b.emit(b.input,'input');b.key('2',b.input);assert.equal(b.read('window.caderactViewport.getDynamicInputState().editing'),false);assert.equal(b.input.value,'25')});

test('P6B routes Circle Radius, Rotate Angle, and Scale Factor through existing sessions',async()=>{const circle=await browser();circle.launch('Circle');typed(circle,'0,0');circle.point(450,300,'pointermove');typeHud(circle,'25');circle.key('Enter');assert.equal(circle.read('modelReader.records()[0].radius'),25);const rotate=await browser();rotate.run('window.__line=recordGateway.createLine({x:0,y:0},{x:10,y:0});recordGateway.createAll([window.__line]);window.caderactSelection.selectOnly(window.__line.id)');rotate.launch('Rotate');typed(rotate,'0,0');typed(rotate,'10,0');rotate.point(450,250,'pointermove');typeHud(rotate,'90');rotate.key('Enter');assert.equal(rotate.read('modelReader.records()[0].end.y'),10);const scale=await browser();scale.run('window.__line=recordGateway.createLine({x:0,y:0},{x:10,y:0});recordGateway.createAll([window.__line]);window.caderactSelection.selectOnly(window.__line.id)');scale.launch('Scale');typed(scale,'0,0');typed(scale,'10,0');scale.point(500,300,'pointermove');typeHud(scale,'2');scale.key('Enter');assert.equal(scale.read('modelReader.records()[0].end.x'),20)});

test('P6B controller cycles editable fields deterministically and Dynamic Input off cancels editing only',async()=>{const b=await browser();assert.equal(b.read('(()=>{const c=window.CaderactDynamicInput.createController();c.update({screenPoint:{x:1,y:1},viewport:{width:500,height:500},fields:[{id:"distance",editable:true,value:"1"},{id:"angle",editable:true,value:"2"}]});c.beginEdit("1");c.cycle();const forward=c.getState().activeFieldId;c.cycle(true);return forward+":"+c.getState().activeFieldId})()'),'angle:distance');b.launch('Line');b.point(400,300);b.point(450,300,'pointermove');typeHud(b,'10');b.run('window.caderactViewport.setDynamicInputEnabled(false)');assert.equal(b.read('window.caderactViewport.getDynamicInputState().visible'),false);assert.equal(b.read('window.caderactCommandRouter.activeCommand'),'Line')});
