'use strict';
const {test}=require('node:test');const assert=require('node:assert/strict');const {browser}=require('../helpers/browser.cjs');

test('P6A is hidden idle and shows resolved Line coordinates then distance and angle',async()=>{const b=await browser();assert.equal(b.read('window.caderactViewport.getDynamicInputState().visible'),false);b.launch('Line');b.point(400,300,'pointermove');let state=b.read('window.caderactViewport.getDynamicInputState()');assert.equal(state.visible,true);assert.equal(state.prompt,'Line: Specify first point');assert.deepEqual(state.fields.map(field=>[field.id,field.value]),[['x','0'],['y','0']]);b.point(400,300);b.point(450,250,'pointermove');state=b.read('window.caderactViewport.getDynamicInputState()');assert.equal(state.prompt,'Line: Specify next point');assert.deepEqual(state.fields.map(field=>[field.id,field.value]),[['distance','14.142'],['angle','45.00°']]);assert.deepEqual(b.read('activeSnapResult.point'),{x:10,y:10})});

test('P6A follows final Ortho and Grid candidates and updates on stationary constraint changes',async()=>{const b=await browser();b.launch('Line');b.point(400,300);b.point(450,250,'pointermove');b.key('Shift',b.document,{code:'ShiftLeft'});assert.deepEqual(b.read('window.caderactViewport.getDynamicInputState().fields.map(field=>field.value)'),['10','0.00°']);b.emit(b.document,'keyup',{key:'Shift',code:'ShiftLeft'});assert.deepEqual(b.read('window.caderactViewport.getDynamicInputState().fields.map(field=>field.value)'),['14.142','45.00°']);b.emit(b.gridSnapButton,'click');b.point(463,238,'pointermove');assert.equal(b.read('activeSnapResult.kind'),'grid');assert.equal(b.read('window.caderactViewport.getDynamicInputState().fields[0].value'),'14.142')});

test('P6A placement flips and clamps at viewport edges',async()=>{const b=await browser();assert.deepEqual(b.read('window.CaderactDynamicInput.place({x:790,y:590},{width:800,height:600})'),{left:552,top:514,flipX:true,flipY:true});assert.deepEqual(b.read('window.CaderactDynamicInput.place({x:10,y:10},{width:800,height:600})'),{left:28,top:28,flipX:false,flipY:false})});

test('P6A hides for selection, pointer exit, Escape, and preference off without document mutation',async()=>{const b=await browser();const before=b.read('({revision:documentController.currentRevision,history:documentController.historyInfo.entryCount})');b.launch('Move');b.point(450,250,'pointermove');assert.equal(b.read('window.caderactViewport.getDynamicInputState().visible'),false);b.key('Escape');b.launch('Line');b.point(450,250,'pointermove');assert.equal(b.read('window.caderactViewport.getDynamicInputState().visible'),true);b.point(900,700,'pointerleave');assert.equal(b.read('window.caderactViewport.getDynamicInputState().visible'),false);b.point(450,250,'pointermove');b.run('window.caderactViewport.setDynamicInputEnabled(false)');assert.equal(b.read('window.caderactViewport.getDynamicInputState().visible'),false);assert.equal(b.read('window.caderactUserPreferences.value.dynamicInputEnabled'),false);assert.deepEqual(b.read('({revision:documentController.currentRevision,history:documentController.historyInfo.entryCount})'),before)});
test('P6 preference defaults on, persists, validates, and reset restores runtime state',async()=>{const b=await browser();assert.equal(b.read('window.caderactViewport.dynamicInputEnabled'),true);b.run('window.caderactViewport.setDynamicInputEnabled(false)');assert.equal(b.read('window.caderactUserPreferences.value.dynamicInputEnabled'),false);b.run('window.caderactUserPreferences.reset()');assert.equal(b.read('window.caderactViewport.dynamicInputEnabled'),true);assert.equal(b.read('(()=>{const storage={getItem:()=>JSON.stringify({version:1,preferences:{dynamicInputEnabled:"bad"}}),setItem:()=>{}};return window.CaderactUserPreferences.create({storage}).value.dynamicInputEnabled})()'),true)});
