const test=require('node:test');const assert=require('node:assert/strict');const{browser}=require('../helpers/browser.cjs');
const typed=(b,v)=>{b.input.value=v;b.emit(b.input,'input');b.key('Enter',b.input)};
const acquire=(b,x,y)=>{b.point(x,y,'pointermove');b.advance(500)};
const quiet=b=>b.run(`for(const k of ['midpoint','center','intersection','quadrant','nearest','perpendicular','tangent','vertex'])window.caderactViewport.setObjectSnapMode(k,false)`);
const state=b=>b.read('({revision:documentController.currentRevision,stateId:documentController.currentStateId,history:documentController.historyInfo.entryCount,dirty:documentController.isDirty})');

test('P8 H/V guides intersect finite Lines exactly',async()=>{
 const h=await browser();h.run(`recordGateway.createAll([recordGateway.createLine({x:0,y:0},{x:-10,y:-10}),recordGateway.createLine({x:20,y:-10},{x:20,y:10})])`);quiet(h);h.launch();acquire(h,400,300);h.point(499,302,'pointermove');assert.equal(h.read('activeSnapResult.trackingGeometry||false'),true);assert.deepEqual(h.read('activeSnapResult.point'),{x:20,y:0});assert.equal(h.read('activeSnapResult.sourceReference.kind'),'object');
 const v=await browser();v.run(`recordGateway.createAll([recordGateway.createLine({x:0,y:0},{x:-10,y:-10}),recordGateway.createLine({x:-10,y:20},{x:10,y:20})])`);quiet(v);v.launch();acquire(v,400,300);v.point(402,201,'pointermove');assert.ok(Math.abs(v.read('activeSnapResult.point.x'))<1e-9);assert.equal(v.read('activeSnapResult.point.y'),20)
});
test('Circle multiplicity, Polyline domains, visibility and locking are respected',async()=>{
 const c=await browser();c.run(`recordGateway.createAll([recordGateway.createLine({x:0,y:0},{x:-10,y:-10}),recordGateway.createCircle({x:20,y:0},5)])`);quiet(c);c.launch();acquire(c,400,300);c.point(523,302,'pointermove');assert.deepEqual(c.read('activeSnapResult.point'),{x:25,y:0});c.point(477,302,'pointermove');assert.deepEqual(c.read('activeSnapResult.point'),{x:15,y:0});
 const p=await browser();p.run(`window.s=recordGateway.createLine({x:0,y:0},{x:-10,y:-10});window.p=recordGateway.createPolyline([{x:10,y:-5},{x:10,y:5},{x:20,y:5}],false);recordGateway.createAll([window.s,window.p])`);quiet(p);p.launch();acquire(p,400,300);p.point(451,302,'pointermove');assert.deepEqual(p.read('activeSnapResult.point'),{x:10,y:0});
 const l=await browser();l.run(`layerGateway.create('R');window.l=modelReader.layers().find(x=>x.name==='R');window.s=recordGateway.createLine({x:0,y:0},{x:-10,y:-10});window.t=recordGateway.createLine({x:20,y:-10},{x:20,y:10});recordGateway.createAll([window.s,window.t]);recordGateway.assignLayer([window.t.id],window.l.id);layerGateway.setLocked(window.l.id,true)`);quiet(l);l.launch();acquire(l,400,300);l.point(499,302,'pointermove');assert.equal(l.read('activeSnapResult.trackingGeometry||false'),true);l.key('Escape');l.run(`layerGateway.setLocked(window.l.id,false);layerGateway.setVisibility(window.l.id,false)`);l.launch();acquire(l,400,300);l.point(499,302,'pointermove');assert.equal(l.read('activeSnapResult.trackingGeometry||false'),false)
});
test('precedence remains direct Osnap then tracking then Grid',async()=>{const b=await browser();b.run(`recordGateway.createAll([recordGateway.createLine({x:0,y:0},{x:-10,y:-10}),recordGateway.createLine({x:20,y:-10},{x:20,y:10})])`);quiet(b);b.launch();acquire(b,400,300);b.emit(b.gridSnapButton,'click');b.point(499,302,'pointermove');assert.equal(b.read('activeSnapResult.trackingGeometry||false'),true);b.point(500,250,'pointermove');assert.equal(b.read('activeSnapResult.kind'),'endpoint');b.emit(b.trackButton,'click');b.point(473,277,'pointermove');assert.equal(b.read('activeSnapResult.kind'),'grid')});
test('Ctrl+Alt+T toggles shared points without mutation or editable conflict',async()=>{const b=await browser();b.run(`recordGateway.createAll([recordGateway.createLine({x:0,y:0},{x:10,y:0})])`);b.launch();b.point(400,300,'pointermove');const before=state(b);b.key('t',b.document,{ctrlKey:true,altKey:true});assert.equal(b.read('window.caderactViewport.getObjectSnapTrackingState().acquiredPoints.length'),1);b.key('t',b.document,{ctrlKey:true,altKey:true});assert.equal(b.read('window.caderactViewport.getObjectSnapTrackingState().acquiredPoints.length'),0);assert.deepEqual(state(b),before);b.key('t',b.input,{ctrlKey:true,altKey:true});assert.equal(b.read('window.caderactViewport.getObjectSnapTrackingState().acquiredPoints.length'),0)});
test('Parallel uses latest accepted segment and needs a direction',async()=>{const b=await browser();b.launch();b.point(450,295,'pointermove');assert.equal(b.read('activeSnapResult?.relationships?.includes("parallel")||false'),false);typed(b,'0,0');typed(b,'10,0');b.point(500,296,'pointermove');assert.deepEqual(b.read('activeSnapResult.point'),{x:20,y:0});assert.ok(b.read('activeSnapResult.relationships').includes('parallel'));assert.ok(b.read('window.caderactViewport.getDynamicInputState().tags').includes('OnParallel'));b.flush();assert.ok(b.renders.at(-1).objectTrackingOverlay.guideSegments.length)});
test('Polar tracking ray intersects a finite Line and keeps exact final HUD coordinates',async()=>{const b=await browser();b.run(`recordGateway.createAll([recordGateway.createLine({x:0,y:0},{x:-5,y:-5}),recordGateway.createLine({x:10,y:5},{x:10,y:15})])`);quiet(b);b.launch();acquire(b,400,300);b.emit(b.polarButton,'click');b.point(451,249,'pointermove');assert.equal(b.read('activeSnapResult.trackingGeometry||false'),true);assert.ok(Math.abs(b.read('activeSnapResult.point.x')-10)<1e-9);assert.ok(Math.abs(b.read('activeSnapResult.point.y')-10)<1e-9);assert.deepEqual(b.read('window.caderactViewport.getDynamicInputState().fields').map(x=>x.value),['10','10'])});
test('Arc guide intersections honor the stored finite sweep',async()=>{const valid=await browser();valid.run(`recordGateway.createAll([recordGateway.createLine({x:0,y:3},{x:-5,y:-2}),recordGateway.createArc({center:{x:20,y:0},radius:5,start:{x:25,y:0},end:{x:15,y:0},sweep:Math.PI})])`);quiet(valid);valid.launch();acquire(valid,400,285);valid.point(480,283,'pointermove');assert.equal(valid.read('activeSnapResult.trackingGeometry||false'),true);const outside=await browser();outside.run(`recordGateway.createAll([recordGateway.createLine({x:0,y:-3},{x:-5,y:-8}),recordGateway.createArc({center:{x:20,y:0},radius:5,start:{x:25,y:0},end:{x:15,y:0},sweep:Math.PI})])`);quiet(outside);outside.launch();acquire(outside,400,315);outside.point(480,317,'pointermove');assert.equal(outside.read('activeSnapResult.trackingGeometry||false'),false)});
