'use strict'
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs')
const {browser}=require('../helpers/browser.cjs')
async function setup(){const b=await browser();b.resize(900,600);b.run(`window.__modelCamera={...camera};window.__layout=modelReader.layouts()[0].id;window.__vp=window.caderactDocumentSession.layoutGateway.createViewport(window.__layout,{frame:{x:20,y:20,width:120,height:80},viewCenter:{x:0,y:0},scale:10,locked:false}).viewport;window.caderactLayoutContext.switchToLayout(window.__layout);window.__paperCamera={...camera};window.__screen=worldToScreen(80,60);window.caderactViewport.layoutInteraction.activateAt(window.__screen)`);return b}
const view=b=>b.read('modelReader.layout(window.__layout).viewports[window.__vp.id]')
test('UX13 viewport pan is a single exact undoable document change and preserves both cameras',async()=>{
 const b=await setup(),before=view(b),records=b.read('modelReader.records()'),history=b.read('documentController.historyInfo.entryCount')
 b.run('layoutInteraction.begin();layoutInteraction.navigate({dx:20,dy:10});layoutInteraction.navigate({dx:15,dy:-5})')
 assert.deepEqual(view(b),before);assert.notDeepEqual(b.read('layoutInteraction.snapshot().viewport.viewCenter'),before.viewCenter)
 b.run('layoutInteraction.commit()');const after=view(b);assert.notDeepEqual(after.viewCenter,before.viewCenter);assert.deepEqual(after.frame,before.frame);assert.equal(b.read('documentController.historyInfo.entryCount'),history+1)
 assert.deepEqual(b.read('modelReader.records()'),records);assert.deepEqual(b.read('({...camera})'),b.read('window.__paperCamera'))
 b.run('documentController.undo()');assert.deepEqual(view(b),before);b.run('documentController.redo()');assert.deepEqual(view(b),after)
 b.run('window.caderactLayoutContext.switchToModel()');assert.deepEqual(b.read('({...camera})'),b.read('window.__modelCamera'))
})
test('UX13 viewport zoom preserves the point under the pointer and PlotScene receives the same viewport',async()=>{
 const b=await setup(),before=view(b)
 b.run('layoutInteraction.navigate({factor:2,screen:window.__screen})');const after=view(b)
 assert.equal(after.scale,5);assert.deepEqual(after.viewCenter,before.viewCenter);assert.deepEqual(after.frame,before.frame)
 b.flush();assert.equal(b.renders.at(-1).layoutViewportOverlay.items[0].scale,5)
 assert.equal(b.read('window.CaderactPaperSpace.projectModelPoint({x:10,y:0},modelReader.layout(window.__layout).viewports[window.__vp.id],"mm").x'),82)
})
test('UX13 locked active viewport consumes navigation without mutation',async()=>{
 const b=await setup();b.run('documentSession.layoutGateway.updateViewport(window.__layout,window.__vp.id,{locked:true})');const before=view(b),revision=b.read('documentController.currentRevision')
 assert.equal(b.read('layoutInteraction.navigate({dx:30,dy:20,factor:2,screen:window.__screen})'),true)
 assert.deepEqual(view(b),before);assert.equal(b.read('documentController.currentRevision'),revision)
})
test('UX13 multiple viewports are independent and active deletion or context replacement exits safely',async()=>{
 const b=await setup();b.run('window.__other=documentSession.layoutGateway.createViewport(window.__layout,{frame:{x:150,y:20,width:80,height:60},viewCenter:{x:100,y:100},scale:50,locked:false}).viewport;layoutInteraction.navigate({dx:20})')
 assert.deepEqual(b.read('modelReader.layout(window.__layout).viewports[window.__other.id]'),b.read('window.__other'))
 b.run('documentSession.layoutGateway.removeViewport(window.__layout,window.__vp.id)');assert.equal(b.read('layoutInteraction.snapshot().activeId'),null)
 b.run('layoutInteraction.activateAt(worldToScreen(180,40));window.caderactLayoutContext.switchToModel()');assert.equal(b.read('layoutInteraction.snapshot().activeId'),null)
 b.run('window.caderactLayoutContext.switchToLayout(window.__layout);layoutInteraction.activateAt(worldToScreen(180,40));documentSession.replaceStore(window.CaderactDocument.createStore({initiallySaved:true}))');assert.equal(b.read('layoutInteraction.snapshot().activeId'),null)
})
test('UX13 frame placement is transient until second corner and Escape exits viewport interaction',async()=>{
 const b=await setup();b.run('layoutInteraction.clear();layoutInteraction.beginPlacement()');const revision=b.read('documentController.currentRevision')
 b.run('layoutInteraction.pointerDown(worldToScreen(50,50));layoutInteraction.pointerMove(worldToScreen(100,100))');assert.equal(b.read('documentController.currentRevision'),revision)
 assert.equal(b.read('layoutInteraction.projectedViewports().at(-1).frameOnly'),true)
 b.run('layoutInteraction.pointerDown(worldToScreen(100,100))');assert.equal(b.read('modelReader.layout(window.__layout).viewportOrder.length'),2)
 b.run('layoutInteraction.activateAt(worldToScreen(75,75))');b.emit(b.document,'keydown',{key:'Escape'});assert.equal(b.read('layoutInteraction.snapshot().activeId'),null)
})
test('UX13 Light and Dark handoff preserves every renderer color and source palettes',async()=>{
 for(const name of ['light','dark']){const b=await browser();b.run(`workspacePreferences.set({canvasTheme:'${name}'});window.__colors=Object.fromEntries(Object.keys(window.CaderactCanvasAppearance.roles).map(key=>[key,viewportSettings[key]]))`);const templates=b.read('window.CaderactWorkspacePreferences.CANVAS_TEMPLATES')
 b.settingsControls['canvas-theme'].value='custom';b.emit(b.settingsControls['canvas-theme'],'change')
 assert.deepEqual(b.read('Object.fromEntries(Object.keys(window.CaderactCanvasAppearance.roles).map(key=>[key,viewportSettings[key]]))'),b.read('window.__colors'))
 b.run('workspacePreferences.set({customCanvasColors:{...workspacePreferences.value.customCanvasColors,background:"#123456"}})');assert.deepEqual(b.read('window.CaderactWorkspacePreferences.CANVAS_TEMPLATES'),templates)
 }
})
test('UX13 handoff presentation persists validates and Reset to Template remains exact',async()=>{
 const b=await browser();b.settingsControls['canvas-theme'].value='custom';b.emit(b.settingsControls['canvas-theme'],'change')
 assert.ok(b.read('workspacePreferences.value.customCanvasPresentation'))
 b.run('window.__saved=workspacePreferences.value;window.__restored=window.CaderactWorkspacePreferences.create({storage:{getItem:()=>JSON.stringify({version:1,preferences:window.__saved})}}).value');assert.deepEqual(b.read('window.__restored'),b.read('window.__saved'))
 b.run('window.__legacy={...window.__saved};delete window.__legacy.customCanvasPresentation;window.__legacyRestored=window.CaderactWorkspacePreferences.create({storage:{getItem:()=>JSON.stringify({version:1,preferences:window.__legacy})}}).value')
 assert.equal(b.read('window.__legacyRestored.customCanvasPresentation'),null);assert.deepEqual(b.read('window.__legacyRestored.customCanvasColors'),b.read('window.__legacy.customCanvasColors'))
 b.settingsControls['canvas-template'].value='blueprint';b.emit(b.settingsControls['canvas-template'],'change');assert.equal(b.read('workspacePreferences.value.customCanvasPresentation'),null)
 assert.deepEqual(b.read('workspacePreferences.value.customCanvasColors'),b.read('window.CaderactWorkspacePreferences.CANVAS_TEMPLATES.blueprint'))
 assert.deepEqual(b.read('window.CaderactCanvasAppearance.normalize({renderer:{geometryColor:"url(evil)"},css:{"position":"fixed"}})'),{colors:{},renderer:{},css:{}})
})
test('UX13 floating placement clamps and recenters without preferences or document state',async()=>{
 const b=await browser(),revision=b.read('documentController.currentRevision'),history=b.read('documentController.historyInfo.entryCount'),preferences=b.read('workspacePreferences.value');b.run(`window.__panel=document.createElement('div');window.__panel.rect={left:10,top:10,width:300,height:200};window.__head=document.createElement('header');window.__float=window.CaderactFloatingDialog.bind(window.__panel,window.__head);window.__float.center()`)
 const initial=b.read('({left:window.__panel.style.left,top:window.__panel.style.top})')
 b.emit(b.window.__head,'pointerdown',{button:0,pointerId:1,clientX:20,clientY:20});b.emit(b.window.__head,'pointermove',{pointerId:1,clientX:-100,clientY:-100});assert.equal(b.window.__panel.style.left,'8px');assert.equal(b.window.__panel.style.top,'8px')
 b.run('window.__float.center()');assert.deepEqual(b.read('({left:window.__panel.style.left,top:window.__panel.style.top})'),initial)
 assert.equal(b.read('documentController.currentRevision'),revision);assert.equal(b.read('documentController.historyInfo.entryCount'),history);assert.deepEqual(b.read('workspacePreferences.value'),preferences)
})
test('UX13 production structure uses a stable bounded Preferences frame and each Custom control once',()=>{
 const html=fs.readFileSync('index.html','utf8'),css=fs.readFileSync('src/css/application-shell.css','utf8'),source=fs.readFileSync('src/js/editor/layout-tabs.js','utf8')
 for(const key of ['background','gridMinor','gridMajor','axisX','axisY','geometry','selection','grip','gripHover','osnap','tracking','crosshair','dynamicSurface','dynamicText'])assert.equal(html.split(`data-canvas-color="${key}"`).length-1,1)
 assert.match(css,/height:min\(540px,calc\(100vh - 24px\)\)/);assert.match(css,/#settings-panel \.settings-panel-body\{flex:1;min-height:0\}/)
 assert.match(source,/CaderactFloatingDialog\.bind\(setupDialog,title\)/)
})
