'use strict';
const {test}=require('node:test');const assert=require('node:assert/strict');const {loadGeometry}=require('../helpers/geometry.cjs');
const planner=()=>loadGeometry().CaderactArrayPlanner;const records=[{id:'a'}];
test('rectangular array plans deterministic signed row/column translations',()=>{const result=planner().rectangular({records,rows:2,columns:3,rowSpacing:-4,columnSpacing:5});assert.equal(result.status,'planned');assert.deepEqual(result.transforms.map(({dx,dy})=>[dx,dy]),[[5,0],[10,0],[0,-4],[5,-4],[10,-4]])});
test('rectangular array rejects degenerate counts, zero repeat spacing, and safety overflow',()=>{const p=planner();assert.equal(p.rectangular({records,rows:1,columns:1,rowSpacing:1,columnSpacing:1}).reason,'no-copies');assert.equal(p.rectangular({records,rows:2,columns:1,rowSpacing:0,columnSpacing:1}).reason,'zero-spacing');assert.equal(p.rectangular({records,rows:502,columns:1,rowSpacing:1,columnSpacing:1}).reason,'copy-limit')});
test('full polar arrays exclude duplicate 360 while partial arrays include the terminal angle',()=>{const p=planner(),full=p.polar({records,center:{x:0,y:0},itemCount:4,fillAngleDegrees:360}),partial=p.polar({records,center:{x:0,y:0},itemCount:4,fillAngleDegrees:180});assert.deepEqual(full.transforms.map(t=>Math.round(t.angle*180/Math.PI)),[90,180,270]);assert.deepEqual(partial.transforms.map(t=>Math.round(t.angle*180/Math.PI)),[60,120,180])});
test('polar arrays support clockwise partial fills and enforce limits',()=>{const p=planner();assert.deepEqual(p.polar({records,center:{x:2,y:3},itemCount:3,fillAngleDegrees:-180}).transforms.map(t=>Math.round(t.angle*180/Math.PI)),[-90,-180]);assert.equal(p.polar({records,center:{x:0,y:0},itemCount:2,fillAngleDegrees:361}).reason,'invalid-angle')});
test('path arrays sample Lines and open Polylines at exact cumulative distances with fixed orientation',()=>{const p=planner(),line=p.path({records,path:{type:'line',start:{x:0,y:0},end:{x:10,y:0}},basePoint:{x:0,y:0},itemCount:3,spacing:4}),poly=p.path({records,path:{type:'polyline',closed:false,vertices:[{x:0,y:0},{x:3,y:0},{x:3,y:4}]},basePoint:{x:1,y:1},itemCount:3,spacing:3});assert.deepEqual(line.transforms.map(t=>[t.dx,t.dy]),[[4,0],[8,0]]);assert.deepEqual(poly.transforms.map(t=>[t.dx,t.dy]),[[2,-1],[2,2]])});
test('path arrays reject closed/short paths and excessive generated records',()=>{const p=planner();assert.equal(p.path({records,path:{type:'polyline',closed:true,vertices:[{x:0,y:0},{x:10,y:0}]},basePoint:{x:0,y:0},itemCount:2,spacing:1}).reason,'invalid-path');assert.equal(p.path({records,path:{type:'line',start:{x:0,y:0},end:{x:1,y:0}},basePoint:{x:0,y:0},itemCount:3,spacing:1}).reason,'path-too-short')});
