'use strict';
const test=require('node:test');
const assert=require('node:assert/strict');
const {browser}=require('../helpers/browser.cjs');
const near=(actual,expected,tolerance=1e-9)=>assert.ok(Math.abs(actual-expected)<=tolerance,`${actual} != ${expected}`);

test('R1 tolerance is model-space, scale-aware, and stable at small and large coordinates',async()=>{const b=await browser();b.window.__points=[{x:1e12,y:1e12},{x:1e12+1000,y:1e12+1000}];const t=b.read('window.CaderactBoundaryTolerance.create(window.__points)');assert.ok(t.linear>=1e-9);assert.ok(t.linear>=32*Number.EPSILON*1e12);assert.equal(b.read('window.CaderactBoundaryTolerance.create([{x:0,y:0},{x:1e-12,y:1e-12}]).linear'),1e-9)});

test('rectangle and closed Polyline adapt to canonical exact line loops',async()=>{const b=await browser();b.window.__edges=[{kind:'line',start:{x:0,y:0},end:{x:4,y:0}},{kind:'line',start:{x:4,y:0},end:{x:4,y:3}},{kind:'line',start:{x:4,y:3},end:{x:0,y:3}},{kind:'line',start:{x:0,y:3},end:{x:0,y:0}}];let result=b.read('window.CaderactBoundaryGeometry.validateLoop(window.__edges)');assert.equal(result.valid,true);assert.equal(result.loop.orientation,'ccw');assert.equal(result.loop.perimeter,14);assert.equal(result.loop.area,12);b.window.__poly={type:'polyline',closed:true,vertices:[{x:0,y:0},{x:4,y:0},{x:4,y:3},{x:0,y:3}]};result=b.read('window.CaderactBoundaryGeometry.adaptClosedPolyline(window.__poly)');assert.equal(result.valid,true);assert.equal(result.edges.length,4)});

test('Circle and rotated Ellipse retain semantic closure and analytic metrics',async()=>{const b=await browser();b.window.__circle={type:'circle',center:{x:2,y:-1},radius:3};let edge=b.read('window.CaderactBoundaryGeometry.adaptEdge(window.__circle).edge');b.window.__edge=edge;let loop=b.read('window.CaderactBoundaryGeometry.validateLoop([window.__edge]).loop');near(loop.area,Math.PI*9);near(loop.perimeter,Math.PI*6);b.window.__ellipse={type:'ellipse',center:{x:0,y:0},majorAxis:{x:3,y:4},minorRadius:2};edge=b.read('window.CaderactBoundaryGeometry.adaptEdge(window.__ellipse).edge');b.window.__edge=edge;loop=b.read('window.CaderactBoundaryGeometry.validateLoop([window.__edge]).loop');near(loop.area,Math.PI*10);assert.equal(loop.edges[0].kind,'ellipse')});

test('mixed line and minor, major, wrapped Arc loops use analytic signed area and perimeter',async()=>{const b=await browser();for(const sweep of [Math.PI,Math.PI*1.5]){const end={x:Math.cos(sweep),y:Math.sin(sweep)};b.window.__edges=[{kind:'arc',center:{x:0,y:0},radius:1,start:{x:1,y:0},end,sweep},{kind:'line',start:end,end:{x:1,y:0}}];const result=b.read('window.CaderactBoundaryGeometry.validateLoop(window.__edges)');assert.equal(result.valid,true);near(result.loop.area,.5*(sweep-Math.sin(sweep)));near(result.loop.perimeter,sweep+Math.hypot(1-end.x,end.y))}const start=350*Math.PI/180,sweep=40*Math.PI/180,a={x:Math.cos(start),y:Math.sin(start)},z={x:Math.cos(start+sweep),y:Math.sin(start+sweep)};b.window.__edges=[{kind:'arc',center:{x:0,y:0},radius:1,start:a,end:z,sweep},{kind:'line',start:z,end:a}];assert.equal(b.read('window.CaderactBoundaryGeometry.validateLoop(window.__edges).valid'),true)});

test('reversal is stable and canonical orientation preserves geometry',async()=>{const b=await browser();b.window.__edges=[{kind:'line',start:{x:0,y:0},end:{x:0,y:2}},{kind:'line',start:{x:0,y:2},end:{x:2,y:2}},{kind:'line',start:{x:2,y:2},end:{x:2,y:0}},{kind:'line',start:{x:2,y:0},end:{x:0,y:0}}];const result=b.read('window.CaderactBoundaryGeometry.canonicalizeLoop(window.__edges)');assert.equal(result.valid,true);assert.equal(result.loop.orientation,'ccw');assert.equal(result.loop.signedArea,4);b.window.__loop=result.loop;const twice=b.read('window.CaderactBoundaryGeometry.reverseLoop(window.CaderactBoundaryGeometry.reverseLoop(window.__loop))');assert.deepEqual(twice.edges,result.loop.edges)});

test('near endpoint closure and deterministic endpoint clustering do not mutate coordinates',async()=>{const b=await browser();b.window.__edges=[{kind:'line',start:{x:0,y:0},end:{x:1,y:0}},{kind:'line',start:{x:1+2e-10,y:0},end:{x:1,y:1}},{kind:'line',start:{x:1,y:1},end:{x:0,y:1}},{kind:'line',start:{x:0,y:1},end:{x:0,y:0}}];const result=b.read('window.CaderactBoundaryGeometry.validateLoop(window.__edges)');assert.equal(result.valid,true);assert.equal(result.loop.edges[1].start.x,1+2e-10);b.window.__points=[{x:1+2e-10,y:0},{x:5,y:5},{x:1,y:0},{x:5+1e-10,y:5}];const a=b.read('window.CaderactBoundaryGeometry.clusterEndpoints(window.__points)'),before=[...b.window.__points].reverse();b.window.__points=before;const c=b.read('window.CaderactBoundaryGeometry.clusterEndpoints(window.__points)');assert.deepEqual(a.clusters.map(x=>x.representative),c.clusters.map(x=>x.representative));assert.deepEqual(a.clusters.map(x=>x.representative),[{x:1,y:0},{x:5,y:5}])});

test('intersection deduplication and semantic Line/Arc splitting are bounded and ordered',async()=>{const b=await browser();b.window.__a={kind:'line',start:{x:-2,y:0},end:{x:2,y:0}};b.window.__c={kind:'circle',center:{x:0,y:0},radius:1};let result=b.read('window.CaderactBoundaryGeometry.intersections(window.__a,window.__c)');assert.equal(result.hits.length,2);assert.ok(result.hits[0].parameterA<result.hits[1].parameterA);result=b.read('window.CaderactBoundaryGeometry.splitEdge(window.__a,[.75,.25,.25])');assert.equal(result.edges.length,3);assert.deepEqual(result.edges.map(edge=>edge.start.x),[-2,-1,1]);b.window.__arc={kind:'arc',center:{x:0,y:0},radius:2,start:{x:2,y:0},end:{x:-2,y:0},sweep:Math.PI};result=b.read('window.CaderactBoundaryGeometry.splitEdge(window.__arc,[.5])');assert.equal(result.edges.length,2);near(result.edges[0].sweep,Math.PI/2)});

test('point classification handles mixed loops, Circle, Ellipse, and boundaries',async()=>{const b=await browser();b.window.__edges=[{kind:'arc',center:{x:0,y:0},radius:2,start:{x:2,y:0},end:{x:-2,y:0},sweep:Math.PI},{kind:'line',start:{x:-2,y:0},end:{x:2,y:0}}];b.run('window.__loop=window.CaderactBoundaryGeometry.validateLoop(window.__edges).loop');assert.equal(b.read('window.CaderactBoundaryGeometry.classifyPoint(window.__loop,{x:0,y:1}).classification'),'inside');assert.equal(b.read('window.CaderactBoundaryGeometry.classifyPoint(window.__loop,{x:0,y:-1}).classification'),'outside');assert.equal(b.read('window.CaderactBoundaryGeometry.classifyPoint(window.__loop,{x:0,y:0}).classification'),'boundary');for(const [record,inside,outside] of [[{type:'circle',center:{x:0,y:0},radius:3},{x:0,y:0},{x:4,y:0}],[{type:'ellipse',center:{x:0,y:0},majorAxis:{x:3,y:4},minorRadius:2},{x:0,y:0},{x:6,y:0}]]){b.window.__record=record;b.run('window.__edge=window.CaderactBoundaryGeometry.adaptEdge(window.__record).edge;window.__loop=window.CaderactBoundaryGeometry.validateLoop([window.__edge]).loop');b.window.__inside=inside;b.window.__outside=outside;assert.equal(b.read('window.CaderactBoundaryGeometry.classifyPoint(window.__loop,window.__inside).classification'),'inside');assert.equal(b.read('window.CaderactBoundaryGeometry.classifyPoint(window.__loop,window.__outside).classification'),'outside')}});

test('nesting assigns deterministic outer, hole, island, and deeper parity',async()=>{const b=await browser();b.window.__loops=[10,8,6,4].map(radius=>[{kind:'circle',center:{x:0,y:0},radius}]);const result=b.read('window.CaderactBoundaryGeometry.classifyNesting(window.__loops)');assert.equal(result.valid,true);assert.deepEqual(result.entries.map(x=>x.depth),[0,1,2,3]);assert.deepEqual(result.entries.map(x=>x.filled),[true,false,true,false]);assert.deepEqual(result.entries.map(x=>x.loop.orientation),['ccw','cw','ccw','cw']);b.window.__loops=[[{kind:'circle',center:{x:-10,y:0},radius:2}],[{kind:'circle',center:{x:10,y:0},radius:2}]];assert.deepEqual(b.read('window.CaderactBoundaryGeometry.classifyNesting(window.__loops).entries.map(x=>x.depth)'),[0,0])});

test('ambiguous, invalid, non-finite, and excessive topology returns structured rejection',async()=>{const b=await browser(),cases=[[[{kind:'line',start:{x:0,y:0},end:{x:1,y:0}},{kind:'line',start:{x:1,y:0},end:{x:0,y:1}}],'open-loop'],[[{kind:'line',start:{x:0,y:0},end:{x:2,y:2}},{kind:'line',start:{x:2,y:2},end:{x:0,y:2}},{kind:'line',start:{x:0,y:2},end:{x:2,y:0}},{kind:'line',start:{x:2,y:0},end:{x:0,y:0}}],'self-intersection'],[[{kind:'line',start:{x:0,y:0},end:{x:2,y:0}},{kind:'line',start:{x:2,y:0},end:{x:1,y:0}},{kind:'line',start:{x:1,y:0},end:{x:0,y:0}}],'overlapping-edges'],[[{kind:'line',start:{x:0,y:0},end:{x:0,y:0}}],'open-loop'],[[{kind:'circle',center:{x:NaN,y:0},radius:1}],'non-finite-edge']];for(const [edges,reason] of cases){b.window.__edges=edges;const result=b.read('window.CaderactBoundaryGeometry.validateLoop(window.__edges)');assert.equal(result.valid,false);assert.equal(result.reason,reason)}b.window.__points=Array.from({length:6},(_,i)=>({x:i,y:0}));assert.equal(b.read('window.CaderactBoundaryGeometry.clusterEndpoints(window.__points,null,5).reason'),'node-limit')});
