'use strict';
const {test}=require('node:test');const assert=require('node:assert/strict');const {loadGeometry}=require('../helpers/geometry.cjs');const w=loadGeometry(),Join=w.CaderactJoinPlanner,Split=w.CaderactSplitBreakPlanner;
const line=(start,end,id)=>({id,type:'line',layerId:'layer-1',color:null,linetype:null,lineweight:null,start:{...start,featureId:`${id}-s`},end:{...end,featureId:`${id}-e`}});
const poly=(vertices,id)=>({id,type:'polyline',layerId:'layer-1',color:null,linetype:null,lineweight:null,closed:false,vertices:vertices.map((value,index)=>({...value,featureId:`${id}-${index}`}))});

test('Join plans connected collinear Lines across orientation and tolerance boundary',()=>{const a=line({x:0,y:0},{x:5,y:0},'a'),b=line({x:10,y:0},{x:5,y:0},'b');let plan=Join.plan({records:[a,b]});assert.equal(plan.status,'planned');assert.deepEqual(plan.geometry,{type:'line',start:a.start,end:b.start});const near=line({x:5+Join.TOLERANCE,y:0},{x:10,y:0},'near');plan=Join.plan({records:[a,near]});assert.equal(plan.status,'planned')});
test('Join rejects gap, non-collinearity, incompatibility, and branching',()=>{const a=line({x:0,y:0},{x:5,y:0},'a');assert.equal(Join.plan({records:[a,line({x:5+Join.TOLERANCE*2,y:0},{x:10,y:0},'gap')]}).reason,'disconnected-gap');assert.equal(Join.plan({records:[a,line({x:5,y:0},{x:5,y:5},'turn')]}).reason,'non-collinear-lines');const other=line({x:5,y:0},{x:10,y:0},'other');other.layerId='layer-2';assert.equal(Join.plan({records:[a,other]}).reason,'incompatible-properties');assert.equal(Join.plan({records:[a,line({x:5,y:0},{x:10,y:0},'b'),line({x:5,y:0},{x:8,y:0},'c')]}).reason,'ambiguous-branch')});
test('Join composes compatible open Polyline and Line without losing vertices',()=>{const p=poly([{x:0,y:0},{x:3,y:2},{x:5,y:0}],'p'),l=line({x:5,y:0},{x:10,y:0},'l'),plan=Join.plan({records:[p,l]});assert.equal(plan.status,'planned');assert.equal(plan.geometry.type,'polyline');assert.deepEqual(plan.geometry.vertices.map(({x,y})=>({x,y})),[{x:0,y:0},{x:3,y:2},{x:5,y:0},{x:10,y:0}])});
test('Split plans two Line pieces only for a valid interior on-entity point',()=>{const source=line({x:0,y:0},{x:10,y:0},'l'),plan=Split.planSplit({record:source,point:{x:4,y:0}});assert.equal(plan.status,'planned');assert.deepEqual(plan.replacement.geometry,{type:'line',start:source.start,end:{x:4,y:0}});assert.deepEqual(plan.creates[0].geometry,{type:'line',start:{x:4,y:0},end:source.end});assert.equal(Split.planSplit({record:source,point:{x:0,y:0}}).reason,'endpoint-split');assert.equal(Split.planSplit({record:source,point:{x:4,y:1}}).reason,'point-off-entity')});
test('Split plans two open Polyline records at an interior segment point',()=>{const source=poly([{x:0,y:0},{x:5,y:0},{x:5,y:5}],'p'),plan=Split.planSplit({record:source,point:{x:2,y:0}});assert.equal(plan.status,'planned');assert.deepEqual(plan.replacement.geometry.vertices.map(({x,y})=>({x,y})),[{x:0,y:0},{x:2,y:0}]);assert.deepEqual(plan.creates[0].geometry.vertices.map(({x,y})=>({x,y})),[{x:2,y:0},{x:5,y:0},{x:5,y:5}]);assert.equal(Split.planSplit({record:source,point:{x:5,y:0}}).reason,'ambiguous-point')});
test('Break removes the interior interval regardless of point order and rejects degeneracy',()=>{const source=line({x:0,y:0},{x:10,y:0},'l'),plan=Split.planBreak({record:source,firstPoint:{x:7,y:0},secondPoint:{x:2,y:0}});assert.equal(plan.status,'planned');assert.deepEqual(plan.replacement.geometry,{type:'line',start:source.start,end:{x:2,y:0}});assert.deepEqual(plan.creates[0].geometry,{type:'line',start:{x:7,y:0},end:source.end});assert.equal(Split.planBreak({record:source,firstPoint:{x:2,y:0},secondPoint:{x:2,y:0}}).reason,'degenerate-break');assert.equal(Split.planBreak({record:source,firstPoint:{x:0,y:0},secondPoint:{x:2,y:0}}).reason,'endpoint-break')});
