'use strict';const test=require('node:test');const assert=require('node:assert/strict');const {browser}=require('../helpers/browser.cjs');
const named=(name='ANSI31',extra='')=>`{kind:"named",name:"${name}",angle:0,scale:1,origin:{x:0,y:0}${extra}}`;

test('R6 registry validates five named patterns and rejects malformed metadata',async()=>{const b=await browser();assert.deepEqual(b.read('window.CaderactHatchPatterns.names'),['ANSI31','ANSI32','ANSI33','GRID','CROSS']);for(const expression of [`{kind:"named",name:"NOPE",angle:0,scale:1,origin:{x:0,y:0}}`,`{kind:"named",name:"ANSI31",angle:0,scale:0,origin:{x:0,y:0}}`,`{kind:"named",name:"ANSI31",angle:NaN,scale:1,origin:{x:0,y:0}}`,`{kind:"named",name:"ANSI31",angle:0,scale:1,origin:{x:Infinity,y:0}}`])assert.ok(b.read(`window.CaderactHatchPatterns.validate(${expression}).length`)>0)});

test('R6 ANSI31 rectangle generation is deterministic and semantically clipped',async()=>{const b=await browser();const result=b.read(`(()=>{const h=recordGateway.createHatch([recordGateway.createPolyline([{x:0,y:0},{x:20,y:0},{x:20,y:10},{x:0,y:10}],true)],${named()}),a=window.CaderactHatchGeometry.generatePattern(h),c=window.CaderactHatchGeometry.generatePattern(h);return{a,c}})()`);assert.equal(result.a.valid,true);assert.ok(result.a.segments.length>0);assert.deepEqual(result.a.segments,result.c.segments);for(const segment of result.a.segments)for(const point of [segment.start,segment.end]){assert.ok(point.x>=-1e-7&&point.x<=20+1e-7);assert.ok(point.y>=-1e-7&&point.y<=10+1e-7)}});

test('R6 multiple and dashed families generate deterministic fragments',async()=>{const b=await browser();for(const name of ['GRID','CROSS','ANSI33']){const result=b.read(`(()=>{const h=recordGateway.createHatch([recordGateway.createCircle({x:0,y:0},12)],${named(name)});return window.CaderactHatchGeometry.generatePattern(h)})()`);assert.equal(result.valid,true);assert.ok(result.segments.length>0);if(name!=='GRID')assert.ok(result.dashFragments>0)}});

test('R6 semantic clipping preserves holes islands circles ellipses and mixed arcs',async()=>{const b=await browser();const hole=b.read(`(()=>{const r=recordGateway.createRegion([recordGateway.createCircle({x:0,y:0},10),recordGateway.createCircle({x:0,y:0},4),recordGateway.createCircle({x:0,y:0},1)]),h=recordGateway.createHatch([r],${named('GRID')});return window.CaderactHatchGeometry.generatePattern(h)})()`);assert.equal(hole.valid,true);for(const segment of hole.segments){const mid={x:(segment.start.x+segment.end.x)/2,y:(segment.start.y+segment.end.y)/2},radius=Math.hypot(mid.x,mid.y);assert.equal(radius>1+1e-6&&radius<4-1e-6,false)}for(const source of [`[recordGateway.createEllipse({center:{x:0,y:0},majorAxis:{x:8,y:0},minorRadius:3})]`,`[recordGateway.createArc({center:{x:0,y:0},radius:4,start:{x:4,y:0},end:{x:-4,y:0},sweep:Math.PI}),recordGateway.createLine({x:-4,y:0},{x:4,y:0})]`])assert.equal(b.read(`window.CaderactHatchGeometry.generatePattern(recordGateway.createHatch(${source},${named()})).valid`),true)});

test('R6 angle scale origin and transforms update only semantic pattern metadata',async()=>{const b=await browser();const result=b.read(`(()=>{const h=recordGateway.createHatch([recordGateway.createCircle({x:2,y:3},5)],{kind:"named",name:"ANSI31",angle:.2,scale:2,origin:{x:1,y:1}});return{m:window.CaderactGeometryTransform.translateRecord(h,4,-2),r:window.CaderactGeometryTransform.rotateRecord(h,{x:0,y:0},.5),s:window.CaderactGeometryTransform.scaleRecord(h,{x:0,y:0},3),x:window.CaderactGeometryTransform.mirrorRecord(h,{x:0,y:0},{x:0,y:1})}})()`);assert.deepEqual(result.m.pattern.origin,{x:5,y:-1});assert.ok(Math.abs(result.r.pattern.angle-.7)<1e-12);assert.equal(result.s.pattern.scale,6);assert.ok(Number.isFinite(result.x.pattern.angle));for(const record of Object.values(result))assert.equal(record.pattern.name,'ANSI31')});

test('R6 persistence round-trips metadata without generated strokes',async()=>{const b=await browser();b.run(`window.__h=recordGateway.createHatch([recordGateway.createCircle({x:0,y:0},8)],{kind:"named",name:"CROSS",angle:.3,scale:2,origin:{x:1,y:-1}});recordGateway.createAll([window.__h]);window.__json=window.CaderactPersistence.serializeDocument(modelReader.snapshot());window.__loaded=window.CaderactPersistence.loadStore(window.__json)`);assert.equal(b.read('window.CaderactPersistence.serializeDocument(window.__loaded.reader.snapshot())'),b.read('window.__json'));assert.equal(b.read('/segments|candidateLines|dashFragments/.test(window.__json)'),false);assert.throws(()=>b.run('window.CaderactDxfExport.exportDocument(modelReader.snapshot())'),/unsupported native records/)});

test('R6 command exposes Solid Pattern name angle scale and creates named Hatch',async()=>{const b=await browser();b.run('window.__r=recordGateway.createRegion([recordGateway.createCircle({x:0,y:0},10)]);recordGateway.createAll([window.__r]);selection.selectOnly(window.__r.id)');b.launch('Hatch');b.run('window.caderactCommandRouter.activeSession.handleOption("pattern");window.caderactCommandRouter.activeSession.handleOption("grid");window.caderactCommandRouter.activeSession.handleOption("angle");window.caderactCommandRouter.activeSession.handleInput("30");window.caderactCommandRouter.activeSession.handleOption("scale");window.caderactCommandRouter.activeSession.handleInput("2")');b.key('Enter');const pattern=b.read('modelReader.records().find(record=>record.type==="hatch").pattern');assert.equal(pattern.kind,'named');assert.equal(pattern.name,'GRID');assert.ok(Math.abs(pattern.angle-Math.PI/6)<1e-12);assert.equal(pattern.scale,2);assert.deepEqual(pattern.origin,{x:0,y:0})});

test('R6 scene projects named segments while selection and measurement stay semantic',async()=>{const b=await browser();b.run(`camera.zoom=20;window.__h=recordGateway.createHatch([recordGateway.createRegion([recordGateway.createCircle({x:0,y:0},10),recordGateway.createCircle({x:0,y:0},4)])],${named('CROSS')});recordGateway.createAll([window.__h])`);b.flush();const scene=b.renders.at(-1);assert.equal(scene.solidFillOverlay.triangles.length,0);assert.ok(scene.propertyDrawGroups.some(group=>group.recordIds.includes(b.read('window.__h.id'))&&group.lineGroup.segments.length>0)||scene.lineGroups.some(group=>group.segments.length>0));assert.equal(b.read('window.CaderactMeasurement.measureRecord(window.__h).area'),84*Math.PI);assert.equal(b.read('window.CaderactSelection.hitTestRecords({screenPoint:worldToScreen(0,0),records:[window.__h],worldToScreen,screenToWorld}).hit'),false)});

test('R6 generation is source-order independent and refuses excessive candidate lines',async()=>{const b=await browser();const result=b.read(`(()=>{const points=[{x:0,y:0},{x:20,y:0},{x:20,y:10},{x:0,y:10}],a=recordGateway.createHatch([recordGateway.createPolyline(points,true)],${named()}),b=recordGateway.createHatch([recordGateway.createPolyline([...points].reverse(),true)],${named()}),ga=window.CaderactHatchGeometry.generatePattern(a),gb=window.CaderactHatchGeometry.generatePattern(b),dense=recordGateway.createHatch([recordGateway.createCircle({x:0,y:0},1)],{kind:"named",name:"ANSI31",angle:0,scale:1e-8,origin:{x:0,y:0}});return{a:ga.segments,b:gb.segments,limit:window.CaderactHatchGeometry.generatePattern(dense)}})()`);assert.deepEqual(result.a,result.b);assert.equal(result.limit.valid,false);assert.equal(result.limit.reason,'candidate-line-limit')});
