'use strict';const test=require('node:test');const assert=require('node:assert/strict');const {browser}=require('../helpers/browser.cjs');

test('R7 named angles are canonical and solid triangulation cannot become named-pattern authority',async()=>{const b=await browser();for(const angle of [-Math.PI,Math.PI+1e-12,Math.PI*4])assert.ok(b.read(`window.CaderactHatchPatterns.validate({kind:"named",name:"ANSI31",angle:${angle},scale:1,origin:{x:0,y:0}}).length`)>0);assert.deepEqual(b.read(`window.CaderactHatchGeometry.triangulate(recordGateway.createHatch([recordGateway.createCircle({x:0,y:0},2)],{kind:"named",name:"ANSI31",angle:0,scale:1,origin:{x:0,y:0}}))`),{valid:false,reason:'not-solid'})});

test('R7 chained transforms preserve valid topology and metadata while overflow rejects',async()=>{const b=await browser();const result=b.read(`(()=>{const h=recordGateway.createHatch([recordGateway.createRegion([recordGateway.createCircle({x:0,y:0},10),recordGateway.createCircle({x:0,y:0},3)])],{kind:"named",name:"ANSI33",angle:.25,scale:2,origin:{x:1,y:2}}),m=window.CaderactGeometryTransform.translateRecord(h,5,-4),r=window.CaderactGeometryTransform.rotateRecord(m,{x:0,y:0},.4),s=window.CaderactGeometryTransform.scaleRecord(r,{x:1,y:1},1.5),x=window.CaderactGeometryTransform.mirrorRecord(s,{x:-2,y:0},{x:3,y:4}),c=recordGateway.copyWithFreshIdentity(x);return{original:h,final:x,copy:c,errors:window.CaderactHatchGeometry.validate(x),generated:window.CaderactHatchGeometry.generatePattern(x)}})()`);assert.deepEqual(result.errors,[]);assert.equal(result.generated.valid,true);assert.deepEqual(result.original.pattern,{kind:'named',name:'ANSI33',angle:.25,scale:2,origin:{x:1,y:2}});assert.notEqual(result.copy.id,result.final.id);assert.notEqual(result.copy.loops[0].featureId,result.final.loops[0].featureId);assert.throws(()=>b.run(`window.CaderactGeometryTransform.scaleRecord(recordGateway.createHatch([recordGateway.createCircle({x:0,y:0},1)],{kind:"named",name:"ANSI31",angle:0,scale:1e308,origin:{x:0,y:0}}),{x:0,y:0},10)`),/Invalid/)});

test('R7 deep valid nesting is deterministic and excessive depth fails explicitly',async()=>{const b=await browser();const valid=b.read(`(()=>{const circles=Array.from({length:8},(_,i)=>recordGateway.createCircle({x:0,y:0},20-i*2)),a=recordGateway.createRegion(circles),b=recordGateway.createRegion([...circles].reverse());return{a:a.loops.map(x=>({depth:x.depth,parentIndex:x.parentIndex})),b:b.loops.map(x=>({depth:x.depth,parentIndex:x.parentIndex})),area:window.CaderactRegionGeometry.measure(a).area}})()`);assert.deepEqual(valid.a,valid.b);assert.ok(valid.area>0);assert.equal(b.read(`(()=>{const circles=Array.from({length:34},(_,i)=>recordGateway.createCircle({x:0,y:0},100-i));return window.CaderactBoundaryGeometry.classifyNesting(window.CaderactRegionGeometry.sourceLoops(circles)).reason})()`),'nesting-depth-limit')});

test('R7 persistence rejects duplicate topology IDs, derived fields, and malformed pattern state',async()=>{const b=await browser();b.run(`window.__h=recordGateway.createHatch([recordGateway.createPolyline([{x:0,y:0},{x:5,y:0},{x:5,y:5},{x:0,y:5}],true)],{kind:"named",name:"GRID",angle:0,scale:1,origin:{x:0,y:0}});recordGateway.createAll([window.__h]);window.__base=JSON.parse(window.CaderactPersistence.serializeDocument(modelReader.snapshot()))`);for(const mutation of [`d.document.records[0].loops[0].edges[1].featureId=d.document.records[0].loops[0].edges[0].featureId`,`d.document.records[0].segments=[]`,`d.document.records[0].pattern.name="UNKNOWN"`,`d.document.records[0].pattern.scale=0`,`d.document.records[0].pattern.angle=12`])assert.throws(()=>b.run(`(()=>{const d=JSON.parse(JSON.stringify(window.__base));${mutation};return window.CaderactPersistence.loadStore(JSON.stringify(d))})()`),/Invalid/)});

test('R7 failed Hatch generation and Escape remain history and document atomic',async()=>{const b=await browser();b.run('window.__r=recordGateway.createRegion([recordGateway.createCircle({x:0,y:0},1)]);recordGateway.createAll([window.__r]);selection.selectOnly(window.__r.id);window.__before=modelReader.snapshot();window.__history=documentController.historyInfo.entryCount');b.launch('Hatch');b.run('window.caderactCommandRouter.activeSession.handleOption("pattern");window.caderactCommandRouter.activeSession.handleOption("scale");window.caderactCommandRouter.activeSession.handleInput("0.00000001")');const failed=b.read('window.caderactCommandRouter.activeSession.finish()');assert.equal(failed.status,'invalid-input');assert.equal(failed.reason,'candidate-line-limit');assert.deepEqual(b.read('modelReader.snapshot()'),b.read('window.__before'));assert.equal(b.read('documentController.historyInfo.entryCount'),b.read('window.__history'));b.key('Escape');assert.equal(b.read('window.caderactCommandRouter.isActive'),false);assert.deepEqual(b.read('modelReader.snapshot()'),b.read('window.__before'))});

test('R7 Region and Hatch stay absent from Osnap Track while ordinary Endpoint remains authoritative',async()=>{const b=await browser();const result=b.read(`(()=>{const line=recordGateway.createLine({x:0,y:0},{x:10,y:0}),region=recordGateway.createRegion([recordGateway.createCircle({x:0,y:0},5)]),hatch=recordGateway.createHatch([region]),resolver=window.CaderactSnapResolver.createResolver(),args={worldToScreen:(x,y)=>({x,y}),gridSpacing:10,enabled:{endpoint:true,midpoint:true,center:true,intersection:true,nearest:true,grid:false}},snap=resolver.resolve({...args,rawWorldPoint:{x:0,y:0},records:[region,hatch,line]}),excluded=resolver.resolve({...args,rawWorldPoint:{x:5,y:0},records:[region,hatch]});return{snap,excluded}})()`);assert.equal(result.snap.kind,'endpoint');assert.equal(result.excluded.snapped,false)});

test('R7 named and solid scene data remain renderer-neutral and DXF rejection is atomic',async()=>{const b=await browser();b.run(`window.__solid=recordGateway.createHatch([recordGateway.createCircle({x:-5,y:0},3)]);window.__named=recordGateway.createHatch([recordGateway.createCircle({x:5,y:0},3)],{kind:"named",name:"CROSS",angle:.2,scale:1,origin:{x:0,y:0}});recordGateway.createAll([window.__solid,window.__named])`);b.flush();const scene=b.renders.at(-1);assert.ok(scene.solidFillOverlay.triangles.length>0);assert.ok(scene.propertyDrawGroups.some(group=>group.recordIds.includes(b.read('window.__named.id'))&&group.lineGroup.segments.length>0)||scene.lineGroups.some(group=>group.segments.length>0));const before=b.read('modelReader.snapshot()');assert.throws(()=>b.run('window.CaderactDxfExport.exportDocument(modelReader.snapshot())'),/unsupported native records/);assert.deepEqual(b.read('modelReader.snapshot()'),before)});
