'use strict';const test=require('node:test');const assert=require('node:assert/strict');const {browser}=require('../helpers/browser.cjs');
const area=t=>t.reduce((sum,[a,b,c])=>sum+Math.abs((b.x-a.x)*(c.y-a.y)-(b.y-a.y)*(c.x-a.x))/2,0);

test('R5 semantic Hatch snapshots Region loops and triangulates rectangle deterministically',async()=>{const b=await browser();const result=b.read(`(()=>{const r=recordGateway.createRegion([recordGateway.createPolyline([{x:0,y:0},{x:6,y:0},{x:6,y:4},{x:0,y:4}],true)]),h=recordGateway.createHatch([r]),a=window.CaderactHatchGeometry.triangulate(h),c=window.CaderactHatchGeometry.triangulate(h);return{r,h,a,c}})()`);assert.equal(result.h.type,'hatch');assert.deepEqual(result.h.pattern,{kind:'solid'});assert.notEqual(result.h.id,result.r.id);assert.notEqual(result.h.loops[0].featureId,result.r.loops[0].featureId);assert.equal(result.a.valid,true);assert.deepEqual(result.a.triangles,result.c.triangles);assert.equal(area(result.a.triangles),24)});

test('R5 hole/island parity is preserved by shared triangles',async()=>{const b=await browser();const result=b.read(`(()=>{const h=recordGateway.createHatch([recordGateway.createRegion([recordGateway.createCircle({x:0,y:0},10),recordGateway.createCircle({x:0,y:0},4),recordGateway.createCircle({x:0,y:0},1)])]),t=window.CaderactHatchGeometry.triangulate(h);return{h,t}})()`);assert.equal(result.t.valid,true);assert.ok(Math.abs(area(result.t.triangles)-85*Math.PI)<.2);for(const triangle of result.t.triangles){const p={x:(triangle[0].x+triangle[1].x+triangle[2].x)/3,y:(triangle[0].y+triangle[1].y+triangle[2].y)/3},r=Math.hypot(p.x,p.y);assert.equal(r>1&&r<4,false)}});

test('R5 direct boundaries include Circle Ellipse Polyline and mixed Line Arc',async()=>{const b=await browser();for(const expression of [`[recordGateway.createCircle({x:0,y:0},3)]`,`[recordGateway.createEllipse({center:{x:0,y:0},majorAxis:{x:5,y:0},minorRadius:2})]`,`[recordGateway.createPolyline([{x:0,y:0},{x:4,y:0},{x:0,y:3}],true)]`,`[recordGateway.createArc({center:{x:0,y:0},radius:2,start:{x:2,y:0},end:{x:-2,y:0},sweep:Math.PI}),recordGateway.createLine({x:-2,y:0},{x:2,y:0})]`])assert.equal(b.read(`window.CaderactHatchGeometry.triangulate(recordGateway.createHatch(${expression})).valid`),true)});

test('R5 Hatch command supports Region selection and R3 point discovery atomically',async()=>{const selected=await browser();selected.run(`window.__r=recordGateway.createRegion([recordGateway.createCircle({x:0,y:0},3)]);recordGateway.createAll([window.__r]);selection.selectOnly(window.__r.id)`);selected.launch('Hatch');selected.key('Enter');assert.equal(selected.read('modelReader.records().filter(x=>x.type==="hatch").length'),1);assert.equal(selected.read('documentController.historyInfo.entryCount'),2);selected.run('documentController.undo()');assert.equal(selected.read('modelReader.records().filter(x=>x.type==="hatch").length'),0);selected.run('documentController.redo()');assert.equal(selected.read('modelReader.records().filter(x=>x.type==="hatch").length'),1);
const point=await browser();point.run(`window.__s=[recordGateway.createLine({x:0,y:0},{x:4,y:0}),recordGateway.createLine({x:4,y:0},{x:4,y:3}),recordGateway.createLine({x:4,y:3},{x:0,y:3}),recordGateway.createLine({x:0,y:3},{x:0,y:0})];recordGateway.createAll(window.__s)`);point.launch('Hatch');point.run('window.caderactCommandRouter.activeSession.handleOption("point")');assert.equal(point.read('window.caderactCommandRouter.activeSession.handlePointerDown({x:2,y:1}).status'),'command-completed')});

test('R5 source ownership, transforms, grip and fresh Copy identities are independent',async()=>{const b=await browser();b.run(`window.__s=recordGateway.createCircle({x:0,y:0},4);window.__h=recordGateway.createHatch([window.__s]);window.__copy=recordGateway.copyWithFreshIdentity(window.__h);window.__moves=[window.CaderactGeometryTransform.translateRecord(window.__h,1,2),window.CaderactGeometryTransform.rotateRecord(window.__h,{x:0,y:0},.5),window.CaderactGeometryTransform.scaleRecord(window.__h,{x:0,y:0},2),window.CaderactGeometryTransform.mirrorRecord(window.__h,{x:0,y:0},{x:0,y:1})]`);assert.notEqual(b.read('window.__copy.id'),b.read('window.__h.id'));assert.notEqual(b.read('window.__copy.loops[0].featureId'),b.read('window.__h.loops[0].featureId'));assert.deepEqual(b.read('window.__moves.map(x=>window.CaderactHatchGeometry.validate(x).length)'),[0,0,0,0]);assert.equal(b.read('window.CaderactGrips.discoverRegionGrips([window.__h],[window.__h.id]).length'),1)});

test('R5 selection uses semantic fill, scene shares triangles, and Hatch emits no snaps',async()=>{const b=await browser();b.run(`camera.zoom=20;window.__h=recordGateway.createHatch([recordGateway.createRegion([recordGateway.createCircle({x:0,y:0},10),recordGateway.createCircle({x:0,y:0},4)])]);recordGateway.createAll([window.__h])`);assert.equal(b.read('window.CaderactSelection.hitTestRecords({screenPoint:worldToScreen(8,0),records:[window.__h],worldToScreen,screenToWorld}).hit'),true);assert.equal(b.read('window.CaderactSelection.hitTestRecords({screenPoint:worldToScreen(0,0),records:[window.__h],worldToScreen,screenToWorld}).hit'),false);b.flush();assert.ok(b.renders.at(-1).solidFillOverlay.triangles.length>0);assert.equal(b.read(`window.CaderactSnapResolver.createResolver().resolve({rawWorldPoint:{x:10,y:0},worldToScreen:(x,y)=>({x,y}),records:[window.__h],gridSpacing:10,enabled:{endpoint:true,midpoint:true,center:true,nearest:true,grid:false}}).snapped`),false)});

test('R5 persistence stores only semantics and DXF rejects Hatch explicitly',async()=>{const b=await browser();b.run(`window.__h=recordGateway.createHatch([recordGateway.createCircle({x:0,y:0},2)]);recordGateway.createAll([window.__h]);window.__json=window.CaderactPersistence.serializeDocument(modelReader.snapshot());window.__loaded=window.CaderactPersistence.loadStore(window.__json)`);assert.equal(b.read('window.CaderactPersistence.serializeDocument(window.__loaded.reader.snapshot())'),b.read('window.__json'));assert.equal(b.read('window.__json.includes("triangles")||window.__json.includes("contours")'),false);assert.throws(()=>b.run('window.CaderactDxfExport.exportDocument(modelReader.snapshot())'),/unsupported native records/)});

test('R5 flattening refuses excessive subdivision before allocation',async()=>{const b=await browser();assert.equal(b.read(`(()=>{const h=recordGateway.createHatch([recordGateway.createCircle({x:0,y:0},1e12)]);return window.CaderactHatchGeometry.flatten(h,{tolerance:1e-12}).reason})()`),'vertex-limit')});
