// PS4: deterministic renderer-neutral Layout plot scene in physical page millimetres.
(() => {
  const freeze=value=>Object.freeze(value)
  function color(value,mode){if(mode==="monochrome")return"#000000";if(mode!=="grayscale")return value;const match=/^#([0-9a-f]{6})$/i.exec(value||"");if(!match)return"#000000";const n=parseInt(match[1],16),r=n>>16,g=n>>8&255,b=n&255,y=Math.round(.2126*r+.7152*g+.0722*b).toString(16).padStart(2,"0");return`#${y}${y}${y}`}
  function intersect(a,b){const left=Math.max(a.x,b.x),bottom=Math.max(a.y,b.y),right=Math.min(a.x+a.width,b.x+b.width),top=Math.min(a.y+a.height,b.y+b.height);return right>left&&top>bottom?{x:left,y:bottom,width:right-left,height:top-bottom}:null}
  function clip(a,b,box){let t0=0,t1=1,dx=b.x-a.x,dy=b.y-a.y;for(const [p,q] of [[-dx,a.x-box.x],[dx,box.x+box.width-a.x],[-dy,a.y-box.y],[dy,box.y+box.height-a.y]]){if(p===0&&q<0)return null;if(p!==0){const r=q/p;if(p<0){if(r>t1)return null;t0=Math.max(t0,r)}else{if(r<t0)return null;t1=Math.min(t1,r)}}}return[{x:a.x+t0*dx,y:a.y+t0*dy},{x:a.x+t1*dx,y:a.y+t1*dy}]}
  function pairs(record){const result=[];if(record.type==="line")result.push([record.start,record.end]);else if(record.type==="polyline"){const count=record.closed?record.vertices.length:record.vertices.length-1;for(let i=0;i<count;i++)result.push([record.vertices[i],record.vertices[(i+1)%record.vertices.length]])}else if(record.type==="circle"||record.type==="arc"||record.type==="ellipse"){const count=record.type==="arc"?64:96,major=record.type==="ellipse"?Math.hypot(record.majorAxis.x,record.majorAxis.y):record.radius,minor=record.type==="ellipse"?record.minorRadius:record.radius,rotation=record.type==="ellipse"?Math.atan2(record.majorAxis.y,record.majorAxis.x):0,start=record.type==="arc"?Math.atan2(record.start.y-record.center.y,record.start.x-record.center.x):0,sweep=record.type==="arc"?record.sweep:Math.PI*2,point=t=>({x:record.center.x+Math.cos(t)*major*Math.cos(rotation)-Math.sin(t)*minor*Math.sin(rotation),y:record.center.y+Math.cos(t)*major*Math.sin(rotation)+Math.sin(t)*minor*Math.cos(rotation)});for(let i=0;i<count;i++)result.push([point(start+sweep*i/count),point(start+sweep*(i+1)/count)])}return result}
  function presentation(record,style,unit){if(record.type?.startsWith("dimension-")){const value=window.CaderactDimensionGeometry.derive(record,style||window.CaderactDocument.DEFAULT_DIMENSION_STYLE,{length:unit});if(!value.supported)return{pairs:[],text:null};const lines=[...value.lines];for(const arc of value.arcs||[]){const count=64;for(let i=0;i<count;i++){const point=t=>({x:arc.center.x+Math.cos(t)*arc.radius,y:arc.center.y+Math.sin(t)*arc.radius});lines.push([point(arc.startAngle+arc.sweep*i/count),point(arc.startAngle+arc.sweep*(i+1)/count)])}}for(const triangle of value.triangles||[])for(let i=0;i<triangle.length;i++)lines.push([triangle[i],triangle[(i+1)%triangle.length]]);return{pairs:lines,text:value.text&&value.text.value?{point:value.text.point,value:value.text.value,height:value.text.height,rotation:value.text.rotation,alignment:"center"}:null}}if(record.type==="text"){const value=window.CaderactAnnotationGeometry.derive(record);return{pairs:[],text:value.supported?{point:value.annotation.point,value:value.annotation.text,height:value.annotation.height,rotation:value.annotation.rotation,alignment:value.annotation.horizontalAlignment}:null}}return{pairs:pairs(record),text:null}}
  function create({layout,job:jobInput,records,layers,documentUnit,dimensionStyles={}}){const page=window.CaderactPaperSpace.derive(layout);if(!page.valid)throw new Error("Invalid Page Setup");const normalized=window.CaderactPlotJob.normalize(jobInput||window.CaderactPlotJob.defaults());if(normalized.status!=="ready")throw new Error("Invalid Plot Job");const job=normalized.job,offset=job.position==="offset"?job.offset:{x:0,y:0},colorMode=window.CaderactPlotJob.sceneColorMode(job),printable={x:page.printable.left,y:page.printable.bottom,width:page.printable.width,height:page.printable.height},byLayer=new Map((layers||[]).map(layer=>[layer.id,layer])),segments=[],texts=[];for(const viewportId of layout.viewportOrder){const viewport=layout.viewports[viewportId],frame={x:viewport.frame.x+offset.x,y:viewport.frame.y+offset.y,width:viewport.frame.width,height:viewport.frame.height},clipBox=intersect(frame,printable);if(!clipBox)continue;for(const record of records||[]){const layer=byLayer.get(record.layerId);if(layer?.visible===false)continue;const stroke=color(window.CaderactObjectProperties.effectiveColor(record,layer),colorMode),content=presentation(record,dimensionStyles[record.dimensionStyleId],documentUnit);for(const pair of content.pairs){const a=window.CaderactPaperSpace.projectModelPoint(pair[0],viewport,documentUnit),b=window.CaderactPaperSpace.projectModelPoint(pair[1],viewport,documentUnit),shiftedA={x:a.x+offset.x,y:a.y+offset.y},shiftedB={x:b.x+offset.x,y:b.y+offset.y},line=clip(shiftedA,shiftedB,clipBox);if(line)segments.push(freeze({viewportId,recordId:record.id,start:freeze(line[0]),end:freeze(line[1]),color:stroke}))}if(content.text){const anchor=window.CaderactPaperSpace.projectModelPoint(content.text.point,viewport,documentUnit),point={x:anchor.x+offset.x,y:anchor.y+offset.y};if(point.x>=clipBox.x&&point.x<=clipBox.x+clipBox.width&&point.y>=clipBox.y&&point.y<=clipBox.y+clipBox.height)texts.push(freeze({viewportId,recordId:record.id,point:freeze(point),value:content.text.value,height:content.text.height*window.CaderactUnits.conversionFactor(documentUnit,"mm")/viewport.scale,rotation:content.text.rotation,alignment:content.text.alignment,color:stroke}))}}}return freeze({unit:"mm",layoutId:layout.id,page:freeze({...page.sheet}),printable:freeze({...printable}),plot:freeze({job,area:job.area,scale:1,placement:job.position,offset:freeze({...job.offset}),colorMode}),segments:freeze(segments),texts:freeze(texts)})}
  window.CaderactPlotScene=freeze({create,transformColor:color})
})()
