// PLOT2: deterministic renderer-neutral Layout output in physical page millimetres.
(() => {
  const freeze=value=>Object.freeze(value)
  const OUTPUT_DASH_MM=freeze({continuous:freeze([]),dashed:freeze([4,2]),dotted:freeze([.5,1.5]),"dash-dot":freeze([4,1.5,.5,1.5])})
  function color(value,mode){if(mode==="monochrome")return"#000000";if(mode!=="grayscale")return value;const match=/^#([0-9a-f]{6})$/i.exec(value||"");if(!match)return"#000000";const n=parseInt(match[1],16),r=n>>16,g=n>>8&255,b=n&255,y=Math.round(.2126*r+.7152*g+.0722*b).toString(16).padStart(2,"0");return`#${y}${y}${y}`}
  function intersect(a,b){const left=Math.max(a.x,b.x),bottom=Math.max(a.y,b.y),right=Math.min(a.x+a.width,b.x+b.width),top=Math.min(a.y+a.height,b.y+b.height);return right>left&&top>bottom?{x:left,y:bottom,width:right-left,height:top-bottom}:null}
  function clip(a,b,box){let t0=0,t1=1,dx=b.x-a.x,dy=b.y-a.y;for(const [p,q] of [[-dx,a.x-box.x],[dx,box.x+box.width-a.x],[-dy,a.y-box.y],[dy,box.y+box.height-a.y]]){if(p===0&&q<0)return null;if(p!==0){const r=q/p;if(p<0){if(r>t1)return null;t0=Math.max(t0,r)}else{if(r<t0)return null;t1=Math.min(t1,r)}}}return[{x:a.x+t0*dx,y:a.y+t0*dy},{x:a.x+t1*dx,y:a.y+t1*dy}]}
  function clipPolygon(points,box){let output=points;const edges=[{inside:p=>p.x>=box.x,point:(a,b)=>{const t=(box.x-a.x)/(b.x-a.x);return{x:box.x,y:a.y+(b.y-a.y)*t}}},{inside:p=>p.x<=box.x+box.width,point:(a,b)=>{const x=box.x+box.width,t=(x-a.x)/(b.x-a.x);return{x,y:a.y+(b.y-a.y)*t}}},{inside:p=>p.y>=box.y,point:(a,b)=>{const t=(box.y-a.y)/(b.y-a.y);return{x:a.x+(b.x-a.x)*t,y:box.y}}},{inside:p=>p.y<=box.y+box.height,point:(a,b)=>{const y=box.y+box.height,t=(y-a.y)/(b.y-a.y);return{x:a.x+(b.x-a.x)*t,y}}}];for(const edge of edges){const input=output;output=[];for(let i=0;i<input.length;i++){const a=input[i],b=input[(i+1)%input.length],ain=edge.inside(a),bin=edge.inside(b);if(ain&&bin)output.push(b);else if(ain&&!bin)output.push(edge.point(a,b));else if(!ain&&bin)output.push(edge.point(a,b),b)}}return output}
  function curveDescriptor(record){if(record.type!=="circle"&&record.type!=="arc"&&record.type!=="ellipse")return null;return{kind:record.type==="arc"?"arc":"ellipse",center:record.center,majorRadius:record.type==="ellipse"?Math.hypot(record.majorAxis.x,record.majorAxis.y):record.radius,minorRadius:record.type==="ellipse"?record.minorRadius:record.radius,rotation:record.type==="ellipse"?Math.atan2(record.majorAxis.y,record.majorAxis.x):0,startAngle:record.type==="arc"?Math.atan2(record.start.y-record.center.y,record.start.x-record.center.x):0,sweep:record.type==="arc"?record.sweep:Math.PI*2}}
  function exactPairs(record){const result=[];if(record.type==="line")result.push([record.start,record.end]);else if(record.type==="polyline"){const count=record.closed?record.vertices.length:record.vertices.length-1;for(let i=0;i<count;i++)result.push([record.vertices[i],record.vertices[(i+1)%record.vertices.length]])}return result}
  function sampledCurvePairs(curve,count=128){const result=[],point=t=>({x:curve.center.x+Math.cos(t)*curve.majorRadius*Math.cos(curve.rotation)-Math.sin(t)*curve.minorRadius*Math.sin(curve.rotation),y:curve.center.y+Math.cos(t)*curve.majorRadius*Math.sin(curve.rotation)+Math.sin(t)*curve.minorRadius*Math.cos(curve.rotation)});for(let i=0;i<count;i++)result.push([point(curve.startAngle+curve.sweep*i/count),point(curve.startAngle+curve.sweep*(i+1)/count)]);return result}
  function boundaryPairs(record){const result=[];for(const loop of record.loops||[])for(const edge of loop.edges||[]){const points=window.CaderactRegionGeometry.sampleEdge(edge);for(let i=1;i<points.length;i++)result.push([points[i-1],points[i]])}return result}
  function presentation(record,style,unit){
    if(record.type?.startsWith("dimension-")){const value=window.CaderactDimensionGeometry.derive(record,style||window.CaderactDocument.DEFAULT_DIMENSION_STYLE,{length:unit});if(!value.supported)return{pairs:[],triangles:[],texts:[]};const lines=[...value.lines];for(const arc of value.arcs||[]){const point=t=>({x:arc.center.x+Math.cos(t)*arc.radius,y:arc.center.y+Math.sin(t)*arc.radius});for(let i=0;i<96;i++)lines.push([point(arc.startAngle+arc.sweep*i/96),point(arc.startAngle+arc.sweep*(i+1)/96)])}return{pairs:lines,triangles:value.triangles||[],texts:value.text?.value?[{point:value.text.point,value:value.text.value,height:value.text.height,rotation:value.text.rotation,alignment:"center"}]:[]}}
    if(record.type==="text"){const value=window.CaderactAnnotationGeometry.derive(record);return{pairs:[],triangles:[],texts:value.supported?[{point:value.annotation.point,value:value.annotation.text,height:value.annotation.height,rotation:value.annotation.rotation,alignment:value.annotation.horizontalAlignment}]:[]}}
    if(record.type==="region")return{pairs:boundaryPairs(record),triangles:[],texts:[]}
    if(record.type==="hatch"){const derived=record.pattern.kind==="named"?window.CaderactHatchGeometry.generatePattern(record):window.CaderactHatchGeometry.triangulate(record);if(!derived.valid)return{pairs:[],triangles:[],texts:[]};return record.pattern.kind==="named"?{pairs:derived.segments.map(segment=>[segment.start,segment.end]),triangles:[],texts:[]}:{pairs:[],triangles:derived.triangles,texts:[]}}
    const curve=curveDescriptor(record);return{pairs:curve?[]:exactPairs(record),curves:curve?[curve]:[],triangles:[],texts:[]}
  }
  function expanded(records,document){const output=[];for(const record of records||[]){if(record.type!=="block-instance"){output.push({record,sourceRecordId:record.id});continue}if(!document)continue;try{for(const entry of window.CaderactBlockTraversal.traverse(document,record).entries)output.push({record:Object.freeze({...window.CaderactGeometryTransform.similarityRecord(entry.record,entry.transform),id:entry.semanticId}),sourceRecordId:record.id})}catch{}}return output}
  function create({layout,job:jobInput,records,layers,document,documentUnit,dimensionStyles={}}){
    const page=window.CaderactPaperSpace.derive(layout);if(!page.valid)throw new Error("Invalid Page Setup");const normalized=window.CaderactPlotJob.normalize(jobInput||window.CaderactPlotJob.defaults());if(normalized.status!=="ready")throw new Error("Invalid Plot Job")
    const job=normalized.job,offset=job.position==="offset"?job.offset:{x:0,y:0},colorMode=window.CaderactPlotJob.sceneColorMode(job),printable={x:page.printable.left,y:page.printable.bottom,width:page.printable.width,height:page.printable.height},byLayer=new Map((layers||[]).map(layer=>[layer.id,layer])),segments=[],curves=[],fills=[],texts=[]
    for(const viewportId of layout.viewportOrder){const viewport=layout.viewports[viewportId],frame={x:viewport.frame.x+offset.x,y:viewport.frame.y+offset.y,width:viewport.frame.width,height:viewport.frame.height},clipBox=intersect(frame,printable);if(!clipBox)continue
      for(const item of expanded(records,document)){const record=item.record,layer=byLayer.get(record.layerId);if(layer?.visible===false)continue;const stroke=color(window.CaderactObjectProperties.effectiveColor(record,layer),colorMode),linetype=window.CaderactObjectProperties.effectiveLinetype(record,layer),lineweight=window.CaderactObjectProperties.effectiveLineweight(record,layer),content=presentation(record,dimensionStyles[record.dimensionStyleId],documentUnit)
        const project=value=>{const point=window.CaderactPaperSpace.projectModelPoint(value,viewport,documentUnit);return{x:point.x+offset.x,y:point.y+offset.y}}
        for(const pair of content.pairs){const line=clip(project(pair[0]),project(pair[1]),clipBox);if(line)segments.push(freeze({viewportId,recordId:record.id,sourceRecordId:item.sourceRecordId,start:freeze(line[0]),end:freeze(line[1]),color:stroke,linetype,lineweight,dashPattern:OUTPUT_DASH_MM[linetype]||OUTPUT_DASH_MM.continuous}))}
        for(const source of content.curves||[]){const factor=window.CaderactUnits.conversionFactor(documentUnit,"mm")/viewport.scale,projected=freeze({viewportId,recordId:record.id,sourceRecordId:item.sourceRecordId,kind:source.kind,center:freeze(project(source.center)),majorRadius:source.majorRadius*factor,minorRadius:source.minorRadius*factor,rotation:source.rotation,startAngle:source.startAngle,sweep:source.sweep,color:stroke,linetype,lineweight,dashPattern:OUTPUT_DASH_MM[linetype]||OUTPUT_DASH_MM.continuous}),inside=sampledCurvePairs(projected).every(pair=>pair.every(point=>point.x>=clipBox.x&&point.x<=clipBox.x+clipBox.width&&point.y>=clipBox.y&&point.y<=clipBox.y+clipBox.height));if(inside)curves.push(projected);else for(const pair of sampledCurvePairs(source)){const line=clip(project(pair[0]),project(pair[1]),clipBox);if(line)segments.push(freeze({viewportId,recordId:record.id,sourceRecordId:item.sourceRecordId,start:freeze(line[0]),end:freeze(line[1]),color:stroke,linetype,lineweight,dashPattern:OUTPUT_DASH_MM[linetype]||OUTPUT_DASH_MM.continuous}))}}
        for(const triangle of content.triangles){const points=clipPolygon(triangle.map(project),clipBox);if(points.length>=3)fills.push(freeze({viewportId,recordId:record.id,sourceRecordId:item.sourceRecordId,points:freeze(points.map(freeze)),color:stroke}))}
        for(const text of content.texts){const point=project(text.point);if(point.x>=clipBox.x&&point.x<=clipBox.x+clipBox.width&&point.y>=clipBox.y&&point.y<=clipBox.y+clipBox.height)texts.push(freeze({viewportId,recordId:record.id,sourceRecordId:item.sourceRecordId,point:freeze(point),value:text.value,height:text.height*window.CaderactUnits.conversionFactor(documentUnit,"mm")/viewport.scale,rotation:text.rotation,alignment:text.alignment,color:stroke}))}
      }
    }
    return freeze({unit:"mm",layoutId:layout.id,page:freeze({...page.sheet}),printable:freeze({...printable}),plot:freeze({job,area:job.area,scale:1,placement:job.position,offset:freeze({...job.offset}),colorMode,modelViewFrames:"excluded",hiddenLayers:"excluded",lockedObjects:"included"}),segments:freeze(segments),curves:freeze(curves),fills:freeze(fills),texts:freeze(texts)})
  }
  window.CaderactPlotScene=freeze({create,transformColor:color,OUTPUT_DASH_MM})
})()
