// DXF5/GB10: deterministic renderer-neutral ASCII DXF export.
(()=>{
const VERSION="AC1018",UNITS={in:1,ft:2,mm:4,cm:5,m:6},LTYPE={continuous:"CONTINUOUS",dashed:"DASHED",dotted:"DOTTED","dash-dot":"DASHDOT"},PATTERNS={CONTINUOUS:[0,[]],DASHED:[.75,[.5,-.25]],DOTTED:[.25,[0,-.25]],DASHDOT:[.9,[.5,-.2,0,-.2]]}
class DxfExportError extends Error{constructor(message,diagnostics){super(message);this.name="DxfExportError";this.diagnostics=Object.freeze(diagnostics)}}
function number(value){if(!Number.isFinite(value))throw new Error("DXF export requires finite numbers.");return Object.is(value,-0)?"0":String(value)}
function integer(value){if(!Number.isSafeInteger(value))throw new Error("DXF export requires safe integers.");return String(value)}
const trueColor=color=>Number.parseInt(color.slice(1),16)
function encodeText(value){let output="";for(let i=0;i<value.length;i++){const code=value.charCodeAt(i),character=value[i];output+=code>=32&&code<=126&&character!=="\\"?character:`\\U+${code.toString(16).toUpperCase().padStart(4,"0")}`}return output}
function exportDocument(document){
 const errors=window.CaderactDocument.validateDocument(document);if(errors.length)throw new DxfExportError(`Cannot export invalid document: ${errors.join("; ")}`,[])
 const unitCode=UNITS[document.units.length];if(!unitCode)throw new DxfExportError(`Unsupported DXF export unit ${document.units.length}.`,[])
 const collector=window.CaderactDxfDiagnostics.createCollector(window.CaderactDxfLimits.DEFAULTS.maxDiagnostics),sortName=(a,b)=>a.name.localeCompare(b.name,undefined,{sensitivity:"base"})||a.name.localeCompare(b.name)
 const layers=Object.values(document.layers).sort(sortName),layerNames=new Map(layers.map(v=>[v.id,v.name])),styles=document.dimensionStyleOrder.map(id=>document.dimensionStyles[id]).sort(sortName),styleNames=new Map(styles.map(v=>[v.id,v.name]))
 const definitions=Object.values(document.blockDefinitions||{}).sort(sortName),definitionNames=new Map(definitions.map(v=>[v.id,v.name]));if(definitions.some(v=>v.name.startsWith("*")))throw new DxfExportError("DXF user Block names may not begin with *.",[])
 const model=Object.values(document.geometry.objects),members=definitions.flatMap(d=>d.recordOrder.map(id=>d.records[id])),all=[...model,...members],supported=new Set(["line","polyline","circle","arc","ellipse","text","dimension-linear","dimension-angular","dimension-radial","block-instance"]),unsupported=all.filter(r=>!supported.has(r.type))
 if(unsupported.length){for(const r of unsupported)collector.add({severity:"error",code:"DXF_EXPORT_UNSUPPORTED_RECORD",message:`DXF cannot export native ${r.type} records.`,entityType:r.type});throw new DxfExportError("DXF export contains unsupported native records.",collector.snapshot())}
 const controlledDimensions=all.filter(r=>r.type.startsWith("dimension-")&&((r.prefixOverride??null)!==null||(r.suffixOverride??null)!==null||(r.toleranceMode??"none")!=="none"||(r.textPositionMode??"automatic")!=="automatic"))
 if(controlledDimensions.length){for(const r of controlledDimensions)collector.add({severity:"error",code:"DXF_EXPORT_DIMENSION_CONTROL_UNSUPPORTED",message:"DXF export cannot preserve this dimension's prefix, suffix, tolerance, or manual text placement.",entityType:r.type});throw new DxfExportError("DXF export contains dimension controls that cannot be represented faithfully.",collector.snapshot())}
 const key=r=>JSON.stringify({...r,id:null,layerId:layerNames.get(r.layerId),dimensionStyleId:styleNames.get(r.dimensionStyleId),definitionId:definitionNames.get(r.definitionId)},(k,v)=>k==="featureId"?undefined:v),records=model.sort((a,b)=>`${a.type}\0${key(a)}`.localeCompare(`${b.type}\0${key(b)}`))
 const dimensions=all.filter(r=>r.type.startsWith("dimension-")),dimensionBlocks=new Map(dimensions.map((r,i)=>[r.id,`*D${i+1}`])),pairs=[],add=(code,value)=>pairs.push(String(code),String(value))
 const common=r=>{const layer=layerNames.get(r.layerId);if(!layer)throw new DxfExportError("Invalid layer reference.",[]);add(8,layer);if(r.color===null)add(62,256);else{add(62,7);add(420,integer(trueColor(r.color)))}add(6,r.linetype===null?"BYLAYER":LTYPE[r.linetype]);add(370,r.lineweight===null?-1:Math.round(r.lineweight*100))}
 const point=(base,p)=>{add(base,number(p.x));add(base+10,number(p.y));add(base+20,0)}
 function entity(r){
  add(0,r.type==="line"?"LINE":r.type==="polyline"?"LWPOLYLINE":r.type.startsWith("dimension-")?"DIMENSION":r.type==="block-instance"?"INSERT":r.type.toUpperCase());common(r)
  if(r.type==="line"){point(10,r.start);point(11,r.end)}
  else if(r.type==="polyline"){add(90,r.vertices.length);add(70,r.closed?1:0);for(const v of r.vertices){add(10,number(v.x));add(20,number(v.y))}}
  else if(r.type==="circle"){point(10,r.center);add(40,number(r.radius))}
  else if(r.type==="arc"){let start=Math.atan2(r.start.y-r.center.y,r.start.x-r.center.x),end=start+r.sweep;if(r.sweep<0){start=Math.atan2(r.end.y-r.center.y,r.end.x-r.center.x);end=start-r.sweep;collector.add({severity:"warning",code:"DXF_ARC_DIRECTION_CANONICALIZED",message:"Exported clockwise Arc as equivalent counterclockwise locus.",entityType:"ARC"})}point(10,r.center);add(40,number(r.radius));add(50,number(start*180/Math.PI));add(51,number(end*180/Math.PI))}
  else if(r.type==="ellipse"){const major=Math.hypot(r.majorAxis.x,r.majorAxis.y),ratio=r.minorRadius/major;if(ratio>1)throw new DxfExportError("DXF ELLIPSE major axis is invalid.",[]);point(10,r.center);point(11,r.majorAxis);add(40,number(ratio));add(41,0);add(42,number(Math.PI*2))}
  else if(r.type==="text"){const j={left:0,center:1,right:2}[r.horizontalAlignment];point(10,r.insertionPoint);add(40,number(r.height));add(1,encodeText(r.text));add(50,number(r.rotation*180/Math.PI));add(72,j);add(73,0);if(j)point(11,r.insertionPoint)}
  else if(r.type==="block-instance"){add(2,definitionNames.get(r.definitionId));point(10,r.insertionPoint);add(41,number(r.mirrored?-r.scale:r.scale));add(42,number(r.scale));add(43,1);add(50,number(r.rotation*180/Math.PI))}
  else{add(2,dimensionBlocks.get(r.id));add(3,styleNames.get(r.dimensionStyleId));if(r.textOverride!==null)add(1,encodeText(r.textOverride));if(r.type==="dimension-linear"){add(70,r.mode==="aligned"?33:32);point(10,r.dimensionLinePoint);point(13,r.firstPoint);point(14,r.secondPoint);if(r.mode!=="aligned")add(50,r.mode==="vertical"?90:0)}else if(r.type==="dimension-angular"){add(70,37);point(10,r.dimensionArcPoint);point(13,r.firstRayPoint);point(14,r.secondRayPoint);point(15,r.vertex)}else{add(70,r.mode==="diameter"?35:36);point(10,r.mode==="diameter"?{x:2*r.centerPoint.x-r.dimensionPoint.x,y:2*r.centerPoint.y-r.dimensionPoint.y}:r.centerPoint);point(11,r.leaderPoint);point(15,r.dimensionPoint);add(40,number(Math.hypot(r.leaderPoint.x-r.dimensionPoint.x,r.leaderPoint.y-r.dimensionPoint.y)))}}
 }
 add(0,"SECTION");add(2,"HEADER");add(9,"$ACADVER");add(1,VERSION);add(9,"$INSUNITS");add(70,unitCode);add(9,"$CLAYER");add(8,layerNames.get(document.currentLayerId));add(9,"$DIMSTYLE");add(2,styleNames.get(document.currentDimensionStyleId));add(0,"ENDSEC")
 add(0,"SECTION");add(2,"TABLES");add(0,"TABLE");add(2,"LTYPE");add(70,Object.keys(PATTERNS).length);for(const [name,[length,values]] of Object.entries(PATTERNS)){add(0,"LTYPE");add(2,name);add(70,0);add(3,name);add(72,65);add(73,values.length);add(40,number(length));for(const value of values)add(49,number(value))}add(0,"ENDTAB")
 add(0,"TABLE");add(2,"LAYER");add(70,layers.length);for(const l of layers){add(0,"LAYER");add(2,l.name);add(70,l.locked?4:0);add(62,l.visible?7:-7);add(420,integer(trueColor(l.color)));add(6,LTYPE[l.linetype]);add(370,Math.round(l.lineweight*100))}add(0,"ENDTAB")
 add(0,"TABLE");add(2,"DIMSTYLE");add(70,styles.length);for(const s of styles){if(s.prefix!==""||s.suffix!==""||s.showUnit!==true||s.arrowStyle!=="closed-filled")throw new DxfExportError(`Dimension style ${s.name} uses formatting not representable by DXF6.`,[{severity:"error",code:"DXF_EXPORT_DIMSTYLE_FORMAT_UNSUPPORTED",message:`Cannot export custom dimension formatting for ${s.name}.`,entityType:"DIMSTYLE"}]);add(0,"DIMSTYLE");add(2,s.name);add(70,0);add(41,number(s.arrowSize));add(42,number(s.extensionGap));add(44,number(s.extensionBeyond));add(140,number(s.textHeight));add(147,number(s.textGap));add(271,integer(s.linearPrecision));add(179,integer(s.angularPrecision))}add(0,"ENDTAB");add(0,"ENDSEC")
 add(0,"SECTION");add(2,"BLOCKS");for(const d of definitions){add(0,"BLOCK");add(8,"0");add(2,d.name);add(70,0);point(10,d.basePoint);add(3,d.name);add(1,"");for(const id of d.recordOrder)entity(d.records[id]);add(0,"ENDBLK");add(8,"0")}for(const r of dimensions){const name=dimensionBlocks.get(r.id);add(0,"BLOCK");add(8,layerNames.get(r.layerId));add(2,name);add(70,1);point(10,{x:0,y:0});add(3,name);add(1,"");add(0,"ENDBLK");add(8,layerNames.get(r.layerId))}add(0,"ENDSEC")
 add(0,"SECTION");add(2,"ENTITIES");for(const r of records)entity(r);add(0,"ENDSEC");add(0,"EOF")
 return Object.freeze({text:`${pairs.join("\n")}\n`,diagnostics:collector.snapshot(),exportedCount:records.length,version:VERSION,unit:document.units.length})
}
window.CaderactDxfExport=Object.freeze({exportDocument,number,encodeText,VERSION,DxfExportError})
})()
