'use strict';
const test=require('node:test');
const assert=require('node:assert/strict');
const {browser}=require('../helpers/browser.cjs');

function create(b,extra=''){return b.read(`(()=>{const record=recordGateway.createLinearDimension({mode:'aligned',firstPoint:{x:0,y:0},secondPoint:{x:3,y:4},dimensionLinePoint:{x:0,y:7}${extra}});recordGateway.createAll([record]);return record})()`)}

test('AN3 prefix suffix and tolerance formatting remain semantic and precision controlled',async()=>{const b=await browser();b.window.__style=b.read('({...modelReader.dimensionStyle(),showUnit:false,linearPrecision:2,prefix:"S",suffix:"E"})');b.window.__measurement={kind:'linear',value:5};assert.equal(b.run('window.CaderactDimensionFormatter.format(window.__measurement,window.__style,{length:"mm"},{textOverride:null,prefixOverride:"[",suffixOverride:"]",toleranceMode:"symmetric",toleranceUpper:.125,toleranceLower:0})'),'[5.00] ±0.13');assert.equal(b.run('window.CaderactDimensionFormatter.format(window.__measurement,window.__style,{length:"mm"},{textOverride:null,prefixOverride:null,suffixOverride:null,toleranceMode:"deviation",toleranceUpper:.2,toleranceLower:.05})'),'S5.00E +0.20 / -0.05');assert.equal(b.run('window.CaderactDimensionFormatter.format(window.__measurement,window.__style,{length:"mm"},{textOverride:"EXACT",prefixOverride:"[",toleranceMode:"symmetric",toleranceUpper:1})'),'EXACT')});

test('AN3 native defaults validate and malformed tolerance or placement fails atomically',async()=>{const b=await browser(),record=create(b);assert.deepEqual({prefix:record.prefixOverride,suffix:record.suffixOverride,tolerance:record.toleranceMode,placement:record.textPositionMode,manual:record.manualTextPosition},{prefix:null,suffix:null,tolerance:'none',placement:'automatic',manual:null});b.window.__record=record;const before=b.read('modelReader.snapshot()'),history=b.read('documentController.historyInfo.entryCount');assert.notEqual(b.read('recordGateway.replace(window.__record.id,{...window.__record,toleranceMode:"symmetric",toleranceUpper:-1}).status'),'committed');assert.deepEqual(b.read('modelReader.snapshot()'),before);assert.equal(b.read('documentController.historyInfo.entryCount'),history);assert.notEqual(b.read('recordGateway.replace(window.__record.id,{...window.__record,textPositionMode:"manual",manualTextPosition:null}).status'),'committed')});

test('AN3 manual text placement is one semantic grip and transforms with the dimension',async()=>{const b=await browser(),record=create(b);b.window.__id=record.id;assert.equal(b.read('recordGateway.setDimensionTextPosition(window.__id,{x:11,y:12}).status'),'committed');const placed=b.read('modelReader.records()[0]');assert.equal(placed.textPositionMode,'manual');assert.ok(placed.manualTextPosition.featureId);b.window.__placed=placed;const presentation=b.read('window.CaderactDimensionGeometry.derive(window.__placed,modelReader.resolveDimensionStyle(window.__placed),modelReader.units())');assert.deepEqual(presentation.text.point,{x:11,y:12});assert.equal(presentation.grips.at(-1).kind,'manualTextPosition');b.run('window.__moved=window.CaderactGeometryTransform.translateRecord(window.__placed,5,-2)');assert.deepEqual(b.read('({x:window.__moved.manualTextPosition.x,y:window.__moved.manualTextPosition.y,featureId:window.__moved.manualTextPosition.featureId})'),{x:16,y:10,featureId:placed.manualTextPosition.featureId});assert.equal(b.read('recordGateway.setDimensionTextPosition(window.__id,null).status'),'committed');assert.equal(b.read('modelReader.records()[0].manualTextPosition'),null)});

test('AN3 controls persist and Undo Redo preserve exact record and feature identity',async()=>{const b=await browser(),record=create(b);b.window.__id=record.id;b.run('recordGateway.replace(window.__id,{...modelReader.records()[0],prefixOverride:"REF ",suffixOverride:" TYP",toleranceMode:"deviation",toleranceUpper:.1,toleranceLower:.2});recordGateway.setDimensionTextPosition(window.__id,{x:8,y:9})');const exact=b.read('modelReader.records()[0]');b.window.__file=b.run('window.CaderactPersistence.serializeDocument(modelReader.snapshot())');b.run('window.__loaded=window.CaderactPersistence.loadStore(window.__file)');assert.deepEqual(b.read('window.__loaded.reader.records()[0]'),exact);b.run('documentController.undo()');assert.equal(b.read('modelReader.records()[0].textPositionMode'),'automatic');b.run('documentController.redo()');assert.deepEqual(b.read('modelReader.records()[0]'),exact)});

test('AN3 loads earlier v3 dimensions without controls using unchanged defaults',async()=>{const b=await browser();create(b);const file=JSON.parse(b.run('window.CaderactPersistence.serializeDocument(modelReader.snapshot())'));for(const key of ['prefixOverride','suffixOverride','toleranceMode','toleranceUpper','toleranceLower','textPositionMode','manualTextPosition'])delete file.document.records[0][key];b.window.__legacy=JSON.stringify(file);b.run('window.__loaded=window.CaderactPersistence.loadStore(window.__legacy)');assert.deepEqual(b.read('(({prefixOverride,suffixOverride,toleranceMode,toleranceUpper,toleranceLower,textPositionMode,manualTextPosition})=>({prefixOverride,suffixOverride,toleranceMode,toleranceUpper,toleranceLower,textPositionMode,manualTextPosition}))(window.__loaded.reader.records()[0])'),{prefixOverride:null,suffixOverride:null,toleranceMode:'none',toleranceUpper:0,toleranceLower:0,textPositionMode:'automatic',manualTextPosition:null})});

test('AN3 DXF refuses controls it cannot preserve instead of silently flattening them',async()=>{const b=await browser();create(b,',prefixOverride:"REF "');assert.throws(()=>b.run('window.CaderactDxfExport.exportDocument(modelReader.snapshot())'),error=>error.diagnostics?.some(item=>item.code==='DXF_EXPORT_DIMENSION_CONTROL_UNSUPPORTED'))});

test('AN3 automatic dimensions remain DXF compatible and alternate units stay deferred',async()=>{const b=await browser();create(b);assert.match(b.run('window.CaderactDxfExport.exportDocument(modelReader.snapshot()).text'),/DIMENSION/);assert.equal(b.read('Object.prototype.hasOwnProperty.call(modelReader.records()[0],"alternateUnits")'),false)});

test('AN3 Properties exposes read-only measurement and single-object controls through history',async()=>{const b=await browser(),record=create(b);b.run(`window.caderactSelection.selectOnly(${JSON.stringify(record.id)});window.caderactPropertiesPanel.open()`);const dimension=b.propertiesContent.children.find(node=>node.children[0]?.textContent==='Dimension'),labels=dimension.children.slice(1).map(row=>row.children[0]?.textContent);assert.ok(labels.includes('Measured Value'));assert.ok(labels.includes('Prefix'));assert.ok(labels.includes('Suffix'));assert.ok(labels.includes('Text Override'));assert.ok(labels.includes('Tolerance'));assert.ok(labels.includes('Text Placement'));const measured=dimension.children.find(row=>row.children[0]?.textContent==='Measured Value');assert.equal(measured.children[1].tag,'span');const prefix=dimension.children.find(row=>row.children[0]?.textContent==='Prefix').children[1],before=b.read('documentController.historyInfo.entryCount');prefix.value='4X ';b.emit(prefix,'change');assert.equal(b.read('modelReader.records()[0].prefixOverride'),'4X ');assert.equal(b.read('documentController.historyInfo.entryCount'),before+1)});

test('AN3 per-object Properties controls stay conservative for multi-selection',async()=>{const b=await browser();b.run(`window.__a=recordGateway.createLinearDimension({mode:'horizontal',firstPoint:{x:0,y:0},secondPoint:{x:4,y:0},dimensionLinePoint:{x:0,y:2}});window.__b=recordGateway.createLinearDimension({mode:'horizontal',firstPoint:{x:0,y:5},secondPoint:{x:8,y:5},dimensionLinePoint:{x:0,y:7}});recordGateway.createAll([window.__a,window.__b]);window.caderactSelection.applyRecordIds([window.__a.id,window.__b.id]);window.caderactPropertiesPanel.open()`);const dimension=b.propertiesContent.children.find(node=>node.children[0]?.textContent==='Dimension'),labels=dimension.children.slice(1).map(row=>row.children[0]?.textContent);assert.deepEqual(labels,['Style','Styles'])});

test('AN3 manual text grip movement uses the existing grip transaction authority',async()=>{const b=await browser(),record=create(b);b.window.__id=record.id;b.run('recordGateway.setDimensionTextPosition(window.__id,{x:0,y:20});window.caderactSelection.selectOnly(window.__id)');b.flush();const before=b.read('modelReader.records()[0]'),history=b.read('documentController.historyInfo.entryCount');b.point(400,200);b.point(425,225,'pointermove');b.point(425,225,'pointerup');const changed=b.read('modelReader.records()[0]');assert.deepEqual([changed.manualTextPosition.x,changed.manualTextPosition.y],[5,15]);assert.equal(changed.manualTextPosition.featureId,before.manualTextPosition.featureId);assert.equal(b.read('documentController.historyInfo.entryCount'),history+1)});
