'use strict'
const test=require('node:test')
const assert=require('node:assert/strict')
const {browser}=require('../helpers/browser.cjs')
function text(b,patch={}){b.window.__text={insertionPoint:{x:-20,y:30},text:'A ± Ø25°',height:2.5,rotation:Math.PI*2-1e-12,horizontalAlignment:'left',...patch};return b.read('(()=>{const r=recordGateway.createText(window.__text);recordGateway.createAll([r]);return r})()')}
function linear(b,distance=.001){return b.read(`(()=>{const r=recordGateway.createLinearDimension({mode:'aligned',firstPoint:{x:0,y:0},secondPoint:{x:${distance},y:0},dimensionLinePoint:{x:0,y:1},textOverride:null});recordGateway.createAll([r]);return r})()`)}

test('D9 tiny and extreme dimension presentations stay finite and selectable',async()=>{const b=await browser();for(const distance of [1e-9,.001,1e6]){const record=linear(b,distance);b.window.__record=record;const presentation=b.read('window.CaderactDimensionGeometry.derive(window.__record,modelReader.resolveDimensionStyle(window.__record),modelReader.units())');assert.equal(presentation.supported,true);assert.ok(JSON.stringify(presentation).includes('null')===false);for(const line of presentation.lines.flat())assert.ok(Number.isFinite(line.x)&&Number.isFinite(line.y))}})

test('D9 Text edge values normalize and projected bounds refresh without a cache',async()=>{const b=await browser(),record=text(b,{text:'X'.repeat(256),height:1e-6,horizontalAlignment:'right'});b.window.__record=record;const first=b.read('window.CaderactAnnotationGeometry.projectedCorners(window.__record,(x,y)=>({x:x*5,y:y*5}))');const changed=b.read('window.CaderactAnnotationGeometry.projectedCorners({...window.__record,text:"短い Unicode",height:100,rotation:Math.PI/2,horizontalAlignment:"center"},(x,y)=>({x:x*5,y:y*5}))');assert.equal(first.length,4);assert.equal(changed.length,4);assert.notDeepEqual(changed,first);assert.ok(changed.flatMap(Object.values).every(Number.isFinite))})

test('D9 overlay replaces nodes and clears deleted and hidden annotations',async()=>{const b=await browser(),record=text(b),overlay=b.viewportHost.children.find(child=>child.className==='annotation-overlay');b.flush();assert.equal(overlay.children.length,1);b.run(`recordGateway.removeAll([${JSON.stringify(record.id)}])`);b.flush();assert.equal(overlay.children.length,0);const again=text(b),oldLayer=b.read('modelReader.snapshot().currentLayerId');b.run("layerGateway.create('Visible');layerGateway.setCurrent(modelReader.layers().find(layer=>layer.name==='Visible').id)");b.run(`layerGateway.setVisibility(${JSON.stringify(oldLayer)},false)`);b.flush();assert.equal(b.renders.at(-1).annotationOverlay.items.some(item=>item.recordId===again.id),false)})

test('D9 Text cancellation and invalid retries leave history and document untouched',async()=>{const b=await browser(),before=b.read('({records:modelReader.records(),history:documentController.historyInfo.entryCount})');b.launch('Text');for(const value of ['0,0','0','bad']){b.input.value=value;b.emit(b.input,'input');b.key('Enter',b.input)}assert.equal(b.read('window.caderactCommandRouter.activeSession.phase'),'height');b.key('Escape');assert.deepEqual(b.read('({records:modelReader.records(),history:documentController.historyInfo.entryCount})'),before);b.flush();assert.equal(b.renders.at(-1).annotationOverlay.items.length,0)})

test('D9 repeated Text mirror remains canonical and stable',async()=>{const b=await browser(),record=text(b,{rotation:.37});b.window.__record=record;for(let index=0;index<100;index++)b.run('window.__record=window.CaderactGeometryTransform.mirrorRecord(window.__record,{x:5,y:-2},{x:5,y:10})');const result=b.read('window.__record');assert.ok(result.rotation>=0&&result.rotation<Math.PI*2);assert.ok(Math.abs(result.rotation-record.rotation)<1e-10);assert.equal(result.insertionPoint.featureId,record.insertionPoint.featureId)})

test('D9 malformed v3 annotation data rejects atomically',async()=>{const b=await browser();text(b);const valid=JSON.parse(b.run('window.CaderactPersistence.serializeDocument(modelReader.snapshot())'));for(const mutate of [file=>file.document.records[0].text=' ',file=>file.document.records[0].height=0,file=>file.document.records[0].rotation=Infinity,file=>file.document.records[0].horizontalAlignment='justify',file=>file.document.records[0].insertionPoint.featureId='']){const file=structuredClone(valid);mutate(file);b.window.__bad=JSON.stringify(file);assert.throws(()=>b.run('window.CaderactPersistence.loadStore(window.__bad)'));assert.equal(b.read('modelReader.records().length'),1)}})

test('D9 dimension formatter suppresses negative zero at supported precisions',async()=>{const b=await browser();for(const precision of [0,3,15]){b.window.__style={...b.window.CaderactDocument.DEFAULT_DIMENSION_STYLE,linearPrecision:precision,angularPrecision:precision,showUnit:false};assert.doesNotMatch(b.run('window.CaderactDimensionFormatter.format({kind:"linear",value:-1e-20},window.__style,{length:"mm"})'),/^-/);assert.doesNotMatch(b.run('window.CaderactDimensionFormatter.format({kind:"angular",value:-1e-20},window.__style,{length:"mm"})'),/^-/)}})
