'use strict';
const {test}=require('node:test');
const assert=require('node:assert/strict');
const {browser}=require('../helpers/browser.cjs');

function typed(b,value){b.input.value=value;b.emit(b.input,'input');b.key('Enter',b.input)}
function state(b){return b.read('({revision:documentController.currentRevision,history:documentController.historyInfo.entryCount,dirty:documentController.isDirty})')}
function plot(b){return b.read('window.CaderactPlotOutput.prepare(window.CaderactPlotJob.defaults())')}

test('BETA1 mechanical detail crosses layers, command modification, Blocks, Hatch, annotation, Layout, PDF, and native reopen',async()=>{
  const b=await browser();
  b.run(`unitGateway.setLengthUnit('mm');layerGateway.create('Machined');layerGateway.create('Annotations');window.__machined=modelReader.layers().find(layer=>layer.name==='Machined');window.__body=recordGateway.createPolyline([{x:-20,y:-10},{x:20,y:-10},{x:20,y:10},{x:-20,y:10}],true);window.__axis=recordGateway.createLine({x:-25,y:0},{x:25,y:0});window.__hole=recordGateway.createCircle({x:0,y:0},5);window.__hatch=recordGateway.createHatch([recordGateway.createCircle({x:12,y:0},2)],{kind:'named',name:'ANSI31',angle:0,scale:1,origin:{x:0,y:0}});window.__dimension=recordGateway.createLinearDimension({mode:'aligned',firstPoint:{x:-20,y:-10},secondPoint:{x:20,y:-10},dimensionLinePoint:{x:0,y:-16},toleranceMode:'symmetric',toleranceUpper:.1});window.__mark=recordGateway.createCenterMark({centerPoint:{x:0,y:0},sizePoint:{x:4,y:0},sourceRecordId:window.__hole.id});window.__note=recordGateway.createText({insertionPoint:{x:-20,y:17},text:'MECHANICAL DETAIL',height:2,rotation:0});window.__leader=recordGateway.createLeader({vertices:[{x:4,y:4},{x:10,y:13}],textPosition:{x:16,y:13},landingLength:1,textOverride:'BORE'});window.__created=recordGateway.createAll([window.__body,window.__axis,window.__hole,window.__hatch,window.__dimension,window.__mark,window.__note,window.__leader]);recordGateway.assignLayer([window.__body.id,window.__axis.id,window.__hole.id,window.__hatch.id],window.__machined.id);window.__bolt=blockDefinitionGateway.create({name:'Bolt',records:[recordGateway.createCircle({x:0,y:0},1),recordGateway.createLine({x:-1,y:0},{x:1,y:0})]}).definition;window.__b1=recordGateway.createBlockInstance({definitionId:window.__bolt.id,insertionPoint:{x:-14,y:0}});window.__b2=recordGateway.createBlockInstance({definitionId:window.__bolt.id,insertionPoint:{x:14,y:0}});recordGateway.createAll([window.__b1,window.__b2]);window.__group=groupGateway.createGroup([window.__b1.id,window.__b2.id],{name:'Fasteners'}).group`);
  assert.equal(b.read('window.__created.status'),'committed');assert.equal(b.read('modelReader.group(window.__group.id).memberIds.length'),2);
  b.run('window.caderactSelection.selectOnly(window.__note.id)');b.launch('Move');typed(b,'0,0');typed(b,'0,2');
  assert.equal(b.read('modelReader.records().find(record=>record.id===window.__note.id).insertionPoint.y'),19);
  b.run('window.caderactSelection.clear();userPreferences.set({orthoEnabled:true,objectSnapEnabled:true,objectSnapTrackingEnabled:true,extensionTrackingEnabled:true})');b.launch('Line');const snapScreen=b.read('worldToScreen(-25,0)');b.point(snapScreen.x,snapScreen.y,'pointermove');assert.equal(b.read('activeSnapResult.kind'),'endpoint');b.key('Escape');b.run('userPreferences.set({orthoEnabled:false,polarEnabled:true})');assert.equal(b.read('userPreferences.value.polarEnabled'),true);
  const modelBefore=b.read('modelReader.snapshot()');b.run(`window.__layout=modelReader.layouts()[0];window.__setup=window.caderactDocumentSession.layoutGateway.setPageSetup(window.__layout.id,{...window.__layout.paper,size:'A3',orientation:'landscape',width:420,height:297});window.caderactLayoutContext.switchToLayout(window.__layout.id);window.__view=window.caderactDocumentSession.layoutGateway.createViewport(window.__layout.id,{frame:{x:25,y:25,width:180,height:120},viewCenter:{x:0,y:0},scale:1,locked:false}).viewport;layoutInteraction.activateAt(worldToScreen(100,80))`);
  assert.equal(b.read('window.__setup.status'),'committed');assert.equal(b.read('window.caderactLayoutContext.snapshot().kind'),'layout');
  b.run('layoutInteraction.clear()');const prepared=plot(b);assert.equal(prepared.status,'ready');assert.ok(prepared.scene.segments.length>0);assert.ok(prepared.scene.texts.some(text=>text.value==='MECHANICAL DETAIL'));assert.ok(prepared.scene.texts.some(text=>text.value.includes('±')));assert.ok(prepared.scene.fills.length>0);
  b.window.__scene=prepared.scene;const pdf=b.read('({length:window.CaderactPdfSerializer.serialize(window.__scene).bytes.length,pagePoints:window.CaderactPdfSerializer.serialize(window.__scene).pagePoints})');assert.ok(pdf.length>500);assert.equal(pdf.pagePoints.width,Number((420*72/25.4).toFixed(5)));
  b.run('window.__serialized=window.CaderactPersistence.serializeDocument(modelReader.snapshot());window.__reopened=window.CaderactPersistence.loadStore(window.__serialized)');assert.deepEqual(b.read('window.__reopened.reader.snapshot()'),b.read('modelReader.snapshot()'));
  b.run('window.caderactDocumentSession.replaceStore(window.__reopened,{reason:"beta-native-open"});window.__continued=recordGateway.createLine({x:30,y:0},{x:35,y:0});recordGateway.createAll([window.__continued])');assert.ok(b.read('modelReader.records().some(record=>record.id===window.__continued.id)'));assert.ok(modelBefore.geometry.objects);
});

test('BETA1 floor plan crosses repeated Blocks, arrays, Block Edit, isolation, selection filter, and output',async()=>{
  const b=await browser();
  b.run(`layerGateway.create('Walls');layerGateway.create('Fixtures');window.__walls=modelReader.layers().find(layer=>layer.name==='Walls');window.__fixtures=modelReader.layers().find(layer=>layer.name==='Fixtures');window.__boundary=recordGateway.createPolyline([{x:-40,y:-25},{x:40,y:-25},{x:40,y:25},{x:-40,y:25}],true);window.__partition=recordGateway.createLine({x:0,y:-25},{x:0,y:25});window.__opening=recordGateway.createLine({x:0,y:-5},{x:0,y:5});window.__fill=recordGateway.createHatch([recordGateway.createCircle({x:28,y:12},3)],{kind:'solid'});window.__label=recordGateway.createText({insertionPoint:{x:-30,y:15},text:'ROOM A',height:2,rotation:0});window.__dim=recordGateway.createLinearDimension({mode:'horizontal',firstPoint:{x:-40,y:-25},secondPoint:{x:40,y:-25},dimensionLinePoint:{x:0,y:-32}});recordGateway.createAll([window.__boundary,window.__partition,window.__opening,window.__fill,window.__label,window.__dim]);recordGateway.assignLayer([window.__boundary.id,window.__partition.id,window.__opening.id],window.__walls.id);window.__doorMember=recordGateway.createLine({x:0,y:0},{x:8,y:0});window.__doorDef=blockDefinitionGateway.create({name:'Door',records:[window.__doorMember]}).definition;window.__doors=[-20,0,20].map(x=>recordGateway.createBlockInstance({definitionId:window.__doorDef.id,insertionPoint:{x,y:0}}));recordGateway.createAll(window.__doors);recordGateway.assignLayer(window.__doors.map(record=>record.id),window.__fixtures.id)`);
  b.run('window.caderactSelection.selectOnly(window.__doors[0].id)');b.launch('Copy');typed(b,'-20,0');typed(b,'-20,15');assert.equal(b.read('modelReader.records().filter(record=>record.type==="block-instance").length'),4);
  b.run('window.caderactSelection.selectOnly(window.__opening.id)');b.launch('AR');b.run('window.caderactCommandRouter.activateOption("rows");window.caderactCommandRouter.submitActiveInput("2");window.caderactCommandRouter.activateOption("columns");window.caderactCommandRouter.submitActiveInput("2")');b.key('Enter');assert.ok(b.read('modelReader.records().filter(record=>record.type==="line").length')>=5);
  b.run('window.caderactSelection.selectOnly(window.__doors[1].id)');b.launch('Rotate');typed(b,'0,0');typed(b,'10,0');typed(b,'90');assert.ok(Math.abs(b.read('modelReader.records().find(record=>record.id===window.__doors[1].id).rotation')-Math.PI/2)<1e-10);
  b.launch('BlockEdit');typed(b,'Door');b.run('window.__edit=window.caderactCommandRouter.activeSession.workspace;window.__edit.select([window.__doorMember.id]);window.__edit.move(1,0)');b.key('Enter');assert.equal(b.read('window.caderactCommandRouter.activeCommand'),null);
  assert.equal(b.read('window.CaderactBlockTraversal.traverse(modelReader.snapshot(),window.__doors[0]).entries[0].record.start.x'),1);
  b.run('window.__afterEdit=modelReader.snapshot();documentController.undo()');assert.equal(b.read('window.CaderactBlockTraversal.traverse(modelReader.snapshot(),window.__doors[0]).entries[0].record.start.x'),0);b.run('documentController.redo()');assert.deepEqual(b.read('modelReader.snapshot()'),b.read('window.__afterEdit'));
  b.run('window.__isolation=window.caderactViewport.setLayerIsolation(window.__walls.id)');assert.equal(b.read('window.__isolation.status'),'layer-isolated');assert.equal(b.read('modelReader.records().filter(record=>record.type==="block-instance").length'),4);b.run('window.caderactViewport.clearLayerIsolation()');
  b.launch('SelectFilter');typed(b,'Type=block-instance');assert.equal(b.read('window.caderactSelection.selectedIds().length'),4);
  b.run('window.caderactSelection.clear();window.__layout=modelReader.layouts()[0].id;window.caderactLayoutContext.switchToLayout(window.__layout)');const prepared=plot(b);assert.equal(prepared.status,'ready');assert.ok(prepared.scene.segments.length>0);assert.ok(b.read('window.CaderactPdfSerializer.serialize(window.CaderactPlotOutput.prepare().scene).bytes.length')>100);
  b.run('window.__native=window.CaderactPersistence.serializeDocument(modelReader.snapshot());window.__loaded=window.CaderactPersistence.loadStore(window.__native)');assert.deepEqual(b.read('window.__loaded.reader.snapshot()'),b.read('modelReader.snapshot()'));
});

test('BETA1 general diagram survives DXF import edit native save export reimport and undo redo',async()=>{
  const b=await browser();b.run(`layerGateway.create('Diagram');window.__diagram=modelReader.layers().find(layer=>layer.name==='Diagram');window.__records=[recordGateway.createPolyline([{x:-15,y:-10},{x:0,y:10},{x:15,y:-10}],false),recordGateway.createCircle({x:25,y:0},4),recordGateway.createArc({center:{x:40,y:0},radius:4,start:{x:44,y:0},end:{x:40,y:4},sweep:Math.PI/2}),recordGateway.createEllipse({center:{x:55,y:0},majorAxis:{x:6,y:0},minorRadius:3}),recordGateway.createText({insertionPoint:{x:0,y:15},text:'SITE A',height:2,rotation:0})];recordGateway.createAll(window.__records);recordGateway.assignLayer(window.__records.map(record=>record.id),window.__diagram.id);window.__beforeMove=modelReader.snapshot()`);
  b.run('window.caderactSelection.selectOnly(window.__records[0].id)');b.launch('Move');typed(b,'0,0');typed(b,'5,0');const moved=b.read('modelReader.snapshot()');assert.notDeepEqual(moved,b.read('window.__beforeMove'));b.run('documentController.undo()');assert.deepEqual(b.read('modelReader.snapshot()'),b.read('window.__beforeMove'));b.run('documentController.redo()');assert.deepEqual(b.read('modelReader.snapshot()'),moved);
  const beforeMeasure=state(b);b.launch('Distance');typed(b,'0,0');typed(b,'3,4');assert.equal(b.read('window.caderactCommandRouter.lastResult.measurement.distance'),5);assert.deepEqual(state(b),beforeMeasure);
  b.run('window.caderactSelection.selectOnly(window.__records[2].id)');b.launch('Align');typed(b,'0,0');typed(b,'5,5');typed(b,'10,0');typed(b,'5,15');assert.equal(b.read('window.caderactCommandRouter.activeCommand'),null);
  b.run('window.__dxf=window.CaderactDxfExport.exportDocument(modelReader.snapshot());window.__imported=window.CaderactDxfImport.createStore(window.__dxf.text).store');assert.equal(b.read('window.__imported.reader.records().length'),5);
  b.run('window.caderactDocumentSession.replaceStore(window.__imported,{reason:"beta-dxf-import"});window.__additional=recordGateway.createLine({x:0,y:0},{x:5,y:5});recordGateway.createAll([window.__additional]);window.__native=window.CaderactPersistence.serializeDocument(modelReader.snapshot());window.__loaded=window.CaderactPersistence.loadStore(window.__native);window.__again=window.CaderactDxfImport.createStore(window.CaderactDxfExport.exportDocument(window.__loaded.reader.snapshot()).text).store');assert.equal(b.read('window.__again.reader.records().length'),6);
  b.run('window.__lead=recordGateway.createLeader({vertices:[{x:4,y:4},{x:8,y:10}],textPosition:{x:12,y:10},landingLength:1,textOverride:"SITE NOTE"});recordGateway.createAll([window.__lead]);window.__symbol=blockDefinitionGateway.create({name:"Site Mark",records:[recordGateway.createCircle({x:0,y:0},1)]}).definition;window.__insert=recordGateway.createBlockInstance({definitionId:window.__symbol.id,insertionPoint:{x:12,y:12}});recordGateway.createAll([window.__insert]);window.caderactLayoutContext.switchToLayout(modelReader.layouts()[0].id)');const prepared=plot(b);assert.equal(prepared.status,'ready');assert.ok(prepared.scene.segments.length>0);assert.ok(prepared.scene.texts.some(text=>text.value==='SITE NOTE'));
});

test('BETA1 recovery restores an edited drawing then continues through Layout PDF without losing file state',async()=>{
  const b=await browser();b.run(`window.__storage=window.CaderactRecoveryStorage.createMemoryStorage();window.__fs=window.CaderactDocumentFileState.create();window.__auto=window.CaderactRecoveryStorage.createAutosave({session:window.caderactDocumentSession,fileState:window.__fs,storage:window.__storage});window.__auto.start();window.__line=recordGateway.createLine({x:-10,y:0},{x:10,y:0});recordGateway.createAll([window.__line])`);
  assert.equal((await b.run('window.__auto.flush()')).status,'autosave-completed');b.run('window.__validation=window.CaderactRecoveryValidation.create({storage:window.__storage})');const candidate=(await b.run('window.__validation.classifyAll()')).candidates.find(value=>value.classification==='valid-newer');assert.ok(candidate);b.window.__candidate=candidate;
  b.run('window.caderactDocumentSession.replaceStore(window.CaderactDocument.createStore({initiallySaved:true}),{reason:"beta-crash"})');assert.equal((await b.run('window.__validation.apply(window.__candidate,{session:window.caderactDocumentSession,fileState:window.__fs,autosave:window.__auto,commandRouter:window.caderactCommandRouter,viewport:window.caderactViewport})')).status,'recovery-applied');
  assert.equal(b.read('modelReader.records().length'),1);b.run('window.__continued=recordGateway.createCircle({x:0,y:0},3);recordGateway.createAll([window.__continued]);window.caderactLayoutContext.switchToLayout(modelReader.layouts()[0].id)');const prepared=plot(b);assert.equal(prepared.status,'ready');assert.ok(b.read('window.CaderactPdfSerializer.serialize(window.CaderactPlotOutput.prepare().scene).bytes.length')>100);assert.equal(state(b).dirty,true);
});

test('BETA1 native Save Open continued edit and DXF exchange use real file actions without Layout contamination',async()=>{
  const b=await browser();
  b.run(`window.__writes=[];window.__nativeFile=null;window.__actions=window.CaderactFileActions.createActions({session:window.caderactDocumentSession,commandRouter:window.caderactCommandRouter,viewport:window.caderactViewport,adapters:{confirmDiscard:async()=>true,pickSaveFile:async()=>({status:'unsupported'}),pickOpenFile:async()=>window.__nativeFile,pickDxfFile:async()=>window.__dxfFile,writeFile:async request=>{window.__writes.push(request);return{status:'committed'}}}});window.__line=recordGateway.createLine({x:0,y:0},{x:20,y:0});window.__circle=recordGateway.createCircle({x:10,y:10},3);recordGateway.createAll([window.__line,window.__circle]);window.__layout=modelReader.layouts()[0].id;window.caderactLayoutContext.switchToLayout(window.__layout);window.caderactDocumentSession.layoutGateway.setPageSetup(window.__layout,{...modelReader.layout(window.__layout).paper,size:'A3',width:420,height:297})`);
  assert.equal((await b.run('window.__actions.save()')).status,'save-completed');assert.equal(state(b).dirty,false);
  b.run(`window.__nativePayload=window.__writes[0].serialized;window.__nativeFile={name:'Detail.caderact',text:async()=>window.__nativePayload}`);
  assert.equal((await b.run('window.__actions.open()')).status,'open-completed');assert.equal(b.read('modelReader.layout(window.__layout).paper.width'),420);assert.equal(b.read('window.caderactLayoutContext.snapshot().kind'),'model');
  b.run('window.__continued=recordGateway.createText({insertionPoint:{x:0,y:16},text:"CONTINUED",height:2,rotation:0});recordGateway.createAll([window.__continued])');assert.equal(state(b).dirty,true);
  assert.equal((await b.run('window.__actions.save()')).status,'save-completed');assert.equal(state(b).dirty,false);
  assert.equal((await b.run('window.__actions.exportDxf()')).status,'dxf-export-completed');
  b.run(`window.__dxfFile={name:'Detail.dxf',text:async()=>window.__writes.at(-1).serialized}`);
  assert.equal((await b.run('window.__actions.openDxf()')).status,'dxf-open-completed');assert.deepEqual(b.read('modelReader.records().map(record=>record.type).sort()'),['circle','line','text']);
  assert.equal(b.read('window.caderactLayoutContext.snapshot().kind'),'model');assert.equal(b.read('modelReader.layouts()[0].paper.width'),297);
});

test('BETA1 Model View navigation, Page Setup, PDF, and Undo Redo share one Layout state',async()=>{
  const b=await browser();b.resize(900,600);
  b.run(`window.__line=recordGateway.createLine({x:-50,y:0},{x:50,y:0});recordGateway.createAll([window.__line]);window.__layout=modelReader.layouts()[0].id;window.__modelCamera={...camera};window.caderactLayoutContext.switchToLayout(window.__layout);window.__viewId=modelReader.layout(window.__layout).viewportOrder[0];window.__before=modelReader.layout(window.__layout);layoutInteraction.activateAt(worldToScreen(80,60));layoutInteraction.begin();layoutInteraction.navigate({dx:20,dy:10});layoutInteraction.commit()`);
  const navigated=b.read('modelReader.layout(window.__layout)');assert.notDeepEqual(navigated.viewports[b.read('window.__viewId')].viewCenter,b.read('window.__before.viewports[window.__viewId].viewCenter'));
  b.run(`window.__setup=window.caderactDocumentSession.layoutGateway.setPageSetup(window.__layout,{...modelReader.layout(window.__layout).paper,margins:{top:15,right:12,bottom:15,left:12}});window.__after=modelReader.layout(window.__layout);window.__scene=window.CaderactPlotOutput.prepare().scene;window.__pdf=window.CaderactPdfSerializer.serialize(window.__scene)`);
  assert.equal(b.read('window.__setup.status'),'committed');assert.equal(b.read('window.__scene.layoutId'),b.read('window.__layout'));assert.ok(b.read('window.__pdf.bytes.length')>100);assert.deepEqual(b.read('modelReader.layout(window.__layout).viewports[window.__viewId].viewCenter'),navigated.viewports[b.read('window.__viewId')].viewCenter);
  b.run('documentController.undo()');assert.deepEqual(b.read('modelReader.layout(window.__layout)'),navigated);b.run('documentController.redo()');assert.deepEqual(b.read('modelReader.layout(window.__layout)'),b.read('window.__after'));
  b.run('window.caderactLayoutContext.switchToModel()');assert.deepEqual(b.read('({...camera})'),b.read('window.__modelCamera'));
});
