'use strict';
const {test}=require('node:test');const assert=require('node:assert/strict');const {browser}=require('../helpers/browser.cjs');
function seed(b){b.run(`window.__members=[recordGateway.createLine({x:-2,y:0},{x:4,y:0}),recordGateway.createText({insertionPoint:{x:0,y:2},text:'Stable',height:1,rotation:0})];window.__definition=blockDefinitionGateway.create({name:'Stable',basePoint:{x:1,y:1},records:window.__members}).definition;window.__instance=recordGateway.createBlockInstance({definitionId:window.__definition.id,insertionPoint:{x:20,y:10},rotation:.4,scale:2,mirrored:true});recordGateway.createAll([window.__instance])`)}

test('GB9 persistence is canonical and strips every runtime Block surface',async()=>{const b=await browser();seed(b);const first=b.run('window.CaderactPersistence.serializeDocument(modelReader.snapshot())');b.run(`window.__shuffled={...modelReader.snapshot(),geometry:{objects:Object.fromEntries(Object.entries(modelReader.snapshot().geometry.objects).reverse())},blockDefinitions:Object.fromEntries(Object.entries(modelReader.snapshot().blockDefinitions).reverse())}`);assert.equal(b.run('window.CaderactPersistence.serializeDocument(window.__shuffled)'),first);for(const term of ['runtimeReference','semanticId','instancePath','expandedGeometry','scene'])assert.equal(first.includes(term),false);b.window.__saved=first;b.run('window.__loaded=window.CaderactPersistence.loadStore(window.__saved)');assert.equal(b.run('window.CaderactPersistence.serializeDocument(window.__loaded.reader.snapshot())'),first)});

test('GB9 malformed runtime fields and global identity collisions reject atomically',async()=>{const b=await browser();seed(b);const before=b.read('modelReader.snapshot()');b.run(`window.__payload=JSON.parse(window.CaderactPersistence.serializeDocument(modelReader.snapshot()))`);for(const mutation of [`p.document.records[0].runtimeReference={}`,`p.document.blockDefinitions[0].records[1].insertionPoint.featureId=p.document.records[0].insertionPoint.featureId`,`p.document.records[0].definitionId='missing'`]){b.run(`window.__bad=JSON.parse(JSON.stringify(window.__payload));(()=>{const p=window.__bad;${mutation}})()`);assert.throws(()=>b.run('window.CaderactPersistence.loadStore(JSON.stringify(window.__bad))'),/Invalid Caderact file/);assert.deepEqual(b.read('modelReader.snapshot()'),before)}});

test('GB9 definition removal is reference-safe and unused removal has exact history',async()=>{const b=await browser();seed(b);assert.equal(b.read('blockDefinitionGateway.remove(window.__definition.id).status'),'definition-in-use');b.run('recordGateway.removeAll([window.__instance.id])');const definition=b.read('window.__definition');assert.equal(b.read('blockDefinitionGateway.remove(window.__definition.id).status'),'committed');assert.equal(b.read('modelReader.blockDefinitions().length'),0);b.run('window.caderactHistory.undo()');assert.deepEqual(b.read('modelReader.blockDefinition(window.__definition.id)'),definition);b.run('window.caderactHistory.redo()');assert.equal(b.read('modelReader.blockDefinitions().length'),0)});

test('GB9 semantic bounds are deterministic, reflected, visibility-aware and bounded',async()=>{const b=await browser();seed(b);b.run(`window.__bounds=window.CaderactBlockTraversal.bounds(modelReader.snapshot(),window.__instance,{isLayerVisible:id=>modelReader.layer(id).visible});window.__again=window.CaderactBlockTraversal.bounds(modelReader.snapshot(),window.__instance,{isLayerVisible:id=>modelReader.layer(id).visible})`);assert.deepEqual(b.read('window.__bounds'),b.read('window.__again'));assert.equal(b.read('window.__bounds.empty'),false);assert.ok(b.read('window.__bounds.minX<window.__bounds.maxX&&window.__bounds.minY<window.__bounds.maxY'));assert.throws(()=>b.run('window.CaderactBlockTraversal.bounds(modelReader.snapshot(),window.__instance,{maxVisits:1})'),/visit limit/);assert.equal(b.read('window.CaderactBlockTraversal.bounds(modelReader.snapshot(),window.__instance,{isLayerVisible:()=>false}).empty'),true)});
