'use strict';
const {test}=require('node:test');
const assert=require('node:assert/strict');
const {browser}=require('../helpers/browser.cjs');

test('GB3 SimilarityTransform covers identity, base mapping, rotation, scale, reflection, composition, and inverse',async()=>{
  const b=await browser();const result=b.read(`(()=>{const S=window.CaderactSimilarityTransform,id=S.identity(),t=S.fromComponents({insertionPoint:{x:10,y:20},basePoint:{x:2,y:3},rotation:Math.PI/2,scale:2,mirrored:true}),child=S.fromComponents({insertionPoint:{x:4,y:5},rotation:-Math.PI/4,scale:.5,mirrored:false}),combined=S.compose(t,child),p={x:7,y:-2},world=S.point(combined,p),back=S.point(S.inverse(combined),world);return{idPoint:S.point(id,p),mapped:S.point(t,{x:2,y:3}),vector:S.vector(t,{x:1,y:0}),parts:S.components(t),world,back,valid:S.isValid(combined)}})()`);assert.deepEqual(result.idPoint,{x:7,y:-2});assert.deepEqual(result.mapped,{x:10,y:20});assert.ok(Math.abs(result.vector.x)<1e-12);assert.equal(result.vector.y,-2);assert.equal(result.parts.scale,2);assert.equal(result.parts.mirrored,true);assert.ok(Math.abs(result.back.x-7)<1e-10&&Math.abs(result.back.y+2)<1e-10);assert.equal(result.valid,true)
});

test('GB3 SimilarityTransform canonicalizes angles and rejects invalid, singular, nonuniform, and overflow results',async()=>{
  const b=await browser();assert.equal(b.read('window.CaderactSimilarityTransform.canonicalAngle(-Math.PI)'),Math.PI);assert.equal(b.read('window.CaderactSimilarityTransform.canonicalAngle(Math.PI*5)'),Math.PI);for(const expression of ['window.CaderactSimilarityTransform.fromComponents({insertionPoint:{x:0,y:0},scale:0})','window.CaderactSimilarityTransform.fromComponents({insertionPoint:{x:0,y:0},scale:Infinity})','window.CaderactSimilarityTransform.inverse({a:0,b:0,c:0,d:0,tx:0,ty:0})','window.CaderactSimilarityTransform.point({a:1e308,b:0,c:0,d:1e308,tx:0,ty:0},{x:1e308,y:0})'])assert.throws(()=>b.run(expression));assert.equal(b.read('window.CaderactSimilarityTransform.isValid({a:2,b:0,c:0,d:3,tx:0,ty:0})'),false)
});

test('GB3 creates deterministic document-owned Definitions outside model space',async()=>{
  const b=await browser();b.run('window.__a=recordGateway.createLine({x:0,y:0},{x:2,y:0});window.__b=recordGateway.createCircle({x:3,y:0},1);window.__created=window.caderactDocumentSession.blockDefinitionGateway.create({name:"Valve",basePoint:{x:1,y:2},records:[window.__b,window.__a],recordOrder:[window.__a.id,window.__b.id]})');const result=b.read('window.__created');assert.equal(result.status,'committed');assert.deepEqual(result.definition.recordOrder,[b.read('window.__a.id'),b.read('window.__b.id')]);assert.equal(b.read('modelReader.records().length'),0);assert.deepEqual(b.read('modelReader.blockDefinition(window.__created.definition.id)'),result.definition);assert.deepEqual(b.read('modelReader.blockDefinitions()'),[result.definition]);assert.equal(b.read('window.caderactDocumentSession.blockDefinitionGateway.create({name:"valve",records:[recordGateway.createLine({x:0,y:0},{x:1,y:0})]}).status'),'validation-failed')
});

test('GB3 Definition validation supports all native semantic member schemas',async()=>{
  const b=await browser();b.run('window.__members=[recordGateway.createLine({x:0,y:0},{x:1,y:0}),recordGateway.createCircle({x:2,y:0},1),recordGateway.createArc({center:{x:4,y:0},radius:1,start:{x:5,y:0},end:{x:4,y:1},sweep:Math.PI/2}),recordGateway.createEllipse({center:{x:6,y:0},majorAxis:{x:2,y:0},minorRadius:1}),recordGateway.createPolyline([{x:0,y:3},{x:2,y:3}],false),recordGateway.createRegion([recordGateway.createCircle({x:10,y:0},2)]),recordGateway.createHatch([recordGateway.createCircle({x:15,y:0},2)],{kind:"named",name:"ANSI31",angle:.2,scale:2,origin:{x:1,y:1}}),recordGateway.createText({insertionPoint:{x:0,y:5},text:"BLOCK",height:2,rotation:.3}),recordGateway.createLinearDimension({mode:"aligned",firstPoint:{x:0,y:8},secondPoint:{x:4,y:8},dimensionLinePoint:{x:0,y:10}})];window.__result=window.caderactDocumentSession.blockDefinitionGateway.create({name:"Semantic",records:window.__members})');assert.equal(b.read('window.__result.status'),'committed');assert.deepEqual(b.read('window.CaderactDocument.validateDocument(modelReader.snapshot())'),[]);assert.equal(b.read('modelReader.records().length'),0);assert.equal(b.read('modelReader.blockDefinitions()[0].recordOrder.length'),9)
});

test('GB3 rejects Group/transient members and global identity collisions atomically',async()=>{
  const b=await browser();b.run('window.__line=recordGateway.createLine({x:0,y:0},{x:1,y:0});recordGateway.createAll([window.__line])');const before=b.read('({document:modelReader.snapshot(),history:documentController.historyInfo})');assert.equal(b.read('window.caderactDocumentSession.blockDefinitionGateway.create({name:"Collision",records:[window.__line]}).status'),'validation-failed');assert.equal(b.read('window.caderactDocumentSession.blockDefinitionGateway.create({name:"Group",records:[{id:"g",name:"G",memberIds:[window.__line.id,"x"]}]}).status'),'validation-failed');assert.equal(b.read('window.caderactDocumentSession.blockDefinitionGateway.create({name:"Preview",records:[{type:"line",start:{x:0,y:0},end:{x:1,y:0}}]}).status'),'validation-failed');assert.deepEqual(b.read('({document:modelReader.snapshot(),history:documentController.historyInfo})'),before)
});

test('GB3 Block Instances receive fresh identities and strict canonical transforms',async()=>{
  const b=await browser();b.run('window.__member=recordGateway.createLine({x:0,y:0},{x:1,y:0});window.__definition=window.caderactDocumentSession.blockDefinitionGateway.create({name:"Unit",records:[window.__member]}).definition;window.__i1=recordGateway.createBlockInstance({definitionId:window.__definition.id,insertionPoint:{x:5,y:6},rotation:Math.PI*3,scale:2,mirrored:true});window.__i2=recordGateway.createBlockInstance({definitionId:window.__definition.id,insertionPoint:{x:5,y:6}});window.__out=recordGateway.createAll([window.__i1,window.__i2])');assert.equal(b.read('window.__out.status'),'committed');assert.equal(new Set(b.read('[window.__i1.id,window.__i1.insertionPoint.featureId,window.__i2.id,window.__i2.insertionPoint.featureId]')).size,4);assert.equal(b.read('window.__i1.rotation'),Math.PI);assert.equal(b.read('window.__i1.scale'),2);assert.equal(b.read('window.__i1.mirrored'),true);assert.throws(()=>b.run('recordGateway.createBlockInstance({definitionId:"missing",insertionPoint:{x:0,y:0}})'));assert.ok(b.read('window.CaderactDocument.validateDocument({...modelReader.snapshot(),geometry:{objects:{...modelReader.snapshot().geometry.objects,[window.__i1.id]:{...window.__i1,scale:0}}}}).some(e=>e.includes("invalid scale"))'))
});

test('GB3 traversal is deterministic with unique paths and composed reflected transforms',async()=>{
  const b=await browser();b.run('window.__leafRecord=recordGateway.createLine({x:0,y:0},{x:1,y:0});window.__leaf=window.caderactDocumentSession.blockDefinitionGateway.create({name:"Leaf",records:[window.__leafRecord]}).definition;window.__nested=recordGateway.createBlockInstance({definitionId:window.__leaf.id,insertionPoint:{x:2,y:0},rotation:Math.PI/2,scale:2,mirrored:true});window.__parent=window.caderactDocumentSession.blockDefinitionGateway.create({name:"Parent",records:[window.__nested]}).definition;window.__topA=recordGateway.createBlockInstance({definitionId:window.__parent.id,insertionPoint:{x:10,y:0},rotation:0,scale:1,mirrored:false});window.__topB=recordGateway.createBlockInstance({definitionId:window.__parent.id,insertionPoint:{x:20,y:0},rotation:0,scale:1,mirrored:false});window.__ta=window.CaderactBlockTraversal.traverse(modelReader.snapshot(),window.__topA);window.__tb=window.CaderactBlockTraversal.traverse(modelReader.snapshot(),window.__topB)');assert.equal(b.read('window.__ta.entries.length'),1);assert.notEqual(b.read('window.__ta.entries[0].semanticId'),b.read('window.__tb.entries[0].semanticId'));assert.deepEqual(b.read('window.__ta.entries[0].instancePath'),b.read('[window.__topA.id,window.__nested.id]'));assert.deepEqual(b.read('window.CaderactSimilarityTransform.point(window.__ta.entries[0].transform,{x:0,y:0})'),{x:12,y:0});assert.equal(b.read('window.CaderactSimilarityTransform.components(window.__ta.entries[0].transform).mirrored'),true)
});

test('GB3 rejects direct/indirect cycles and enforces depth 32',async()=>{
  const b=await browser();b.run('window.__line=recordGateway.createLine({x:0,y:0},{x:1,y:0});window.__a=window.caderactDocumentSession.blockDefinitionGateway.create({name:"A",records:[window.__line]}).definition;window.__toA=recordGateway.createBlockInstance({definitionId:window.__a.id,insertionPoint:{x:0,y:0}})');assert.equal(b.read('window.caderactDocumentSession.blockDefinitionGateway.replace(window.__a.id,{records:[window.__toA]}).status'),'validation-failed');b.run('window.__b=window.caderactDocumentSession.blockDefinitionGateway.create({name:"B",records:[window.__toA]}).definition;window.__toB=recordGateway.createBlockInstance({definitionId:window.__b.id,insertionPoint:{x:0,y:0}})');assert.equal(b.read('window.caderactDocumentSession.blockDefinitionGateway.replace(window.__a.id,{records:[window.__toB]}).status'),'validation-failed');const depth=await browser();depth.run('window.__leaf=window.caderactDocumentSession.blockDefinitionGateway.create({name:"D0",records:[recordGateway.createLine({x:0,y:0},{x:1,y:0})]}).definition;for(let i=1;i<32;i++){const nested=recordGateway.createBlockInstance({definitionId:window.__leaf.id,insertionPoint:{x:0,y:0}});window.__leaf=window.caderactDocumentSession.blockDefinitionGateway.create({name:"D"+i,records:[nested]}).definition}');assert.equal(depth.read('modelReader.blockDefinitions().length'),32);depth.run('window.__tooDeep=recordGateway.createBlockInstance({definitionId:window.__leaf.id,insertionPoint:{x:0,y:0}})');assert.equal(depth.read('window.caderactDocumentSession.blockDefinitionGateway.create({name:"D32",records:[window.__tooDeep]}).status'),'validation-failed')
});

test('GB3 traversal independently guards cycles, depth, semantic, and visit limits',async()=>{
  const b=await browser();b.run('window.__r=recordGateway.createLine({x:0,y:0},{x:1,y:0});window.__d=window.caderactDocumentSession.blockDefinitionGateway.create({name:"T",records:[window.__r]}).definition;window.__i=recordGateway.createBlockInstance({definitionId:window.__d.id,insertionPoint:{x:0,y:0}})');assert.throws(()=>b.run('window.CaderactBlockTraversal.traverse(modelReader.snapshot(),window.__i,{maxSemanticRecords:0})'),/semantic record limit/);assert.throws(()=>b.run('window.CaderactBlockTraversal.traverse(modelReader.snapshot(),window.__i,{maxVisits:1})'),/visit limit/);assert.throws(()=>b.run('window.CaderactBlockTraversal.traverse(modelReader.snapshot(),window.__i,{maxDepth:0})'),/depth/);b.run('window.__bad={...modelReader.snapshot(),blockDefinitions:{[window.__d.id]:{...window.__d,records:{[window.__i.id]:window.__i},recordOrder:[window.__i.id]}}}');assert.throws(()=>b.run('window.CaderactBlockTraversal.traverse(window.__bad,window.__i)'),/cycle/)
});

test('GB3 Definition create/replace/remove uses atomic history and exact Undo/Redo',async()=>{
  const b=await browser();b.run('window.__r=recordGateway.createLine({x:0,y:0},{x:1,y:0});window.__created=window.caderactDocumentSession.blockDefinitionGateway.create({name:"History",records:[window.__r]});window.__original=window.__created.definition');assert.equal(b.read('documentController.undo().status'),'undone');assert.equal(b.read('modelReader.blockDefinitions().length'),0);assert.equal(b.read('documentController.redo().status'),'redone');assert.deepEqual(b.read('modelReader.blockDefinitions()[0]'),b.read('window.__original'));assert.equal(b.read('window.caderactDocumentSession.blockDefinitionGateway.replace(window.__original.id,{name:"Changed"}).status'),'committed');assert.equal(b.read('documentController.undo().status'),'undone');assert.equal(b.read('modelReader.blockDefinitions()[0].name'),'History');assert.equal(b.read('window.caderactDocumentSession.blockDefinitionGateway.remove(window.__original.id).status'),'committed');assert.equal(b.read('documentController.undo().status'),'undone');assert.deepEqual(b.read('modelReader.blockDefinitions()[0]'),b.read('window.__original'))
});

test('GB3 persistence round-trips semantic Definitions/Instances and old v3 defaults empty',async()=>{
  const b=await browser();b.run('window.__r=recordGateway.createText({insertionPoint:{x:1,y:2},text:"Persist",height:2,rotation:.2});window.__d=window.caderactDocumentSession.blockDefinitionGateway.create({name:"Persisted",basePoint:{x:1,y:2},records:[window.__r]}).definition;window.__i=recordGateway.createBlockInstance({definitionId:window.__d.id,insertionPoint:{x:9,y:8},rotation:.5,scale:3,mirrored:true});recordGateway.createAll([window.__i]);window.__serialized=window.CaderactPersistence.serializeDocument(modelReader.snapshot());window.__loaded=window.CaderactPersistence.loadStore(window.__serialized)');assert.deepEqual(b.read('window.__loaded.reader.snapshot()'),b.read('modelReader.snapshot()'));assert.equal(b.read('window.CaderactPersistence.serializeDocument(window.__loaded.reader.snapshot())'),b.read('window.__serialized'));const payload=JSON.parse(b.read('window.__serialized'));assert.equal(Object.hasOwn(payload.document.blockDefinitions[0],'expandedGeometry'),false);delete payload.document.blockDefinitions;payload.document.records=[];b.window.__old=JSON.stringify(payload);b.run('window.__oldStore=window.CaderactPersistence.loadStore(window.__old)');assert.deepEqual(b.read('window.__oldStore.reader.blockDefinitions()'),[])
});

test('GB3 malformed persisted Block state is rejected strictly',async()=>{
  const b=await browser();b.run('window.__r=recordGateway.createLine({x:0,y:0},{x:1,y:0});window.__d=window.caderactDocumentSession.blockDefinitionGateway.create({name:"Bad",records:[window.__r]}).definition;window.__i=recordGateway.createBlockInstance({definitionId:window.__d.id,insertionPoint:{x:0,y:0}});recordGateway.createAll([window.__i]);window.__payload=JSON.parse(window.CaderactPersistence.serializeDocument(modelReader.snapshot()))');for(const mutation of ['p.document.records[0].definitionId="missing"','p.document.records[0].scale=0','p.document.records[0].rotation=7','p.document.records[0].mirrored="yes"','p.document.blockDefinitions[0].recordOrder.push(p.document.blockDefinitions[0].recordOrder[0])','p.document.blockDefinitions[0].records[0].extra=true','p.document.blockDefinitions[0].records[0].id=p.document.records[0].id']){b.run(`window.__bad=JSON.parse(JSON.stringify(window.__payload));(()=>{const p=window.__bad;${mutation}})()`);assert.throws(()=>b.run('window.CaderactPersistence.loadStore(JSON.stringify(window.__bad))'),/Invalid Caderact file/)}
});

test('GB3 shared semantic transform preserves Region/Hatch/Text/Dimension meaning',async()=>{
  const b=await browser();b.run('window.__records=[recordGateway.createRegion([recordGateway.createCircle({x:0,y:0},2)]),recordGateway.createHatch([recordGateway.createCircle({x:5,y:0},2)],{kind:"named",name:"ANSI31",angle:.3,scale:2,origin:{x:1,y:1}}),recordGateway.createText({insertionPoint:{x:0,y:5},text:"T",height:2,rotation:.2}),recordGateway.createLinearDimension({mode:"aligned",firstPoint:{x:0,y:8},secondPoint:{x:4,y:8},dimensionLinePoint:{x:0,y:10}})];window.__transform=window.CaderactSimilarityTransform.fromComponents({insertionPoint:{x:10,y:20},rotation:.5,scale:3,mirrored:true});window.__out=window.__records.map(r=>window.CaderactGeometryTransform.similarityRecord(r,window.__transform))');assert.deepEqual(b.read('window.CaderactRegionGeometry.validate(window.__out[0])'),[]);assert.deepEqual(b.read('window.CaderactHatchGeometry.validate(window.__out[1])'),[]);assert.equal(b.read('window.__out[2].height'),6);assert.equal(b.read('window.CaderactAnnotationGeometry.validate(window.__out[2]).length'),0);assert.equal(b.read('window.CaderactDimensionGeometry.measure(window.__out[3]).value'),12);assert.equal(b.read('window.__out[1].pattern.scale'),6)
});

test('GB3 exposes documented hard limits without changing Group behavior',async()=>{const b=await browser();assert.deepEqual(b.read('[window.CaderactDocument.MAX_BLOCK_DEFINITIONS,window.CaderactDocument.MAX_BLOCK_MEMBERS,window.CaderactDocument.MAX_BLOCK_INSTANCES,window.CaderactDocument.MAX_BLOCK_EDGES,window.CaderactDocument.MAX_BLOCK_DEPTH,window.CaderactBlockTraversal.MAX_SEMANTIC_RECORDS,window.CaderactBlockTraversal.MAX_VISITS]'),[5000,10000,100000,100000,32,100000,1000000]);b.run('window.__a=recordGateway.createLine({x:0,y:0},{x:1,y:0});window.__b=recordGateway.createLine({x:0,y:1},{x:1,y:1});recordGateway.createAll([window.__a,window.__b]);window.__g=window.caderactDocumentSession.groupGateway.createGroup([window.__a.id,window.__b.id]).group');assert.deepEqual(b.read('modelReader.groupForRecord(window.__a.id)'),b.read('window.__g'));assert.equal(b.read('modelReader.blockDefinitions().length'),0)});
