'use strict'
const test=require('node:test')
const assert=require('node:assert/strict')
const {browser}=require('../helpers/browser.cjs')

function dimension(b,override=null){return b.read(`(()=>{const record=recordGateway.createLinearDimension({mode:'horizontal',firstPoint:{x:0,y:0},secondPoint:{x:10,y:0},dimensionLinePoint:{x:5,y:4},textOverride:${JSON.stringify(override)}});recordGateway.createAll([record]);return record})()`)}
function state(b){return b.read('({snapshot:modelReader.snapshot(),history:documentController.historyInfo.entryCount,revision:documentController.currentRevision})')}
function typed(b,value){b.input.value=value;b.emit(b.input,'input');b.key('Enter',b.input)}

test('new documents own one current Standard style with stable defaults',async()=>{const b=await browser(),styles=b.read('modelReader.dimensionStyles()');assert.equal(styles.length,1);assert.equal(styles[0].name,'Standard');assert.equal(styles[0].id,b.read('modelReader.currentDimensionStyleId()'));assert.deepEqual(Object.fromEntries(Object.entries(styles[0]).filter(([key])=>!['id','name'].includes(key))),b.read('window.CaderactDocument.DEFAULT_DIMENSION_STYLE'));assert.equal(b.read('modelReader.snapshot().formatVersion'),3)})

test('style create duplicate rename edit and set-current are exact one-step history mutations',async()=>{const b=await browser(),original=b.read('modelReader.dimensionStyle()');let before=state(b);const created=b.read("dimensionStyleGateway.create('Large')");assert.equal(created.status,'committed');assert.notEqual(created.style.id,original.id);assert.equal(state(b).history,before.history+1);before=state(b);const duplicate=b.read(`dimensionStyleGateway.duplicate(${JSON.stringify(created.style.id)})`);assert.equal(duplicate.style.name,'Large Copy');assert.notEqual(duplicate.style.id,created.style.id);assert.equal(state(b).history,before.history+1);before=state(b);assert.equal(b.read(`dimensionStyleGateway.rename(${JSON.stringify(created.style.id)},'Presentation')`).status,'committed');assert.equal(b.read(`modelReader.dimensionStyle(${JSON.stringify(created.style.id)}).name`),'Presentation');assert.equal(state(b).history,before.history+1);before=state(b);assert.equal(b.read(`dimensionStyleGateway.update(${JSON.stringify(created.style.id)},{textHeight:6,linearPrecision:1})`).status,'committed');assert.equal(state(b).history,before.history+1);before=state(b);assert.equal(b.read(`dimensionStyleGateway.setCurrent(${JSON.stringify(created.style.id)})`).status,'committed');assert.equal(b.read('modelReader.currentDimensionStyleId()'),created.style.id);assert.equal(state(b).history,before.history+1);b.run('documentController.undo()');assert.equal(b.read('modelReader.currentDimensionStyleId()'),original.id);b.run('documentController.redo()');assert.equal(b.read('modelReader.currentDimensionStyleId()'),created.style.id)})

test('style validation rejects names and numeric settings without partial mutation',async()=>{const b=await browser();b.read("dimensionStyleGateway.create('Large')");const style=b.read("modelReader.dimensionStyles().find(style=>style.name==='Large')"),before=state(b);for(const expression of [`dimensionStyleGateway.rename('${style.id}',' ')`,`dimensionStyleGateway.rename('${style.id}','Standard')`,`dimensionStyleGateway.rename('${style.id}','${'x'.repeat(65)}')`,`dimensionStyleGateway.rename('${style.id}','bad\\u0001')`,`dimensionStyleGateway.update('${style.id}',{textHeight:0})`,`dimensionStyleGateway.update('${style.id}',{arrowSize:-1})`,`dimensionStyleGateway.update('${style.id}',{linearPrecision:16})`,`dimensionStyleGateway.update('${style.id}',{textGap:Infinity})`])assert.notEqual(b.read(expression).status,'committed');assert.deepEqual(state(b),before)})

test('delete blocks current and referenced styles but removes unused non-current style exactly',async()=>{const b=await browser();const standard=b.read('modelReader.currentDimensionStyleId()'),unused=b.read("dimensionStyleGateway.create('Unused').style"),used=b.read("dimensionStyleGateway.create('Used').style"),record=dimension(b);assert.equal(b.read(`dimensionStyleGateway.delete(${JSON.stringify(standard)}).status`),'current-style');b.read(`dimensionStyleGateway.assign([${JSON.stringify(record.id)}],${JSON.stringify(used.id)})`);assert.equal(b.read(`dimensionStyleGateway.delete(${JSON.stringify(used.id)}).status`),'style-in-use');const before=state(b);assert.equal(b.read(`dimensionStyleGateway.delete(${JSON.stringify(unused.id)}).status`),'committed');assert.equal(state(b).history,before.history+1);b.run('documentController.undo()');assert.equal(b.read(`modelReader.dimensionStyle(${JSON.stringify(unused.id)}).id`),unused.id);b.run('documentController.redo()');assert.equal(b.read(`modelReader.dimensionStyles().some(style=>style.id===${JSON.stringify(unused.id)})`),false)})

test('assignment preserves dimension identity geometry properties and text override',async()=>{const b=await browser(),record=dimension(b,'EXACT'),style=b.read("dimensionStyleGateway.create('Large').style"),before=state(b);assert.equal(b.read(`dimensionStyleGateway.assign([${JSON.stringify(record.id)}],${JSON.stringify(style.id)}).status`),'committed');const changed=b.read('modelReader.records()[0]');assert.deepEqual({...changed,dimensionStyleId:record.dimensionStyleId},record);assert.equal(changed.dimensionStyleId,style.id);assert.equal(state(b).history,before.history+1);b.run('documentController.undo()');assert.deepEqual(b.read('modelReader.records()[0]'),record);b.run('documentController.redo()');assert.deepEqual(b.read('modelReader.records()[0]'),changed)})

test('style edits propagate presentation without rewriting dimensions and respect Text Override',async()=>{const b=await browser(),automatic=dimension(b),override=dimension(b,'LOCKED'),styleId=automatic.dimensionStyleId,recordsBefore=b.read('modelReader.records()');b.window.__automaticId=automatic.id;const beforeAuto=b.read('(()=>{const record=modelReader.records().find(value=>value.id===window.__automaticId);return window.CaderactDimensionGeometry.derive(record,modelReader.resolveDimensionStyle(record),modelReader.units()).text})()');b.read(`dimensionStyleGateway.update(${JSON.stringify(styleId)},{textHeight:7,textGap:2,arrowSize:5,extensionBeyond:4,linearPrecision:1})`);assert.deepEqual(b.read('modelReader.records()'),recordsBefore);const after=b.read('modelReader.records().map(record=>({override:record.textOverride,text:window.CaderactDimensionGeometry.derive(record,modelReader.resolveDimensionStyle(record),modelReader.units()).text}))');const automaticText=after.find(value=>value.override===null).text,overrideText=after.find(value=>value.override==='LOCKED').text;assert.notEqual(automaticText.height,beforeAuto.height);assert.match(automaticText.value,/10\.0/);assert.equal(overrideText.value,'LOCKED');assert.ok(override.id)})

test('v3 persistence preserves style order IDs current style and references exactly',async()=>{const b=await browser(),large=b.read("dimensionStyleGateway.create('Large').style"),small=b.read("dimensionStyleGateway.create('Small').style");b.run(`dimensionStyleGateway.update(${JSON.stringify(large.id)},{textHeight:8});dimensionStyleGateway.setCurrent(${JSON.stringify(small.id)})`);const record=dimension(b);b.read(`dimensionStyleGateway.assign([${JSON.stringify(record.id)}],${JSON.stringify(large.id)})`);const snapshot=b.read('modelReader.snapshot()'),serialized=b.run('window.CaderactPersistence.serializeDocument(modelReader.snapshot())');b.window.__file=serialized;b.run('window.__loaded=window.CaderactPersistence.loadStore(window.__file)');assert.deepEqual(b.read('window.__loaded.reader.snapshot()'),snapshot);assert.equal(JSON.parse(serialized).fileVersion,3)})

test('copy and every shared transform preserve style while copy receives fresh identities',async()=>{const b=await browser(),style=b.read("dimensionStyleGateway.create('Large').style");b.read(`dimensionStyleGateway.setCurrent(${JSON.stringify(style.id)})`);const record=dimension(b);b.window.__r=record;for(const expression of ["translateRecord(window.__r,1,2)","rotateRecord(window.__r,{x:0,y:0},1)","scaleRecord(window.__r,{x:0,y:0},2)","mirrorRecord(window.__r,{x:0,y:0},{x:0,y:1})"]){const transformed=b.read(`window.CaderactGeometryTransform.${expression}`);assert.equal(transformed.dimensionStyleId,style.id)}const copy=b.read('recordGateway.copyWithFreshIdentity(window.__r)');assert.equal(copy.dimensionStyleId,style.id);assert.notEqual(copy.id,record.id)})

test('dimension commands capture current style at command start',async()=>{const b=await browser(),styleA=b.read("dimensionStyleGateway.create('A').style"),styleB=b.read("dimensionStyleGateway.create('B').style");b.read(`dimensionStyleGateway.setCurrent(${JSON.stringify(styleA.id)})`);b.launch('Linear');typed(b,'0,0');b.read(`dimensionStyleGateway.setCurrent(${JSON.stringify(styleB.id)})`);typed(b,'10,0');typed(b,'5,4');assert.equal(b.read("modelReader.records().find(record=>record.type==='dimension-linear').dimensionStyleId"),styleA.id);b.launch('Aligned');for(const point of ['0,10','3,14','2,15'])typed(b,point);b.launch('Angular');for(const point of ['20,0','10,0','10,10','15,5'])typed(b,point);b.run('window.__circle=recordGateway.createCircle({x:30,y:0},5);recordGateway.createAll([window.__circle]);window.caderactSelection.selectOnly(window.__circle.id)');b.launch('DRA');typed(b,'37,3');assert.equal(b.read(`modelReader.records().filter(record=>record.type.startsWith('dimension-')&&record.dimensionStyleId===${JSON.stringify(styleB.id)}).length`),3);assert.equal(b.read("modelReader.records().find(record=>record.type==='dimension-radial').dimensionStyleId"),styleB.id)})
