'use strict';
const test=require('node:test');const assert=require('node:assert/strict');const {browser}=require('../helpers/browser.cjs');

test('D1 document defaults to strict v2 and migrates a valid v1 file',async()=>{const b=await browser();assert.equal(b.read('modelReader.snapshot().formatVersion'),2);assert.deepEqual(b.read('modelReader.dimensionStyle()'),{textHeight:2.5,arrowSize:2.5,extensionGap:1,extensionBeyond:1,textGap:.75,linearPrecision:3,angularPrecision:2,showUnit:true,prefix:'',suffix:'',arrowStyle:'closed-filled'});const v2=JSON.parse(b.run('window.CaderactPersistence.serializeDocument(modelReader.snapshot())'));const v1=structuredClone(v2);v1.fileVersion=1;v1.document.formatVersion=1;delete v1.document.dimensionStyle;b.window.__legacy=JSON.stringify(v1);b.run('window.__migrated=window.CaderactPersistence.loadStore(window.__legacy)');assert.equal(b.read('window.__migrated.reader.snapshot().formatVersion'),2);assert.deepEqual(b.read('window.__migrated.reader.dimensionStyle()'),b.read('window.CaderactDocument.DEFAULT_DIMENSION_STYLE'))});

test('native dimensions own stable feature IDs and strict v2 round-trip',async()=>{const b=await browser();b.run(`window.__dims=[recordGateway.createLinearDimension({mode:'aligned',firstPoint:{x:0,y:0},secondPoint:{x:10,y:0},dimensionLinePoint:{x:0,y:3}}),recordGateway.createAngularDimension({firstRayPoint:{x:1,y:0},vertex:{x:0,y:0},secondRayPoint:{x:0,y:1},dimensionArcPoint:{x:2,y:2}}),recordGateway.createRadialDimension({mode:'diameter',centerPoint:{x:0,y:0},dimensionPoint:{x:5,y:0},leaderPoint:{x:8,y:2}})];recordGateway.createAll(window.__dims)`);const records=b.read('modelReader.records()');assert.deepEqual(records.map(x=>x.type).sort(),['dimension-angular','dimension-linear','dimension-radial']);const ids=records.flatMap(record=>Object.values(record).filter(value=>value&&value.featureId).map(value=>value.featureId));assert.equal(new Set(ids).size,10);const serialized=b.run('window.CaderactPersistence.serializeDocument(modelReader.snapshot())');assert.equal(JSON.parse(serialized).fileVersion,2);b.window.__file=serialized;b.run('window.__loaded=window.CaderactPersistence.loadStore(window.__file)');assert.deepEqual(b.read('window.__loaded.reader.records()'),records);const invalid=JSON.parse(serialized);invalid.document.records[0].extra=true;b.window.__bad=JSON.stringify(invalid);assert.throws(()=>b.run('window.CaderactPersistence.loadStore(window.__bad)'),/unknown field/)});

test('dimension style changes are atomic metadata history and undo exactly',async()=>{const b=await browser();const before=b.read('modelReader.dimensionStyle()');const outcome=b.read(`(()=>{window.__styleResult=dimensionStyleGateway.set({textHeight:4,prefix:'~'});return window.__styleResult})()`);assert.equal(outcome.status,'committed');assert.equal(b.read('documentController.historyInfo.entryCount'),1);assert.equal(b.read('modelReader.dimensionStyle().textHeight'),4);b.run('documentController.undo()');assert.deepEqual(b.read('modelReader.dimensionStyle()'),before);b.run('documentController.redo()');assert.equal(b.read('modelReader.dimensionStyle().prefix'),'~')});

test('linear measurement, formatting and geometry are deterministic for all modes',async()=>{const b=await browser();for(const [mode,expected] of [['horizontal',3],['vertical',4],['aligned',5]]){b.window.__record={type:'dimension-linear',mode,firstPoint:{x:0,y:0},secondPoint:{x:3,y:4},dimensionLinePoint:{x:0,y:8},textOverride:null};assert.equal(b.read('window.CaderactDimensionGeometry.measure(window.__record).value'),expected);const presentation=b.read(`window.CaderactDimensionGeometry.derive(window.__record,{...window.CaderactDocument.DEFAULT_DIMENSION_STYLE},{length:'mm'})`);assert.equal(presentation.supported,true);assert.equal(presentation.lines.length,3);assert.equal(presentation.triangles.length,2);assert.match(presentation.text.value,/mm$/)}b.run(`window.__record.textOverride='CUSTOM'`);assert.equal(b.read(`window.CaderactDimensionGeometry.derive(window.__record,window.CaderactDocument.DEFAULT_DIMENSION_STYLE,{length:'mm'}).text.value`),'CUSTOM')});

test('scene projects dimension lines, filled triangles and model-sized DOM annotation data',async()=>{const b=await browser();b.run(`recordGateway.createAll([recordGateway.createLinearDimension({mode:'horizontal',firstPoint:{x:0,y:0},secondPoint:{x:10,y:0},dimensionLinePoint:{x:0,y:5}})])`);b.resize(800,600);b.flush();const scene=b.renders.at(-1);assert.equal(scene.triangleGroups[0].triangles.length,2);assert.equal(scene.annotationOverlay.items.length,1);assert.equal(scene.annotationOverlay.items[0].fontSize,12.5);assert.ok(scene.drawGroups.some(group=>group.lineGroup.segments.length>=12));assert.equal(b.read('documentController.historyInfo.entryCount'),1)});

test('angular presentation is native while radial presentation remains deferred',async()=>{const b=await browser();b.window.__angular={type:'dimension-angular',firstRayPoint:{x:1,y:0},vertex:{x:0,y:0},secondRayPoint:{x:0,y:1},dimensionArcPoint:{x:1,y:1},textOverride:null};b.window.__radial={type:'dimension-radial',mode:'diameter',centerPoint:{x:0,y:0},dimensionPoint:{x:3,y:4},leaderPoint:{x:7,y:4}};assert.equal(b.read('window.CaderactDimensionGeometry.measure(window.__angular).value'),Math.PI/2);assert.equal(b.read('window.CaderactDimensionGeometry.measure(window.__radial).value'),10);assert.equal(b.read('window.CaderactDimensionGeometry.derive(window.__angular,window.CaderactDocument.DEFAULT_DIMENSION_STYLE,{length:"mm"}).supported'),true);assert.deepEqual(b.read('window.CaderactDimensionGeometry.derive(window.__radial,window.CaderactDocument.DEFAULT_DIMENSION_STYLE,{length:"mm"})'),{supported:false,measurement:{kind:'linear',value:10},reason:'presentation-deferred'})});
