'use strict';
const test=require('node:test');
const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const {browser}=require('../helpers/browser.cjs');

function exportImport(b){b.run('window.__exported=window.CaderactDxfExport.exportDocument(modelReader.snapshot());window.__roundtrip=window.CaderactDxfImport.createStore(window.__exported.text)');return b.read('({text:window.__exported.text,diagnostics:window.__exported.diagnostics,records:window.__roundtrip.store.reader.records(),layers:window.__roundtrip.store.reader.layers(),document:window.__roundtrip.store.reader.snapshot(),unit:window.__roundtrip.unit})')}
function clean(record){const point=value=>value&&typeof value==='object'?Object.fromEntries(Object.entries(value).filter(([key])=>key!=='featureId').map(([key,child])=>[key,point(child)])):value;const value=point(record);delete value.id;delete value.layerId;return value}
function near(a,b,tolerance=1e-10){assert.ok(Math.abs(a-b)<=tolerance,`${a} != ${b}`)}

test('writer emits valid deterministic AC1018 ASCII structure and supported units',async()=>{for(const [unit,code] of [['in',1],['ft',2],['mm',4],['cm',5],['m',6]]){const b=await browser();b.run(`layerGateway.rename(modelReader.snapshot().defaultLayerId,'0');unitGateway.setLengthUnit(${JSON.stringify(unit)})`);const first=b.run('window.CaderactDxfExport.exportDocument(modelReader.snapshot()).text'),second=b.run('window.CaderactDxfExport.exportDocument(modelReader.snapshot()).text');assert.equal(first,second);assert.match(first,/\n\$ACADVER\n1\nAC1018\n/);assert.match(first,new RegExp(`\\n\\$INSUNITS\\n70\\n${code}\\n`));b.window.__text=first;assert.equal(b.read('window.CaderactDxfParser.parse(window.__text).source.acadVersion'),'AC1018');assert.equal(b.read('window.CaderactDxfImport.createStore(window.__text).unit'),unit);assert.match(first,/^0\nSECTION\n/);assert.match(first,/0\nEOF\n$/)}});

test('numeric serialization is round-trip safe, finite-only, and normalizes negative zero',async()=>{const b=await browser();assert.equal(b.run('window.CaderactDxfExport.number(-0)'),'0');assert.equal(b.run('window.CaderactDxfExport.number(1.2345678901234567)'),'1.2345678901234567');for(const expression of ['NaN','Infinity','-Infinity'])assert.throws(()=>b.run(`window.CaderactDxfExport.number(${expression})`),/finite/)});

test('Line, open/closed Polyline, Circle, and rotated Ellipse round trip semantically',async()=>{const b=await browser();b.run(`layerGateway.rename(modelReader.snapshot().defaultLayerId,'0');recordGateway.createAll([recordGateway.createLine({x:-2,y:3},{x:7,y:-4}),recordGateway.createPolyline([{x:0,y:0},{x:4,y:1},{x:5,y:5}],false),recordGateway.createPolyline([{x:-1,y:-1},{x:2,y:-1},{x:0,y:3}],true),recordGateway.createCircle({x:8,y:9},2.5),recordGateway.createEllipse({center:{x:12,y:-4},majorAxis:{x:3,y:4},minorRadius:2})])`);const before=b.read('modelReader.records().map(record=>record)'),after=exportImport(b).records,sort=values=>values.map(clean).sort((a,c)=>JSON.stringify(a).localeCompare(JSON.stringify(c)));assert.deepEqual(sort(after),sort(before))});

test('minor, major, wrapped, and clockwise mirrored Arc loci survive without complementary arcs',async()=>{const b=await browser();b.run(`layerGateway.rename(modelReader.snapshot().defaultLayerId,'0');function arc(start,sweep,radius=5){return recordGateway.createArc({center:{x:0,y:0},radius,start:{x:Math.cos(start)*radius,y:Math.sin(start)*radius},end:{x:Math.cos(start+sweep)*radius,y:Math.sin(start+sweep)*radius},sweep})}recordGateway.createAll([arc(0,Math.PI/3),arc(.2,Math.PI*1.5),arc(350*Math.PI/180,20*Math.PI/180),arc(Math.PI/2,-Math.PI/2)])`);const result=exportImport(b),records=result.records.filter(value=>value.type==='arc');assert.deepEqual(records.map(value=>Math.round(value.sweep*180/Math.PI)).sort((a,c)=>a-c),[60,90,270,20].sort((a,c)=>a-c));assert.ok(result.diagnostics.some(value=>value.code==='DXF_ARC_DIRECTION_CANONICALIZED'));for(const record of records)near(Math.hypot(record.start.x,record.start.y),5)});

test('Text Left/Center/Right, rotation, Unicode, and literal escape text round trip',async()=>{const b=await browser();b.run(`layerGateway.rename(modelReader.snapshot().defaultLayerId,'0');recordGateway.createAll([recordGateway.createText({insertionPoint:{x:1,y:2},text:'Left ±',height:2,rotation:0,horizontalAlignment:'left'}),recordGateway.createText({insertionPoint:{x:3,y:4},text:'中央 Ø',height:3,rotation:Math.PI/2,horizontalAlignment:'center'}),recordGateway.createText({insertionPoint:{x:-2,y:8},text:'Right '+String.fromCharCode(92)+'U+0041',height:1.5,rotation:Math.PI*1.75,horizontalAlignment:'right'})])`);const before=b.read('modelReader.records().map(r=>r)'),result=exportImport(b),after=result.records;for(const source of before){const target=after.find(value=>value.text===source.text);assert.ok(target);assert.equal(target.horizontalAlignment,source.horizontalAlignment);assert.deepEqual({x:target.insertionPoint.x,y:target.insertionPoint.y},{x:source.insertionPoint.x,y:source.insertionPoint.y});near(target.rotation,source.rotation);assert.equal(target.height,source.height)}assert.match(result.text,/\\U\+00B1/);assert.match(result.text,/\\U\+005CU\+0041/)});

test('layers, visibility, locking, assignment, and native properties round trip',async()=>{const b=await browser();b.run(`layerGateway.rename(modelReader.snapshot().defaultLayerId,'0');layerGateway.create('Hidden');layerGateway.create('Locked');window.__hidden=modelReader.layers().find(l=>l.name==='Hidden');window.__locked=modelReader.layers().find(l=>l.name==='Locked');window.__a=recordGateway.createLine({x:0,y:0},{x:1,y:0});window.__b=recordGateway.createCircle({x:3,y:3},1);recordGateway.createAll([window.__a,window.__b]);recordGateway.assignLayer([window.__a.id],window.__hidden.id);recordGateway.assignLayer([window.__b.id],window.__locked.id);recordGateway.setProperties([window.__b.id],{color:'#ff0000',linetype:'dashed',lineweight:.35});window.__tx=documentController.beginTransaction();window.__tx.replaceIn('layers',window.__hidden.id,{...window.__hidden,visible:false,color:'#123456',linetype:'dotted',lineweight:.7});window.__tx.replaceIn('layers',window.__locked.id,{...window.__locked,locked:true,color:'#abcdef',linetype:'dash-dot',lineweight:.5});window.__tx.publish()`);const result=exportImport(b),layers=Object.fromEntries(result.layers.map(value=>[value.name,value]));assert.deepEqual({visible:layers.Hidden.visible,locked:layers.Hidden.locked,color:layers.Hidden.color,linetype:layers.Hidden.linetype,lineweight:layers.Hidden.lineweight},{visible:false,locked:false,color:'#123456',linetype:'dotted',lineweight:.7});assert.deepEqual({visible:layers.Locked.visible,locked:layers.Locked.locked,color:layers.Locked.color,linetype:layers.Locked.linetype,lineweight:layers.Locked.lineweight},{visible:true,locked:true,color:'#abcdef',linetype:'dash-dot',lineweight:.5});const circle=result.records.find(value=>value.type==='circle');assert.equal(result.layers.find(value=>value.id===circle.layerId).name,'Locked');assert.deepEqual({color:circle.color,linetype:circle.linetype,lineweight:circle.lineweight},{color:'#ff0000',linetype:'dashed',lineweight:.35})});

test('unrepresentable dimension formatting and Ellipse fail explicitly',async()=>{const dimension=await browser();dimension.run(`dimensionStyleGateway.set({prefix:'custom '})`);assert.throws(()=>dimension.run('window.CaderactDxfExport.exportDocument(modelReader.snapshot())'),/formatting not representable/);const diagnostic=dimension.read(`(()=>{try{window.CaderactDxfExport.exportDocument(modelReader.snapshot())}catch(error){return error.diagnostics[0]}})()`);assert.equal(diagnostic.code,'DXF_EXPORT_DIMSTYLE_FORMAT_UNSUPPORTED');const ellipse=await browser();ellipse.run(`recordGateway.createAll([recordGateway.createEllipse({center:{x:0,y:0},majorAxis:{x:1,y:0},minorRadius:2})])`);assert.throws(()=>ellipse.run('window.CaderactDxfExport.exportDocument(modelReader.snapshot())'),/major axis/)});

test('Export DXF file action writes independently without changing native filename or state',async()=>{const b=await browser();b.run(`recordGateway.createAll([recordGateway.createLine({x:0,y:0},{x:1,y:1})]);window.__writes=[];window.__actions=window.CaderactFileActions.createActions({session:window.caderactDocumentSession,commandRouter:window.caderactCommandRouter,viewport:window.caderactViewport,adapters:{writeFile:async value=>{window.__writes.push(value);},confirmDiscard:async()=>true}});window.__before={filename:window.__actions.filename,revision:documentController.currentRevision,stateId:documentController.currentStateId,history:documentController.historyInfo,dirty:documentController.isDirty,document:window.CaderactPersistence.serializeDocument(modelReader.snapshot())}`);const outcome=await b.run('window.__actions.exportDxf()'),after=b.read('({filename:window.__actions.filename,revision:documentController.currentRevision,stateId:documentController.currentStateId,history:documentController.historyInfo,dirty:documentController.isDirty,document:window.CaderactPersistence.serializeDocument(modelReader.snapshot()),write:window.__writes[0]})');assert.equal(outcome.status,'dxf-export-completed');assert.equal(after.filename,'Untitled.caderact');assert.deepEqual({...after,write:undefined},{...b.read('window.__before'),write:undefined});assert.equal(after.write.filename,'Untitled.dxf');assert.equal(after.write.mimeType,'application/dxf');assert.equal(b.fileExportDxfButton.listeners.click.length,1)});

test('DXF remains isolated from renderers and native persistence remains authoritative',async()=>{const root=path.join(__dirname,'../..');for(const file of ['src/js/rendering/Canvas2DRenderer.js','src/js/rendering/WebGPURenderer.js'])assert.doesNotMatch(fs.readFileSync(path.join(root,file),'utf8'),/dxf/i);const b=await browser();assert.equal(b.read('window.CaderactPersistence.FILE_VERSION'),3)});

test('complete mixed supported drawing reimports with every native export type',async()=>{const b=await browser();b.run(`layerGateway.rename(modelReader.snapshot().defaultLayerId,'0');recordGateway.createAll([recordGateway.createLine({x:0,y:0},{x:1,y:1}),recordGateway.createPolyline([{x:0,y:2},{x:2,y:2}],false),recordGateway.createCircle({x:4,y:4},1),recordGateway.createArc({center:{x:6,y:6},radius:2,start:{x:8,y:6},end:{x:6,y:8},sweep:Math.PI/2}),recordGateway.createEllipse({center:{x:9,y:9},majorAxis:{x:3,y:1},minorRadius:1}),recordGateway.createText({insertionPoint:{x:12,y:12},text:'Mixed',height:2,rotation:.25,horizontalAlignment:'right'})])`);const result=exportImport(b);assert.deepEqual(result.records.map(value=>value.type).sort(),['arc','circle','ellipse','line','polyline','text'])});
