'use strict';
const test=require('node:test');
const assert=require('node:assert/strict');
const {browser}=require('../helpers/browser.cjs');

function roundTrip(b){b.run('window.__dx=window.CaderactDxfExport.exportDocument(modelReader.snapshot());window.__di=window.CaderactDxfImport.createStore(window.__dx.text)');return b.read('({text:window.__dx.text,diagnostics:window.__di.diagnostics,document:window.__di.store.reader.snapshot(),records:window.__di.store.reader.records(),styles:window.__di.store.reader.dimensionStyles()})')}
const strip=value=>JSON.parse(JSON.stringify(value),(key,child)=>key==='id'||key==='featureId'||key==='layerId'||key==='dimensionStyleId'?undefined:child)

test('DXF6 round trips linear, aligned, angular, radius, and diameter dimensions semantically',async()=>{const b=await browser();b.run(`recordGateway.createAll([
recordGateway.createLinearDimension({mode:'horizontal',firstPoint:{x:0,y:0},secondPoint:{x:10,y:2},dimensionLinePoint:{x:4,y:5},textOverride:'TEN'}),
recordGateway.createLinearDimension({mode:'vertical',firstPoint:{x:20,y:0},secondPoint:{x:22,y:8},dimensionLinePoint:{x:25,y:4}}),
recordGateway.createLinearDimension({mode:'aligned',firstPoint:{x:0,y:10},secondPoint:{x:3,y:14},dimensionLinePoint:{x:1,y:16}}),
recordGateway.createAngularDimension({firstRayPoint:{x:31,y:0},vertex:{x:30,y:0},secondRayPoint:{x:30,y:1},dimensionArcPoint:{x:32,y:2}}),
recordGateway.createRadialDimension({mode:'radius',centerPoint:{x:40,y:0},dimensionPoint:{x:45,y:0},leaderPoint:{x:47,y:2}}),
recordGateway.createRadialDimension({mode:'diameter',centerPoint:{x:60,y:0},dimensionPoint:{x:65,y:0},leaderPoint:{x:68,y:2}})])`);const before=b.read('modelReader.records()'),result=roundTrip(b);assert.deepEqual(result.records.map(r=>r.type).sort(),before.map(r=>r.type).sort());assert.deepEqual(result.records.map(strip).sort((a,c)=>JSON.stringify(a).localeCompare(JSON.stringify(c))),before.map(strip).sort((a,c)=>JSON.stringify(a).localeCompare(JSON.stringify(c))));assert.match(result.text,/\nBLOCKS\n/);assert.equal(result.records.length,6)});

test('DIMSTYLE fields, current style, and dimension style references survive with fresh native identities',async()=>{const b=await browser();b.run(`window.__s=dimensionStyleGateway.create('Architectural').style;dimensionStyleGateway.update(window.__s.id,{textHeight:4,textGap:1.25,arrowSize:3,extensionGap:.5,extensionBeyond:2,linearPrecision:5,angularPrecision:4});dimensionStyleGateway.setCurrent(window.__s.id);recordGateway.createAll([recordGateway.createLinearDimension({mode:'horizontal',firstPoint:{x:0,y:0},secondPoint:{x:5,y:0},dimensionLinePoint:{x:2,y:2},dimensionStyleId:window.__s.id})])`);const oldId=b.read('window.__s.id'),result=roundTrip(b),style=result.styles.find(s=>s.name==='Architectural'),record=result.records[0];assert.ok(style);assert.notEqual(style.id,oldId);assert.deepEqual({textHeight:style.textHeight,textGap:style.textGap,arrowSize:style.arrowSize,extensionGap:style.extensionGap,extensionBeyond:style.extensionBeyond,linearPrecision:style.linearPrecision,angularPrecision:style.angularPrecision},{textHeight:4,textGap:1.25,arrowSize:3,extensionGap:.5,extensionBeyond:2,linearPrecision:5,angularPrecision:4});assert.equal(record.dimensionStyleId,style.id);assert.equal(result.document.currentDimensionStyleId,style.id)});

test('unsupported dimension kinds and rotated linear dimensions skip explicitly',async()=>{const b=await browser(),source=['0','SECTION','2','HEADER','9','$ACADVER','1','AC1018','9','$INSUNITS','70','4','0','ENDSEC','0','SECTION','2','ENTITIES','0','DIMENSION','70','34','10','0','20','0','13','0','23','0','14','1','24','1','0','DIMENSION','70','32','10','0','20','2','13','0','23','0','14','2','24','2','50','30','0','ENDSEC','0','EOF'].join('\n')+'\n';b.window.__source=source;const result=b.read('window.CaderactDxfImport.createStore(window.__source)');assert.equal(result.importedCount,0);assert.ok(result.diagnostics.some(d=>d.code==='DXF_DIMENSION_TYPE_UNSUPPORTED'));assert.ok(result.diagnostics.some(d=>d.code==='DXF_ROTATED_DIMENSION_UNSUPPORTED'))});

test('malformed supported DIMENSION is fatal and import remains isolated',async()=>{const b=await browser(),source=['0','SECTION','2','HEADER','9','$ACADVER','1','AC1018','9','$INSUNITS','70','4','0','ENDSEC','0','SECTION','2','ENTITIES','0','DIMENSION','70','33','10','0','20','2','13','0','23','0','14','2','0','ENDSEC','0','EOF'].join('\n')+'\n';b.window.__source=source;assert.throws(()=>b.run('window.CaderactDxfImport.createStore(window.__source)'),/second definition point/);assert.equal(b.read('modelReader.records().length'),0);assert.equal(b.read('documentController.historyInfo.entryCount'),0)});

test('dimension layers and explicit object properties survive including hidden and locked layers',async()=>{const b=await browser();b.run(`layerGateway.create('Dims');window.__layer=modelReader.layers().find(l=>l.name==='Dims');window.__d=recordGateway.createRadialDimension({mode:'radius',centerPoint:{x:0,y:0},dimensionPoint:{x:4,y:0},leaderPoint:{x:6,y:2}});recordGateway.createAll([window.__d]);recordGateway.assignLayer([window.__d.id],window.__layer.id);recordGateway.setProperties([window.__d.id],{color:'#12ab34',linetype:'dashed',lineweight:.35});window.__tx=documentController.beginTransaction();window.__tx.replaceIn('layers',window.__layer.id,{...window.__layer,visible:false,locked:true});window.__tx.publish()`);const result=roundTrip(b),record=result.records[0],layer=Object.values(result.document.layers).find(l=>l.name==='Dims');assert.deepEqual({visible:layer.visible,locked:layer.locked},{visible:false,locked:true});assert.equal(record.layerId,layer.id);assert.deepEqual({color:record.color,linetype:record.linetype,lineweight:record.lineweight},{color:'#12ab34',linetype:'dashed',lineweight:.35})});

test('unknown style references fall back explicitly and malformed DIMSTYLE rejects atomically',async()=>{const b=await browser(),head=['0','SECTION','2','HEADER','9','$ACADVER','1','AC1018','9','$INSUNITS','70','4','0','ENDSEC'],dim=['0','DIMENSION','3','Missing','70','32','10','0','20','2','13','0','23','0','14','4','24','0','50','0'];b.window.__unknown=[...head,'0','SECTION','2','ENTITIES',...dim,'0','ENDSEC','0','EOF'].join('\n')+'\n';const result=b.read('window.CaderactDxfImport.createStore(window.__unknown)');assert.equal(result.importedCount,1);assert.ok(result.diagnostics.some(d=>d.code==='DXF_DIMSTYLE_REFERENCE_UNKNOWN'));b.window.__bad=[...head,'0','SECTION','2','TABLES','0','TABLE','2','DIMSTYLE','70','1','0','DIMSTYLE','2','Bad','140','0','0','ENDTAB','0','ENDSEC','0','SECTION','2','ENTITIES','0','ENDSEC','0','EOF'].join('\n')+'\n';assert.throws(()=>b.run('window.CaderactDxfImport.createStore(window.__bad)'),/text height/);assert.equal(b.read('modelReader.records().length'),0)});

test('dimension export is deterministic across native identities and mixed content reimports once',async()=>{const make=async()=>{const b=await browser();b.run(`recordGateway.createAll([recordGateway.createLine({x:0,y:0},{x:1,y:1}),recordGateway.createText({insertionPoint:{x:2,y:2},text:'DXF6',height:1,rotation:0,horizontalAlignment:'left'}),recordGateway.createLinearDimension({mode:'aligned',firstPoint:{x:0,y:0},secondPoint:{x:3,y:4},dimensionLinePoint:{x:1,y:6}})])`);return{b,text:b.run('window.CaderactDxfExport.exportDocument(modelReader.snapshot()).text')}};const a=await make(),c=await make();assert.equal(a.text,c.text);a.b.window.__source=a.text;const records=a.b.read('window.CaderactDxfImport.createStore(window.__source).store.reader.records()');assert.deepEqual(records.map(r=>r.type).sort(),['dimension-linear','line','text'])});
