const test=require('node:test'),assert=require('node:assert/strict'),{browser}=require('../helpers/browser.cjs')
const head=['0','SECTION','2','HEADER','9','$ACADVER','1','AC1018','9','$INSUNITS','70','4','0','ENDSEC']
const line=['0','LINE','8','0','10','1','20','2','11','4','21','2']
const insert=(name,x=0,y=0,sx=1,sy=1,rotation=0)=>['0','INSERT','8','0','2',name,'10',String(x),'20',String(y),'41',String(sx),'42',String(sy),'50',String(rotation)]
function dxf(blocks=[],entities=[]){return [...head,'0','SECTION','2','BLOCKS',...blocks.flat(),'0','ENDSEC','0','SECTION','2','ENTITIES',...entities.flat(),'0','ENDSEC','0','EOF'].join('\n')+'\n'}
const block=(name,members= line,base={x:0,y:0})=>['0','BLOCK','8','0','2',name,'70','0','10',String(base.x),'20',String(base.y),'30','0','3',name,'1','',...members,'0','ENDBLK','8','0']

test('GB10 imports BLOCK/ENDBLK and INSERT as native definitions and instances with fresh identities',async()=>{const b=await browser();b.window.__dxf=dxf([block('Part',line,{x:2,y:3})],[insert('Part',10,20)]);b.run('window.__result=window.CaderactDxfImport.createStore(window.__dxf)');const result=b.read('({definitions:window.__result.store.reader.blockDefinitions(),records:window.__result.store.reader.records(),parsed:window.__result.parsed.blocks})');assert.equal(result.definitions.length,1);assert.equal(result.definitions[0].name,'Part');assert.deepEqual(result.definitions[0].basePoint,{x:2,y:3});assert.equal(result.definitions[0].records[result.definitions[0].recordOrder[0]].type,'line');assert.equal(result.records[0].type,'block-instance');assert.equal(result.records[0].definitionId,result.definitions[0].id);assert.notEqual(result.records[0].id,result.definitions[0].recordOrder[0]);assert.equal(result.parsed[0].entities[0].type,'LINE')})

test('GB10 resolves forward and nested INSERT references without flattening',async()=>{const b=await browser();b.window.__dxf=dxf([block('Outer',insert('Inner',5,6)),block('Inner')],[insert('Outer',20,30),insert('Inner',40,50)]);b.run('window.__s=window.CaderactDxfImport.createStore(window.__dxf).store');const value=b.read('({defs:window.__s.reader.blockDefinitions(),records:window.__s.reader.records()})'),outer=value.defs.find(d=>d.name==='Outer'),inner=value.defs.find(d=>d.name==='Inner'),nested=outer.records[outer.recordOrder[0]];assert.equal(nested.type,'block-instance');assert.equal(nested.definitionId,inner.id);assert.equal(value.records.length,2);assert.equal(value.defs.length,2)})

test('GB10 canonicalizes rotations and signed uniform scales and rejects invalid transforms',async()=>{for(const [sx,sy,rotation,mirrored,angle] of [[2,2,450,false,Math.PI/2],[-2,2,-90,true,-Math.PI/2],[2,-2,0,true,Math.PI],[-2,-2,0,false,Math.PI]]){const b=await browser();b.window.__dxf=dxf([block('B')],[insert('B',0,0,sx,sy,rotation)]);const r=b.read('window.CaderactDxfImport.createStore(window.__dxf).store.reader.records()[0]');assert.equal(r.scale,2);assert.equal(r.mirrored,mirrored);assert.ok(Math.abs(r.rotation-angle)<1e-10)}for(const [sx,sy,pattern] of [[2,3,/nonuniform/],[0,0,/nonzero/]]){const b=await browser();b.window.__dxf=dxf([block('B')],[insert('B',0,0,sx,sy)]);assert.throws(()=>b.run('window.CaderactDxfImport.createStore(window.__dxf)'),pattern)}})

test('GB10 rejects missing references, duplicate names, cycles, and malformed termination atomically',async()=>{const cases=[[dxf([], [insert('Missing')]),/missing block/],[dxf([block('A'),block('a')]),/Duplicate block/],[dxf([block('A',insert('B')),block('B',insert('A'))]),/cycle/],[dxf([block('A').slice(0,-4)]),/missing ENDBLK/]];for(const [source,pattern] of cases){const b=await browser();b.window.__dxf=source;assert.throws(()=>b.run('window.CaderactDxfImport.createStore(window.__dxf)'),pattern);assert.equal(b.read('modelReader.records().length'),0);assert.equal(b.read('documentController.historyInfo.entryCount'),0)}})

test('GB10 preserves Layer 0 members and deterministically maps BYBLOCK to native ByLayer',async()=>{const byblock=['0','LINE','8','0','62','0','6','BYBLOCK','370','-2','10','0','20','0','11','1','21','0'],b=await browser();b.window.__dxf=dxf([block('B',byblock)],[insert('B')]);b.run('window.__r=window.CaderactDxfImport.createStore(window.__dxf)');const value=b.read('({d:window.__r.store.reader.blockDefinitions()[0],layers:window.__r.store.reader.layers(),diagnostics:window.__r.diagnostics})'),member=value.d.records[value.d.recordOrder[0]];assert.equal(member.layerId,value.layers.find(l=>l.name==='0').id);assert.equal(member.color,null);assert.ok(value.diagnostics.some(d=>d.code==='DXF_BYBLOCK_FALLBACK'))})

test('GB10 exports definitions once, nested INSERTs and transforms, then semantically reimports',async()=>{const b=await browser();b.run("window.__leaf=blockDefinitionGateway.create({name:'Leaf',basePoint:{x:2,y:3},records:[recordGateway.createLine({x:1,y:2},{x:4,y:2}),recordGateway.createText({insertionPoint:{x:1,y:4},text:'Block',height:1,rotation:0})]}).definition;window.__nested=recordGateway.createBlockInstance({definitionId:window.__leaf.id,insertionPoint:{x:5,y:6},rotation:.25,scale:2,mirrored:true});window.__outer=blockDefinitionGateway.create({name:'Outer',records:[window.__nested]}).definition;recordGateway.createAll([recordGateway.createBlockInstance({definitionId:window.__outer.id,insertionPoint:{x:20,y:30},rotation:-.5,scale:3,mirrored:false}),recordGateway.createBlockInstance({definitionId:window.__leaf.id,insertionPoint:{x:40,y:50},rotation:1,scale:4,mirrored:true})]);window.__out=window.CaderactDxfExport.exportDocument(modelReader.snapshot());window.__back=window.CaderactDxfImport.createStore(window.__out.text).store");const result=b.read('({text:window.__out.text,defs:window.__back.reader.blockDefinitions(),records:window.__back.reader.records()})');assert.equal((result.text.match(/\nBLOCK\n/g)||[]).length,2);assert.equal((result.text.match(/\nINSERT\n/g)||[]).length,3);assert.equal(result.defs.length,2);assert.equal(result.records.length,2);assert.deepEqual(result.defs.map(d=>d.name).sort(),['Leaf','Outer']);assert.deepEqual(result.defs.find(d=>d.name==='Leaf').basePoint,{x:2,y:3});assert.equal(result.defs.find(d=>d.name==='Outer').records[result.defs.find(d=>d.name==='Outer').recordOrder[0]].type,'block-instance')})

test('GB10 exports unused definitions and rejects unsupported definition members before output',async()=>{const b=await browser();b.run("window.__unused=blockDefinitionGateway.create({name:'Unused',records:[recordGateway.createCircle({x:0,y:0},2)]}).definition;window.__text=window.CaderactDxfExport.exportDocument(modelReader.snapshot()).text");assert.match(b.read('window.__text'),/\nUnused\n/);b.run("window.__region=recordGateway.createRegion([recordGateway.createCircle({x:0,y:0},2)]);blockDefinitionGateway.create({name:'Unsupported',records:[window.__region]})");assert.throws(()=>b.run('window.CaderactDxfExport.exportDocument(modelReader.snapshot())'),/unsupported native records/)})
