'use strict';
const test=require('node:test');
const assert=require('node:assert/strict');
const {browser}=require('../helpers/browser.cjs');

const layer=(name,{flags=0,color=7}={})=>['0','LAYER','2',name,'70',String(flags),'62',String(color),'6','CONTINUOUS','370','-3'];
function text(values={}){const horizontal=values.horizontal??0;return ['0','TEXT','8',values.layer||'0','10',String(values.x??1),'20',String(values.y??2),'30',String(values.z??0),'40',String(values.height??2.5),'1',values.content??'Label','50',String(values.rotation??0),'72',String(horizontal),'73',String(values.vertical??0),...(values.second?['11',String(values.second.x),'21',String(values.second.y),'31',String(values.second.z??0)]:[]),...(values.color===undefined?[]:['62',String(values.color)]),...(values.trueColor===undefined?[]:['420',String(values.trueColor)]),...(values.linetype===undefined?[]:['6',values.linetype]),...(values.lineweight===undefined?[]:['370',String(values.lineweight)]),...(values.width===undefined?[]:['41',String(values.width)]),...(values.oblique===undefined?[]:['51',String(values.oblique)]),...(values.generation===undefined?[]:['71',String(values.generation)]),...(values.style===undefined?[]:['7',values.style]),...(values.extrusion||[])]}
function dxf(entities,{layers=[layer('0')]}={}){return ['0','SECTION','2','HEADER','9','$ACADVER','1','AC1027','9','$INSUNITS','70','4','0','ENDSEC','0','SECTION','2','TABLES','0','TABLE','2','LAYER','70',String(layers.length),...layers.flat(),'0','ENDTAB','0','ENDSEC','0','SECTION','2','ENTITIES',...entities.flat(),'0','ENDSEC','0','EOF'].join('\n')+'\n'}
function load(b,entities,options={}){b.window.__dxf=dxf(entities,options);b.run('window.__imported=window.CaderactDxfImport.createStore(window.__dxf)');return b.read('({records:window.__imported.store.reader.records(),layers:window.__imported.store.reader.layers(),visible:window.__imported.store.reader.visibleRecords().map(r=>r.id),editable:window.__imported.store.reader.editableRecords().map(r=>r.id),diagnostics:window.__imported.diagnostics,errors:window.CaderactDocument.validateDocument(window.__imported.store.reader.snapshot())})')}

test('basic Left TEXT maps content, first point, height, and fresh native identities',async()=>{const b=await browser();b.window.__dxf=dxf([text({x:4,y:-3,content:'ROOM 101',height:3})]);b.run('window.__a=window.CaderactDxfImport.createStore(window.__dxf);window.__b=window.CaderactDxfImport.createStore(window.__dxf)');const result=b.read(`(()=>{const a=window.__a.store.reader.records()[0],b=window.__b.store.reader.records()[0];return{a,ids:[a.id,a.insertionPoint.featureId,b.id,b.insertionPoint.featureId],errors:window.CaderactDocument.validateDocument(window.__a.store.reader.snapshot())}})()`);assert.equal(result.a.type,'text');assert.equal(result.a.text,'ROOM 101');assert.deepEqual({x:result.a.insertionPoint.x,y:result.a.insertionPoint.y},{x:4,y:-3});assert.equal(result.a.height,3);assert.equal(result.a.horizontalAlignment,'left');assert.equal(new Set(result.ids).size,4);assert.deepEqual(result.errors,[])});

test('Center and Right TEXT use the second alignment point exactly',async()=>{const result=load(await browser(),[text({horizontal:1,x:99,y:98,second:{x:10,y:20},content:'Center'}),text({horizontal:2,x:97,y:96,second:{x:-5,y:7},content:'Right'})]);const records=result.records.sort((a,b)=>a.text.localeCompare(b.text));assert.deepEqual(records.map(value=>[value.text,value.horizontalAlignment,value.insertionPoint.x,value.insertionPoint.y]),[['Center','center',10,20],['Right','right',-5,7]])});

test('rotation converts degrees to canonical radians including wraparound',async()=>{const result=load(await browser(),[text({rotation:90}),text({rotation:450,x:3}),text({rotation:-90,x:5})]),rotations=result.records.sort((a,b)=>a.insertionPoint.x-b.insertionPoint.x).map(value=>value.rotation);assert.ok(Math.abs(rotations[0]-Math.PI/2)<1e-12);assert.ok(Math.abs(rotations[1]-Math.PI/2)<1e-12);assert.ok(Math.abs(rotations[2]-3*Math.PI/2)<1e-12)});

test('content preserves decoded Unicode and enforces native length and validity',async()=>{const result=load(await browser(),[text({content:'Café 短い \\U+00B1 \\U+00D8'})]);assert.equal(result.records[0].text,'Café 短い ± Ø');assert.equal(load(await browser(),[text({content:'x'.repeat(256)})]).records[0].text.length,256);for(const values of [{content:' '},{content:'x'.repeat(257)},{content:'bad\u0001'},{height:0},{height:-1},{height:'NaN'}]){const b=await browser();b.window.__dxf=dxf([text(values)]);assert.throws(()=>b.run('window.CaderactDxfImport.createStore(window.__dxf)'),/TEXT|finite number/)}});

test('unsupported justification and material formatting skip with structured warnings',async()=>{for(const [values,code] of [[{horizontal:3},'DXF_TEXT_JUSTIFICATION_UNSUPPORTED'],[{vertical:1},'DXF_TEXT_JUSTIFICATION_UNSUPPORTED'],[{width:2},'DXF_TEXT_FORMATTING_UNSUPPORTED'],[{oblique:15},'DXF_TEXT_FORMATTING_UNSUPPORTED'],[{generation:2},'DXF_TEXT_FORMATTING_UNSUPPORTED']]){const result=load(await browser(),[text(values)]);assert.equal(result.records.length,0);assert.ok(result.diagnostics.some(value=>value.code===code))}const styled=load(await browser(),[text({style:'ROMANS'})]);assert.equal(styled.records.length,1);assert.ok(styled.diagnostics.some(value=>value.code==='DXF_TEXT_STYLE_IGNORED'))});

test('MTEXT and non-planar TEXT are skipped without flattening',async()=>{const entities=[['0','MTEXT','10','0','20','0','40','2','1','Multi'],text({z:1}),text({x:3,extrusion:['210','1','220','0','230','1']}),text({x:5,horizontal:1,second:{x:5,y:5,z:2}})],result=load(await browser(),entities);assert.equal(result.records.length,0);assert.ok(result.diagnostics.some(value=>value.code==='DXF_MTEXT_UNSUPPORTED'));assert.equal(result.diagnostics.filter(value=>value.code==='DXF_TEXT_NON_PLANAR').reduce((sum,value)=>sum+(value.count||1),0),3)});

test('TEXT reuses DXF3 layer and property mapping including hidden and locked behavior',async()=>{const result=load(await browser(),[text({layer:'Hidden'}),text({layer:'Locked',x:3,color:1,linetype:'DASHED',lineweight:50})],{layers:[layer('0'),layer('Hidden',{color:-3}),layer('Locked',{flags:4,color:2})]});const byLayer=Object.fromEntries(result.layers.map(value=>[value.name,value])),hidden=result.records.find(value=>value.layerId===byLayer.Hidden.id),locked=result.records.find(value=>value.layerId===byLayer.Locked.id);assert.equal(hidden.color,null);assert.deepEqual({color:locked.color,linetype:locked.linetype,lineweight:locked.lineweight},{color:'#ff0000',linetype:'dashed',lineweight:.5});assert.deepEqual(result.visible,[locked.id]);assert.deepEqual(result.editable,[])});

test('imported TEXT uses native annotation, selection, persistence, transform, and non-Osnap authorities',async()=>{const b=await browser();b.window.__dxf=dxf([text({x:0,y:0,content:'Native',horizontal:1,second:{x:0,y:0},rotation:30})]);b.run(`window.__imported=window.CaderactDxfImport.createStore(window.__dxf);window.caderactDocumentSession.replaceStore(window.__imported.store,{reason:'dxf-test'})`);b.flush();const record=b.read('modelReader.records()[0]'),scene=b.renders.at(-1);assert.ok(scene.annotationOverlay.items.some(value=>value.recordId===record.id&&value.text==='Native'));assert.equal(b.read('window.CaderactSelection.hitTestRecords({screenPoint:{x:400,y:300},records:modelReader.records(),worldToScreen:(x,y)=>({x:400+x*5,y:300-y*5})}).hit'),true);b.window.__record=record;assert.equal(b.read('window.CaderactCurveDescriptor.atomicCurves(window.__record).valid'),false);assert.equal(b.read('window.CaderactMeasurement.measureRecord(window.__record)'),null);assert.equal(b.read('window.CaderactGeometryTransform.translateRecord(window.__record,2,3).insertionPoint.x'),2);const serialized=b.run('window.CaderactPersistence.serializeDocument(modelReader.snapshot())');b.window.__serialized=serialized;b.run('window.__loaded=window.CaderactPersistence.loadStore(window.__serialized)');assert.deepEqual(b.read('window.__loaded.reader.records()[0]'),record)});

test('mixed geometry and TEXT import together while malformed TEXT remains atomic',async()=>{const line=['0','LINE','8','0','10','0','20','0','11','5','21','0'],result=load(await browser(),[line,text({x:2,content:'Mixed'})]);assert.deepEqual(result.records.map(value=>value.type).sort(),['line','text']);const b=await browser();b.run(`recordGateway.createAll([recordGateway.createLine({x:20,y:20},{x:30,y:30})]);window.__before=window.CaderactPersistence.serializeDocument(modelReader.snapshot());window.__bad={name:'bad.dxf',text:async()=>window.__dxf};window.__files=window.CaderactFileActions.createActions({session:window.caderactDocumentSession,commandRouter:window.caderactCommandRouter,viewport:window.caderactViewport,adapters:{confirmDiscard:async()=>true,pickDxfFile:async()=>window.__bad,writeFile:async()=>{}}})`);b.window.__dxf=dxf([text({height:0})]);assert.equal((await b.run('window.__files.openDxf()')).status,'dxf-open-failed');assert.equal(b.run('window.CaderactPersistence.serializeDocument(modelReader.snapshot())'),b.run('window.__before'))});
