'use strict';
const test=require('node:test');
const assert=require('node:assert/strict');
const {browser}=require('../helpers/browser.cjs');

const layer=(name,{flags=0,color=7,trueColor,linetype='CONTINUOUS',lineweight=-3}={})=>['0','LAYER','2',name,'70',String(flags),'62',String(color),'6',linetype,'370',String(lineweight),...(trueColor===undefined?[]:['420',String(trueColor)])];
const line=({name='0',color=256,trueColor,linetype='BYLAYER',lineweight=-1,x=0}={})=>['0','LINE','8',name,'62',String(color),'6',linetype,'370',String(lineweight),...(trueColor===undefined?[]:['420',String(trueColor)]),'10',String(x),'20','0','11',String(x+1),'21','1'];
function source({layers=[layer('0')],entities=[line()],current='0',includeTables=true}={}){return ['0','SECTION','2','HEADER','9','$ACADVER','1','AC1027','9','$INSUNITS','70','4','9','$CLAYER','8',current,'0','ENDSEC',...(includeTables?['0','SECTION','2','TABLES','0','TABLE','2','LAYER','70',String(layers.length),...layers.flat(),'0','ENDTAB','0','ENDSEC']:[]),'0','SECTION','2','ENTITIES',...entities.flat(),'0','ENDSEC','0','EOF'].join('\n')+'\n'}
function load(b,text){b.window.__dxf=text;b.run('window.__result=window.CaderactDxfImport.createStore(window.__dxf)');return b.read(`(()=>{const store=window.__result.store,document=store.reader.snapshot();return{document,layers:store.reader.layers(),records:store.reader.records(),visible:store.reader.visibleRecords().map(r=>r.id),editable:store.reader.editableRecords().map(r=>r.id),diagnostics:window.__result.diagnostics,history:store.controller.historyInfo,dirty:store.controller.isDirty,errors:window.CaderactDocument.validateDocument(document)}})()`)}

test('DXF layers receive fresh native IDs, preserve assignment, and honor $CLAYER',async()=>{const b=await browser(),result=load(b,source({layers:[layer('0'),layer('Walls',{color:1,linetype:'DASHED',lineweight:35})],entities:[line({name:'Walls'})],current:'Walls'}));assert.equal(result.layers.length,2);const zero=result.layers.find(value=>value.name==='0'),walls=result.layers.find(value=>value.name==='Walls');assert.ok(zero.id!==walls.id&&!['0','Walls'].includes(walls.id));assert.equal(result.document.defaultLayerId,zero.id);assert.equal(result.document.currentLayerId,walls.id);assert.equal(result.records[0].layerId,walls.id);assert.deepEqual(result.errors,[]);assert.deepEqual(result.history,{entryCount:0,cursor:0});assert.equal(result.dirty,true)});

test('every DXF2 geometry type resolves its entity layer through the same map',async()=>{const entities=[line({name:'Geometry'}),['0','LWPOLYLINE','8','Geometry','90','2','70','0','10','0','20','0','10','2','20','0'],['0','POLYLINE','8','Geometry','70','0','0','VERTEX','10','0','20','1','0','VERTEX','10','2','20','1','0','SEQEND'],['0','CIRCLE','8','Geometry','10','0','20','0','40','2'],['0','ARC','8','Geometry','10','0','20','0','40','2','50','0','51','90'],['0','ELLIPSE','8','Geometry','10','0','20','0','11','3','21','0','40','.5','41','0','42',String(Math.PI*2)]];const result=load(await browser(),source({layers:[layer('0'),layer('Geometry')],entities})),geometry=result.layers.find(value=>value.name==='Geometry');assert.deepEqual(result.records.map(value=>value.type).sort(),['arc','circle','ellipse','line','polyline','polyline']);assert.ok(result.records.every(value=>value.layerId===geometry.id))});

test('layer visibility and locking integrate with authoritative native readers',async()=>{const b=await browser(),result=load(b,source({layers:[layer('0'),layer('Off',{color:-2}),layer('Frozen',{flags:1}),layer('Locked',{flags:4})],entities:[line(),line({name:'Off',x:2}),line({name:'Frozen',x:4}),line({name:'Locked',x:6})]}));const byName=Object.fromEntries(result.layers.map(value=>[value.name,value]));assert.equal(byName.Off.visible,false);assert.equal(byName.Frozen.visible,false);assert.equal(byName.Locked.locked,true);const records=Object.fromEntries(result.records.map(value=>[result.layers.find(layer=>layer.id===value.layerId).name,value.id]));assert.deepEqual(result.visible.sort(),[records['0'],records.Locked].sort());assert.deepEqual(result.editable,[records['0']]);assert.ok(result.diagnostics.some(value=>value.code==='DXF_LAYER_FROZEN_COLLAPSED'))});

test('layer and entity colors map ACI/truecolor and preserve ByLayer/ByBlock fallback',async()=>{const b=await browser(),result=load(b,source({layers:[layer('0',{color:3,trueColor:0x123456})],entities:[line(),line({x:2,color:1}),line({x:4,color:2,trueColor:0xabcdef}),line({x:6,color:0})]}));assert.equal(result.layers[0].color,'#123456');const records=result.records.sort((a,b)=>a.start.x-b.start.x);assert.deepEqual(records.map(value=>value.color),[null,'#ff0000','#abcdef',null]);assert.ok(result.diagnostics.some(value=>value.code==='DXF_BYBLOCK_FALLBACK'))});

test('linetype and lineweight mapping is deterministic and loss is diagnosed',async()=>{const b=await browser(),result=load(b,source({layers:[layer('0',{linetype:'HIDDEN',lineweight:30})],entities:[line(),line({x:2,linetype:'DOT',lineweight:35}),line({x:4,linetype:'CUSTOM',lineweight:30}),line({x:6,linetype:'BYBLOCK',lineweight:-2})]}));assert.equal(result.layers[0].linetype,'dashed');assert.equal(result.layers[0].lineweight,.25);const records=result.records.sort((a,b)=>a.start.x-b.start.x);assert.deepEqual(records.map(value=>[value.linetype,value.lineweight]),[[null,null],['dotted',.35],[null,.25],[null,null]]);assert.ok(result.diagnostics.some(value=>value.code==='DXF_LINETYPE_FALLBACK'));assert.ok(result.diagnostics.some(value=>value.code==='DXF_LINEWEIGHT_FALLBACK'))});

test('missing tables/layers and unusable $CLAYER recover predictably',async()=>{const b=await browser(),missing=load(b,source({includeTables:false,entities:[line({name:'Unknown'})]}));assert.equal(missing.layers.length,1);assert.equal(missing.layers[0].name,'0');assert.equal(missing.records[0].layerId,missing.document.defaultLayerId);assert.ok(missing.diagnostics.some(value=>value.code==='DXF_LAYER_TABLE_MISSING'));assert.ok(missing.diagnostics.some(value=>value.code==='DXF_ENTITY_LAYER_UNKNOWN'));const locked=load(await browser(),source({layers:[layer('0'),layer('Locked',{flags:4})],current:'Locked'}));assert.notEqual(locked.document.currentLayerId,locked.layers.find(value=>value.name==='Locked').id);assert.ok(locked.diagnostics.some(value=>value.code==='DXF_CURRENT_LAYER_UNAVAILABLE'))});

test('malformed layer tables, duplicates, and resource limits reject atomically',async()=>{for(const [text,options,pattern] of [[source({layers:[layer('0'),layer('zero'),layer('ZERO')]}),{},/Duplicate layer/],[source({layers:[['0','LAYER','2','0','62','7']]}),{},/missing or duplicate property/],[source({layers:[layer('0'),layer('A')]}),{limits:{maxTableEntries:1}},/table-entry limit/]]){const b=await browser();b.window.__dxf=text;b.window.__options=options;assert.throws(()=>b.run('window.CaderactDxfImport.createStore(window.__dxf,window.__options)'),pattern)}});

test('property converters cover deterministic ACI and nearest-lineweight ties',async()=>{const b=await browser(),values=b.read(`({red:window.CaderactDxfProperties.aciToHex(1),green:window.CaderactDxfProperties.aciToHex(3),negative:window.CaderactDxfProperties.aciToHex(-1),tie:window.CaderactDxfProperties.lineweight(30).value,exact:window.CaderactDxfProperties.lineweight(70).value})`);assert.deepEqual(values,{red:'#ff0000',green:'#00ff00',negative:null,tie:.25,exact:.7})});

test('imported properties use the ordinary renderer-neutral property pipeline',async()=>{const b=await browser();b.window.__dxf=source({layers:[layer('0',{color:1,linetype:'DASHED',lineweight:50})],entities:[line()]});b.run(`window.__imported=window.CaderactDxfImport.createStore(window.__dxf);window.caderactDocumentSession.replaceStore(window.__imported.store,{reason:'dxf-test'})`);b.flush();const scene=b.renders.at(-1),record=b.read('modelReader.records()[0]'),group=scene.propertyDrawGroups.find(value=>Array.from(value.recordIds).includes(record.id));assert.equal(group.style.color,'#ff0000');assert.equal(group.style.linetype,'dashed');assert.equal(group.style.lineweight,.5);assert.equal(group.lineGroup.color,'#ff0000');assert.ok(group.lineGroup.dashPattern.length);assert.equal(group.lineGroup.lineWidth,2)});
