'use strict';
const test=require('node:test');
const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const {browser}=require('../helpers/browser.cjs');

const fixture=fs.readFileSync(path.join(__dirname,'../fixtures/dxf/cad-export-like-ac1018.dxf'),'utf8');
function load(b,text,limits){b.window.__source=text;b.window.__limits=limits||{};b.run('window.__loaded=window.CaderactDxfImport.createStore(window.__source,{limits:window.__limits})');return b.read('({parsed:window.__loaded.parsed,diagnostics:window.__loaded.diagnostics,document:window.__loaded.store.reader.snapshot(),records:window.__loaded.store.reader.records(),styles:window.__loaded.store.reader.dimensionStyles()})')}
const source=entities=>['0','SECTION','2','HEADER','9','$ACADVER','1','AC1018','9','$INSUNITS','70','4','0','ENDSEC','0','SECTION','2','ENTITIES',...entities.flat(),'0','ENDSEC','0','EOF'].join('\n')+'\n';

test('curated CAD-like AC1018 fixture tolerates legal ordering, metadata, numeric notation, and line endings',async()=>{const lines=fixture.trimEnd().split('\n'),spaced=lines.map((line,index)=>index%2===0?`  ${line}  `:line).join('\n')+'\n';for(const text of [fixture,fixture.replace(/\n/g,'\r\n'),spaced]){const b=await browser(),result=load(b,text);assert.deepEqual(result.records.map(r=>r.type).sort(),['dimension-linear','line','text']);assert.equal(result.records.find(r=>r.type==='line').start.x,-125);assert.equal(result.records.find(r=>r.type==='text').text,'Fixture ±');assert.equal(result.styles.find(s=>s.name==='ISO-25').textHeight,2.5);assert.ok(result.diagnostics.some(d=>d.code==='DXF_UNSUPPORTED_SECTION'&&d.section==='BLOCKS'))}});

test('malformed dimension flags, truncation, controls, and incomplete pairs reject without active-document mutation',async()=>{const b=await browser();b.run(`recordGateway.createAll([recordGateway.createLine({x:9,y:9},{x:10,y:10})]);window.__before=window.CaderactPersistence.serializeDocument(modelReader.snapshot());window.__history=documentController.historyInfo;window.__revision=documentController.currentRevision`);const invalid=[source([['0','DIMENSION','10','0','20','0']]),fixture.slice(0,-8),source([['0','TEXT','10','0','20','0','40','1','1','Bad\\U+000AData']]),'0\nSECTION\n2'];for(const text of invalid){b.window.__bad=text;assert.throws(()=>b.run('window.CaderactDxfImport.createStore(window.__bad)'))}assert.equal(b.read('window.CaderactPersistence.serializeDocument(modelReader.snapshot())'),b.read('window.__before'));assert.deepEqual(b.read('documentController.historyInfo'),b.read('window.__history'));assert.equal(b.read('documentController.currentRevision'),b.read('window.__revision'))});

test('diagnostics aggregate repeated warnings and cap distinct hostile diagnostics',async()=>{const b=await browser(),repeated=source(Array.from({length:40},()=>['0','INSERT','2','X']));let parsed=load(b,repeated,{maxDiagnostics:5}).parsed;const warning=parsed.diagnostics.find(d=>d.code==='DXF_UNSUPPORTED_ENTITY');assert.equal(warning.count,40);const varied=source(Array.from({length:20},(_,i)=>['0',`UNSUPPORTED_${i}`]));parsed=load(b,varied,{maxDiagnostics:5}).parsed;assert.ok(parsed.diagnostics.some(d=>d.code==='DXF_DIAGNOSTIC_LIMIT'));assert.ok(parsed.diagnostics.length<=6)});

test('supported numerical extremes remain finite and stable after two DXF generations',async()=>{const b=await browser();b.run(`recordGateway.createAll([recordGateway.createLine({x:-1e12,y:1e-12},{x:1e12,y:-1e-12}),recordGateway.createCircle({x:-5,y:6},1e-9),recordGateway.createArc({center:{x:0,y:0},radius:7,start:{x:7*Math.cos(350*Math.PI/180),y:7*Math.sin(350*Math.PI/180)},end:{x:7*Math.cos(10*Math.PI/180),y:7*Math.sin(10*Math.PI/180)},sweep:20*Math.PI/180}),recordGateway.createEllipse({center:{x:8,y:-9},majorAxis:{x:3,y:4},minorRadius:5e-8}),recordGateway.createLinearDimension({mode:'aligned',firstPoint:{x:-3.125,y:7.75},secondPoint:{x:9.5,y:-2.25},dimensionLinePoint:{x:1.125,y:12.875},textOverride:'awkward'})])`);b.run(`window.__e1=window.CaderactDxfExport.exportDocument(modelReader.snapshot()).text;window.__i1=window.CaderactDxfImport.createStore(window.__e1);window.__e2=window.CaderactDxfExport.exportDocument(window.__i1.store.reader.snapshot()).text;window.__i2=window.CaderactDxfImport.createStore(window.__e2);window.__e3=window.CaderactDxfExport.exportDocument(window.__i2.store.reader.snapshot()).text`);assert.equal(b.read('window.__e2'),b.read('window.__e3'));assert.equal(b.read('window.__i2.store.reader.records().length'),5);assert.equal(b.read('window.CaderactDocument.validateDocument(window.__i2.store.reader.snapshot()).length'),0);const arc=b.read('window.__i2.store.reader.records().find(r=>r.type==="arc")');assert.ok(Math.abs(arc.sweep-20*Math.PI/180)<1e-12)});

test('dimension anonymous block names and mixed semantic export are deterministic across fresh IDs',async()=>{async function build(){const b=await browser();b.run(`layerGateway.create('B');window.__style=dimensionStyleGateway.create('Precise').style;dimensionStyleGateway.update(window.__style.id,{linearPrecision:6});recordGateway.createAll([recordGateway.createText({insertionPoint:{x:1,y:1},text:'safe <script>',height:1,rotation:0,horizontalAlignment:'left'}),recordGateway.createLinearDimension({mode:'horizontal',firstPoint:{x:0,y:0},secondPoint:{x:5,y:0},dimensionLinePoint:{x:2,y:2},dimensionStyleId:window.__style.id}),recordGateway.createRadialDimension({mode:'radius',centerPoint:{x:10,y:0},dimensionPoint:{x:12,y:0},leaderPoint:{x:14,y:1},dimensionStyleId:window.__style.id})])`);return b.run('window.CaderactDxfExport.exportDocument(modelReader.snapshot()).text')}const first=await build(),second=await build();assert.equal(first,second);assert.match(first,/\n\*D1\n/);assert.match(first,/\n\*D2\n/)});

test('large supported drawings map linearly through parser/import/export smoke paths',async()=>{const count=2000,entities=Array.from({length:count},(_,i)=>['0','LINE','8','0','10',String(i),'20',String(-i),'11',String(i+1),'21',String(1-i)]),b=await browser(),result=load(b,source(entities),{maxEntities:count+1,maxGroupPairs:20000});assert.equal(result.records.length,count);b.window.__document=result.document;const exported=b.read('window.CaderactDxfExport.exportDocument(window.__document)');assert.equal(exported.exportedCount,count);assert.ok(exported.text.length>count*40)});

test('DXF strings remain inert data and renderers stay DXF-neutral',async()=>{const b=await browser(),payload='<img src=x onerror=window.__dxfExecuted=true>',dxf=source([['0','TEXT','8','0','10','0','20','0','40','1','1',payload]]);b.window.__dxfExecuted=false;const result=load(b,dxf);assert.equal(result.records[0].text,payload);assert.equal(b.read('window.__dxfExecuted'),false);const root=path.join(__dirname,'../..');for(const file of ['src/js/rendering/Canvas2DRenderer.js','src/js/rendering/WebGPURenderer.js'])assert.doesNotMatch(fs.readFileSync(path.join(root,file),'utf8'),/dxf/i)});
