const test=require('node:test');const assert=require('node:assert/strict');const{browser}=require('../helpers/browser.cjs');
const ids=['recovery-dialog','recovery-message','recovery-candidates','recovery-details','recovery-apply','recovery-dismiss','recovery-cancel','unsaved-dialog','unsaved-message','unsaved-save','unsaved-discard','unsaved-cancel','document-save-state'];
function elements(b){b.window.__elements={};for(const id of ids){const tag=id==='recovery-candidates'?'select':id.includes('apply')||id.includes('dismiss')||id.includes('cancel')||id.includes('save')||id.includes('discard')?'button':'div';const el=b.document.createElement(tag);el.owner=b.document;b.window.__elements[id]=el}return b.window.__elements}
function line(b){b.run('recordGateway.createAll([recordGateway.createLine({x:0,y:0},{x:2,y:1})])')}
async function setup({withRecovery=true}={}){const b=await browser();elements(b);b.run(`window.__storage=window.CaderactRecoveryStorage.createMemoryStorage();window.__fs=window.CaderactDocumentFileState.create();window.__auto=window.CaderactRecoveryStorage.createAutosave({session:window.caderactDocumentSession,fileState:window.__fs,storage:window.__storage});window.__auto.start()`);if(withRecovery){line(b);await b.run('window.__auto.flush()');b.run('window.caderactDocumentSession.replaceStore(window.CaderactDocument.createStore({initiallySaved:true}),{reason:"ux-test"})')}b.run(`window.__validation=window.CaderactRecoveryValidation.create({storage:window.__storage});window.__ux=window.CaderactFileSafetyUx.create({recoveryValidation:window.__validation,session:window.caderactDocumentSession,fileState:window.__fs,autosave:window.__auto,viewport:window.caderactViewport,commandRouter:window.caderactCommandRouter,elements:window.__elements,feedback:()=>({showTemporary:(message,kind)=>{window.__notice={message,kind}}})})`);return b}

test('FS5 startup without recovery does not interrupt the editor',async()=>{const b=await setup({withRecovery:false}),result=await b.run('window.__ux.startup()');assert.equal(result.status,'recovery-list-classified');assert.equal(b.window.__elements['recovery-dialog'].hidden,true);assert.equal(b.read('window.__ux.candidates.length'),0)});

test('FS5 startup presents valid recovery with safe text and deterministic multiple-candidate order',async()=>{const b=await setup(),first=(await b.run('window.__storage.list()')).records[0];b.window.__second={...first,recoveryKey:'recovery_'+'f'.repeat(32),sequence:2,timestamp:first.timestamp+10,displayName:'<b>Not HTML</b>',filename:'unsafe.caderact'};await b.run('window.__storage.put(window.__second)');await b.run('window.__ux.startup()');const dialog=b.window.__elements['recovery-dialog'],select=b.window.__elements['recovery-candidates'];assert.equal(dialog.hidden,false);assert.equal(select.children.length,2);assert.match(select.children[0].textContent,/<b>Not HTML<\/b>/);assert.equal(select.children[0].children.length,0);assert.equal(b.window.__elements['recovery-apply'].disabled,false)});

test('FS5 Recover delegates to authenticated FS3 apply and leaves recovered work dirty',async()=>{const b=await setup();await b.run('window.__ux.startup()');const outcome=await b.run('window.__ux.recover()');assert.equal(b.read('documentController.isDirty'),true);assert.equal(b.read('modelReader.records().length'),1);assert.equal(b.window.__elements['recovery-dialog'].hidden,true);assert.match(b.read('window.__notice.message'),/Recovered drawing/);assert.equal(outcome,undefined)});

test('FS5 Dismiss removes only the selected record and reports delete failure safely',async()=>{const b=await setup();await b.run('window.__ux.startup()');const key=b.read('window.__ux.candidates[0].recoveryKey');await b.run('window.__ux.dismiss()');b.window.__key=key;assert.equal((await b.run('window.__storage.get(window.__key)')).record,null);const failing=await setup();failing.run(`window.__badValidation={classifyAll:()=>window.__validation.classifyAll(),dismiss:async()=>({status:'recovery-delete-failed'}),apply:(...args)=>window.__validation.apply(...args)};window.__badUx=window.CaderactFileSafetyUx.create({recoveryValidation:window.__badValidation,session:window.caderactDocumentSession,fileState:window.__fs,autosave:window.__auto,viewport:window.caderactViewport,commandRouter:window.caderactCommandRouter,elements:window.__elements,feedback:()=>({showTemporary:(message,kind)=>{window.__notice={message,kind}}})})`);await failing.run('window.__badUx.startup()');await failing.run('window.__badUx.dismiss()');assert.match(failing.read('window.__notice.message'),/remains available/)});

test('FS5 corrupt and incompatible records are informational and never offered as recoverable',async()=>{const b=await setup(),record=(await b.run('window.__storage.list()')).records[0];b.run('window.__storage.delete(window.__auto.recoveryKey)');b.window.__bad={...record,payloadFingerprint:'0'.repeat(64)};await b.run('window.__storage.put(window.__bad)');await b.run('window.__ux.startup()');assert.equal(b.window.__elements['recovery-dialog'].hidden,false);assert.equal(b.window.__elements['recovery-apply'].disabled,true);assert.match(b.window.__elements['recovery-details'].textContent,/damaged/)});

test('FS5 unsaved modal defaults safely to Cancel and supports keyboard Escape',async()=>{const b=await setup({withRecovery:false});b.run('window.__decision=window.__ux.requestUnsaved({operation:"opening another file",filename:"Drawing.caderact"})');assert.equal(b.document.activeElement,b.window.__elements['unsaved-cancel']);b.emit(b.document,'keydown',{key:'Escape'});assert.equal(await b.run('window.__decision'),'cancel');assert.equal(b.window.__elements['unsaved-dialog'].hidden,true);b.run('window.__decision=window.__ux.requestUnsaved({operation:"creating a drawing"})');b.emit(b.document,'keydown',{key:'Enter'});assert.equal(await b.run('window.__decision'),'cancel')});

test('FS5 destructive guard continues only for committed Save or explicit Discard',async()=>{for(const [decision,durability,expected]of [['save','committed','new-completed'],['save','initiated','new-cancelled'],['save','failed','new-cancelled'],['cancel','committed','new-cancelled'],['discard','failed','new-completed']]){const b=await browser();line(b);b.run(`window.__ops=window.CaderactFileActions.createActions({session:window.caderactDocumentSession,commandRouter:window.caderactCommandRouter,viewport:window.caderactViewport,adapters:{resolveUnsaved:async()=>${JSON.stringify(decision)},pickSaveFile:async()=>({status:'unsupported'}),writeFile:async()=>({status:${JSON.stringify(durability)}}),confirmDiscard:async()=>false}})`);const before=b.read('modelReader.snapshot()'),outcome=await b.run('window.__ops.newProject()');assert.equal(outcome.status,expected);if(expected==='new-cancelled')assert.deepEqual(b.read('modelReader.snapshot()'),before)}});

test('FS5 save-state feedback distinguishes dirty clean saving failed and initiated states',async()=>{const b=await setup({withRecovery:false}),state=b.window.__elements['document-save-state'];assert.match(state.textContent,/Saved/);line(b);assert.match(state.textContent,/Unsaved changes/);b.run('window.__ux.presentOutcome({status:"save-started"})');assert.match(state.textContent,/Saving/);b.run('window.__ux.presentOutcome({status:"save-failed",reason:"write-failed"})');assert.match(state.textContent,/Save failed/);b.run('window.__ux.presentOutcome({status:"save-initiated"})');assert.match(state.textContent,/Download unconfirmed/);b.run('documentController.markStateSaved(documentController.captureStateToken());window.__ux.presentOutcome({status:"save-completed"})');assert.match(state.textContent,/Saved/)});

test('FS5 beforeunload warns only for dirty work and autosave failure uses restrained feedback',async()=>{const b=await setup({withRecovery:false});assert.equal(b.emit(b.window,'beforeunload').defaultPrevented,false);line(b);const dirty=b.emit(b.window,'beforeunload');assert.equal(dirty.defaultPrevented,true);b.run('documentController.markStateSaved(documentController.captureStateToken())');const clean=b.emit(b.window,'beforeunload');assert.equal(clean.defaultPrevented,false);b.run('window.__notice=null;window.__ux.presentAutosave({status:"autosave-completed"})');assert.equal(b.read('window.__notice'),null);b.run('window.__ux.presentAutosave({status:"autosave-failed"})');assert.match(b.read('window.__notice.message'),/Automatic recovery/)});
