const test=require('node:test');const assert=require('node:assert/strict');const{browser}=require('../helpers/browser.cjs');
function line(b){b.run('recordGateway.createAll([recordGateway.createLine({x:0,y:0},{x:1,y:1})])')}
function actions(b,body){b.run(`window.__safeFileState=window.CaderactDocumentFileState.create();window.__safeActions=window.CaderactFileActions.createActions({session:window.caderactDocumentSession,commandRouter:window.caderactCommandRouter,viewport:window.caderactViewport,fileState:window.__safeFileState,${body}})`)}
function snapshot(b){return b.read('({document:modelReader.snapshot(),state:documentController.currentStateId,revision:documentController.currentRevision,history:documentController.historyInfo,dirty:documentController.isDirty,file:window.__safeFileState.value,recovery:window.caderactFiles.recovery?.recoveryKey||null})')}

test('FS4 empty malformed truncated and unsupported native files fail before replacement',async()=>{for(const [text,reason]of [['','invalid-file'],['{','invalid-file'],[JSON.stringify({fileVersion:999}),'incompatible-version']]){const b=await browser();line(b);b.window.__text=text;actions(b,`adapters:{confirmDiscard:async()=>true,pickOpenFile:async()=>({name:'hostile.caderact',text:async()=>window.__text}),writeFile:async()=>({status:'committed'})}`);const before=snapshot(b),outcome=await b.run('window.__safeActions.open()');assert.equal(outcome.status,'open-failed');assert.equal(outcome.reason,reason);assert.deepEqual(snapshot(b),before)}});

test('FS4 native size gate rejects file metadata and decoded text before parsing',async()=>{for(const fileExpression of [`({name:'large.caderact',size:window.CaderactFileActions.MAX_NATIVE_INPUT_BYTES+1,text:async()=>{throw new Error('must not read')}})`,`({name:'large.caderact',text:async()=>'x'.repeat(window.CaderactFileActions.MAX_NATIVE_INPUT_BYTES+1)})`]){const b=await browser();line(b);actions(b,`adapters:{confirmDiscard:async()=>true,pickOpenFile:async()=>${fileExpression},writeFile:async()=>({status:'committed'})}`);const before=snapshot(b),outcome=await b.run('window.__safeActions.open()');assert.equal(outcome.reason,'resource-rejected');assert.deepEqual(snapshot(b),before)}});

test('FS4 picker cancellation permission denial and read failure have distinct atomic outcomes',async()=>{for(const [picker,status,reason]of [[`async()=>{const e=new Error('cancel');e.name='AbortError';throw e}`,'open-cancelled','picker-cancelled'],[`async()=>{const e=new Error('denied');e.name='NotAllowedError';throw e}`,'open-failed','permission-denied'],[`async()=>({name:'x.caderact',text:async()=>{throw new Error('reader')}})`,'open-failed','read-failed']]){const b=await browser();line(b);actions(b,`adapters:{confirmDiscard:async()=>true,pickOpenFile:${picker},writeFile:async()=>({status:'committed'})}`);const before=snapshot(b),outcome=await b.run('window.__safeActions.open()');assert.equal(outcome.status,status);assert.equal(outcome.reason,reason);assert.deepEqual(snapshot(b),before)}});

test('FS4 Save As cancellation permission write and close-equivalent failures preserve exact state and metadata',async()=>{for(const [picker,write,status,reason]of [[`async()=>({status:'cancelled'})`,`async()=>({status:'committed'})`,'save-as-cancelled','picker-cancelled'],[`async()=>{const e=new Error('denied');e.name='NotAllowedError';throw e}`,`async()=>({status:'committed'})`,'save-as-failed','permission-denied'],[`async()=>({status:'selected',handle:{name:'x.caderact'},filename:'x.caderact'})`,`async()=>{throw new Error('close failed')}`,'save-as-failed','write-failed']]){const b=await browser();line(b);actions(b,`adapters:{confirmDiscard:async()=>true,pickSaveFile:${picker},writeFile:${write}}`);const before=snapshot(b),outcome=await b.run('window.__safeActions.saveAs()');assert.equal(outcome.status,status);assert.equal(outcome.reason,reason);assert.equal(b.read('documentController.isDirty'),true);assert.equal(b.read('window.__safeFileState.value.filename'),before.file.filename);assert.equal(b.read('window.__safeFileState.value.lastManualSaveFingerprint'),null)}});

test('FS4 malformed and oversized DXF fail without file or recovery-session mutation',async()=>{for(const fileExpression of [`({name:'bad.dxf',text:async()=>'0\\nSECTION\\n2'})`,`({name:'large.dxf',size:window.CaderactFileActions.MAX_DXF_INPUT_BYTES+1,text:async()=>{throw new Error('must not read')}})`]){const b=await browser();line(b);actions(b,`adapters:{confirmDiscard:async()=>true,pickDxfFile:async()=>${fileExpression},writeFile:async()=>({status:'committed'})}`);const before=snapshot(b),outcome=await b.run('window.__safeActions.openDxf()');assert.equal(outcome.status,'dxf-open-failed');assert.deepEqual(snapshot(b),before)}});

test('FS4 DXF export completes generation before output and honors durability results',async()=>{for(const [output,status,durability]of [[`({status:'initiated'})`,'dxf-export-initiated','initiated'],[`({status:'committed'})`,'dxf-export-completed','committed'],[`({status:'failed',reason:'permission-denied'})`,'dxf-export-failed',undefined]]){const b=await browser();line(b);actions(b,`adapters:{confirmDiscard:async()=>true,writeFile:async()=>${output}}`);const before=snapshot(b),outcome=await b.run('window.__safeActions.exportDxf()');assert.equal(outcome.status,status);if(durability)assert.equal(outcome.durability,durability);assert.deepEqual(snapshot(b),before)}});

test('FS4 unsupported Region export is rejected before an external write begins',async()=>{const b=await browser();b.run(`window.__writes=0;const lines=[recordGateway.createLine({x:0,y:0},{x:1,y:0}),recordGateway.createLine({x:1,y:0},{x:1,y:1}),recordGateway.createLine({x:1,y:1},{x:0,y:1}),recordGateway.createLine({x:0,y:1},{x:0,y:0})];recordGateway.createAll([recordGateway.createRegion(lines)])`);actions(b,`adapters:{confirmDiscard:async()=>true,writeFile:async()=>{window.__writes+=1;return{status:'committed'}}}`);const before=snapshot(b),outcome=await b.run('window.__safeActions.exportDxf()');assert.equal(outcome.status,'dxf-export-failed');assert.equal(outcome.reason,'unsupported-document');assert.equal(b.read('window.__writes'),0);assert.deepEqual(snapshot(b),before)});

test('FS4 failed replacement leaves file metadata unchanged',async()=>{const b=await browser();line(b);const serialized=b.run('window.CaderactPersistence.serializeDocument(modelReader.snapshot())');b.window.__serialized=serialized;b.run(`window.__safeFileState=window.CaderactDocumentFileState.create();window.__badSession={get reader(){return window.caderactDocumentSession.reader},get controller(){return window.caderactDocumentSession.controller},replaceStore(){return{status:'invalid-store'}}};window.__safeActions=window.CaderactFileActions.createActions({session:window.__badSession,commandRouter:window.caderactCommandRouter,viewport:window.caderactViewport,fileState:window.__safeFileState,adapters:{confirmDiscard:async()=>true,pickOpenFile:async()=>({name:'new.caderact',text:async()=>window.__serialized}),writeFile:async()=>({status:'committed'})}})`);const before=b.read('window.__safeFileState.value'),outcome=await b.run('window.__safeActions.open()');assert.equal(outcome.status,'open-failed');assert.equal(outcome.reason,'replacement-failed');assert.deepEqual(b.read('window.__safeFileState.value'),before)});
