'use strict'
const test=require('node:test')
const assert=require('node:assert/strict')
const {browser}=require('../helpers/browser.cjs')
function typed(b,value){b.input.value=value;b.emit(b.input,'input');b.key('Enter',b.input)}
function create(b,overrides={}){b.window.__textArgs={insertionPoint:{x:1,y:2},text:'ROOM 101',height:2.5,rotation:0,horizontalAlignment:'left',...overrides};return b.read('(()=>{const record=recordGateway.createText(window.__textArgs);recordGateway.createAll([record]);return record})()')}

test('native Text validates semantic content and round-trips exactly in v3',async()=>{const b=await browser(),record=create(b);assert.equal(record.type,'text');assert.ok(record.insertionPoint.featureId);assert.deepEqual(b.read('window.CaderactAnnotationGeometry.validate(modelReader.records()[0])'),[]);const serialized=b.run('window.CaderactPersistence.serializeDocument(modelReader.snapshot())');assert.equal(JSON.parse(serialized).fileVersion,3);b.window.__file=serialized;b.run('window.__loaded=window.CaderactPersistence.loadStore(window.__file)');assert.deepEqual(b.read('window.__loaded.reader.records()[0]'),record);for(const patch of [{text:''},{text:'   '},{text:'x'.repeat(257)},{text:'bad\u0001'},{height:0},{height:Infinity},{rotation:-1},{horizontalAlignment:'top'}]){b.window.__patch=patch;assert.ok(b.read('window.CaderactAnnotationGeometry.validate({...modelReader.records()[0],...window.__patch}).length')>0)}})

test('Text command uses point then height rotation content and publishes once',async()=>{const b=await browser(),before=b.read('documentController.historyInfo.entryCount');b.launch('DTEXT');typed(b,'10,20');assert.equal(b.read('window.caderactCommandRouter.activeSession.phase'),'height');typed(b,'3');typed(b,'90');typed(b,'North');const record=b.read("modelReader.records().find(record=>record.type==='text')");assert.deepEqual({x:record.insertionPoint.x,y:record.insertionPoint.y},{x:10,y:20});assert.equal(record.height,3);assert.ok(Math.abs(record.rotation-Math.PI/2)<1e-12);assert.equal(record.text,'North');assert.equal(record.horizontalAlignment,'left');assert.equal(b.read('documentController.historyInfo.entryCount'),before+1)})

test('Text transform policy preserves identity and changes semantic orientation and height',async()=>{const b=await browser(),record=create(b,{rotation:Math.PI/4,horizontalAlignment:'right'});b.window.__r=record;const moved=b.read('window.CaderactGeometryTransform.translateRecord(window.__r,3,4)'),rotated=b.read('window.CaderactGeometryTransform.rotateRecord(window.__r,{x:0,y:0},Math.PI/2)'),scaled=b.read('window.CaderactGeometryTransform.scaleRecord(window.__r,{x:0,y:0},2)'),mirrored=b.read('window.CaderactGeometryTransform.mirrorRecord(window.__r,{x:0,y:0},{x:0,y:1})'),copy=b.read('recordGateway.copyWithFreshIdentity(window.__r)');assert.equal(moved.insertionPoint.featureId,record.insertionPoint.featureId);assert.ok(Math.abs(rotated.rotation-3*Math.PI/4)<1e-12);assert.equal(scaled.height,5);assert.ok(Math.abs(mirrored.rotation-3*Math.PI/4)<1e-12);assert.notEqual(copy.id,record.id);assert.notEqual(copy.insertionPoint.featureId,record.insertionPoint.featureId);assert.equal(copy.text,record.text)})

test('Text shares annotation descriptors selection bounds and insertion grip',async()=>{const b=await browser(),record=create(b,{horizontalAlignment:'center'});b.window.__id=record.id;b.flush();const scene=b.renders.at(-1);assert.ok(scene.annotationOverlay.items.some(item=>item.recordId===record.id&&item.role==='text'));const hit=b.read('window.CaderactSelection.hitTestRecords({screenPoint:{x:405,y:290},records:modelReader.records(),worldToScreen:(x,y)=>({x:400+x*5,y:300-y*5})}).hit');assert.equal(hit,true);b.run('window.caderactSelection.selectOnly(window.__id)');assert.equal(b.read('window.CaderactGrips.discoverGeometryGrips(modelReader.records(),window.caderactSelection.selectedIds())[0].kind'),'insertionPoint')})

test('Text remains outside Osnap curve and measurement authorities',async()=>{const b=await browser();create(b);assert.equal(b.read('window.CaderactMeasurement.measureRecord(modelReader.records()[0])'),null);assert.equal(b.read('window.CaderactCurveDescriptor.atomicCurves(modelReader.records()[0]).valid'),false)})
