'use strict';
const test=require('node:test');const assert=require('node:assert/strict');const {browser}=require('../helpers/browser.cjs');
const plain=value=>JSON.parse(JSON.stringify(value));
function state(b){return b.read('({records:modelReader.records(),revision:documentController.currentRevision,history:documentController.historyInfo.entryCount,dirty:documentController.isDirty})')}
function seed(b){return b.read(`(()=>{const records=[recordGateway.createLine({x:0,y:0},{x:10,y:0}),recordGateway.createCircle({x:20,y:0},4),recordGateway.createArc({center:{x:30,y:0},radius:4,start:{x:34,y:0},end:{x:30,y:4},sweep:Math.PI/2}),recordGateway.createEllipse({center:{x:40,y:0},majorAxis:{x:5,y:0},minorRadius:2}),recordGateway.createPolyline([{x:50,y:0},{x:55,y:5}],false)];recordGateway.createAll(records);return records})()`)}

test('all new drawable records start ByLayer and new layers carry appearance-preserving defaults',async()=>{const b=await browser(),records=seed(b);for(const record of records)assert.deepEqual({color:record.color,linetype:record.linetype,lineweight:record.lineweight},{color:null,linetype:null,lineweight:null});assert.deepEqual(b.read('window.CaderactObjectProperties.layerProperties(modelReader.layer(modelReader.snapshot().defaultLayerId))'),{color:'#e8edf4',linetype:'continuous',lineweight:.25});b.run(`layerGateway.create('Properties')`);assert.deepEqual(b.read(`window.CaderactObjectProperties.layerProperties(modelReader.layers().find(layer=>layer.name==='Properties'))`),{color:'#e8edf4',linetype:'continuous',lineweight:.25})});

test('batch color, linetype, and lineweight edits preserve geometry and identities in one transaction',async()=>{const b=await browser(),records=seed(b),ids=records.slice(0,2).map(record=>record.id),before=state(b);const outcome=b.read(`recordGateway.setProperties(${JSON.stringify(ids)},{color:'#ff0000',linetype:'dashed',lineweight:.35})`);assert.equal(outcome.status,'committed');assert.equal(outcome.updatedCount,2);const after=state(b);assert.equal(after.revision,before.revision+1);assert.equal(after.history,before.history+1);for(const original of records.slice(0,2)){const edited=after.records.find(record=>record.id===original.id);assert.deepEqual({...edited,color:null,linetype:null,lineweight:null},original);assert.deepEqual({color:edited.color,linetype:edited.linetype,lineweight:edited.lineweight},{color:'#ff0000',linetype:'dashed',lineweight:.35})}});

test('each property resets to ByLayer and exact no-op edits create no history',async()=>{const b=await browser(),record=seed(b)[0];b.run(`recordGateway.setProperties([${JSON.stringify(record.id)}],{color:'#123abc',linetype:'dash-dot',lineweight:.7})`);assert.equal(b.read(`recordGateway.setProperties([${JSON.stringify(record.id)}],{color:'#123abc'}).status`),'no-op');const before=state(b);assert.equal(b.read(`recordGateway.setProperties([${JSON.stringify(record.id)}],{color:null,linetype:null,lineweight:null}).status`),'committed');assert.deepEqual(b.read(`window.CaderactObjectProperties.recordProperties(modelReader.records().find(record=>record.id===${JSON.stringify(record.id)}))`),{color:null,linetype:null,lineweight:null});assert.equal(state(b).history,before.history+1)});

test('strict patch validation rejects malformed values, unknown keys, and immutable-field edits atomically',async()=>{const b=await browser(),id=seed(b)[0].id,before=state(b);for(const patch of [{color:'#fff'},{color:'red'},{linetype:'hidden'},{lineweight:-1},{lineweight:.2},{lineweight:null,id:'changed'},{layerId:'changed'}])assert.notEqual(b.read(`recordGateway.setProperties([${JSON.stringify(id)}],${JSON.stringify(patch)}).status`),'committed');assert.deepEqual(state(b),before)});

test('source validation rejects missing, hidden, or locked records all-or-nothing',async()=>{const b=await browser(),records=seed(b),ids=records.slice(0,2).map(record=>record.id);assert.equal(b.read(`recordGateway.setProperties([${JSON.stringify(ids[0])},'missing'],{color:'#ff0000'}).status`),'selection-not-editable');b.run(`layerGateway.create('Blocked');window.__blocked=modelReader.layers().find(layer=>layer.name==='Blocked');recordGateway.assignLayer([${JSON.stringify(ids[1])}],window.__blocked.id);layerGateway.setVisibility(window.__blocked.id,false)`);const before=state(b);assert.equal(b.read(`recordGateway.setProperties(${JSON.stringify(ids)},{color:'#ff0000'}).status`),'selection-not-editable');assert.deepEqual(state(b),before);b.run(`layerGateway.setVisibility(window.__blocked.id,true);layerGateway.setLocked(window.__blocked.id,true)`);assert.equal(b.read(`recordGateway.setProperties([${JSON.stringify(ids[1])}],{color:'#ff0000'}).status`),'selection-not-editable')});

test('aggregation returns actual shared values or the non-persistent MIXED sentinel',async()=>{const b=await browser(),records=seed(b),ids=records.slice(0,2).map(record=>record.id);assert.deepEqual(b.read(`modelReader.aggregateRecordProperties(${JSON.stringify(ids)})`),{color:null,linetype:null,lineweight:null});b.run(`recordGateway.setProperties([${JSON.stringify(ids[0])}],{color:'#ff0000'})`);assert.equal(b.run(`modelReader.aggregateRecordProperties(${JSON.stringify(ids)}).color===window.CaderactObjectProperties.MIXED`),true);assert.equal(b.run(`JSON.stringify(modelReader.aggregateRecordProperties(${JSON.stringify(ids)}))`).includes('MIXED'),false);b.run(`recordGateway.setProperties(${JSON.stringify(ids)},{color:'#00ff00'})`);assert.equal(b.read(`modelReader.aggregateRecordProperties(${JSON.stringify(ids)}).color`),'#00ff00')});

test('Undo and Redo restore exact multi-selection override values and identities',async()=>{const b=await browser(),records=seed(b),ids=records.slice(0,3).map(record=>record.id),before=plain(records.slice(0,3));b.run(`recordGateway.setProperties(${JSON.stringify(ids)},{color:'#abcdef',linetype:'dotted',lineweight:.5})`);const edited=b.read(`modelReader.records().filter(record=>${JSON.stringify(ids)}.includes(record.id))`);b.run('documentController.undo()');assert.deepEqual(b.read(`modelReader.records().filter(record=>${JSON.stringify(ids)}.includes(record.id))`),before.slice().sort((a,z)=>a.id.localeCompare(z.id)));b.run('documentController.redo()');assert.deepEqual(b.read(`modelReader.records().filter(record=>${JSON.stringify(ids)}.includes(record.id))`),edited)});

test('effective resolution follows the owning layer while explicit overrides win',async()=>{const b=await browser(),id=seed(b)[0].id,layerId=b.read('modelReader.snapshot().currentLayerId'),record=`modelReader.records().find(record=>record.id===${JSON.stringify(id)})`;assert.equal(b.read(`window.CaderactObjectProperties.effectiveColor(${record},modelReader.layer(${JSON.stringify(layerId)}))`),'#e8edf4');b.run(`window.__tx=documentController.beginTransaction();window.__layer=window.__tx.readIn('layers',${JSON.stringify(layerId)});window.__tx.replaceIn('layers',${JSON.stringify(layerId)},{...window.__layer,color:'#112233',linetype:'dash-dot',lineweight:.7});window.__tx.publish()`);assert.deepEqual(b.read(`(()=>{const record=${record},layer=modelReader.layer(record.layerId);return {color:window.CaderactObjectProperties.effectiveColor(record,layer),linetype:window.CaderactObjectProperties.effectiveLinetype(record,layer),lineweight:window.CaderactObjectProperties.effectiveLineweight(record,layer)}})()`),{color:'#112233',linetype:'dash-dot',lineweight:.7});b.run(`recordGateway.setProperties([${JSON.stringify(id)}],{color:'#aabbcc',linetype:'continuous',lineweight:.13})`);assert.deepEqual(b.read(`(()=>{const record=${record},layer=modelReader.layer(record.layerId);return {color:window.CaderactObjectProperties.effectiveColor(record,layer),linetype:window.CaderactObjectProperties.effectiveLinetype(record,layer),lineweight:window.CaderactObjectProperties.effectiveLineweight(record,layer)}})()`),{color:'#aabbcc',linetype:'continuous',lineweight:.13})});

test('v1 remains compatible with old property-less files and round-trips exact overrides',async()=>{const b=await browser(),id=seed(b)[0].id;b.run(`recordGateway.setProperties([${JSON.stringify(id)}],{color:'#Ab12Ef',linetype:'dashed',lineweight:1})`);const serialized=b.run('window.CaderactPersistence.serializeDocument(modelReader.snapshot())');assert.equal(JSON.parse(serialized).fileVersion,3);b.run(`window.__loaded=window.CaderactPersistence.loadStore(${JSON.stringify(serialized)})`);assert.equal(b.run('window.CaderactPersistence.serializeDocument(window.__loaded.reader.snapshot())'),serialized);const old=JSON.parse(serialized);old.fileVersion=1;old.document.formatVersion=1;delete old.document.dimensionStyles;delete old.document.currentDimensionStyleId;delete old.document.groups;delete old.document.nextGroupNumber;for(const layer of old.document.layers)for(const key of ['color','linetype','lineweight'])delete layer[key];for(const record of old.document.records)for(const key of ['color','linetype','lineweight'])delete record[key];b.window.__old=JSON.stringify(old);b.run('window.__oldStore=window.CaderactPersistence.loadStore(window.__old)');assert.deepEqual(b.read('window.CaderactObjectProperties.recordProperties(window.__oldStore.reader.records()[0])'),{color:null,linetype:null,lineweight:null});assert.deepEqual(b.read('window.CaderactObjectProperties.layerProperties(window.__oldStore.reader.layers()[0])'),{color:'#e8edf4',linetype:'continuous',lineweight:.25})});

test('malformed persisted object and layer properties are rejected while unknown fields stay closed',async()=>{for(const corrupt of [`window.__p.document.records[0].color='red'`,`window.__p.document.records[0].linetype='bad'`,`window.__p.document.records[0].lineweight=.2`,`window.__p.document.layers[0].color=null`,`window.__p.document.records[0].opacity=.5`]){const b=await browser();seed(b);b.run(`window.__p=JSON.parse(window.CaderactPersistence.serializeDocument(modelReader.snapshot()));${corrupt};window.__bad=JSON.stringify(window.__p)`);assert.throws(()=>b.run('window.CaderactPersistence.loadStore(window.__bad)'),/Invalid Caderact file/)}});

test('transform/copy helpers preserve overrides and Offset inherits them',async()=>{const b=await browser(),record=seed(b)[0];b.run(`recordGateway.setProperties([${JSON.stringify(record.id)}],{color:'#ff00ff',linetype:'dash-dot',lineweight:.7});window.__styled=modelReader.records().find(record=>record.id===${JSON.stringify(record.id)})`);for(const expression of [`window.CaderactGeometryTransform.translateRecord(window.__styled,1,2)`,`window.CaderactGeometryTransform.rotateRecord(window.__styled,{x:0,y:0},.5)`,`window.CaderactGeometryTransform.scaleRecord(window.__styled,{x:0,y:0},2)`,`window.CaderactGeometryTransform.mirrorRecord(window.__styled,{x:0,y:0},{x:0,y:1})`,`recordGateway.copyWithFreshIdentity(window.__styled)`])assert.deepEqual(b.read(`window.CaderactObjectProperties.recordProperties(${expression})`),{color:'#ff00ff',linetype:'dash-dot',lineweight:.7});b.run(`window.caderactSelection.selectOnly(window.__styled.id)`);b.launch('Offset');b.point(450,280,'pointermove');b.point(450,280);assert.equal(b.read(`modelReader.records().some(record=>record.id!==window.__styled.id&&record.type==='line'&&record.start.y===1&&record.color==='#ff00ff'&&record.linetype==='dash-dot'&&record.lineweight===.7)`),true)});

test('Trim and Extend replacement publication preserve target overrides',async()=>{const b=await browser(),target=seed(b)[0];b.run(`recordGateway.setProperties([${JSON.stringify(target.id)}],{color:'#13579b',linetype:'dotted',lineweight:.5});window.__target=modelReader.records().find(record=>record.id===${JSON.stringify(target.id)});window.__trim={status:'planned',targetRecordId:window.__target.id,targetType:'line',replacement:{geometry:{type:'line',start:{x:0,y:0},end:{x:5,y:0}},preserveRecordId:true,featureIdentityIntent:{start:{role:'preserve-existing-feature',featureId:window.__target.start.featureId},end:{role:'preserve-existing-feature',featureId:window.__target.end.featureId}}},creates:[]};recordGateway.publishTrimPlan(window.__trim)`);assert.deepEqual(b.read(`window.CaderactObjectProperties.recordProperties(modelReader.records().find(record=>record.id===${JSON.stringify(target.id)}))`),{color:'#13579b',linetype:'dotted',lineweight:.5});b.run(`window.__trimmed=modelReader.records().find(record=>record.id===${JSON.stringify(target.id)});window.__extend={status:'planned',kind:'extend',targetRecordId:window.__trimmed.id,targetType:'line',sourceGeometry:{type:'line',start:{x:0,y:0},end:{x:5,y:0}},replacement:{geometry:{type:'line',start:{x:0,y:0},end:{x:12,y:0}},preserveRecordId:true,featureIdentityIntent:{start:{role:'preserve-existing-feature',featureId:window.__trimmed.start.featureId},end:{role:'preserve-existing-feature',featureId:window.__trimmed.end.featureId}}}};recordGateway.publishExtendPlan(window.__extend)`);assert.deepEqual(b.read(`window.CaderactObjectProperties.recordProperties(modelReader.records().find(record=>record.id===${JSON.stringify(target.id)}))`),{color:'#13579b',linetype:'dotted',lineweight:.5})});
