'use strict';
const {test}=require('node:test');
const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const {browser}=require('../helpers/browser.cjs');
const root=path.resolve(__dirname,'../..');
const decode=value=>Buffer.from(value).toString('latin1');

function scene(b,{orientation='landscape',mode='plot-color'}={}){b.run(`(()=>{const layout=modelReader.layouts()[0];window.caderactDocumentSession.layoutGateway.setPageSetup(layout.id,{...layout.paper,size:'A4',orientation:'${orientation}'});recordGateway.createAll([recordGateway.createLine({x:-50,y:0},{x:50,y:0}),recordGateway.createText({insertionPoint:{x:0,y:5},text:'PDF NOTE',height:2,rotation:.25})]);window.caderactDocumentSession.layoutGateway.createViewport(layout.id,{frame:{x:10,y:10,width:layout.paper.width-20,height:layout.paper.height-20},viewCenter:{x:0,y:0},scale:10,locked:true});window.__layout=layout.id})()`);b.window.__job={...b.window.CaderactPlotJob.defaults(),colorMode:mode};return b.read(`window.CaderactPlotScene.create({layout:modelReader.layout(window.__layout),job:window.__job,records:modelReader.visibleRecords(),layers:modelReader.layers(),documentUnit:modelReader.units().length,dimensionStyles:Object.fromEntries(modelReader.dimensionStyles().map(s=>[s.id,s]))})`)}

test('PDF2 emits a valid deterministic PDF structure and cross-reference table',async()=>{const b=await browser(),plot=scene(b);b.window.__scene=plot;const first=b.read('Array.from(window.CaderactPdfSerializer.serialize(window.__scene).bytes)'),second=b.read('Array.from(window.CaderactPdfSerializer.serialize(window.__scene).bytes)'),text=decode(first);assert.deepEqual(first,second);assert.match(text,/^%PDF-1\.4/);assert.match(text,/\/Type \/Catalog/);assert.match(text,/xref\n0 6/);assert.match(text,/startxref\n\d+\n%%EOF/)});

test('PDF2 MediaBox preserves landscape and portrait A4 dimensions in points',async()=>{for(const [orientation,width,height] of [['landscape',297,210],['portrait',210,297]]){const b=await browser(),plot=scene(b,{orientation});b.window.__scene=plot;const result=b.read('({bytes:Array.from(window.CaderactPdfSerializer.serialize(window.__scene).bytes),pagePoints:window.CaderactPdfSerializer.serialize(window.__scene).pagePoints})'),text=decode(result.bytes);assert.ok(Math.abs(result.pagePoints.width-width*72/25.4)<1e-4);assert.ok(Math.abs(result.pagePoints.height-height*72/25.4)<1e-4);assert.match(text,/\/MediaBox \[0 0 [\d.]+ [\d.]+\]/)}});

test('PDF2 serializes plot geometry and text as vector operators',async()=>{const b=await browser(),plot=scene(b);b.window.__scene=plot;const result=b.read('(()=>{const r=window.CaderactPdfSerializer.serialize(window.__scene);return{bytes:Array.from(r.bytes),primitiveCounts:r.primitiveCounts}})()'),text=decode(result.bytes);assert.equal(result.primitiveCounts.segments,plot.segments.length);assert.equal(result.primitiveCounts.texts,plot.texts.length);assert.match(text,/ m [\d.-]+ [\d.-]+ l S/);assert.match(text,/BT\n/);assert.match(text,/\(PDF NOTE\) Tj/);assert.match(text,/\/Subtype \/Type1 \/BaseFont \/Helvetica/)});

test('PDF2 preserves Plot Display Grayscale and Monochrome plot-scene colors',async()=>{for(const mode of ['plot-color','display-color','grayscale','monochrome']){const b=await browser(),plot=scene(b,{mode});b.window.__scene=plot;const text=decode(b.read('Array.from(window.CaderactPdfSerializer.serialize(window.__scene).bytes)'));assert.equal(plot.plot.job.colorMode,mode);assert.match(text,/[\d.]+ [\d.]+ [\d.]+ RG/)}});

test('PDF2 empty Layout is a valid vector page and malformed scenes reject',async()=>{const b=await browser(),layout=b.read('modelReader.layouts()[0]');b.window.__layout=layout;const plot=b.read(`window.CaderactPlotScene.create({layout:window.__layout,records:[],layers:modelReader.layers(),documentUnit:'mm'})`);b.window.__scene=plot;const text=decode(b.read('Array.from(window.CaderactPdfSerializer.serialize(window.__scene).bytes)'));assert.match(text,/\/Count 1/);assert.throws(()=>b.run('window.CaderactPdfSerializer.serialize({})'))});

test('PDF2 reports built-in font substitution rather than silently dropping Unicode',async()=>{const b=await browser();b.window.__scene={unit:'mm',layoutId:'layout',page:{width:10,height:10},printable:{x:0,y:0,width:10,height:10},plot:{},segments:[],texts:[{point:{x:1,y:1},value:'A😀',height:2,rotation:0,alignment:'left',color:'#000000'}]};const result=b.read('(()=>{const r=window.CaderactPdfSerializer.serialize(window.__scene);return{bytes:Array.from(r.bytes),warnings:r.warnings}})()'),text=decode(result.bytes);assert.equal(result.warnings.length,1);assert.match(text,/\(A\?\) Tj/)});

test('PDF2 export UX derives safe filenames and reuses the shared output preparation',()=>{const html=fs.readFileSync(path.join(root,'index.html'),'utf8'),source=fs.readFileSync(path.join(root,'src/js/editor/pdf-export.js'),'utf8');assert.match(html,/layout-export-pdf/);assert.match(source,/CaderactPlotOutput/);assert.doesNotMatch(source,/caderactPlotPreview/);assert.match(source,/application\/pdf/);assert.match(source,/download initiated/);assert.doesNotMatch(source,/CaderactPlotScene\.create|toDataURL|drawImage/)});

test('PDF2 export remains outside native save history and DXF authorities',()=>{const source=fs.readFileSync(path.join(root,'src/js/editor/pdf-export.js'),'utf8'),dxf=fs.readFileSync(path.join(root,'src/js/io/dxf/DxfExport.js'),'utf8');for(const forbidden of ['DocumentFileState','manualSave','markSaved','beginTransaction','recordGateway'])assert.doesNotMatch(source,new RegExp(forbidden));assert.doesNotMatch(dxf,/PdfSerializer|caderactPdfExport/)});
