'use strict';
const {test}=require('node:test');
const assert=require('node:assert/strict');
const fs=require('node:fs');
const {browser}=require('../helpers/browser.cjs');
const decode=value=>Buffer.from(value).toString('latin1');

function seed(b){b.run(`recordGateway.createAll([recordGateway.createLine({x:-20,y:0},{x:20,y:0}),recordGateway.createText({insertionPoint:{x:0,y:5},text:'PLOT3',height:2,rotation:0})]);window.__first=modelReader.layouts()[0];window.__a3=window.caderactDocumentSession.layoutGateway.create('A3 Sheet',{paper:{size:'A3',orientation:'landscape',width:420,height:297,units:'mm',margins:{top:12,right:12,bottom:12,left:12}}}).layout;window.__letter=window.caderactDocumentSession.layoutGateway.create('Letter Portrait',{paper:{size:'Letter',orientation:'portrait',width:215.9,height:279.4,units:'mm',margins:{top:8,right:8,bottom:8,left:8}}}).layout;window.caderactLayoutContext.switchToLayout(window.__a3.id)`)}

test('PLOT3 normalizes Current Selected and All scopes in document Layout order',async()=>{const b=await browser();seed(b);const ids=b.read('modelReader.layouts().map(layout=>layout.id)'),current=b.read('window.__a3.id');assert.deepEqual(b.read(`window.CaderactPlotBatch.normalize({scope:'current'},modelReader.layouts(),${JSON.stringify(current)}).batch.layoutIds`),[current]);assert.deepEqual(b.read(`window.CaderactPlotBatch.normalize({scope:'selected',layoutIds:[${JSON.stringify(ids[2])},${JSON.stringify(ids[0])}]},modelReader.layouts(),${JSON.stringify(current)}).batch.layoutIds`),[ids[0],ids[2]]);assert.deepEqual(b.read(`window.CaderactPlotBatch.normalize({scope:'all'},modelReader.layouts(),${JSON.stringify(current)}).batch.layoutIds`),ids);assert.equal(b.read(`window.CaderactPlotBatch.normalize({scope:'selected',layoutIds:[]},modelReader.layouts(),${JSON.stringify(current)}).status`),'invalid-plot-batch')})

test('PLOT3 prepares each Layout through PlotOutput without changing active context or document state',async()=>{const b=await browser();seed(b);const before=b.read(`({context:window.caderactLayoutContext.snapshot(),revision:documentController.currentRevision,history:documentController.historyInfo.entryCount,dirty:documentController.isDirty})`),result=b.read(`window.CaderactPlotOutput.prepareBatch({scope:'all',outputMode:'multi-page'},window.CaderactPlotJob.defaults())`),after=b.read(`({context:window.caderactLayoutContext.snapshot(),revision:documentController.currentRevision,history:documentController.historyInfo.entryCount,dirty:documentController.isDirty})`);assert.equal(result.status,'ready');assert.deepEqual(result.pages.map(page=>page.layout.id),b.read('modelReader.layouts().map(layout=>layout.id)'));assert.deepEqual(after,before);for(const page of result.pages){assert.equal(page.scene.layoutId,page.layout.id);assert.deepEqual({width:page.scene.page.width,height:page.scene.page.height},{width:page.layout.paper.width,height:page.layout.paper.height})}})

test('PLOT3 vector PDF supports mixed physical page sizes and preserves searchable page content',async()=>{const b=await browser();seed(b);b.run(`window.__batch=window.CaderactPlotOutput.prepareBatch({scope:'all',outputMode:'multi-page'},window.CaderactPlotJob.defaults());window.__pdf=window.CaderactPdfSerializer.serializePages(window.__batch.pages.map(page=>page.scene))`);const result=b.read(`({pageCount:window.__pdf.pageCount,pages:window.__pdf.pages,bytes:Array.from(window.__pdf.bytes),sceneCount:window.__batch.pages.length})`),pdf=decode(result.bytes);assert.equal(result.pageCount,result.sceneCount);assert.equal((pdf.match(/\/Type \/Page\b/g)||[]).length,result.pageCount);assert.match(pdf,new RegExp(`/Count ${result.pageCount}`));assert.equal(result.pages[1].width,Number((420*72/25.4).toFixed(5)));assert.equal(result.pages[2].height,Number((279.4*72/25.4).toFixed(5)));assert.equal((pdf.match(/\(PLOT3\) Tj/g)||[]).length,result.pageCount);assert.doesNotMatch(pdf,/\/Subtype \/Image/)})

test('PLOT3 separate filenames are safe deterministic and collision-resistant',async()=>{const b=await browser();b.window.__layouts=[{name:'Plan/A'},{name:'Plan:A'},{name:'CON<>*'},{name:'Plan/A'}];assert.deepEqual(b.read(`window.CaderactPlotBatch.filenames('Demo.caderact',window.__layouts)`),['Demo-Plan-A.pdf','Demo-Plan-A-2.pdf','Demo-CON---.pdf','Demo-Plan-A-3.pdf']);assert.deepEqual(b.read(`window.CaderactPlotBatch.filenames('',[{name:''}])`),['Untitled-Untitled.pdf'])})

test('PLOT3 production UI exposes scope selection page preview and both output modes',()=>{const preview=fs.readFileSync('src/js/editor/plot-preview.js','utf8'),pdf=fs.readFileSync('src/js/editor/pdf-export.js','utf8');for(const label of ['Current Layout','Selected Layouts','All Layouts','Single multi-page PDF','Separate PDF per Layout','Preview page'])assert.match(preview,new RegExp(label));assert.match(preview,/prepareBatch/);assert.match(preview,/pageSelect/);assert.match(pdf,/serializePages/);assert.match(pdf,/outputMode==="separate"/);assert.match(pdf,/CaderactPlotBatch\.filenames/)})
