'use strict';
const {test}=require('node:test');
const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const {browser}=require('../helpers/browser.cjs');
const decode=value=>Buffer.from(value).toString('latin1');
const root=path.resolve(__dirname,'../..');

function makeScene(b,mode='plot-color'){
  b.run(`(()=>{const layout=modelReader.layouts()[0];for(const id of [...layout.viewportOrder])window.caderactDocumentSession.layoutGateway.removeViewport(layout.id,id);window.caderactDocumentSession.layoutGateway.createViewport(layout.id,{frame:{x:10,y:10,width:277,height:190},viewCenter:{x:0,y:0},scale:1,locked:true});window.__layout=layout.id;window.__job={...window.CaderactPlotJob.defaults(),colorMode:${JSON.stringify(mode)}}})()`)
  return b.read(`window.CaderactPlotScene.create({layout:modelReader.layout(window.__layout),job:window.__job,records:modelReader.visibleRecords(),layers:modelReader.layers(),document:modelReader.snapshot(),documentUnit:modelReader.units().length,dimensionStyles:Object.fromEntries(modelReader.dimensionStyles().map(style=>[style.id,style]))})`)
}

test('PLOT2 resolves explicit and ByLayer stroke properties into physical output styles',async()=>{
  const b=await browser();b.run(`layerGateway.create('Plot');window.__layer=modelReader.layers().find(layer=>layer.name==='Plot');window.__tx=documentController.beginTransaction();window.__stored=window.__tx.readIn('layers',window.__layer.id);window.__tx.replaceIn('layers',window.__layer.id,{...window.__stored,color:'#123456',linetype:'dash-dot',lineweight:.7});window.__tx.publish();window.__by=recordGateway.createLine({x:-20,y:0},{x:20,y:0});window.__explicit=recordGateway.createLine({x:-20,y:5},{x:20,y:5});recordGateway.createAll([window.__by,window.__explicit]);recordGateway.assignLayer([window.__by.id,window.__explicit.id],window.__layer.id);recordGateway.setProperties([window.__explicit.id],{color:'#abcdef',linetype:'dotted',lineweight:.13})`);const scene=makeScene(b),by=scene.segments.find(line=>line.sourceRecordId===b.read('window.__by.id')),explicit=scene.segments.find(line=>line.sourceRecordId===b.read('window.__explicit.id'));assert.deepEqual({color:by.color,linetype:by.linetype,lineweight:by.lineweight,dashPattern:by.dashPattern},{color:'#123456',linetype:'dash-dot',lineweight:.7,dashPattern:[4,1.5,.5,1.5]});assert.deepEqual({color:explicit.color,linetype:explicit.linetype,lineweight:explicit.lineweight,dashPattern:explicit.dashPattern},{color:'#abcdef',linetype:'dotted',lineweight:.13,dashPattern:[.5,1.5]})
});

test('PLOT2 covers curves text region solid/named hatch and transformed nested Blocks',async()=>{
  const b=await browser();b.run(`window.__records=[recordGateway.createLine({x:-10,y:-10},{x:10,y:-10}),recordGateway.createPolyline([{x:-10,y:-5},{x:0,y:-2},{x:10,y:-5}],false),recordGateway.createCircle({x:-8,y:8},2),recordGateway.createArc({center:{x:0,y:8},radius:2,start:{x:2,y:8},end:{x:0,y:10},sweep:Math.PI/2}),recordGateway.createEllipse({center:{x:8,y:8},majorAxis:{x:3,y:0},minorRadius:1}),recordGateway.createText({insertionPoint:{x:0,y:13},text:'SEARCHABLE',height:2,rotation:0}),recordGateway.createRegion([recordGateway.createCircle({x:-10,y:18},2)]),recordGateway.createHatch([recordGateway.createCircle({x:0,y:18},2)],{kind:'solid'}),recordGateway.createHatch([recordGateway.createCircle({x:10,y:18},2)],{kind:'named',name:'ANSI31',angle:0,scale:1,origin:{x:0,y:0}})];recordGateway.createAll(window.__records);window.__leaf=blockDefinitionGateway.create({name:'Leaf',records:[recordGateway.createLine({x:0,y:0},{x:4,y:0})]}).definition;window.__nested=recordGateway.createBlockInstance({definitionId:window.__leaf.id,insertionPoint:{x:3,y:0},rotation:.25,scale:2,mirrored:false});window.__outer=blockDefinitionGateway.create({name:'Outer',records:[window.__nested]}).definition;window.__top=recordGateway.createBlockInstance({definitionId:window.__outer.id,insertionPoint:{x:20,y:0},rotation:.5,scale:2,mirrored:true});recordGateway.createAll([window.__top])`);const scene=makeScene(b);assert.ok(scene.segments.length>10);assert.equal(scene.curves.length,3);assert.ok(scene.fills.length>0);assert.ok(scene.texts.some(text=>text.value==='SEARCHABLE'));assert.ok(scene.segments.some(line=>line.sourceRecordId===b.read('window.__top.id')&&line.recordId.includes('/')));assert.equal(scene.plot.modelViewFrames,'excluded')
});

test('PLOT2 excludes hidden layers, includes locked layers, clips every primitive, and transforms colors deterministically',async()=>{
  const b=await browser();b.run(`layerGateway.create('Hidden');layerGateway.create('Locked');window.__hiddenLayer=modelReader.layers().find(layer=>layer.name==='Hidden');window.__lockedLayer=modelReader.layers().find(layer=>layer.name==='Locked');window.__hidden=recordGateway.createLine({x:-500,y:0},{x:500,y:0});window.__locked=recordGateway.createLine({x:-500,y:2},{x:500,y:2});recordGateway.createAll([window.__hidden,window.__locked]);recordGateway.setProperties([window.__locked.id],{color:'#ff0000'});recordGateway.assignLayer([window.__hidden.id],window.__hiddenLayer.id);recordGateway.assignLayer([window.__locked.id],window.__lockedLayer.id);layerGateway.setVisibility(window.__hiddenLayer.id,false);layerGateway.setLocked(window.__lockedLayer.id,true)`);const color=makeScene(b),gray=makeScene(b,'grayscale'),mono=makeScene(b,'monochrome');assert.equal(color.segments.some(line=>line.sourceRecordId===b.read('window.__hidden.id')),false);assert.equal(color.segments.some(line=>line.sourceRecordId===b.read('window.__locked.id')),true);assert.ok(color.segments.every(line=>line.start.x>=10&&line.end.x<=287));assert.equal(gray.segments.find(line=>line.sourceRecordId===b.read('window.__locked.id')).color,'#363636');assert.equal(mono.segments.find(line=>line.sourceRecordId===b.read('window.__locked.id')).color,'#000000');assert.equal(color.plot.lockedObjects,'included')
});

test('PLOT2 Preview and PDF consume the same styled scene and PDF remains vector/searchable',async()=>{
  const b=await browser();b.run(`window.__line=recordGateway.createLine({x:-10,y:0},{x:10,y:0});window.__text=recordGateway.createText({insertionPoint:{x:0,y:5},text:'VECTOR TEXT',height:2,rotation:0});recordGateway.createAll([window.__line,window.__text]);recordGateway.setProperties([window.__line.id],{color:'#00aa44',linetype:'dashed',lineweight:1})`);const scene=makeScene(b);b.window.__scene=scene;const result=b.read(`(()=>{const value=window.CaderactPdfSerializer.serialize(window.__scene);return{bytes:Array.from(value.bytes),counts:value.primitiveCounts}})()`),pdf=decode(result.bytes);assert.equal(result.counts.segments,scene.segments.length);assert.equal(result.counts.fills,scene.fills.length);assert.match(pdf,/2\.83465 w/);assert.match(pdf,/\[[\d.]+ [\d.]+\] 0 d/);assert.match(pdf,/\(VECTOR TEXT\) Tj/);assert.doesNotMatch(pdf,/\/Subtype \/Image/)
});

test('PLOT2R preview draws one solid output boundary and scales physical lineweight with paper zoom',async()=>{
  const source=fs.readFileSync(path.join(root,'src/js/editor/plot-preview.js'),'utf8');assert.match(source,/ctx\.setLineDash\(\[\]\);ctx\.strokeRect/);assert.doesNotMatch(source,/ctx\.setLineDash\(\[4,3\]\)/);assert.match(source,/ctx\.lineWidth=\(value\.lineweight\|\|\.25\)\*renderScale/);assert.doesNotMatch(source,/Math\.max\([^;]*lineweight/);const physical=.25,fit=2.4;assert.equal(physical*fit*2/(physical*fit),2)
});

test('PLOT2R1 uses the real DPR backing store once and submits floating coordinates once',async()=>{
  const b=await browser();b.window.devicePixelRatio=2.5;b.load('src/js/editor/plot-preview.js');b.run(`window.__calls=[];window.__widths=[];window.__ctx={set lineWidth(value){window.__widths.push(value)},set strokeStyle(value){},set fillStyle(value){},set font(value){},set textAlign(value){},setTransform(...value){window.__calls.push(['transform',...value])},clearRect(){},fillRect(){},save(){},restore(){},beginPath(){window.__calls.push(['begin'])},moveTo(...value){window.__calls.push(['move',...value])},lineTo(...value){window.__calls.push(['line',...value])},ellipse(...value){window.__calls.push(['ellipse',...value])},stroke(){window.__calls.push(['stroke'])},fill(){},closePath(){},fillText(){},translate(){},rotate(){},strokeRect(...value){window.__calls.push(['boundary',...value])},setLineDash(value){window.__calls.push(['dash',...value])}};window.__canvas={style:{},dataset:{},getContext:()=>window.__ctx};window.__surface={clientWidth:703,clientHeight:617};window.__scene={unit:'mm',page:{width:137,height:91},printable:{x:7,y:5,width:123,height:81},segments:[{start:{x:10.125,y:12.375},end:{x:88.625,y:41.875},color:'#000000',lineweight:.25,dashPattern:[]}],curves:[],fills:[],texts:[]};window.__render=window.CaderactPlotPreviewRenderer.renderSceneToCanvas(window.__canvas,window.__surface,window.__scene,1.3)`);const value=b.read(`({render:window.__render,canvas:{width:window.__canvas.width,height:window.__canvas.height,style:window.__canvas.style},calls:window.__calls,widths:window.__widths})`),transform=value.calls.find(call=>call[0]==='transform'),moves=value.calls.filter(call=>call[0]==='move'),lines=value.calls.filter(call=>call[0]==='line');assert.equal(value.canvas.width,Math.round(value.render.width*2.5));assert.equal(value.canvas.height,Math.round(value.render.height*2.5));assert.equal(transform[1],value.canvas.width/value.render.width);assert.equal(transform[4],value.canvas.height/value.render.height);assert.equal(moves.length,1);assert.equal(lines.length,1);assert.notEqual(moves[0][1],Math.round(moves[0][1]));assert.notEqual(lines[0][2],Math.round(lines[0][2]));assert.equal(value.widths.at(-1),.25*value.render.renderScale)
});

test('PLOT2R2 fits portrait landscape and custom sheets to the actual centered preview body',async()=>{
  const b=await browser();b.load('src/js/editor/plot-preview.js');b.window.__surface={clientWidth:800,clientHeight:600,scrollWidth:1200,scrollHeight:900,scrollLeft:0,scrollTop:0};for(const page of [{width:297,height:210},{width:210,height:297},{width:420,height:297},{width:216,height:279},{width:513.25,height:187.75}]){b.window.__page=page;const value=b.read('window.CaderactPlotPreviewRenderer.fitMetrics(window.__surface,window.__page,1)');assert.ok(value.width<=value.availableWidth+1e-10);assert.ok(value.height<=value.availableHeight+1e-10);assert.ok(Math.abs(value.width/value.height-page.width/page.height)<1e-12);assert.ok(Math.abs(Math.max((value.availableWidth-value.width)/2,(value.availableHeight-value.height)/2))>=0)}const centered=b.read('window.CaderactPlotPreviewRenderer.centerSurface(window.__surface)');assert.deepEqual(centered,{left:200,top:150});assert.deepEqual(b.read('({left:window.__surface.scrollLeft,top:window.__surface.scrollTop})'),centered)
});

test('PLOT2R2 Preview-only layout removes the Plot settings track and resize preserves manual zoom state',()=>{
  const source=fs.readFileSync(path.join(root,'src/js/editor/plot-preview.js'),'utf8'),css=fs.readFileSync(path.join(root,'src/css/application-shell.css'),'utf8');assert.match(source,/body\.classList\.toggle\("is-preview-only",mode!=="plot"\)/);assert.match(css,/\.plot-dialog-body\.is-preview-only\{grid-template-columns:minmax\(0,1fr\);grid-template-rows:minmax\(0,1fr\)\}/);assert.match(source,/zoom=1;fitted=true/);assert.match(source,/if\(dialog\.open&&fitted\)render\(\)/);assert.match(source,/function setZoom\(value\).*fitted=zoom===1/);assert.doesNotMatch(source,/ResizeObserver\(\(\)=>\{if\(dialog\.open\)render\(\)/)
});

test('PLOT2R keeps exact Line/Polyline vertices and native curve primitives through PDF',async()=>{
  const b=await browser();b.run(`window.__line=recordGateway.createLine({x:-7,y:-3},{x:11,y:9});window.__poly=recordGateway.createPolyline([{x:-9,y:4},{x:2,y:7},{x:13,y:1}],false);window.__circle=recordGateway.createCircle({x:20,y:20},3);window.__arc=recordGateway.createArc({center:{x:30,y:20},radius:4,start:{x:34,y:20},end:{x:30,y:24},sweep:Math.PI/2});window.__ellipse=recordGateway.createEllipse({center:{x:40,y:20},majorAxis:{x:5,y:0},minorRadius:2});recordGateway.createAll([window.__line,window.__poly,window.__circle,window.__arc,window.__ellipse])`);const scene=makeScene(b);assert.equal(scene.segments.filter(item=>item.sourceRecordId===b.read('window.__line.id')).length,1);assert.equal(scene.segments.filter(item=>item.sourceRecordId===b.read('window.__poly.id')).length,2);assert.equal(scene.curves.length,3);b.window.__scene=scene;const pdf=decode(b.read('Array.from(window.CaderactPdfSerializer.serialize(window.__scene).bytes)'));assert.ok((pdf.match(/ c\n/g)||[]).length>=6);assert.equal((pdf.match(/ m /g)||[]).length>=3,true)
});
