'use strict';
const {test}=require('node:test');const assert=require('node:assert/strict');const {browser}=require('../helpers/browser.cjs');
const state=b=>b.read('({revision:documentController.currentRevision,history:documentController.historyInfo,dirty:documentController.isDirty,records:modelReader.records(),context:window.caderactLayoutContext.snapshot()})');

test('PS1 new and legacy v3 documents receive stable document-owned Layout1',async()=>{const b=await browser();const layout=b.read('modelReader.layouts()[0]');assert.equal(layout.name,'Layout1');assert.deepEqual(layout.paper,b.read('window.CaderactPaperSpace.DEFAULT'));const old=JSON.parse(b.run('window.CaderactPersistence.serializeDocument(modelReader.snapshot())'));delete old.document.layouts;delete old.document.layoutOrder;b.window.__old=JSON.stringify(old);b.run('window.__loaded=window.CaderactPersistence.loadStore(window.__old)');assert.equal(b.read('window.__loaded.reader.layouts()[0].name'),'Layout1');assert.match(b.read('window.__loaded.reader.layouts()[0].id'),/^layout_/)});

test('PS1 create rename reorder delete are atomic exact Layout history',async()=>{const b=await browser(),base=b.read('documentController.historyInfo.entryCount');b.run('window.__a=window.caderactDocumentSession.layoutGateway.create("Sheet A").layout;window.__b=window.caderactDocumentSession.layoutGateway.create("Sheet B").layout');assert.equal(b.read('documentController.historyInfo.entryCount'),base+2);assert.equal(b.read('window.caderactDocumentSession.layoutGateway.rename(window.__a.id,"Plan").status'),'committed');assert.equal(b.read('window.caderactDocumentSession.layoutGateway.rename(window.__b.id,"plan").status'),'duplicate-name');assert.equal(b.read('window.caderactDocumentSession.layoutGateway.reorder(window.__b.id,0).status'),'committed');const exact=b.read('modelReader.snapshot()');assert.equal(b.read('window.caderactDocumentSession.layoutGateway.remove(window.__a.id).status'),'committed');b.run('documentController.undo()');assert.deepEqual(b.read('modelReader.snapshot()'),exact);b.run('documentController.redo()');assert.equal(b.read('modelReader.layout(window.__a.id)'),null)});

test('PS1 Model Layout switching is ephemeral and preserves geometry',async()=>{const b=await browser();b.run('recordGateway.createAll([recordGateway.createLine({x:0,y:0},{x:10,y:0})])');const before=state(b),id=b.read('modelReader.layouts()[0].id');b.window.__layout=id;assert.equal(b.read('window.caderactLayoutContext.switchToLayout(window.__layout).status'),'context-switched');assert.equal(b.read('window.caderactLayoutContext.snapshot().kind'),'layout');assert.deepEqual(b.read('modelReader.records()'),before.records);assert.equal(b.read('documentController.currentRevision'),before.revision);assert.deepEqual(b.read('documentController.historyInfo'),before.history);assert.equal(b.read('documentController.isDirty'),before.dirty);b.run('window.caderactLayoutContext.switchToModel()');assert.equal(b.read('window.caderactLayoutContext.snapshot().kind'),'model')});

test('PS1 active context reconciles after delete Undo Redo and replacement',async()=>{const b=await browser(),id=b.read('modelReader.layouts()[0].id');b.window.__id=id;b.run('window.caderactLayoutContext.switchToLayout(window.__id);window.caderactDocumentSession.layoutGateway.remove(window.__id)');assert.equal(b.read('window.caderactLayoutContext.snapshot().kind'),'model');b.run('documentController.undo();window.caderactLayoutContext.switchToLayout(window.__id);documentController.redo()');assert.equal(b.read('window.caderactLayoutContext.snapshot().kind'),'model');b.run('window.__next=window.CaderactDocument.createStore({initiallySaved:true});window.caderactDocumentSession.replaceStore(window.__next)');assert.equal(b.read('window.caderactLayoutContext.snapshot().kind'),'model')});

test('PS1 save load preserves Layout IDs names order and paper metadata',async()=>{const b=await browser();b.run('window.__created=window.caderactDocumentSession.layoutGateway.create("Details").layout;window.caderactDocumentSession.layoutGateway.reorder(window.__created.id,0);window.__serialized=window.CaderactPersistence.serializeDocument(modelReader.snapshot());window.__loaded=window.CaderactPersistence.loadStore(window.__serialized)');assert.deepEqual(b.read('window.__loaded.reader.snapshot().layouts'),b.read('modelReader.snapshot().layouts'));assert.deepEqual(b.read('window.__loaded.reader.snapshot().layoutOrder'),b.read('modelReader.snapshot().layoutOrder'))});

test('PS1 Layout context renders no Model records and blocks ordinary commands',async()=>{const b=await browser();b.run('recordGateway.createAll([recordGateway.createLine({x:0,y:0},{x:10,y:0})]);window.caderactLayoutContext.switchToLayout(modelReader.layouts()[0].id)');b.flush();assert.equal(b.renders.at(-1).recordCount,undefined);const before=state(b);assert.deepEqual(b.read('window.caderactCommandRouter.execute("Line")'),{status:'command-unavailable',command:'Line',reason:'workspace-context'});assert.deepEqual(state(b),before)});

test('PS1 Layout names are deterministic and globally safe',async()=>{const b=await browser();assert.equal(b.read('window.caderactDocumentSession.layoutGateway.create("Model").status'),'invalid-name');assert.equal(b.read('window.caderactDocumentSession.layoutGateway.create(" Layout1 ").status'),'duplicate-name');b.run('window.__x=window.caderactDocumentSession.layoutGateway.create("Sheet").layout');const ids=b.read('Object.keys(modelReader.snapshot().layouts)');assert.equal(new Set(ids).size,ids.length);assert.deepEqual(b.read('window.CaderactDocument.validateDocument(modelReader.snapshot())'),[])});

test('PS1 production workspace exposes compact overflow-safe Model Layout tabs',()=>{const fs=require('node:fs'),path=require('node:path'),root=path.resolve(__dirname,'../..'),html=fs.readFileSync(path.join(root,'index.html'),'utf8'),css=fs.readFileSync(path.join(root,'src/css/application-shell.css'),'utf8');assert.match(html,/id="layout-tabs"/);assert.match(html,/id="layout-add"/);assert.match(html,/layout-tabs\.js/);assert.match(css,/\.layout-tabs\{[^}]*overflow-x:auto/);assert.match(css,/\.layout-tab\.is-active/)});
