'use strict';
const {test}=require('node:test');const assert=require('node:assert/strict');const {browser}=require('../helpers/browser.cjs');
const setup=(size,orientation,width=1,height=1,margins={top:10,right:10,bottom:10,left:10})=>({size,orientation,width,height,units:'mm',margins});

test('PS2 default page is physical A4 landscape with printable margins',async()=>{const b=await browser(),layout=b.read('modelReader.layouts()[0]');assert.deepEqual(layout.paper,{size:'A4',orientation:'landscape',width:297,height:210,units:'mm',margins:{top:10,right:10,bottom:10,left:10},plot:{area:'layout',scale:1,placement:'centered',offset:{x:0,y:0},colorMode:'color'}});b.window.__layout=layout;assert.deepEqual(b.read('window.CaderactPaperSpace.derive(window.__layout)'),{valid:true,unit:'mm',sheet:{left:0,bottom:0,right:297,top:210,width:297,height:210},printable:{left:10,bottom:10,right:287,top:200,width:277,height:190}})});

test('PS2 A4 A3 Letter Legal portrait and landscape use authoritative dimensions',async()=>{const b=await browser(),id=b.read('modelReader.layouts()[0].id');b.window.__id=id;const expected={A4:[210,297],A3:[297,420],Letter:[215.9,279.4],Legal:[215.9,355.6]};for(const [size,[w,h]] of Object.entries(expected)){b.window.__setup=setup(size,'portrait');assert.equal(b.read('window.caderactDocumentSession.layoutGateway.setPageSetup(window.__id,window.__setup).status'),'committed');assert.deepEqual(b.read('modelReader.layout(window.__id).paper').width,w);assert.deepEqual(b.read('modelReader.layout(window.__id).paper').height,h);b.window.__setup=setup(size,'landscape');b.run('window.caderactDocumentSession.layoutGateway.setPageSetup(window.__id,window.__setup)');assert.deepEqual([b.read('modelReader.layout(window.__id).paper.width'),b.read('modelReader.layout(window.__id).paper.height')],[h,w])}});

test('PS2 Custom dimensions and margins validate printable area',async()=>{const b=await browser(),id=b.read('modelReader.layouts()[0].id');b.window.__id=id;b.window.__valid=setup('Custom','portrait',500,700,{top:15,right:20,bottom:25,left:30});assert.equal(b.read('window.caderactDocumentSession.layoutGateway.setPageSetup(window.__id,window.__valid).status'),'committed');assert.deepEqual(b.read('window.CaderactPaperSpace.derive(modelReader.layout(window.__id)).printable'),{left:30,bottom:25,right:480,top:685,width:450,height:660});for(const value of [setup('Custom','portrait',0,10),setup('Custom','portrait',NaN,10),setup('Custom','portrait',20,20,{top:10,right:10,bottom:10,left:10})]){b.window.__bad=value;assert.equal(b.read('window.caderactDocumentSession.layoutGateway.setPageSetup(window.__id,window.__bad).status'),'invalid-page-setup')}});

test('PS2 Page Setup is one exact history mutation and switching remains ephemeral',async()=>{const b=await browser(),id=b.read('modelReader.layouts()[0].id'),before=b.read('modelReader.layout(modelReader.layouts()[0].id)'),history=b.read('documentController.historyInfo.entryCount');b.window.__id=id;b.window.__setup=setup('A3','portrait');assert.equal(b.read('window.caderactDocumentSession.layoutGateway.setPageSetup(window.__id,window.__setup).status'),'committed');const exact=b.read('modelReader.layout(window.__id)');assert.equal(b.read('documentController.historyInfo.entryCount'),history+1);assert.equal(b.read('documentController.isDirty'),true);b.run('documentController.undo()');assert.deepEqual(b.read('modelReader.layout(window.__id)'),before);b.run('documentController.redo()');assert.deepEqual(b.read('modelReader.layout(window.__id)'),exact);const revision=b.read('documentController.currentRevision');b.run('window.caderactLayoutContext.switchToLayout(window.__id);window.caderactLayoutContext.switchToModel()');assert.equal(b.read('documentController.currentRevision'),revision)});

test('PS2 page configuration persists and PS1 paper migrates deterministically',async()=>{const b=await browser(),id=b.read('modelReader.layouts()[0].id');b.window.__id=id;b.window.__setup=setup('Legal','portrait',1,1,{top:12,right:13,bottom:14,left:15});b.run('window.caderactDocumentSession.layoutGateway.setPageSetup(window.__id,window.__setup);window.__serialized=window.CaderactPersistence.serializeDocument(modelReader.snapshot());window.__loaded=window.CaderactPersistence.loadStore(window.__serialized)');assert.deepEqual(b.read('window.__loaded.reader.layout(window.__id).paper'),b.read('modelReader.layout(window.__id).paper'));const old=JSON.parse(b.run('window.__serialized'));old.document.layouts[0].paper={width:297,height:210,units:'mm'};b.window.__old=JSON.stringify(old);b.run('window.__oldStore=window.CaderactPersistence.loadStore(window.__old)');assert.deepEqual(b.read('window.__oldStore.reader.layouts()[0].paper'),b.read('window.CaderactPaperSpace.DEFAULT'))});

test('PS2 active Layout scene projects sheet and margins from physical coordinates',async()=>{const b=await browser();b.resize(900,600);const id=b.read('modelReader.layouts()[0].id');b.window.__id=id;b.run('window.caderactLayoutContext.switchToLayout(window.__id)');b.flush();const overlay=b.renders.at(-1).paperSpaceOverlay;assert.equal(overlay.unit,'mm');assert.equal(overlay.sheet.width,297);assert.equal(overlay.printable.width,277);assert.equal(overlay.segments.length,32);assert.equal(b.renders.at(-1).grid.minorSegments.length,0);assert.equal(b.renders.at(-1).triangleGroups.find(group=>group.role==='paper').triangles.length,2)});

test('PS2 fit Pan Zoom and theme changes never alter physical page dimensions',async()=>{const b=await browser();b.resize(900,600);const id=b.read('modelReader.layouts()[0].id');b.window.__id=id;b.run('window.caderactLayoutContext.switchToLayout(window.__id)');b.flush();const physical=b.renders.at(-1).paperSpaceOverlay.sheet;b.emit(b.canvas,'wheel',{deltaY:-120,clientX:450,clientY:300});b.flush();assert.deepEqual(b.renders.at(-1).paperSpaceOverlay.sheet,physical);b.run('window.caderactWorkspacePreferences.set("canvasTheme","light")');b.flush();assert.deepEqual(b.renders.at(-1).paperSpaceOverlay.sheet,physical)});

test('PS2 Model remains isolated and Page Setup UI is Layout-only context action',async()=>{const b=await browser();b.run('recordGateway.createAll([recordGateway.createLine({x:0,y:0},{x:10,y:0})])');const records=b.read('modelReader.records()');b.window.__setup=setup('A3','landscape');b.run('window.caderactDocumentSession.layoutGateway.setPageSetup(modelReader.layouts()[0].id,window.__setup)');assert.deepEqual(b.read('modelReader.records()'),records);const fs=require('node:fs'),path=require('node:path'),root=path.resolve(__dirname,'../..'),source=fs.readFileSync(path.join(root,'src/js/editor/layout-tabs.js'),'utf8');assert.match(source,/openPageSetup/);assert.match(source,/contextmenu/);assert.doesNotMatch(source,/model.*setPageSetup/i)});
