'use strict';
const {test}=require('node:test');const assert=require('node:assert/strict');const {browser}=require('../helpers/browser.cjs');
const create=(b,extra='')=>b.run(`(()=>{const layout=modelReader.layouts()[0];return window.caderactDocumentSession.layoutGateway.createViewport(layout.id,{frame:{x:20,y:20,width:120,height:80},viewCenter:{x:0,y:0},scale:10,locked:false${extra}}).viewport})()`);

test('PS3 creates stable document-owned rectangular Layout Viewports',async()=>{const b=await browser(),viewport=create(b);assert.match(viewport.id,/^id_/);assert.deepEqual([viewport.frame.x,viewport.frame.y,viewport.frame.width,viewport.frame.height],[20,20,120,80]);assert.deepEqual([viewport.viewCenter.x,viewport.viewCenter.y],[0,0]);assert.equal(viewport.scale,10);assert.equal(viewport.locked,false);assert.deepEqual(b.read('window.CaderactDocument.validateDocument(modelReader.snapshot())'),[])});

test('PS3 standard and custom scales use document unit conversion',async()=>{const b=await browser(),viewport=create(b),id=b.read('modelReader.layouts()[0].id');b.window.__v=viewport;b.window.__id=id;for(const scale of [1,2,5,10,20,50,100,37.5]){b.window.__scale=scale;assert.equal(b.read('window.caderactDocumentSession.layoutGateway.updateViewport(window.__id,window.__v.id,{scale:window.__scale},{viewChange:true}).status'),'committed')}assert.equal(b.read('window.caderactDocumentSession.layoutGateway.updateViewport(window.__id,window.__v.id,{scale:0},{viewChange:true}).status'),'invalid-viewport');b.window.__point={x:1,y:0};assert.equal(b.read('window.CaderactPaperSpace.projectModelPoint(window.__point,modelReader.layout(window.__id).viewports[window.__v.id],"m").x'),20+60+1000/37.5)});

test('PS3 move resize pan scale lock and delete are atomic exact history',async()=>{const b=await browser(),viewport=create(b),layoutId=b.read('modelReader.layouts()[0].id');b.window.__v=viewport;b.window.__layout=layoutId;const history=b.read('documentController.historyInfo.entryCount');assert.equal(b.read('window.caderactDocumentSession.layoutGateway.updateViewport(window.__layout,window.__v.id,{frame:{x:30,y:40,width:90,height:60}}).status'),'committed');assert.equal(b.read('window.caderactDocumentSession.layoutGateway.updateViewport(window.__layout,window.__v.id,{viewCenter:{x:10,y:20}},{viewChange:true}).status'),'committed');assert.equal(b.read('window.caderactDocumentSession.layoutGateway.updateViewport(window.__layout,window.__v.id,{locked:true}).status'),'committed');assert.equal(b.read('window.caderactDocumentSession.layoutGateway.updateViewport(window.__layout,window.__v.id,{scale:50},{viewChange:true}).status'),'viewport-locked');const exact=b.read('modelReader.layout(window.__layout).viewports[window.__v.id]');assert.equal(b.read('documentController.historyInfo.entryCount'),history+3);b.run('documentController.undo()');assert.equal(b.read('modelReader.layout(window.__layout).viewports[window.__v.id].locked'),false);b.run('documentController.redo()');assert.deepEqual(b.read('modelReader.layout(window.__layout).viewports[window.__v.id]'),exact);assert.equal(b.read('window.caderactDocumentSession.layoutGateway.removeViewport(window.__layout,window.__v.id).status'),'committed');b.run('documentController.undo()');assert.deepEqual(b.read('modelReader.layout(window.__layout).viewports[window.__v.id]'),exact)});

test('PS3 multiple viewports reference one unchanged Model table',async()=>{const b=await browser();b.run('recordGateway.createAll([recordGateway.createLine({x:-100,y:0},{x:100,y:0})])');const model=b.read('modelReader.records()'),a=create(b),layoutId=b.read('modelReader.layouts()[0].id');b.window.__layout=layoutId;b.run('window.__b=window.caderactDocumentSession.layoutGateway.createViewport(window.__layout,{frame:{x:150,y:20,width:100,height:80},viewCenter:{x:50,y:0},scale:5,locked:true}).viewport');assert.equal(b.read('Object.keys(modelReader.layout(window.__layout).viewports).length'),2);assert.deepEqual(b.read('modelReader.records()'),model);assert.notEqual(a.id,b.read('window.__b.id'))});

test('PS3 renderer-neutral projection clips Model geometry to each frame',async()=>{const b=await browser();b.resize(900,600);b.run('recordGateway.createAll([recordGateway.createLine({x:-1000,y:0},{x:1000,y:0})])');const viewport=create(b),layoutId=b.read('modelReader.layouts()[0].id');b.window.__layout=layoutId;b.run('window.caderactLayoutContext.switchToLayout(window.__layout)');b.flush();const item=b.renders.at(-1).layoutViewportOverlay.items[0];assert.equal(item.id,viewport.id);assert.equal(item.screenSegments.length,16);const groups=b.renders.at(-1).drawGroups.filter(group=>group.viewportId===viewport.id);assert.ok(groups.some(group=>group.role==='frame'));const model=groups.find(group=>!group.role).lineGroup.segments,frame=item.screenSegments;const xs=Array.from(model).filter((_,i)=>i%2===0);const frameXs=Array.from(frame).filter((_,i)=>i%2===0);assert.ok(Math.min(...xs)>=Math.min(...frameXs)-1e-6);assert.ok(Math.max(...xs)<=Math.max(...frameXs)+1e-6)});

test('PS3 persistence and PS2 migration preserve viewport identity',async()=>{const b=await browser(),viewport=create(b);b.run('window.__file=window.CaderactPersistence.serializeDocument(modelReader.snapshot());window.__loaded=window.CaderactPersistence.loadStore(window.__file)');assert.deepEqual(b.read('window.__loaded.reader.layouts()[0].viewports'),b.read('modelReader.layouts()[0].viewports'));const old=JSON.parse(b.run('window.__file'));delete old.document.layouts[0].viewports;delete old.document.layouts[0].viewportOrder;b.window.__old=JSON.stringify(old);b.run('window.__oldStore=window.CaderactPersistence.loadStore(window.__old)');assert.deepEqual(b.read('window.__oldStore.reader.layouts()[0].viewports'),{});assert.equal(b.read('window.__oldStore.reader.layouts()[0].viewportOrder.length'),0);assert.ok(viewport.id)});

test('PS3 malformed viewports reject without damaging Model geometry',async()=>{const b=await browser();b.run('recordGateway.createAll([recordGateway.createLine({x:0,y:0},{x:1,y:1})]);window.__file=window.CaderactPersistence.serializeDocument(modelReader.snapshot())');const before=b.read('modelReader.records()'),bad=JSON.parse(b.run('window.__file'));bad.document.layouts[0].viewports=[{id:'vp_bad',frame:{x:0,y:0,width:-1,height:2},viewCenter:{x:0,y:0},scale:1,locked:false}];bad.document.layouts[0].viewportOrder=['vp_bad'];b.window.__bad=JSON.stringify(bad);assert.throws(()=>b.run('window.CaderactPersistence.loadStore(window.__bad)'));assert.deepEqual(b.read('modelReader.records()'),before)});

test('PS3 production UI exposes Layout controls selection and Properties',()=>{const fs=require('node:fs'),path=require('node:path'),root=path.resolve(__dirname,'../..'),html=fs.readFileSync(path.join(root,'index.html'),'utf8'),source=fs.readFileSync(path.join(root,'src/js/editor/layout-tabs.js'),'utf8'),properties=fs.readFileSync(path.join(root,'src/js/editor/properties-panel.js'),'utf8'),documentSource=fs.readFileSync(path.join(root,'src/js/document/CaderactDocument.js'),'utf8');for(const id of ['layout-viewport-create','layout-viewport-scale','layout-viewport-lock'])assert.match(html,new RegExp(id));assert.match(source,/selectViewport/);assert.match(source,/viewChange:true/);for(const field of ['Layout Viewport','Paper Frame','Model View','Center X','Center Y'])assert.match(properties,new RegExp(field));assert.match(documentSource,/viewport-locked/)});
