'use strict';
const {test}=require('node:test');
const assert=require('node:assert/strict');
const {browser}=require('../helpers/browser.cjs');

function setup(b){b.run(`(()=>{const layout=modelReader.layouts()[0];recordGateway.createAll([recordGateway.createLine({x:-1000,y:0},{x:1000,y:0})]);const viewport=window.caderactDocumentSession.layoutGateway.createViewport(layout.id,{frame:{x:0,y:0,width:297,height:210},viewCenter:{x:0,y:0},scale:10,locked:true}).viewport;window.__layoutId=layout.id;window.__viewport=viewport})()`)}
const scene=b=>b.read(`window.CaderactPlotScene.create({layout:modelReader.layout(window.__layoutId),records:modelReader.visibleRecords(),layers:modelReader.layers(),documentUnit:modelReader.units().length})`);

test('PS4 defaults Layout output to physical 1:1 color',async()=>{const b=await browser();assert.deepEqual(b.read('modelReader.layouts()[0].paper.plot'),{area:'layout',scale:1,placement:'centered',offset:{x:0,y:0},colorMode:'color'})});

test('PS4 Page Setup publishes plot changes atomically with exact Undo Redo',async()=>{const b=await browser(),id=b.read('modelReader.layouts()[0].id');b.window.__id=id;const before=b.read('documentController.historyInfo.entryCount');assert.equal(b.read(`window.caderactDocumentSession.layoutGateway.setPageSetup(window.__id,{...modelReader.layout(window.__id).paper,plot:{area:'layout',scale:1,placement:'offset',offset:{x:3,y:4},colorMode:'grayscale'}}).status`),'committed');assert.equal(b.read('documentController.historyInfo.entryCount'),before+1);b.run('documentController.undo()');assert.equal(b.read('modelReader.layout(window.__id).paper.plot.colorMode'),'color');b.run('documentController.redo()');assert.deepEqual(b.read('modelReader.layout(window.__id).paper.plot'),{area:'layout',scale:1,placement:'offset',offset:{x:3,y:4},colorMode:'grayscale'})});

test('PS4 plot scene applies viewport scale and printable clipping in millimetres',async()=>{const b=await browser();setup(b);const output=scene(b);assert.equal(output.unit,'mm');assert.equal(output.plot.scale,1);assert.ok(output.segments.length);for(const line of output.segments)for(const point of [line.start,line.end]){assert.ok(point.x>=output.printable.x-1e-9&&point.x<=output.printable.x+output.printable.width+1e-9);assert.ok(point.y>=output.printable.y-1e-9&&point.y<=output.printable.y+output.printable.height+1e-9)}});

test('PS4 color modes are deterministic and do not mutate source colors',async()=>{const b=await browser();assert.equal(b.read(`window.CaderactPlotScene.transformColor('#ff0000','color')`),'#ff0000');assert.equal(b.read(`window.CaderactPlotScene.transformColor('#ff0000','grayscale')`),'#363636');assert.equal(b.read(`window.CaderactPlotScene.transformColor('#ff0000','monochrome')`),'#000000');const before=b.read('modelReader.records()');b.run(`(()=>{const layout=modelReader.layouts()[0];window.caderactDocumentSession.layoutGateway.setPageSetup(layout.id,{...layout.paper,plot:{...layout.paper.plot,colorMode:'monochrome'}})})()`);assert.deepEqual(b.read('modelReader.records()'),before)});

test('PS4 plot scene supports multiple viewports and excludes UI overlays',async()=>{const b=await browser();setup(b);b.run(`window.caderactDocumentSession.layoutGateway.createViewport(window.__layoutId,{frame:{x:50,y:50,width:100,height:80},viewCenter:{x:50,y:0},scale:5,locked:false})`);const output=scene(b);assert.equal(new Set(output.segments.map(item=>item.viewportId)).size,3);for(const key of ['grid','crosshair','selection','snap','tracking','dynamicInput'])assert.equal(Object.hasOwn(output,key),false)});

test('PS4 native persistence round trips plot configuration and migrates PS3 defaults',async()=>{const b=await browser();b.run(`(()=>{const layout=modelReader.layouts()[0];window.caderactDocumentSession.layoutGateway.setPageSetup(layout.id,{...layout.paper,plot:{area:'layout',scale:1,placement:'offset',offset:{x:7,y:-2},colorMode:'monochrome'}});window.__file=window.CaderactPersistence.serializeDocument(modelReader.snapshot())})()`);assert.deepEqual(b.read('window.CaderactPersistence.loadStore(window.__file).reader.layouts()[0].paper.plot'),{area:'layout',scale:1,placement:'offset',offset:{x:7,y:-2},colorMode:'monochrome'});const old=JSON.parse(b.run('window.__file'));delete old.document.layouts[0].paper.plot;b.window.__old=JSON.stringify(old);assert.deepEqual(b.read('window.CaderactPersistence.loadStore(window.__old).reader.layouts()[0].paper.plot'),{area:'layout',scale:1,placement:'centered',offset:{x:0,y:0},colorMode:'color'})});

test('PS4 malformed plot configuration rejects without damaging active data',async()=>{const b=await browser();setup(b);const before=b.read('modelReader.snapshot()'),bad=JSON.parse(b.run('window.CaderactPersistence.serializeDocument(modelReader.snapshot())'));bad.document.layouts[0].paper.plot.colorMode='sepia';b.window.__bad=JSON.stringify(bad);assert.throws(()=>b.run('window.CaderactPersistence.loadStore(window.__bad)'));assert.deepEqual(b.read('modelReader.snapshot()'),before)});

test('PS4 Page Setup UI exposes Paper Margins and Plot sections and DXF stays Model-only',()=>{const fs=require('node:fs'),path=require('node:path'),root=path.resolve(__dirname,'../..'),ui=fs.readFileSync(path.join(root,'src/js/editor/layout-tabs.js'),'utf8'),dxf=fs.readFileSync(path.join(root,'src/js/io/dxf/DxfExport.js'),'utf8');for(const label of ['Paper','Margins / printable area','Plot / Output','Grayscale','Monochrome'])assert.match(ui,new RegExp(label));assert.doesNotMatch(dxf,/CaderactPlotScene|paper\.plot|layoutViewport/)});
