'use strict';
const {test}=require('node:test');
const assert=require('node:assert/strict');
const fs=require('node:fs');
const {browser}=require('../helpers/browser.cjs');

function setup(b){b.run(`(()=>{const layout=modelReader.layouts()[0];recordGateway.createAll([recordGateway.createLine({x:-1000,y:0},{x:1000,y:0})]);window.caderactDocumentSession.layoutGateway.createViewport(layout.id,{frame:{x:0,y:0,width:297,height:210},viewCenter:{x:0,y:0},scale:10,locked:true});window.__layoutId=layout.id})()`)}
const scene=(b,job='window.CaderactPlotJob.defaults()')=>b.read(`window.CaderactPlotScene.create({layout:modelReader.layout(window.__layoutId),job:${job},records:modelReader.visibleRecords(),layers:modelReader.layers(),documentUnit:modelReader.units().length})`);

test('PLOT1 defaults are immutable ephemeral vector Layout output',async()=>{const b=await browser(),job=b.read('window.CaderactPlotJob.defaults()');assert.deepEqual(job,{destination:'pdf',outputType:'vector',colorMode:'plot-color',area:'layout',scale:{mode:'one-to-one',paper:1,model:1},position:'center',offset:{x:0,y:0}});assert.equal(b.read("Object.hasOwn(modelReader.layouts()[0].paper,'plot')"),false)});

test('PLOT1 validates supported job choices and truthfully rejects deferred output',async()=>{const b=await browser();for(const patch of [{outputType:'raster'},{area:'extents'},{scale:{mode:'fit',paper:1,model:1}},{destination:'printer'}]){b.window.__job={...b.window.CaderactPlotJob.defaults(),...patch};assert.equal(b.read('window.CaderactPlotJob.normalize(window.__job).status'),'invalid-plot-job')}for(const colorMode of ['plot-color','display-color','grayscale','monochrome']){b.window.__job={...b.window.CaderactPlotJob.defaults(),colorMode};assert.equal(b.read('window.CaderactPlotJob.normalize(window.__job).status'),'ready')}});

test('PLOT1 PlotJob never mutates Page Setup history revision or dirty state',async()=>{const b=await browser(),before=b.read('({paper:modelReader.layouts()[0].paper,revision:documentController.currentRevision,history:documentController.historyInfo.entryCount,dirty:documentController.isDirty})');b.run(`window.__job=window.CaderactPlotJob.normalize({...window.CaderactPlotJob.defaults(),colorMode:'monochrome',position:'offset',offset:{x:3,y:4}}).job`);assert.deepEqual(b.read('({paper:modelReader.layouts()[0].paper,revision:documentController.currentRevision,history:documentController.historyInfo.entryCount,dirty:documentController.isDirty})'),before)});

test('PLOT1 Page Setup live preview accepts a draft sheet without publishing it',async()=>{const b=await browser(),before=b.read('({paper:modelReader.layouts()[0].paper,revision:documentController.currentRevision,history:documentController.historyInfo.entryCount,dirty:documentController.isDirty})');b.run(`(()=>{const layout=modelReader.layouts()[0];window.caderactLayoutContext.switchToLayout(layout.id);window.__draftLayout={...layout,paper:{...layout.paper,size:'Custom',width:420,height:210}};window.__draftPreview=window.CaderactPlotOutput.prepare(window.CaderactPlotJob.defaults(),{layout:window.__draftLayout})})()`);assert.equal(b.read('window.__draftPreview.status'),'ready');assert.deepEqual(b.read('[window.__draftPreview.scene.page.width,window.__draftPreview.scene.page.height]'),[420,210]);assert.deepEqual(b.read('({paper:modelReader.layouts()[0].paper,revision:documentController.currentRevision,history:documentController.historyInfo.entryCount,dirty:documentController.isDirty})'),before)});

test('PLOT1 plot scene applies viewport scale offset and printable clipping in millimetres',async()=>{const b=await browser();setup(b);const output=scene(b,"({...window.CaderactPlotJob.defaults(),position:'offset',offset:{x:2,y:3}})");assert.equal(output.unit,'mm');assert.equal(output.plot.scale,1);assert.deepEqual(output.plot.offset,{x:2,y:3});assert.ok(output.segments.length);for(const line of output.segments)for(const point of [line.start,line.end]){assert.ok(point.x>=output.printable.x-1e-9&&point.x<=output.printable.x+output.printable.width+1e-9);assert.ok(point.y>=output.printable.y-1e-9&&point.y<=output.printable.y+output.printable.height+1e-9)}});

test('PLOT1 color modes are deterministic and source colors stay unchanged',async()=>{const b=await browser();setup(b);const before=b.read('modelReader.records()');for(const [mode,expected] of [['plot-color','#e8edf4'],['display-color','#e8edf4'],['grayscale','#ececec'],['monochrome','#000000']]){const output=scene(b,`({...window.CaderactPlotJob.defaults(),colorMode:'${mode}'})`);assert.equal(output.segments[0].color,expected)}assert.deepEqual(b.read('modelReader.records()'),before)});

test('PLOT1 plot scene supports multiple viewports and excludes UI overlays',async()=>{const b=await browser();setup(b);b.run(`window.caderactDocumentSession.layoutGateway.createViewport(window.__layoutId,{frame:{x:50,y:50,width:100,height:80},viewCenter:{x:50,y:0},scale:5,locked:false})`);const output=scene(b);assert.equal(new Set(output.segments.map(item=>item.viewportId)).size,3);for(const key of ['grid','crosshair','selection','snap','tracking','dynamicInput'])assert.equal(Object.hasOwn(output,key),false)});

test('PLOT1 native output drops legacy paper.plot while loading it safely',async()=>{const b=await browser(),serialized=JSON.parse(b.run('window.CaderactPersistence.serializeDocument(modelReader.snapshot())'));assert.equal(serialized.document.layouts[0].paper.plot,undefined);serialized.document.layouts[0].paper.plot={area:'layout',scale:1,placement:'offset',offset:{x:7,y:-2},colorMode:'monochrome'};b.window.__legacy=JSON.stringify(serialized);const loaded=b.read('window.CaderactPersistence.loadStore(window.__legacy).reader.layouts()[0].paper');assert.equal(loaded.plot,undefined);assert.equal(loaded.width,297)});

test('PLOT1 unified Page Setup UI keeps persistent paper and ephemeral PlotJob authorities separate',()=>{const page=fs.readFileSync('src/js/editor/layout-tabs.js','utf8'),plot=fs.readFileSync('src/js/editor/plot-preview.js','utf8'),output=fs.readFileSync('src/js/editor/plot-output.js','utf8'),pdf=fs.readFileSync('src/js/editor/pdf-export.js','utf8');for(const label of ['Destination','Paper','Paper units','Margins and Position','Output Type','Output Color','View and Output Area','Scale','Linetypes and Lineweights','Visibility and Output Options'])assert.match(page,new RegExp(label));assert.match(page,/Raster — PLOT2",true/);assert.match(page,/Extents — PLOT2",true/);assert.match(page,/readSetupJob/);assert.match(page,/CaderactPlotOutput\?\.prepare\?\.\(job,\{layout:/);assert.match(page,/session\.layoutGateway\.setPageSetup\(setupLayoutId,paper\)/);assert.doesNotMatch(page,/setPageSetup\([^)]*job/);assert.match(plot,/renderSceneToCanvas/);assert.match(output,/options\.layout\|\|session\.reader\.layout/);assert.match(pdf,/CaderactPlotOutput/);assert.doesNotMatch(pdf,/caderactPlotPreview/)});
