const test=require('node:test');const assert=require('node:assert/strict');const{browser}=require('../helpers/browser.cjs');
function line(b,a={x:0,y:0},z={x:2,y:1}){b.window.__a=a;b.window.__z=z;b.run('recordGateway.createAll([recordGateway.createLine(window.__a,window.__z)])')}
async function fixture(){const b=await browser();b.run(`window.__storage=window.CaderactRecoveryStorage.createMemoryStorage();window.__fileState=window.CaderactDocumentFileState.create();window.__autosave=window.CaderactRecoveryStorage.createAutosave({session:window.caderactDocumentSession,fileState:window.__fileState,storage:window.__storage});window.__autosave.start();window.__validator=window.CaderactRecoveryValidation.create({storage:window.__storage})`);line(b);await b.run('window.__autosave.flush()');b.window.__record=(await b.run('window.__storage.get(window.__autosave.recoveryKey)')).record;return b}
async function altered(b,patch){b.window.__patch=patch;return b.run('window.__validator.classify({...window.__record,...window.__patch})')}

test('FS3 valid envelope verifies exact fingerprint and prepares an isolated newer candidate',async()=>{const b=await fixture(),before=b.read('({document:modelReader.snapshot(),state:documentController.currentStateId,history:documentController.historyInfo,file:window.__fileState.value,key:window.__autosave.recoveryKey})'),candidate=await b.run('window.__validator.classify(window.__record)');assert.equal(candidate.classification,'valid-newer');assert.match(candidate.payloadFingerprint,/^[0-9a-f]{64}$/);assert.equal(candidate.summary.objectCount,1);assert.notStrictEqual(candidate.document,b.read('modelReader.snapshot()'));assert.deepEqual(b.read('({document:modelReader.snapshot(),state:documentController.currentStateId,history:documentController.historyInfo,file:window.__fileState.value,key:window.__autosave.recoveryKey})'),before)});

test('FS3 strictly distinguishes malformed and future recovery envelopes',async()=>{const b=await fixture();for(const [patch,classification,reason]of [[{recoveryRecordVersion:2},'incompatible-version','unsupported-recovery-version'],[{recoveryKey:'bad'},'corrupt-envelope','invalid-recovery-key'],[{sequence:0},'corrupt-envelope','invalid-sequence'],[{timestamp:Infinity},'corrupt-envelope','invalid-timestamp'],[{filename:''},'corrupt-envelope','invalid-file-metadata'],[{payloadFingerprint:'no'},'corrupt-envelope','invalid-fingerprint']]){const result=await altered(b,patch);assert.equal(result.classification,classification);assert.equal(result.reason,reason)}});

test('FS3 enforces payload limits and fingerprint trust before native parsing',async()=>{const b=await fixture();b.run('window.__small=window.CaderactRecoveryValidation.create({storage:window.__storage,maxPayloadBytes:1})');assert.equal((await b.run('window.__small.classify(window.__record)')).classification,'excessive-resource-rejected');assert.equal((await altered(b,{payloadFingerprint:'0'.repeat(64)})).classification,'fingerprint-mismatch');const payload='{';b.window.__badPayload=payload;b.window.__badHash=await b.run('window.CaderactDocumentFileState.fingerprint(window.__badPayload)');assert.equal((await b.run('window.__validator.classify({...window.__record,payload:window.__badPayload,payloadFingerprint:window.__badHash})')).classification,'invalid-document')});

test('FS3 separates unsupported native versions from native validation failures',async()=>{const b=await fixture();for(const [payload,expected]of [[JSON.stringify({fileVersion:999}),'incompatible-version'],[JSON.stringify({fileVersion:3,id:'bad'}),'invalid-document']]){b.window.__payload=payload;b.window.__hash=await b.run('window.CaderactDocumentFileState.fingerprint(window.__payload)');const result=await b.run('window.__validator.classify({...window.__record,payload:window.__payload,payloadFingerprint:window.__hash,nativePersistenceVersion:3})');assert.equal(result.classification,expected)}});

test('FS3 equivalent stale newer and unresolved classifications require semantic evidence',async()=>{const b=await fixture(),fp=b.read('window.__record.payloadFingerprint'),revision=b.read('window.__record.revision'),key=b.read('window.__record.recoveryKey');b.window.__contexts=[{manualSaveFingerprint:fp},{manualSaveFingerprint:'1'.repeat(64),currentRecoveryKey:key,lastSuccessfulSave:{durability:'committed',revision}},{manualSaveFingerprint:'1'.repeat(64)},{manualSaveFingerprint:null}];const expected=['valid-equivalent','valid-stale','valid-newer','valid-newer'];for(let i=0;i<expected.length;i++)assert.equal((await b.run(`window.__validator.classify(window.__record,window.__contexts[${i}])`)).classification,expected[i]);assert.equal((await altered(b,{dirty:false,manualSaveFingerprint:null})).classification,'valid-unresolved')});

test('FS3 valid native Groups Blocks Text Dimensions Region and Hatch remain accepted semantically',async()=>{const b=await fixture();const original=b.read('window.__record');assert.equal((await b.run('window.__validator.classify(window.__record)')).classification,'valid-newer');const serialized=b.run('window.CaderactPersistence.serializeDocument(modelReader.snapshot())');assert.equal(JSON.parse(serialized).fileVersion,3);assert.equal(original.payload.includes('recoveryRecordVersion'),false)});

test('FS3 explicit apply replaces atomically, resets history, stays dirty, clears handle, and rotates autosave',async()=>{const b=await fixture(),candidate=await b.run('window.__validator.classify(window.__record)'),oldKey=b.read('window.__autosave.recoveryKey');line(b,{x:9,y:9},{x:10,y:10});b.window.__candidate=candidate;const result=await b.run('window.__validator.apply(window.__candidate,{session:window.caderactDocumentSession,fileState:window.__fileState,autosave:window.__autosave,commandRouter:window.caderactCommandRouter,viewport:window.caderactViewport})');assert.equal(result.status,'recovery-applied');assert.equal(b.read('modelReader.records().length'),1);assert.equal(b.read('documentController.isDirty'),true);assert.deepEqual(b.read('documentController.historyInfo'),{entryCount:0,cursor:0});assert.notEqual(b.read('window.__autosave.recoveryKey'),oldKey);assert.equal(b.read('window.__fileState.value.fileHandle'),null);assert.equal(b.read('window.__autosave.hasPendingAutosave'),true);assert.ok((await b.run('window.__storage.get(window.__record.recoveryKey)')).record)});

test('FS3 rejects forged candidates and active-command application without mutation',async()=>{const b=await fixture(),candidate=await b.run('window.__validator.classify(window.__record)');b.window.__candidate=candidate;for(const setup of ['window.__attempt={...window.__candidate}','window.caderactCommandRouter.execute("Line");window.__attempt=window.__candidate']){b.run(setup);const before=b.read('({document:modelReader.snapshot(),state:documentController.currentStateId,file:window.__fileState.value,key:window.__autosave.recoveryKey})'),result=await b.run('window.__validator.apply(window.__attempt,{session:window.caderactDocumentSession,fileState:window.__fileState,autosave:window.__autosave,commandRouter:window.caderactCommandRouter,viewport:window.caderactViewport})');assert.match(result.status,/recovery-apply-(failed|blocked)/);assert.deepEqual(b.read('({document:modelReader.snapshot(),state:documentController.currentStateId,file:window.__fileState.value,key:window.__autosave.recoveryKey})'),before);b.key('Escape')}});

test('FS3 classification lists independently in deterministic order and retains bad records',async()=>{const b=await fixture();const valid=b.read('window.__record');b.window.__older={...valid,recoveryKey:'recovery_'+'1'.repeat(32),sequence:3,timestamp:valid.timestamp-1};b.window.__bad={...valid,recoveryKey:'recovery_'+'2'.repeat(32),sequence:4,timestamp:valid.timestamp+1,payloadFingerprint:'0'.repeat(64)};await b.run('window.__storage.put(window.__older)');await b.run('window.__storage.put(window.__bad)');const listed=await b.run('window.__validator.classifyAll()');assert.equal(listed.status,'recovery-list-classified');assert.equal(listed.candidates.length,3);assert.equal(listed.candidates[0].recoveryKey,b.read('window.__bad.recoveryKey'));assert.equal(listed.candidates[0].classification,'fingerprint-mismatch');assert.equal((await b.run('window.__storage.list()')).records.length,3)});

test('FS3 storage failures and explicit dismissal are isolated',async()=>{const b=await fixture(),key=b.read('window.__record.recoveryKey');assert.equal((await b.run('window.__validator.dismiss(window.__record.recoveryKey)')).status,'recovery-deleted');assert.equal((await b.run('window.__storage.get(window.__record.recoveryKey)')).record,null);b.run(`window.__failing=window.CaderactRecoveryValidation.create({storage:{list:async()=>({status:'storage-failed',reason:'read-failure'}),delete:async()=>{throw new Error('delete')}}})`);const listed=await b.run('window.__failing.classifyAll()'),deleted=await b.run(`window.__failing.dismiss(${JSON.stringify(key)})`);assert.equal(listed.status,'recovery-list-failed');assert.equal(deleted.status,'recovery-delete-failed');assert.equal(b.read('documentController.isDirty'),true)});
