// PDF2: deterministic vector PDF serialization of CaderactPlotScene.
(() => {
  const PT_PER_MM=72/25.4
  const number=value=>{if(!Number.isFinite(value))throw new Error("PDF coordinate must be finite");const normalized=Math.abs(value)<1e-10?0:value;return Number(normalized.toFixed(5)).toString()}
  const rgb=value=>{const match=/^#([0-9a-f]{6})$/i.exec(value||"");if(!match)return[0,0,0];const n=parseInt(match[1],16);return[n>>16,(n>>8)&255,n&255].map(channel=>number(channel/255))}
  function pdfText(value,warnings){let output="";for(const character of String(value)){const code=character.codePointAt(0);if(code<32&&character!=="\t")continue;if(code>255){output+="?";warnings.add("Some Unicode characters were replaced because the built-in PDF font cannot encode them.");continue}output+=character==="\\"?"\\\\":character==="("?"\\(":character===")"?"\\)":code>=127?`\\${code.toString(8).padStart(3,"0")}`:character}return output}
  function ellipseCommands(curve){const commands=[],point=t=>({x:curve.center.x+Math.cos(t)*curve.majorRadius*Math.cos(curve.rotation)-Math.sin(t)*curve.minorRadius*Math.sin(curve.rotation),y:curve.center.y+Math.cos(t)*curve.majorRadius*Math.sin(curve.rotation)+Math.sin(t)*curve.minorRadius*Math.cos(curve.rotation)}),derivative=t=>({x:-Math.sin(t)*curve.majorRadius*Math.cos(curve.rotation)-Math.cos(t)*curve.minorRadius*Math.sin(curve.rotation),y:-Math.sin(t)*curve.majorRadius*Math.sin(curve.rotation)+Math.cos(t)*curve.minorRadius*Math.cos(curve.rotation)}),parts=Math.max(1,Math.ceil(Math.abs(curve.sweep)/(Math.PI/2))),step=curve.sweep/parts,start=point(curve.startAngle);commands.push(`${number(start.x*PT_PER_MM)} ${number(start.y*PT_PER_MM)} m`);for(let index=0;index<parts;index++){const a=curve.startAngle+step*index,b=a+step,k=4/3*Math.tan(step/4),p0=point(a),p3=point(b),d0=derivative(a),d1=derivative(b),p1={x:p0.x+k*d0.x,y:p0.y+k*d0.y},p2={x:p3.x-k*d1.x,y:p3.y-k*d1.y};commands.push(`${number(p1.x*PT_PER_MM)} ${number(p1.y*PT_PER_MM)} ${number(p2.x*PT_PER_MM)} ${number(p2.y*PT_PER_MM)} ${number(p3.x*PT_PER_MM)} ${number(p3.y*PT_PER_MM)} c`)}commands.push("S");return commands}
  function content(scene,warnings){const commands=["q","1 J","1 j"];for(const fill of scene.fills||[]){const [r,g,b]=rgb(fill.color),points=fill.points||[];if(points.length<3)continue;commands.push(`${r} ${g} ${b} rg`,`${number(points[0].x*PT_PER_MM)} ${number(points[0].y*PT_PER_MM)} m`);for(let index=1;index<points.length;index++)commands.push(`${number(points[index].x*PT_PER_MM)} ${number(points[index].y*PT_PER_MM)} l`);commands.push("h f")}let stroke=null,width=null,dash=null;const style=value=>{if(value.color!==stroke){stroke=value.color;const [r,g,b]=rgb(stroke);commands.push(`${r} ${g} ${b} RG`)}const nextWidth=Math.max(.01,Number(value.lineweight)||.25);if(nextWidth!==width){width=nextWidth;commands.push(`${number(width*PT_PER_MM)} w`)}const nextDash=JSON.stringify(value.dashPattern||[]);if(nextDash!==dash){dash=nextDash;commands.push(`[${(value.dashPattern||[]).map(item=>number(item*PT_PER_MM)).join(" ")}] 0 d`)}};for(const curve of scene.curves||[]){style(curve);commands.push(...ellipseCommands(curve))}for(const line of scene.segments){style(line);commands.push(`${number(line.start.x*PT_PER_MM)} ${number(line.start.y*PT_PER_MM)} m ${number(line.end.x*PT_PER_MM)} ${number(line.end.y*PT_PER_MM)} l S`)}for(const text of scene.texts||[]){const [r,g,b]=rgb(text.color),angle=Number(text.rotation)||0,c=Math.cos(angle),s=Math.sin(angle),size=Math.max(.1,text.height*PT_PER_MM),escaped=pdfText(text.value,warnings),advance=String(text.value).length*size*.5,shift=text.alignment==="right"?-advance:text.alignment==="center"?-advance/2:0;commands.push("BT",`${r} ${g} ${b} rg`,`/F1 ${number(size)} Tf`,`${number(c)} ${number(s)} ${number(-s)} ${number(c)} ${number(text.point.x*PT_PER_MM)} ${number(text.point.y*PT_PER_MM)} Tm`,`${number(shift)} 0 Td`,`(${escaped}) Tj`,"ET")}commands.push("Q");return commands.join("\n")+"\n"}
  function serialize(scene){if(!scene||scene.unit!=="mm"||!Number.isFinite(scene.page?.width)||!Number.isFinite(scene.page?.height)||scene.page.width<=0||scene.page.height<=0||!Array.isArray(scene.segments)||!Array.isArray(scene.texts)||(scene.curves!==undefined&&!Array.isArray(scene.curves))||(scene.fills!==undefined&&!Array.isArray(scene.fills)))throw new Error("Invalid Caderact plot scene");const warnings=new Set(),stream=content(scene,warnings),width=number(scene.page.width*PT_PER_MM),height=number(scene.page.height*PT_PER_MM),objects=[null,"<< /Type /Catalog /Pages 2 0 R >>","<< /Type /Pages /Kids [3 0 R] /Count 1 >>",`<< /Type /Page /Parent 2 0 R /MediaBox [0 0 ${width} ${height}] /Resources << /Font << /F1 5 0 R >> >> /Contents 4 0 R >>`,`<< /Length ${stream.length} >>\nstream\n${stream}endstream`,`<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica /Encoding /WinAnsiEncoding >>`],parts=["%PDF-1.4\n% Caderact vector plot\n"],offsets=[0];for(let index=1;index<objects.length;index++){offsets[index]=parts.join("").length;parts.push(`${index} 0 obj\n${objects[index]}\nendobj\n`)}const xref=parts.join("").length;parts.push(`xref\n0 ${objects.length}\n0000000000 65535 f \n`);for(let index=1;index<objects.length;index++)parts.push(`${String(offsets[index]).padStart(10,"0")} 00000 n \n`);parts.push(`trailer\n<< /Size ${objects.length} /Root 1 0 R >>\nstartxref\n${xref}\n%%EOF\n`);const text=parts.join(""),bytes=new TextEncoder().encode(text);return Object.freeze({bytes,mimeType:"application/pdf",warnings:Object.freeze(Array.from(warnings)),pagePoints:Object.freeze({width:Number(width),height:Number(height)}),primitiveCounts:Object.freeze({segments:scene.segments.length,curves:(scene.curves||[]).length,fills:(scene.fills||[]).length,texts:scene.texts.length})})}
  window.CaderactPdfSerializer=Object.freeze({PT_PER_MM,serialize})
})()
