// PDF2: deterministic vector PDF serialization of CaderactPlotScene.
(() => {
  const PT_PER_MM=72/25.4
  const number=value=>{if(!Number.isFinite(value))throw new Error("PDF coordinate must be finite");const normalized=Math.abs(value)<1e-10?0:value;return Number(normalized.toFixed(5)).toString()}
  const rgb=value=>{const match=/^#([0-9a-f]{6})$/i.exec(value||"");if(!match)return[0,0,0];const n=parseInt(match[1],16);return[n>>16,(n>>8)&255,n&255].map(channel=>number(channel/255))}
  function pdfText(value,warnings){let output="";for(const character of String(value)){const code=character.codePointAt(0);if(code<32&&character!=="\t")continue;if(code>255){output+="?";warnings.add("Some Unicode characters were replaced because the built-in PDF font cannot encode them.");continue}output+=character==="\\"?"\\\\":character==="("?"\\(":character===")"?"\\)":code>=127?`\\${code.toString(8).padStart(3,"0")}`:character}return output}
  function content(scene,warnings){const commands=["q","1 J","1 j"];let stroke=null;for(const line of scene.segments){if(line.color!==stroke){stroke=line.color;const [r,g,b]=rgb(stroke);commands.push(`${r} ${g} ${b} RG`)}commands.push(`${number(line.start.x*PT_PER_MM)} ${number(line.start.y*PT_PER_MM)} m ${number(line.end.x*PT_PER_MM)} ${number(line.end.y*PT_PER_MM)} l S`)}for(const text of scene.texts||[]){const [r,g,b]=rgb(text.color),angle=Number(text.rotation)||0,c=Math.cos(angle),s=Math.sin(angle),size=Math.max(.1,text.height*PT_PER_MM),escaped=pdfText(text.value,warnings),advance=String(text.value).length*size*.5,shift=text.alignment==="right"?-advance:text.alignment==="center"?-advance/2:0;commands.push("BT",`${r} ${g} ${b} rg`,`/F1 ${number(size)} Tf`,`${number(c)} ${number(s)} ${number(-s)} ${number(c)} ${number(text.point.x*PT_PER_MM)} ${number(text.point.y*PT_PER_MM)} Tm`,`${number(shift)} 0 Td`,`(${escaped}) Tj`,"ET")}commands.push("Q");return commands.join("\n")+"\n"}
  function serialize(scene){if(!scene||scene.unit!=="mm"||!Number.isFinite(scene.page?.width)||!Number.isFinite(scene.page?.height)||scene.page.width<=0||scene.page.height<=0||!Array.isArray(scene.segments)||!Array.isArray(scene.texts))throw new Error("Invalid Caderact plot scene");const warnings=new Set(),stream=content(scene,warnings),width=number(scene.page.width*PT_PER_MM),height=number(scene.page.height*PT_PER_MM),objects=[null,"<< /Type /Catalog /Pages 2 0 R >>","<< /Type /Pages /Kids [3 0 R] /Count 1 >>",`<< /Type /Page /Parent 2 0 R /MediaBox [0 0 ${width} ${height}] /Resources << /Font << /F1 5 0 R >> >> /Contents 4 0 R >>`,`<< /Length ${stream.length} >>\nstream\n${stream}endstream`,`<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica /Encoding /WinAnsiEncoding >>`],parts=["%PDF-1.4\n% Caderact vector plot\n"],offsets=[0];for(let index=1;index<objects.length;index++){offsets[index]=parts.join("").length;parts.push(`${index} 0 obj\n${objects[index]}\nendobj\n`)}const xref=parts.join("").length;parts.push(`xref\n0 ${objects.length}\n0000000000 65535 f \n`);for(let index=1;index<objects.length;index++)parts.push(`${String(offsets[index]).padStart(10,"0")} 00000 n \n`);parts.push(`trailer\n<< /Size ${objects.length} /Root 1 0 R >>\nstartxref\n${xref}\n%%EOF\n`);const text=parts.join(""),bytes=new TextEncoder().encode(text);return Object.freeze({bytes,mimeType:"application/pdf",warnings:Object.freeze(Array.from(warnings)),pagePoints:Object.freeze({width:Number(width),height:Number(height)}),primitiveCounts:Object.freeze({segments:scene.segments.length,texts:scene.texts.length})})}
  window.CaderactPdfSerializer=Object.freeze({PT_PER_MM,serialize})
})()
