// D8: pure semantic geometry for single-line Text annotations.
(() => {
  const MAX_TEXT_LENGTH=256
  const ALIGNMENTS=Object.freeze(["left","center","right"])
  function normalizeRotation(value){if(!Number.isFinite(value))return NaN;const turn=Math.PI*2;return((value%turn)+turn)%turn}
  function validate(record){const errors=[];if(typeof record?.text!=="string"||record.text.length>MAX_TEXT_LENGTH||!/\S/u.test(record.text)||/[\u0000-\u001f\u007f]/.test(record.text))errors.push("invalid-text");if(!Number.isFinite(record?.height)||record.height<=0)errors.push("invalid-height");if(!Number.isFinite(record?.rotation)||record.rotation<0||record.rotation>=Math.PI*2)errors.push("invalid-rotation");if(!ALIGNMENTS.includes(record?.horizontalAlignment))errors.push("invalid-alignment");if(!Number.isFinite(record?.insertionPoint?.x)||!Number.isFinite(record?.insertionPoint?.y)||typeof record?.insertionPoint?.featureId!=="string"||!record.insertionPoint.featureId)errors.push("invalid-insertion-point");return Object.freeze(errors)}
  function derive(record){const errors=validate(record);if(errors.length)return Object.freeze({supported:false,errors});return Object.freeze({supported:true,annotation:Object.freeze({ownerRecordId:record.id??null,role:"text",text:record.text,point:Object.freeze({x:record.insertionPoint.x,y:record.insertionPoint.y}),height:record.height,rotation:record.rotation,horizontalAlignment:record.horizontalAlignment}),grips:Object.freeze([Object.freeze({kind:"insertionPoint",featureId:record.insertionPoint.featureId,point:Object.freeze({x:record.insertionPoint.x,y:record.insertionPoint.y})})])})}
  function projectedCorners(record,worldToScreen){const presentation=derive(record);if(!presentation.supported)return Object.freeze([]);const anchor=worldToScreen(record.insertionPoint.x,record.insertionPoint.y),unit=worldToScreen(record.insertionPoint.x+1,record.insertionPoint.y),scale=Math.hypot(unit.x-anchor.x,unit.y-anchor.y),width=record.text.length*record.height*scale*.6,height=record.height*scale*1.1,x0=record.horizontalAlignment==="left"?0:record.horizontalAlignment==="center"?-width/2:-width,x1=x0+width,y0=-height/2,y1=height/2,angle=-record.rotation,c=Math.cos(angle),s=Math.sin(angle);return Object.freeze([[x0,y0],[x1,y0],[x1,y1],[x0,y1]].map(([x,y])=>Object.freeze({x:anchor.x+x*c-y*s,y:anchor.y+x*s+y*c})))}
  window.CaderactAnnotationGeometry=Object.freeze({MAX_TEXT_LENGTH,ALIGNMENTS,normalizeRotation,validate,derive,projectedCorners})
})()
