// R1: pure semantic boundary edges, loops, topology, splitting and nesting.
(() => {
  const TAU=Math.PI*2
  const LIMITS=Object.freeze({atomicCurves:10000,intersectionTests:250000,intersections:50000,nodes:50000,splitEdges:100000,loopEdges:10000,loops:1000,nestingDepth:32})
  const ok=value=>Object.freeze({valid:true,...value}),bad=(reason,detail={})=>Object.freeze({valid:false,reason,...detail})
  const point=value=>Object.freeze({x:value.x,y:value.y}),finitePoint=value=>Number.isFinite(value?.x)&&Number.isFinite(value?.y)
  const distance=(a,b)=>Math.hypot(a.x-b.x,a.y-b.y)
  const normalize=angle=>window.CaderactArcGeometry.normalizeAngle(angle)
  function collectPoints(value,result=[]){if(finitePoint(value))result.push(value);else if(Array.isArray(value))for(const child of value)collectPoints(child,result);else if(value&&typeof value==="object")for(const child of Object.values(value))collectPoints(child,result);return result}
  function toleranceFor(value,tolerance){return tolerance||window.CaderactBoundaryTolerance.create(collectPoints(value))}
  function arcStart(edge){return Math.atan2(edge.start.y-edge.center.y,edge.start.x-edge.center.x)}
  function evaluate(edge,parameter){if(edge.kind==="line")return point({x:edge.start.x+(edge.end.x-edge.start.x)*parameter,y:edge.start.y+(edge.end.y-edge.start.y)*parameter});if(edge.kind==="arc"){const angle=arcStart(edge)+edge.sweep*parameter;return point({x:edge.center.x+Math.cos(angle)*edge.radius,y:edge.center.y+Math.sin(angle)*edge.radius})}if(edge.kind==="circle")return point({x:edge.center.x+Math.cos(parameter)*edge.radius,y:edge.center.y+Math.sin(parameter)*edge.radius});if(edge.kind==="ellipse")return point(window.CaderactEllipseGeometry.pointAt({...edge,majorRadius:Math.hypot(edge.majorAxis.x,edge.majorAxis.y)},parameter));return point({x:NaN,y:NaN})}
  function tangent(edge,parameter){if(edge.kind==="line"){const dx=edge.end.x-edge.start.x,dy=edge.end.y-edge.start.y,length=Math.hypot(dx,dy);return point({x:dx/length,y:dy/length})}if(edge.kind==="arc"){const angle=arcStart(edge)+edge.sweep*parameter,sign=Math.sign(edge.sweep);return point({x:-Math.sin(angle)*sign,y:Math.cos(angle)*sign})}if(edge.kind==="circle")return point({x:-Math.sin(parameter),y:Math.cos(parameter)});if(edge.kind==="ellipse"){const a=Math.hypot(edge.majorAxis.x,edge.majorAxis.y),u={x:edge.majorAxis.x/a,y:edge.majorAxis.y/a},v={x:-u.y,y:u.x},dx=-a*Math.sin(parameter)*u.x+edge.minorRadius*Math.cos(parameter)*v.x,dy=-a*Math.sin(parameter)*u.y+edge.minorRadius*Math.cos(parameter)*v.y,length=Math.hypot(dx,dy);return point({x:dx/length,y:dy/length})}return point({x:NaN,y:NaN})}
  function adaptEdge(value){
    const described=window.CaderactCurveDescriptor.describe(value)
    if(!described.valid||described.kind==="polyline")return bad(described.reason||"unsupported-edge")
    if(described.kind==="line")return ok({edge:Object.freeze({kind:"line",start:point(described.start),end:point(described.end)})})
    if(described.kind==="arc"){const start=point({x:described.center.x+Math.cos(described.startAngle)*described.radius,y:described.center.y+Math.sin(described.startAngle)*described.radius}),end=point({x:described.center.x+Math.cos(described.startAngle+described.sweep)*described.radius,y:described.center.y+Math.sin(described.startAngle+described.sweep)*described.radius});return ok({edge:Object.freeze({kind:"arc",center:point(described.center),radius:described.radius,start,end,sweep:described.sweep})})}
    if(described.kind==="circle")return ok({edge:Object.freeze({kind:"circle",center:point(described.center),radius:described.radius})})
    return ok({edge:Object.freeze({kind:"ellipse",center:point(described.center),majorAxis:point(described.majorAxis),minorRadius:described.minorRadius})})
  }
  function adaptClosedPolyline(record){const described=window.CaderactCurveDescriptor.describe(record);if(!described.valid)return bad(described.reason);if(described.kind!=="polyline"||!described.closed)return bad("polyline-not-closed");return ok({edges:Object.freeze(described.segments.map(segment=>Object.freeze({kind:"line",start:point(segment.start),end:point(segment.end)})))})}
  function endpoints(edge){return edge.kind==="line"||edge.kind==="arc"?[edge.start,edge.end]:[]}
  function reverseEdge(edge){if(edge.kind==="line")return Object.freeze({...edge,start:edge.end,end:edge.start});if(edge.kind==="arc")return Object.freeze({...edge,start:edge.end,end:edge.start,sweep:-edge.sweep});if(edge.kind==="circle")return Object.freeze({...edge,clockwise:!edge.clockwise});if(edge.kind==="ellipse")return Object.freeze({...edge,clockwise:!edge.clockwise});throw new Error("Unsupported boundary edge")}
  function length(edge){if(edge.kind==="line")return distance(edge.start,edge.end);if(edge.kind==="arc")return Math.abs(edge.sweep)*edge.radius;if(edge.kind==="circle")return TAU*edge.radius;if(edge.kind==="ellipse"){const a=Math.hypot(edge.majorAxis.x,edge.majorAxis.y),b=edge.minorRadius,h=((a-b)/(a+b))**2;return Math.PI*(a+b)*(1+3*h/(10+Math.sqrt(4-3*h)))}return NaN}
  function areaContribution(edge){if(edge.kind==="line")return .5*(edge.start.x*edge.end.y-edge.end.x*edge.start.y);if(edge.kind==="arc"){const a=arcStart(edge),b=a+edge.sweep,r=edge.radius,c=edge.center;return .5*(r*c.x*(Math.sin(b)-Math.sin(a))-r*c.y*(Math.cos(b)-Math.cos(a))+r*r*edge.sweep)}if(edge.kind==="circle")return (edge.clockwise?-1:1)*Math.PI*edge.radius*edge.radius;if(edge.kind==="ellipse")return (edge.clockwise?-1:1)*Math.PI*Math.hypot(edge.majorAxis.x,edge.majorAxis.y)*edge.minorRadius;return NaN}
  function edgeBounds(edge){
    if(edge.kind==="line")return Object.freeze({minX:Math.min(edge.start.x,edge.end.x),minY:Math.min(edge.start.y,edge.end.y),maxX:Math.max(edge.start.x,edge.end.x),maxY:Math.max(edge.start.y,edge.end.y)})
    if(edge.kind==="circle")return Object.freeze({minX:edge.center.x-edge.radius,minY:edge.center.y-edge.radius,maxX:edge.center.x+edge.radius,maxY:edge.center.y+edge.radius})
    if(edge.kind==="ellipse"){const a=Math.hypot(edge.majorAxis.x,edge.majorAxis.y),xRadius=Math.hypot(edge.majorAxis.x,-edge.majorAxis.y/a*edge.minorRadius),yRadius=Math.hypot(edge.majorAxis.y,edge.majorAxis.x/a*edge.minorRadius);return Object.freeze({minX:edge.center.x-xRadius,minY:edge.center.y-yRadius,maxX:edge.center.x+xRadius,maxY:edge.center.y+yRadius})}
    const points=[edge.start,edge.end],start=arcStart(edge);for(const angle of [0,Math.PI/2,Math.PI,Math.PI*1.5])if(window.CaderactArcGeometry.angleOnSweep(angle,start,edge.sweep))points.push({x:edge.center.x+Math.cos(angle)*edge.radius,y:edge.center.y+Math.sin(angle)*edge.radius});return Object.freeze({minX:Math.min(...points.map(p=>p.x)),minY:Math.min(...points.map(p=>p.y)),maxX:Math.max(...points.map(p=>p.x)),maxY:Math.max(...points.map(p=>p.y))})
  }
  function descriptor(edge){if(edge.kind==="line")return window.CaderactCurveDescriptor.describeLine(edge.start,edge.end);if(edge.kind==="arc")return window.CaderactCurveDescriptor.describeArc(edge.center,edge.radius,edge.start,edge.sweep);if(edge.kind==="circle")return window.CaderactCurveDescriptor.describeCircle(edge.center,edge.radius);return window.CaderactCurveDescriptor.describeEllipse(edge.center,edge.majorAxis,edge.minorRadius)}
  function pointOnEdge(edge,p,tolerance){const curve=descriptor(edge),nearest=window.CaderactCurveParameter.nearestParameter(curve,p);return nearest.valid&&distance(nearest.point,p)<=tolerance.linear}
  function edgeFinite(edge){if(edge.kind==="line")return finitePoint(edge.start)&&finitePoint(edge.end);if(edge.kind==="arc")return finitePoint(edge.center)&&finitePoint(edge.start)&&finitePoint(edge.end)&&Number.isFinite(edge.radius)&&Number.isFinite(edge.sweep);if(edge.kind==="circle")return finitePoint(edge.center)&&Number.isFinite(edge.radius);if(edge.kind==="ellipse")return finitePoint(edge.center)&&finitePoint(edge.majorAxis)&&Number.isFinite(edge.minorRadius);return false}
  function lineOverlap(a,b,t){const cross=(p,q,r)=>(q.x-p.x)*(r.y-p.y)-(q.y-p.y)*(r.x-p.x),scale=Math.max(1,length(a),length(b));if(Math.abs(cross(a.start,a.end,b.start))>t.linear*scale||Math.abs(cross(a.start,a.end,b.end))>t.linear*scale)return false;const axis=Math.abs(a.end.x-a.start.x)>=Math.abs(a.end.y-a.start.y)?"x":"y",values=[a.start[axis],a.end[axis]].sort((x,y)=>x-y),other=[b.start[axis],b.end[axis]].sort((x,y)=>x-y);return Math.min(values[1],other[1])-Math.max(values[0],other[0])>t.linear}
  function intersections(edgeA,edgeB,tolerance,limit=LIMITS.intersections){const t=toleranceFor([edgeA,edgeB],tolerance);if(edgeA.kind==="ellipse"||edgeB.kind==="ellipse")return bad("ellipse-intersection-unsupported");if(edgeA.kind==="line"&&edgeB.kind==="line"&&lineOverlap(edgeA,edgeB,t))return bad("overlapping-edges");const result=window.CaderactCurveIntersection.intersectAtomic(descriptor(edgeA),descriptor(edgeB));if(!result.valid)return bad(result.reason||"intersection-failed");const hits=[];for(const hit of result.hits){if(!hit.onA||!hit.onB)continue;if(hits.some(item=>distance(item.point,hit.point)<=t.linear))continue;if(hits.length>=limit)return bad("intersection-limit");hits.push(Object.freeze({point:point(hit.point),parameterA:hit.parameterA,parameterB:hit.parameterB}))}hits.sort((a,b)=>a.parameterA-b.parameterA||a.parameterB-b.parameterB||a.point.x-b.point.x||a.point.y-b.point.y);return ok({hits:Object.freeze(hits)})}
  function splitEdge(edge,parameters,tolerance,limit=LIMITS.splitEdges){if(!["line","arc"].includes(edge.kind))return bad("edge-not-splittable");const t=toleranceFor(edge,tolerance),values=[0,1,...parameters].filter(Number.isFinite).map(value=>Math.max(0,Math.min(1,value))).sort((a,b)=>a-b),unique=[];for(const value of values)if(!unique.length||Math.abs(value-unique.at(-1))>t.parameter)unique.push(value);if(unique.length-1>limit)return bad("split-edge-limit");const pieces=[];for(let i=1;i<unique.length;i++){const a=unique[i-1],b=unique[i];if(b-a<=t.parameter)continue;const start=evaluate(edge,a),end=evaluate(edge,b);pieces.push(edge.kind==="line"?Object.freeze({kind:"line",start,end}):Object.freeze({kind:"arc",center:edge.center,radius:edge.radius,start,end,sweep:edge.sweep*(b-a)}))}return ok({edges:Object.freeze(pieces)})}
  function clusterEndpoints(points,tolerance,limit=LIMITS.nodes){if(points.length>limit)return bad("node-limit");const t=toleranceFor(points,tolerance),ordered=points.map((value,index)=>({point:point(value),index})).sort((a,b)=>a.point.x-b.point.x||a.point.y-b.point.y||a.index-b.index),parent=ordered.map((_,i)=>i),buckets=new Map(),cell=t.linear
    const root=i=>{while(parent[i]!==i){parent[i]=parent[parent[i]];i=parent[i]}return i},join=(a,b)=>{a=root(a);b=root(b);if(a!==b)parent[Math.max(a,b)]=Math.min(a,b)}
    for(let i=0;i<ordered.length;i++){const p=ordered[i].point,gx=Math.floor(p.x/cell),gy=Math.floor(p.y/cell);for(let x=gx-1;x<=gx+1;x++)for(let y=gy-1;y<=gy+1;y++)for(const j of buckets.get(`${x}:${y}`)||[])if(distance(p,ordered[j].point)<=t.linear)join(i,j);const key=`${gx}:${gy}`,bucket=buckets.get(key)||[];bucket.push(i);buckets.set(key,bucket)}
    const groups=new Map();for(let i=0;i<ordered.length;i++){const r=root(i),group=groups.get(r)||[];group.push(ordered[i]);groups.set(r,group)}const clusters=Array.from(groups.values(),group=>{group.sort((a,b)=>a.point.x-b.point.x||a.point.y-b.point.y||a.index-b.index);return Object.freeze({representative:group[0].point,indices:Object.freeze(group.map(item=>item.index).sort((a,b)=>a-b))})}).sort((a,b)=>a.representative.x-b.representative.x||a.representative.y-b.representative.y);return ok({clusters:Object.freeze(clusters),tolerance:t})}
  function validateLoop(input,tolerance){const edges=Array.from(input||[]),t=toleranceFor(edges,tolerance);if(!edges.length)return bad("empty-loop");if(edges.length>LIMITS.loopEdges)return bad("loop-edge-limit");if(edges.length===1&&!['circle','ellipse'].includes(edges[0].kind))return bad("open-loop");if(edges.length>1&&edges.some(edge=>!['line','arc'].includes(edge.kind)))return bad("closed-edge-mixed-with-chain");for(const edge of edges){if(!Number.isFinite(length(edge))||length(edge)<=t.linear)return bad("degenerate-edge");if(collectPoints(edge).some(p=>!finitePoint(p)))return bad("non-finite-edge")}
    if(edges.some(edge=>!edgeFinite(edge)))return bad("non-finite-edge");if(edges.length>1)for(let i=0;i<edges.length;i++)if(!window.CaderactBoundaryTolerance.samePoint(edges[i].end,edges[(i+1)%edges.length].start,t))return bad("open-loop",{edgeIndex:i})
    let tests=0;for(let i=0;i<edges.length;i++)for(let j=i+1;j<edges.length;j++){if(++tests>LIMITS.intersectionTests)return bad("intersection-test-limit");const adjacent=j===i+1||(i===0&&j===edges.length-1),hit=intersections(edges[i],edges[j],t);if(!hit.valid)return hit;for(const item of hit.hits){const shared=adjacent&&endpoints(edges[i]).some(a=>endpoints(edges[j]).some(b=>window.CaderactBoundaryTolerance.samePoint(a,b,t)&&window.CaderactBoundaryTolerance.samePoint(a,item.point,t)));if(!shared)return bad(adjacent?"invalid-tangent-contact":"self-intersection")}}
    const signedArea=edges.reduce((sum,edge)=>sum+areaContribution(edge),0);if(!Number.isFinite(signedArea)||Math.abs(signedArea)<=t.area)return bad("degenerate-area");const bounds=edges.map(edgeBounds),loopBounds=Object.freeze({minX:Math.min(...bounds.map(b=>b.minX)),minY:Math.min(...bounds.map(b=>b.minY)),maxX:Math.max(...bounds.map(b=>b.maxX)),maxY:Math.max(...bounds.map(b=>b.maxY))});return ok({loop:Object.freeze({kind:"boundary-loop",edges:Object.freeze(edges),orientation:signedArea>0?"ccw":"cw",signedArea,area:Math.abs(signedArea),perimeter:edges.reduce((sum,edge)=>sum+length(edge),0),bounds:loopBounds}),tolerance:t})}
  function reverseLoop(loop){return Object.freeze({...loop,edges:Object.freeze([...loop.edges].reverse().map(reverseEdge)),orientation:loop.orientation==="ccw"?"cw":"ccw",signedArea:-loop.signedArea})}
  function canonicalizeLoop(input,{orientation="ccw",tolerance}={}){const validated=input?.kind==="boundary-loop"?ok({loop:input,tolerance:toleranceFor(input,tolerance)}):validateLoop(input,tolerance);if(!validated.valid)return validated;let loop=validated.loop;if(loop.orientation!==orientation)loop=reverseLoop(loop);if(loop.edges.length>1){const keys=loop.edges.map(edge=>`${edge.start.x},${edge.start.y},${edge.kind}`),minimum=keys.reduce((best,key,index)=>key<keys[best]?index:best,0),edges=[...loop.edges.slice(minimum),...loop.edges.slice(0,minimum)];loop=Object.freeze({...loop,edges:Object.freeze(edges)})}return ok({loop,tolerance:validated.tolerance})}
  function classifyPoint(loop,p,tolerance){if(!finitePoint(p))return bad("non-finite-point");const t=toleranceFor([loop,p],tolerance);for(const edge of loop.edges)if(pointOnEdge(edge,p,t))return ok({classification:"boundary"});if(loop.edges.length===1){const edge=loop.edges[0];if(edge.kind==="circle")return ok({classification:distance(p,edge.center)<edge.radius?"inside":"outside"});if(edge.kind==="ellipse"){const a=Math.hypot(edge.majorAxis.x,edge.majorAxis.y),u={x:edge.majorAxis.x/a,y:edge.majorAxis.y/a},v={x:-u.y,y:u.x},dx=p.x-edge.center.x,dy=p.y-edge.center.y,q=((dx*u.x+dy*u.y)/a)**2+((dx*v.x+dy*v.y)/edge.minorRadius)**2;return ok({classification:q<1?"inside":"outside"})}}
    let winding=0;for(const edge of loop.edges){if(edge.kind==="line"){const a=edge.start,b=edge.end,cross=(b.x-a.x)*(p.y-a.y)-(p.x-a.x)*(b.y-a.y);if(a.y<=p.y&&b.y>p.y&&cross>0)winding++;else if(a.y>p.y&&b.y<=p.y&&cross<0)winding--}else if(edge.kind==="arc"){const ratio=(p.y-edge.center.y)/edge.radius;if(Math.abs(ratio)>1)continue;for(const angle of [Math.asin(ratio),Math.PI-Math.asin(ratio)])if(window.CaderactArcGeometry.angleOnSweep(angle,arcStart(edge),edge.sweep)){const x=edge.center.x+Math.cos(angle)*edge.radius;if(x<=p.x+t.linear)continue;const direction=Math.cos(angle)*Math.sign(edge.sweep);if(Math.abs(direction)>t.parameter)winding+=direction>0?1:-1}}}return ok({classification:winding===0?"outside":"inside"})
  }
  function interiorPoint(loop,tolerance){if(loop.edges.length===1&&['circle','ellipse'].includes(loop.edges[0].kind))return loop.edges[0].center;const t=toleranceFor(loop,tolerance),center={x:(loop.bounds.minX+loop.bounds.maxX)/2,y:(loop.bounds.minY+loop.bounds.maxY)/2};if(classifyPoint(loop,center,t).classification==="inside")return center;for(const edge of loop.edges){const mid=evaluate(edge,.5),tan=tangent(edge,.5),sign=loop.orientation==="ccw"?1:-1,step=Math.max(t.linear*4,Math.min(loop.bounds.maxX-loop.bounds.minX,loop.bounds.maxY-loop.bounds.minY)*1e-6),candidate={x:mid.x-tan.y*sign*step,y:mid.y+tan.x*sign*step};if(classifyPoint(loop,candidate,t).classification==="inside")return candidate}return null}
  function classifyNesting(inputs,tolerance){if(inputs.length>LIMITS.loops)return bad("loop-limit");const t=toleranceFor(inputs,tolerance),loops=[];for(const input of inputs){const value=input?.kind==="boundary-loop"?validateLoop(input.edges,t):validateLoop(input,t);if(!value.valid)return value;loops.push(value.loop)}let tests=0;for(let i=0;i<loops.length;i++)for(let j=i+1;j<loops.length;j++)for(const a of loops[i].edges)for(const b of loops[j].edges){if(++tests>LIMITS.intersectionTests)return bad("intersection-test-limit");const hit=intersections(a,b,t);if(!hit.valid)return hit;if(hit.hits.length)return bad("touching-or-crossing-loops")}
    const parent=new Array(loops.length).fill(null);for(let i=0;i<loops.length;i++){const sample=interiorPoint(loops[i],t);if(!sample)return bad("interior-point-unavailable");const containers=[];for(let j=0;j<loops.length;j++)if(i!==j&&loops[j].area>loops[i].area&&classifyPoint(loops[j],sample,t).classification==="inside")containers.push(j);containers.sort((a,b)=>loops[a].area-loops[b].area||a-b);parent[i]=containers[0]??null}
    const depth=index=>{let value=0,current=parent[index],seen=new Set([index]);while(current!==null){if(seen.has(current))return Infinity;seen.add(current);value++;current=parent[current]}return value},entries=[];for(let i=0;i<loops.length;i++){const d=depth(i);if(d>LIMITS.nestingDepth)return bad("nesting-depth-limit");const canonical=canonicalizeLoop(loops[i],{orientation:d%2?"cw":"ccw",tolerance:t});entries.push({loop:canonical.loop,sourceIndex:i,parentSourceIndex:parent[i],depth:d,filled:d%2===0})}entries.sort((a,b)=>a.depth-b.depth||b.loop.area-a.loop.area||a.loop.bounds.minX-b.loop.bounds.minX||a.loop.bounds.minY-b.loop.bounds.minY);const positions=new Map(entries.map((entry,index)=>[entry.sourceIndex,index])),result=entries.map(entry=>Object.freeze({loop:entry.loop,parentIndex:entry.parentSourceIndex===null?null:positions.get(entry.parentSourceIndex),depth:entry.depth,filled:entry.filled}));return ok({entries:Object.freeze(result),tolerance:t})}
  window.CaderactBoundaryGeometry=Object.freeze({LIMITS,adaptEdge,adaptClosedPolyline,evaluate,tangent,reverseEdge,edgeBounds,edgeLength:length,edgeAreaContribution:areaContribution,intersections,splitEdge,clusterEndpoints,validateLoop,canonicalizeLoop,reverseLoop,classifyPoint,classifyNesting})
})()
