// ME1: pure model-space point measurement and presentation boundary.
(() => {
  const freezePoint=value=>Object.freeze({x:value.x,y:value.y})
  function pointToPoint(start,end){
    if(!Number.isFinite(start?.x)||!Number.isFinite(start?.y)||!Number.isFinite(end?.x)||!Number.isFinite(end?.y))throw new Error("Measurement points must be finite")
    const deltaX=end.x-start.x,deltaY=end.y-start.y,distance=Math.hypot(deltaX,deltaY)
    const raw=distance===0?null:Math.atan2(deltaY,deltaX),angleRadians=raw===null?null:(raw<0?raw+Math.PI*2:raw)
    return Object.freeze({start:freezePoint(start),end:freezePoint(end),deltaX,deltaY,distance,angleRadians,angleDegrees:angleRadians===null?null:angleRadians*180/Math.PI})
  }
  function format(result,unit,precision=3){const length=value=>window.CaderactUnits.format(value,unit,precision),angle=result.angleDegrees===null?"—":`${result.angleDegrees.toFixed(precision)}°`;return Object.freeze({distance:length(result.distance),deltaX:length(result.deltaX),deltaY:length(result.deltaY),angle,start:`${length(result.start.x)}, ${length(result.start.y)}`,end:`${length(result.end.x)}, ${length(result.end.y)}`,summary:`Distance = ${length(result.distance)}; ΔX = ${length(result.deltaX)}; ΔY = ${length(result.deltaY)}; Angle = ${angle}`})}
  function measureRecord(record){
    if(!record||typeof record!=="object")return null
    if(record.type==="line")return Object.freeze({type:"line",length:Math.hypot(record.end.x-record.start.x,record.end.y-record.start.y)})
    if(record.type==="circle"){const circumference=Math.PI*2*record.radius;return Object.freeze({type:"circle",radius:record.radius,diameter:record.radius*2,circumference,perimeter:circumference,area:Math.PI*record.radius*record.radius})}
    if(record.type==="arc"){const sweepRadians=record.sweep,sweepDegrees=sweepRadians*180/Math.PI;return Object.freeze({type:"arc",radius:record.radius,diameter:record.radius*2,sweepRadians,sweepDegrees,arcLength:Math.abs(sweepRadians)*record.radius})}
    if(record.type==="polyline"){let length=0;const count=record.closed?record.vertices.length:Math.max(0,record.vertices.length-1);for(let index=0;index<count;index++){const a=record.vertices[index],b=record.vertices[(index+1)%record.vertices.length];length+=Math.hypot(b.x-a.x,b.y-a.y)}const base={type:"polyline",length,vertexCount:record.vertices.length,closed:Boolean(record.closed)};if(!record.closed)return Object.freeze(base);const vertices=record.vertices.length>1&&samePoint(record.vertices[0],record.vertices.at(-1))?record.vertices.slice(0,-1):record.vertices,signedArea=shoelace(vertices),selfIntersecting=hasSelfIntersection(vertices);return Object.freeze({...base,perimeter:length,signedArea,selfIntersecting,...(!selfIntersecting?{area:Math.abs(signedArea)}:{})})}
    if(record.type==="ellipse"){const majorRadius=Math.hypot(record.majorAxis.x,record.majorAxis.y),minorRadius=record.minorRadius;return Object.freeze({type:"ellipse",majorRadius,minorRadius,majorDiameter:majorRadius*2,minorDiameter:minorRadius*2,area:Math.PI*majorRadius*minorRadius})}
    if(record.type==="region"||record.type==="hatch")return window.CaderactRegionGeometry.measure(record)
    return null
  }
  function samePoint(a,b){return a.x===b.x&&a.y===b.y}
  function shoelace(vertices){let twice=0;for(let i=0;i<vertices.length;i++){const a=vertices[i],b=vertices[(i+1)%vertices.length];twice+=a.x*b.y-b.x*a.y}return twice/2}
  function onSegment(a,b,p,tolerance){return p.x>=Math.min(a.x,b.x)-tolerance&&p.x<=Math.max(a.x,b.x)+tolerance&&p.y>=Math.min(a.y,b.y)-tolerance&&p.y<=Math.max(a.y,b.y)+tolerance}
  function segmentsIntersect(a,b,c,d){const scale=Math.max(1,Math.abs(a.x),Math.abs(a.y),Math.abs(b.x),Math.abs(b.y),Math.abs(c.x),Math.abs(c.y),Math.abs(d.x),Math.abs(d.y)),tolerance=(window.CaderactIntersectionClassifier?.LINEAR_TOLERANCE||1e-9)*scale,cross=(p,q,r)=>(q.x-p.x)*(r.y-p.y)-(q.y-p.y)*(r.x-p.x),o1=cross(a,b,c),o2=cross(a,b,d),o3=cross(c,d,a),o4=cross(c,d,b);if(((o1>tolerance&&o2< -tolerance)||(o1< -tolerance&&o2>tolerance))&&((o3>tolerance&&o4< -tolerance)||(o3< -tolerance&&o4>tolerance)))return true;return Math.abs(o1)<=tolerance&&onSegment(a,b,c,tolerance)||Math.abs(o2)<=tolerance&&onSegment(a,b,d,tolerance)||Math.abs(o3)<=tolerance&&onSegment(c,d,a,tolerance)||Math.abs(o4)<=tolerance&&onSegment(c,d,b,tolerance)}
  function hasSelfIntersection(vertices){const count=vertices.length;if(count<3)return false;for(let i=0;i<count;i++)for(let j=i+1;j<count;j++){if(j===i+1||(i===0&&j===count-1))continue;if(segmentsIntersect(vertices[i],vertices[(i+1)%count],vertices[j],vertices[(j+1)%count]))return true}return false}
  function measureIncludedAngle(p1,vertex,p2){const ax=p1.x-vertex.x,ay=p1.y-vertex.y,bx=p2.x-vertex.x,by=p2.y-vertex.y,al=Math.hypot(ax,ay),bl=Math.hypot(bx,by);if(!(al>0&&bl>0))return Object.freeze({valid:false,reason:"degenerate-ray"});const angleRadians=Math.acos(Math.max(-1,Math.min(1,(ax*bx+ay*by)/(al*bl))));return Object.freeze({valid:true,p1:freezePoint(p1),vertex:freezePoint(vertex),p2:freezePoint(p2),angleRadians,angleDegrees:angleRadians*180/Math.PI})}
  function pointToAtomic(sourcePoint,curve){if(curve.kind==="circle"&&samePoint(sourcePoint,curve.center))return Object.freeze({valid:true,distance:curve.radius,sourcePoint:freezePoint(sourcePoint),targetPoint:null,parameter:null});const nearest=window.CaderactCurveParameter.nearestParameter(curve,sourcePoint);if(!nearest.valid)return nearest;return Object.freeze({valid:true,distance:Math.hypot(nearest.point.x-sourcePoint.x,nearest.point.y-sourcePoint.y),sourcePoint:freezePoint(sourcePoint),targetPoint:nearest.point,parameter:nearest.parameter})}
  function measurePointToRecord(sourcePoint,record){const descriptor=window.CaderactCurveDescriptor.describe(record);if(!descriptor.valid||descriptor.kind==="ellipse")return Object.freeze({valid:false,reason:descriptor.kind==="ellipse"?"ellipse-distance-unsupported":descriptor.reason});if(descriptor.kind!=="polyline")return pointToAtomic(sourcePoint,descriptor);let best=null;for(const segment of descriptor.segments){const result=pointToAtomic(sourcePoint,segment),candidate=result.valid?{...result,segmentIndex:segment.segmentIndex}:null;if(candidate&&(!best||candidate.distance<best.distance))best=candidate}return best?Object.freeze(best):Object.freeze({valid:false,reason:"no-segments"})}
  function atomicEndpoints(curve){return curve.kind==="line"?[curve.start,curve.end]:curve.kind==="arc"?[window.CaderactCurveParameter.pointAt(curve,0),window.CaderactCurveParameter.pointAt(curve,1)]:[]}
  function pair(pointA,pointB){return Object.freeze({valid:true,distance:Math.hypot(pointB.x-pointA.x,pointB.y-pointA.y),pointA:freezePoint(pointA),pointB:freezePoint(pointB)})}
  function radialPoints(curve,toward){if(curve.kind!=="circle"&&curve.kind!=="arc")return[];const base=Math.atan2(toward.y-curve.center.y,toward.x-curve.center.x),angles=[base,base+Math.PI],points=[];for(const angle of angles){if(curve.kind==="arc"&&!window.CaderactArcGeometry.angleOnSweep(angle,curve.startAngle,curve.sweep))continue;points.push(window.CaderactCurveParameter.pointAt(curve,curve.kind==="arc"?window.CaderactCurveParameter.arcAngleToParameter(curve,window.CaderactArcGeometry.normalizeAngle(angle)):angle))}return points}
  function atomicDistance(a,b){const intersections=window.CaderactCurveIntersection.intersectAtomic(a,b);if(intersections.valid){const hits=intersections.hits.filter(hit=>hit.onA&&hit.onB).sort((x,y)=>x.point.x-y.point.x||x.point.y-y.point.y);if(hits.length)return Object.freeze({valid:true,distance:0,pointA:hits[0].point,pointB:hits[0].point})}const candidates=[];for(const p of atomicEndpoints(a)){const result=pointToAtomic(p,b);if(result.valid&&result.targetPoint)candidates.push(pair(p,result.targetPoint))}for(const p of atomicEndpoints(b)){const result=pointToAtomic(p,a);if(result.valid&&result.targetPoint)candidates.push(pair(result.targetPoint,p))}if((a.kind==="circle"||a.kind==="arc")&&(b.kind==="circle"||b.kind==="arc")){for(const pa of radialPoints(a,b.center))for(const pb of radialPoints(b,a.center))candidates.push(pair(pa,pb))}for(const [line,round,reversed] of [[a,b,false],[b,a,true]])if(line.kind==="line"&&(round.kind==="circle"||round.kind==="arc")){const centerProjection=pointToAtomic(round.center,line);if(centerProjection.valid&&centerProjection.targetPoint)for(const rp of radialPoints(round,centerProjection.targetPoint))candidates.push(reversed?pair(rp,centerProjection.targetPoint):pair(centerProjection.targetPoint,rp))}if(!candidates.length)return Object.freeze({valid:false,reason:"unsupported-pair"});candidates.sort((x,y)=>x.distance-y.distance||x.pointA.x-y.pointA.x||x.pointA.y-y.pointA.y);return candidates[0]}
  function measureRecordToRecord(recordA,recordB){const a=window.CaderactCurveDescriptor.atomicCurves(recordA),b=window.CaderactCurveDescriptor.atomicCurves(recordB);if(!a.valid||!b.valid||a.curves.some(x=>x.kind==="ellipse")||b.curves.some(x=>x.kind==="ellipse"))return Object.freeze({valid:false,reason:"unsupported-pair"});let best=null;for(const curveA of a.curves)for(const curveB of b.curves){const result=atomicDistance(curveA,curveB);if(result.valid&&(!best||result.distance<best.distance))best=result;if(best?.distance===0)return best}return best||Object.freeze({valid:false,reason:"unsupported-pair"})}
  function measureCumulative(points){const accepted=Object.freeze(Array.from(points||[],freezePoint));let totalLength=0,segmentLength=0;for(let index=1;index<accepted.length;index++){segmentLength=Math.hypot(accepted[index].x-accepted[index-1].x,accepted[index].y-accepted[index-1].y);totalLength+=segmentLength}return Object.freeze({points:accepted,segmentLength,totalLength})}
  function formatObject(result,field,unit,precision=3){const value=result?.[field];if(!Number.isFinite(value))return null;const labels={length:result.type==="polyline"?"Polyline Length":"Length",circumference:"Length",arcLength:"Arc Length",radius:"Radius",diameter:"Diameter",perimeter:"Perimeter",area:"Area"},label=labels[field];if(!label)return null;const formatted=field==="area"?window.CaderactUnits.formatArea(value,unit,precision):window.CaderactUnits.format(value,unit,precision);let summary=`${label} = ${formatted}`;if(field==="area"&&Number.isFinite(result.perimeter))summary+=`; Perimeter = ${window.CaderactUnits.format(result.perimeter,unit,precision)}`;return Object.freeze({field,label,value,formatted,summary})}
  window.CaderactMeasurement=Object.freeze({pointToPoint,format,measureRecord,formatObject,measureIncludedAngle,measurePointToRecord,measureRecordToRecord,measureCumulative})
})()
