const test=require('node:test');const assert=require('node:assert/strict');const {browser}=require('../helpers/browser.cjs');
const near=(a,b)=>assert.ok(Math.abs(a-b)<1e-8,`${a} != ${b}`);const typed=(b,v)=>{b.input.value=v;b.key('Enter',b.input)};const state=b=>b.read('({revision:documentController.currentRevision,stateId:documentController.currentStateId,history:documentController.historyInfo,dirty:documentController.isDirty,records:modelReader.records()})');

test('ME4 included-angle authority returns the smaller unsigned angle and rejects degenerate rays',async()=>{const b=await browser(),m=(a,v,c)=>b.read(`window.CaderactMeasurement.measureIncludedAngle(${JSON.stringify(a)},${JSON.stringify(v)},${JSON.stringify(c)})`);for(const [p,degrees] of [[{x:0,y:1},90],[{x:1,y:1},45],[{x:-1,y:0},180],[{x:1,y:0},0],[{x:0,y:-1},90]])near(m({x:1,y:0},{x:0,y:0},p).angleDegrees,degrees);assert.equal(m({x:0,y:0},{x:0,y:0},{x:1,y:0}).reason,'degenerate-ray')});

test('point-to-record respects finite Line, Circle, Arc, and Polyline domains',async()=>{const b=await browser(),q=(p,r)=>b.read(`window.CaderactMeasurement.measurePointToRecord(${JSON.stringify(p)},${r})`);let x=q({x:2,y:3},`recordGateway.createLine({x:0,y:0},{x:4,y:0})`);assert.deepEqual(x.targetPoint,{x:2,y:0});assert.equal(x.distance,3);x=q({x:8,y:3},`recordGateway.createLine({x:0,y:0},{x:4,y:0})`);assert.deepEqual(x.targetPoint,{x:4,y:0});near(x.distance,5);x=q({x:10,y:0},`recordGateway.createCircle({x:0,y:0},4)`);assert.deepEqual(x.targetPoint,{x:4,y:0});assert.equal(x.distance,6);x=q({x:0,y:0},`recordGateway.createCircle({x:0,y:0},4)`);assert.equal(x.distance,4);assert.equal(x.targetPoint,null);x=q({x:-5,y:0},`recordGateway.createArc({center:{x:0,y:0},radius:5,start:{x:5,y:0},end:{x:0,y:5},sweep:Math.PI/2})`);near(x.targetPoint.x,0);near(x.targetPoint.y,5);x=q({x:2,y:2},`recordGateway.createPolyline([{x:0,y:0},{x:4,y:0},{x:4,y:4}],false)`);assert.equal(x.segmentIndex,0);assert.deepEqual(x.targetPoint,{x:2,y:0});x=q({x:0,y:2},`recordGateway.createPolyline([{x:0,y:0},{x:4,y:0},{x:4,y:4}],true)`);assert.equal(x.segmentIndex,2);assert.equal(x.distance,Math.SQRT2)});

test('record-to-record handles intersections, separated Lines/Circles/Arcs, and Polylines',async()=>{const b=await browser(),m=(a,c)=>b.read(`window.CaderactMeasurement.measureRecordToRecord(${a},${c})`),line=a=>`recordGateway.createLine(${JSON.stringify(a[0])},${JSON.stringify(a[1])})`;assert.equal(m(line([[0,0],[10,0]].map(([x,y])=>({x,y}))),line([[5,-5],[5,5]].map(([x,y])=>({x,y})))).distance,0);near(m(line([{x:0,y:0},{x:10,y:0}]),line([{x:0,y:3},{x:10,y:3}])).distance,3);near(m(`recordGateway.createCircle({x:0,y:0},2)`,`recordGateway.createCircle({x:10,y:0},3)`).distance,5);near(m(`recordGateway.createCircle({x:0,y:0},10)`,`recordGateway.createCircle({x:2,y:0},3)`).distance,5);assert.equal(m(line([{x:-10,y:0},{x:10,y:0}]),`recordGateway.createCircle({x:0,y:0},3)`).distance,0);assert.equal(m(`recordGateway.createArc({center:{x:0,y:0},radius:5,start:{x:5,y:0},end:{x:0,y:5},sweep:Math.PI/2})`,`recordGateway.createArc({center:{x:10,y:0},radius:5,start:{x:5,y:0},end:{x:10,y:5},sweep:-Math.PI/2})`).distance,0);near(m(`recordGateway.createPolyline([{x:0,y:0},{x:5,y:0}],false)`,line([{x:0,y:3},{x:5,y:3}])).distance,3);assert.equal(m(`recordGateway.createPolyline([{x:0,y:0},{x:5,y:0}],false)`,`recordGateway.createPolyline([{x:2,y:-2},{x:2,y:2}],false)`).distance,0);assert.equal(m(`recordGateway.createEllipse({center:{x:0,y:0},majorAxis:{x:5,y:0},minorRadius:2})`,line([{x:10,y:0},{x:20,y:0}])).valid,false)});

test('Angle command uses final resolved candidate for preview HUD and result without mutation',async()=>{const b=await browser(),before=state(b);b.launch('ANG');typed(b,'10,0');typed(b,'0,0');b.point(400,250,'pointermove');assert.equal(b.read('window.caderactViewport.getDynamicInputState().fields[0].value'),'90.00°');b.flush();assert.equal(b.renders.at(-1).measurementOverlay.segments.length,8);b.point(400,250);near(b.read('window.caderactCommandRouter.lastResult.measurement.angleDegrees'),90);assert.deepEqual(state(b),before)});

test('DistanceObject and MinDist provide transient exact connectors and read-only results',async()=>{const p=await browser();p.run(`window.__line=recordGateway.createLine({x:0,y:0},{x:10,y:0});recordGateway.createAll([window.__line])`);const stable=state(p);p.launch('DOBJ');typed(p,'5,5');p.point(425,302,'pointermove');p.flush();assert.equal(p.renders.at(-1).measurementOverlay.distance,5);p.point(425,302);assert.equal(p.read('window.caderactCommandRouter.lastResult.measurement.distance'),5);assert.deepEqual(state(p),stable);const m=await browser();m.run(`recordGateway.createAll([recordGateway.createLine({x:0,y:0},{x:10,y:0}),recordGateway.createLine({x:0,y:5},{x:10,y:5})])`);const before=state(m);m.launch('MinDist');m.point(425,300);m.point(425,275,'pointermove');m.flush();assert.equal(m.renders.at(-1).measurementOverlay.distance,5);m.point(425,275);assert.equal(m.read('window.caderactCommandRouter.lastResult.measurement.distance'),5);assert.deepEqual(state(m),before)});

test('DistanceSum reports live segment/total, rejects duplicates, supports Step Undo, and completes read-only',async()=>{const b=await browser(),before=state(b);b.launch('DSUM');typed(b,'0,0');typed(b,'3,4');typed(b,'3,4');assert.equal(b.read('window.caderactCommandRouter.lastResult.reason'),'zero-length-segment');typed(b,'6,8');b.point(430,240,'pointermove');assert.deepEqual(b.read('window.caderactViewport.getDynamicInputState().fields.map(x=>x.value)'),['4','14']);assert.equal(b.window.caderactViewport.stepUndoActiveCommand().status,'step-undone');typed(b,'6,8');b.key('Enter',b.input);assert.equal(b.read('window.caderactCommandRouter.lastResult.measurement.totalLength'),10);assert.deepEqual(state(b),before)});
