'use strict';
const test=require('node:test');const assert=require('node:assert/strict');const {browser}=require('../helpers/browser.cjs');
function typed(b,value){b.input.value=value;b.emit(b.input,'input');return b.key('Enter',b.input)}
function near(actual,expected,tolerance=1e-9){assert.ok(Math.abs(actual-expected)<=tolerance,`${actual} != ${expected}`)}

test('Aligned aliases resolve conflict-free to one repeatable command',async()=>{const b=await browser();for(const name of ['Aligned','DIMALIGNED','DAL'])assert.equal(b.read(`window.caderactCommandRegistry.resolve(${JSON.stringify(name)}).name`),'Aligned');assert.equal(b.read(`window.caderactCommandRegistry.resolve('Aligned').repeatable`),true)});

test('P1 P2 P3 commits one native aligned dimension with true length',async()=>{const b=await browser();b.launch('Aligned');assert.match(b.run('window.caderactCommandRouter.activeSession.prompt'),/first extension/i);typed(b,'0,0');assert.match(b.run('window.caderactCommandRouter.activeSession.prompt'),/second extension/i);typed(b,'3,4');assert.match(b.run('window.caderactCommandRouter.activeSession.prompt'),/dimension line/i);typed(b,'-1,3');const record=b.read('modelReader.records()[0]');assert.equal(record.type,'dimension-linear');assert.equal(record.mode,'aligned');assert.deepEqual([record.firstPoint.x,record.firstPoint.y,record.secondPoint.x,record.secondPoint.y,record.dimensionLinePoint.x,record.dimensionLinePoint.y],[0,0,3,4,-1,3]);assert.equal(b.run('window.CaderactDimensionGeometry.measure(modelReader.records()[0]).value'),5)});

test('aligned presentation stays parallel to P1-P2 and extension lines stay perpendicular',async()=>{const b=await browser();b.launch('DAL');typed(b,'1,2');typed(b,'7,5');typed(b,'3,9');const scene=b.read('window.CaderactDimensionGeometry.derive(modelReader.records()[0],modelReader.dimensionStyle(),modelReader.units())');const source={x:6,y:3},dimension={x:scene.lines[2][1].x-scene.lines[2][0].x,y:scene.lines[2][1].y-scene.lines[2][0].y},extension={x:scene.lines[0][1].x-scene.lines[0][0].x,y:scene.lines[0][1].y-scene.lines[0][0].y};near(source.x*dimension.y-source.y*dimension.x,0);near(source.x*extension.x+source.y*extension.y,0)});

test('placement on either side preserves measurement and flips perpendicular offset',async()=>{const b=await browser();b.window.__style=b.run('modelReader.dimensionStyle()');b.window.__units=b.run('modelReader.units()');const derive=p=>b.read(`window.CaderactDimensionGeometry.derive({type:'dimension-linear',mode:'aligned',firstPoint:{x:0,y:0},secondPoint:{x:4,y:3},dimensionLinePoint:${JSON.stringify(p)},textOverride:null},window.__style,window.__units)`);const left=derive({x:-3,y:4}),right=derive({x:3,y:-4});assert.equal(left.measurement.value,5);assert.equal(right.measurement.value,5);const cross=s=>4*s.lines[2][0].y-3*s.lines[2][0].x;assert.ok(cross(left)>0);assert.ok(cross(right)<0)});

test('near-horizontal, near-vertical, reversed, and tiny finite spans remain aligned',async()=>{const b=await browser();for(const [a,c,d] of [[{x:0,y:0},{x:100,y:1},{x:0,y:5}],[{x:0,y:0},{x:1,y:100},{x:5,y:0}],[{x:8,y:6},{x:0,y:0},{x:4,y:8}],[{x:0,y:0},{x:1e-8,y:2e-8},{x:-1e-8,y:1e-8}]]){b.window.__r={type:'dimension-linear',mode:'aligned',firstPoint:a,secondPoint:c,dimensionLinePoint:d,textOverride:null};const result=b.read('({measurement:window.CaderactDimensionGeometry.measure(window.__r),presentation:window.CaderactDimensionGeometry.derive(window.__r,modelReader.dimensionStyle(),modelReader.units())})');near(result.measurement.value,Math.hypot(c.x-a.x,c.y-a.y),1e-12);assert.equal(result.presentation.supported,true);for(const line of result.presentation.lines)for(const point of line){assert.equal(Number.isFinite(point.x),true);assert.equal(Number.isFinite(point.y),true)}}});

test('coincident definition points reject retryably with no mutation',async()=>{const b=await browser();b.launch('Aligned');typed(b,'2,2');typed(b,'2,2');assert.equal(b.read('window.caderactCommandRouter.activeSession.phase'),'second');assert.equal(b.read('modelReader.records().length'),0);assert.equal(b.read('documentController.historyInfo.entryCount'),0);typed(b,'5,6');typed(b,'0,8');assert.equal(b.read('modelReader.records()[0].mode'),'aligned')});

test('live preview uses the same D1 derivation as the committed record',async()=>{const b=await browser();b.resize(800,600);b.flush();b.launch('DIMALIGNED');typed(b,'0,0');typed(b,'6,8');b.point(425,250,'pointermove');b.flush();assert.equal(b.renders.at(-1).annotationOverlay.items.length,1);const transient=b.read('window.caderactCommandRouter.activeSession.getDimensionPreview()');b.point(425,250);const committed=b.read('modelReader.records()[0]');b.window.__a=transient;b.window.__b=committed;assert.deepEqual(b.read('({...window.CaderactDimensionGeometry.derive(window.__a,modelReader.dimensionStyle(),modelReader.units()),grips:undefined})'),b.read('({...window.CaderactDimensionGeometry.derive(window.__b,modelReader.dimensionStyle(),modelReader.units()),grips:undefined})'))});

test('typed relative input, shared snaps, and first-point acquisition use the authoritative path',async()=>{const b=await browser();b.resize(800,600);b.flush();b.run('recordGateway.createAll([recordGateway.createLine({x:0,y:0},{x:10,y:0})]);window.caderactViewport.setGridSnapEnabled(false);window.caderactViewport.setObjectSnapTrackingEnabled(false)');b.launch('Aligned');b.point(400,300,'pointermove');b.point(400,300);assert.deepEqual(b.read('window.caderactCommandRouter.activeSession.draft.acceptedPoints()[0]'),{x:0,y:0});b.point(450,300,'pointermove');b.point(450,300);assert.deepEqual(b.read('window.caderactCommandRouter.activeSession.draft.acceptedPoints()[1]'),{x:10,y:0});typed(b,'@2,4');const point=b.read("modelReader.records().find(record=>record.type==='dimension-linear').dimensionLinePoint");assert.deepEqual([point.x,point.y],[12,4])});

test('publication is atomic, retryable, one history step, and exact through Undo Redo persistence',async()=>{const b=await browser();b.launch('Aligned');typed(b,'0,0');typed(b,'3,4');b.run('window.__blocker=documentController.beginTransaction()');typed(b,'-1,3');assert.equal(b.read('window.caderactCommandRouter.lastResult.reason'),'commit-failed');assert.equal(b.read('window.caderactCommandRouter.activeSession.draft.acceptedPoints().length'),2);assert.equal(b.read('modelReader.records().length'),0);b.run('window.__blocker.rollback()');typed(b,'-1,3');const exact=b.read('modelReader.records()[0]');assert.equal(b.read('documentController.historyInfo.entryCount'),1);b.run('documentController.undo()');assert.equal(b.read('modelReader.records().length'),0);b.run('documentController.redo()');assert.deepEqual(b.read('modelReader.records()[0]'),exact);b.window.__file=b.run('window.CaderactPersistence.serializeDocument(modelReader.snapshot())');b.run('window.__loaded=window.CaderactPersistence.loadStore(window.__file)');assert.deepEqual(b.read('window.__loaded.reader.records()[0]'),exact)});

test('current layer ByLayer properties, Escape, and repeat lifecycle remain authoritative',async()=>{for(const points of [[],['0,0'],['0,0','5,2']]){const b=await browser();b.launch('Aligned');for(const point of points)typed(b,point);b.key('Escape');assert.equal(b.read('modelReader.records().length'),0)}const b=await browser();b.run("layerGateway.create('Dimensions',{makeCurrent:true});window.__layer=modelReader.snapshot().currentLayerId");b.launch('Aligned');typed(b,'0,0');typed(b,'5,2');typed(b,'1,7');const record=b.read('modelReader.records()[0]');assert.equal(record.layerId,b.run('window.__layer'));assert.deepEqual({color:record.color,linetype:record.linetype,lineweight:record.lineweight},{color:null,linetype:null,lineweight:null});b.run('window.caderactCommandRouter.repeatLastCommand()');assert.equal(b.read('window.caderactCommandRouter.activeSession.phase'),'first')});
