'use strict';
const test=require('node:test');const assert=require('node:assert/strict');const {browser}=require('../helpers/browser.cjs');
function typed(b,value){b.input.value=value;b.emit(b.input,'input');return b.key('Enter',b.input)}

test('AN1 commands register once through AF1',async()=>{const b=await browser();for(const name of ['DimBaseline','DimContinue','Ordinate','ArcLength','CenterMark','CenterLine'])assert.equal(b.read(`window.caderactCommandRegistry.resolve(${JSON.stringify(name)}).name`),name)});

test('Baseline and Continue publish ordinary editable Linear dimensions',async()=>{const b=await browser();b.launch('DimBaseline');for(const value of ['0,0','10,0','20,0'])typed(b,value);assert.deepEqual(b.read('modelReader.records().map(r=>[r.type,r.firstPoint.x,r.secondPoint.x]).sort((a,b)=>a[2]-b[2])'),[['dimension-linear',0,10],['dimension-linear',0,20]]);b.key('Enter',b.input);b.run('selection.applyRecordIds([modelReader.records().find(r=>r.secondPoint.x===20).id])');b.launch('DimContinue');typed(b,'30,0');b.key('Enter',b.input);assert.deepEqual(b.read('modelReader.records().map(r=>[r.firstPoint.x,r.secondPoint.x]).sort((a,b)=>a[1]-b[1])'),[[0,10],[0,20],[20,30]]);assert.equal(b.read('documentController.historyInfo.entryCount'),3)});

test('native Ordinate and Arc Length use shared measurement/style/persistence',async()=>{const b=await browser();b.run(`window.__o=recordGateway.createOrdinateDimension({axis:'x',datumPoint:{x:0,y:0},featurePoint:{x:7,y:4},leaderPoint:{x:9,y:8}});window.__a=recordGateway.createArcLengthDimension({centerPoint:{x:0,y:0},startPoint:{x:10,y:0},endPoint:{x:0,y:10},dimensionArcPoint:{x:12,y:0},sweep:Math.PI/2,sourceRecordId:'arc-source'});recordGateway.createAll([window.__o,window.__a])`);assert.equal(b.read('window.CaderactDimensionGeometry.measure(window.__o).value'),7);assert.ok(Math.abs(b.read('window.CaderactDimensionGeometry.measure(window.__a).value')-Math.PI*5)<1e-12);const exact=b.read('modelReader.records()');b.run('window.__file=window.CaderactPersistence.serializeDocument(modelReader.snapshot());window.__loaded=window.CaderactPersistence.loadStore(window.__file)');assert.deepEqual(b.read('window.__loaded.reader.records()'),exact)});

test('Center Mark and Center Line are semantic native transformable annotations',async()=>{const b=await browser();b.run(`window.__m=recordGateway.createCenterMark({centerPoint:{x:2,y:3},sizePoint:{x:5,y:3},sourceRecordId:'circle-source'});window.__c=recordGateway.createCenterLine({firstPoint:{x:0,y:2},secondPoint:{x:0,y:8},extension:1,sourceRecordIds:['line-a','line-b']});recordGateway.createAll([window.__m,window.__c]);window.__moved=window.CaderactGeometryTransform.translateRecord(window.__m,4,-1)`);assert.deepEqual(b.read('[window.__moved.centerPoint.x,window.__moved.centerPoint.y,window.__moved.sourceRecordId]'),[6,2,'circle-source']);assert.equal(b.read('window.CaderactDimensionGeometry.derive(window.__m,modelReader.dimensionStyle(),modelReader.units()).lines.length'),2);assert.equal(b.read('window.CaderactDimensionGeometry.derive(window.__c,modelReader.dimensionStyle(),modelReader.units()).lines.length'),1)});

test('Center Line rejects nonparallel sources without document mutation',async()=>{const b=await browser();b.resize(800,600);b.flush();b.run(`recordGateway.createAll([recordGateway.createLine({x:-20,y:0},{x:20,y:0}),recordGateway.createLine({x:0,y:-20},{x:0,y:20})])`);const before=b.read('documentController.historyInfo.entryCount');b.launch('CenterLine');b.point(350,300);b.point(400,350);assert.equal(b.read('documentController.historyInfo.entryCount'),before);assert.equal(b.run('window.caderactCommandRouter.activeCommand'),'CenterLine')});
