'use strict';
const test=require('node:test');const assert=require('node:assert/strict');const {browser}=require('../helpers/browser.cjs');
function typed(b,value){b.input.value=value;b.emit(b.input,'input');return b.key('Enter',b.input)}

test('Leader and MLeader register once through AF1',async()=>{const b=await browser();assert.equal(b.run('window.caderactCommandRegistry.resolve("LEADER").name'),'Leader');assert.equal(b.run('window.caderactCommandRegistry.resolve("MLEADER").name'),'MLeader')});

test('Leader accepts resolved vertices, multiline content, and one atomic native commit',async()=>{const b=await browser();b.launch('Leader');typed(b,'0,0');typed(b,'10,5');typed(b,'15,5');assert.equal(b.read('documentController.historyInfo.entryCount'),0);b.key('Enter',b.input);typed(b,'First\\nSecond');const record=b.read('modelReader.records()[0]');assert.equal(record.type,'dimension-leader');assert.equal(record.vertices.length,3);assert.equal(record.textOverride,'First\nSecond');assert.equal(record.layerId,b.read('modelReader.snapshot().currentLayerId'));assert.equal(b.read('documentController.historyInfo.entryCount'),1);b.run('documentController.undo()');assert.equal(b.read('modelReader.records().length'),0);b.run('documentController.redo()');assert.deepEqual(b.read('modelReader.records()[0]'),record)});

test('Leader preview and committed presentation share one renderer-neutral geometry authority',async()=>{const b=await browser();b.launch('Leader');typed(b,'0,0');typed(b,'10,0');b.run('window.__preview=window.caderactCommandRouter.activeSession.getDimensionPreview()');const before=b.read('documentController.historyInfo.entryCount');b.key('Enter',b.input);typed(b,'Note');const committed=b.read('modelReader.records()[0]');assert.equal(before,0);b.window.__record=committed;assert.deepEqual(b.read('window.CaderactDimensionGeometry.derive(window.__preview,modelReader.dimensionStyle(),modelReader.units()).lines'),b.read('window.CaderactDimensionGeometry.derive(window.__record,modelReader.dimensionStyle(),modelReader.units()).lines'))});

test('Multileader owns independently identified branches with shared content and add/remove options',async()=>{const b=await browser();b.launch('MLeader');typed(b,'0,0');typed(b,'10,0');b.run('window.caderactCommandRouter.activeSession.handleOption("add")');typed(b,'0,10');typed(b,'10,10');b.run('window.caderactCommandRouter.activeSession.handleOption("text")');typed(b,'Shared');const record=b.read('modelReader.records()[0]');assert.equal(record.type,'dimension-multileader');assert.equal(record.branches.length,2);assert.equal(new Set(record.branches.map(branch=>branch.featureId)).size,2);assert.equal(record.textOverride,'Shared');const b2=await browser();b2.launch('MLeader');typed(b2,'0,0');typed(b2,'10,0');b2.run('window.caderactCommandRouter.activeSession.handleOption("add")');typed(b2,'0,10');typed(b2,'10,10');b2.run('window.caderactCommandRouter.activeSession.handleOption("remove")');b2.run('window.caderactCommandRouter.activeSession.handleOption("text")');typed(b2,'One');assert.equal(b2.read('modelReader.records()[0].branches.length'),1)});

test('Leader records transform, expose semantic grips, edit content, and persist exactly',async()=>{const b=await browser();b.run(`window.__record=recordGateway.createLeader({vertices:[{x:0,y:0},{x:5,y:2},{x:8,y:2}],textPosition:{x:10,y:2},landingLength:1,textOverride:'A\\nB'});recordGateway.createAll([window.__record]);selection.applyRecordIds([window.__record.id]);window.__moved=window.CaderactGeometryTransform.translateRecord(window.__record,3,4)`);assert.deepEqual(b.read('window.__moved.vertices.map(p=>[p.x,p.y])'),[[3,4],[8,6],[11,6]]);assert.equal(b.read('window.CaderactGrips.discoverDimensionGrips(modelReader.records(),selection.selectedIds()).length'),4);const exact=b.read('modelReader.records()[0]');b.run('window.__file=window.CaderactPersistence.serializeDocument(modelReader.snapshot());window.__loaded=window.CaderactPersistence.loadStore(window.__file)');assert.deepEqual(b.read('window.__loaded.reader.records()[0]'),exact)});

test('Leader cancellation and invalid text remain mutation free',async()=>{const b=await browser();b.launch('Leader');typed(b,'0,0');typed(b,'10,0');b.key('Enter',b.input);typed(b,'');assert.equal(b.run('window.caderactCommandRouter.activeCommand'),'Leader');assert.equal(b.read('documentController.historyInfo.entryCount'),0);b.key('Escape');assert.equal(b.read('modelReader.records().length'),0)});
