'use strict';
const test=require('node:test');const assert=require('node:assert/strict');const {browser}=require('../helpers/browser.cjs');
function typed(b,value){b.input.value=value;b.emit(b.input,'input');return b.key('Enter',b.input)}
function near(actual,expected,tolerance=1e-9){assert.ok(Math.abs(actual-expected)<=tolerance,`${actual} != ${expected}`)}
function create(b,first='10,0',vertex='0,0',second='0,10',placement='6,6'){b.launch('Angular');for(const point of [first,vertex,second,placement])typed(b,point);return b.read("modelReader.records().find(record=>record.type==='dimension-angular')")}

test('Angular aliases are conflict-free and repeatable',async()=>{const b=await browser();for(const name of ['Angular','DIMANGULAR','DAN'])assert.equal(b.read(`window.caderactCommandRegistry.resolve(${JSON.stringify(name)}).name`),'Angular');assert.equal(b.read("window.caderactCommandRegistry.resolve('Angular').repeatable"),true)});

test('four-point workflow commits one native angular dimension',async()=>{const b=await browser();b.launch('Angular');for(const [point,prompt] of [['10,0',/vertex/i],['0,0',/second ray/i],['0,10',/arc location/i]]){typed(b,point);assert.match(b.run('window.caderactCommandRouter.activeSession.prompt'),prompt)}typed(b,'6,6');const record=b.read('modelReader.records()[0]');assert.equal(record.type,'dimension-angular');assert.deepEqual([record.firstRayPoint.x,record.vertex.x,record.secondRayPoint.y,record.dimensionArcPoint.x],[10,0,10,6]);assert.equal(record.textOverride,null)});

test('30 45 90 and 135 degree records reuse included-angle measurement',async()=>{for(const degrees of [30,45,90,135]){const b=await browser(),radians=degrees*Math.PI/180;b.window.__record={type:'dimension-angular',firstRayPoint:{x:10,y:0},vertex:{x:0,y:0},secondRayPoint:{x:10*Math.cos(radians),y:10*Math.sin(radians)},dimensionArcPoint:{x:5,y:5},textOverride:null};near(b.run('window.CaderactDimensionGeometry.measure(window.__record).value'),radians)}});

test('reversing rays preserves magnitude and equivalent deterministic presentation',async()=>{const b=await browser();b.window.__style=b.run('modelReader.dimensionStyle()');b.window.__units=b.run('modelReader.units()');const expression=(a,c)=>`window.CaderactDimensionGeometry.derive({type:'dimension-angular',firstRayPoint:${JSON.stringify(a)},vertex:{x:0,y:0},secondRayPoint:${JSON.stringify(c)},dimensionArcPoint:{x:4,y:4},textOverride:null},window.__style,window.__units)`;const forward=b.read(expression({x:10,y:0},{x:0,y:10})),reverse=b.read(expression({x:0,y:10},{x:10,y:0}));assert.equal(forward.measurement.value,reverse.measurement.value);assert.deepEqual({arcs:forward.arcs,triangles:forward.triangles,text:forward.text,bounds:forward.bounds},{arcs:reverse.arcs,triangles:reverse.triangles,text:reverse.text,bounds:reverse.bounds});const sort=lines=>lines.map(line=>JSON.stringify(line)).sort();assert.deepEqual(sort(forward.lines),sort(reverse.lines))});

test('degenerate rays and exact 0 or 180 degrees reject in their phases',async()=>{for(const [first,vertex,second,reason] of [['0,0','0,0',null,'degenerate-first-ray'],['10,0','0,0','0,0','degenerate-ray'],['10,0','0,0','5,0','zero-angle'],['10,0','0,0','-5,0','straight-angle']]){const b=await browser();b.launch('Angular');typed(b,first);typed(b,vertex);if(second)typed(b,second);assert.equal(b.read('window.caderactCommandRouter.lastResult.reason'),reason);assert.equal(b.read('modelReader.records().length'),0)}});

test('near-collinear valid rays and small normal large placement radii stay finite',async()=>{for(const [angle,radius] of [[1e-6,1e-5],[Math.PI/4,5],[Math.PI-1e-6,1e6]]){const b=await browser(),second={x:10*Math.cos(angle),y:10*Math.sin(angle)},placement={x:radius*Math.cos(angle/2),y:radius*Math.sin(angle/2)};b.window.__record={type:'dimension-angular',firstRayPoint:{x:10,y:0},vertex:{x:0,y:0},secondRayPoint:second,dimensionArcPoint:placement,textOverride:null};const scene=b.read('window.CaderactDimensionGeometry.derive(window.__record,modelReader.dimensionStyle(),modelReader.units())');assert.equal(scene.supported,true);near(scene.arcs[0].radius,radius,1e-8);near(scene.arcs[0].sweep,angle,1e-9);for(const triangle of scene.triangles)for(const point of triangle)assert.equal(Number.isFinite(point.x)&&Number.isFinite(point.y),true)}});

test('placement at vertex rejects retryably and publication failure preserves definition',async()=>{const b=await browser();b.launch('Angular');for(const point of ['10,0','0,0','0,10'])typed(b,point);typed(b,'0,0');assert.equal(b.read('window.caderactCommandRouter.lastResult.reason'),'invalid-placement-radius');assert.equal(b.read('window.caderactCommandRouter.activeSession.phase'),'placement');b.run('window.__blocker=documentController.beginTransaction()');typed(b,'5,5');assert.equal(b.read('window.caderactCommandRouter.lastResult.reason'),'commit-failed');assert.equal(b.read('window.caderactCommandRouter.activeSession.draft.acceptedPoints().length'),3);b.run('window.__blocker.rollback()');typed(b,'5,5');assert.equal(b.run("modelReader.records().find(record=>record.type==='dimension-angular').type"),'dimension-angular')});

test('pure geometry owns centered arc tangent arrows readable text and semantic grips',async()=>{const b=await browser();b.window.__r={type:'dimension-angular',firstRayPoint:{x:10,y:0,featureId:'a'},vertex:{x:0,y:0,featureId:'v'},secondRayPoint:{x:0,y:10,featureId:'b'},dimensionArcPoint:{x:6,y:6,featureId:'d'},textOverride:null};const p=b.read('window.CaderactDimensionGeometry.derive(window.__r,modelReader.dimensionStyle(),modelReader.units())'),arc=p.arcs[0];assert.deepEqual(arc.center,{x:0,y:0});near(arc.radius,Math.hypot(6,6));near(arc.sweep,Math.PI/2);for(let index=0;index<2;index++){const triangle=p.triangles[index],tip=triangle[0],base={x:(triangle[1].x+triangle[2].x)/2,y:(triangle[1].y+triangle[2].y)/2},radial={x:tip.x,y:tip.y};near((base.x-tip.x)*radial.x+(base.y-tip.y)*radial.y,0)}assert.equal(Number.isFinite(p.text.point.x)&&Number.isFinite(p.text.rotation),true);assert.match(p.text.value,/90\.00°/);assert.deepEqual(p.grips.map(grip=>grip.featureId),['a','v','b','d'])});

test('live preview and committed record derive identically and share arc scene primitives',async()=>{const b=await browser();b.resize(800,600);b.flush();b.launch('Angular');for(const point of ['10,0','0,0','0,10'])typed(b,point);b.point(430,270,'pointermove');b.flush();assert.equal(b.renders.at(-1).arcOverlay.preview.length,1);assert.equal(b.renders.at(-1).triangleGroups[0].triangles.length,2);assert.equal(b.renders.at(-1).annotationOverlay.items.length,1);const preview=b.read('window.caderactCommandRouter.activeSession.getDimensionPreview()');b.point(430,270);const committed=b.read("modelReader.records().find(record=>record.type==='dimension-angular')");b.window.__a=preview;b.window.__b=committed;const a=b.read('window.CaderactDimensionGeometry.derive(window.__a,modelReader.dimensionStyle(),modelReader.units())'),c=b.read('window.CaderactDimensionGeometry.derive(window.__b,modelReader.dimensionStyle(),modelReader.units())');assert.deepEqual({...a,grips:undefined},{...c,grips:undefined});assert.deepEqual(a.grips.map(grip=>grip.point),c.grips.map(grip=>grip.point))});

test('typed relative and endpoint snapped points use the authoritative point path',async()=>{const b=await browser();b.resize(800,600);b.flush();b.run('recordGateway.createAll([recordGateway.createLine({x:0,y:0},{x:10,y:0})]);window.caderactViewport.setGridSnapEnabled(false);window.caderactViewport.setObjectSnapTrackingEnabled(false)');b.launch('DAN');b.point(450,300,'pointermove');b.point(450,300);b.point(400,300,'pointermove');b.point(400,300);typed(b,'@0,10');typed(b,'@5,-5');const record=b.read("modelReader.records().find(record=>record.type==='dimension-angular')");assert.deepEqual([record.firstRayPoint.x,record.firstRayPoint.y,record.vertex.x,record.vertex.y,record.secondRayPoint.x,record.secondRayPoint.y,record.dimensionArcPoint.x,record.dimensionArcPoint.y],[10,0,0,0,0,10,5,5])});

test('commit uses one history entry and exact v2 persistence',async()=>{const b=await browser(),record=create(b);assert.equal(b.read('documentController.historyInfo.entryCount'),1);b.run('documentController.undo()');assert.equal(b.read('modelReader.records().length'),0);b.run('documentController.redo()');assert.deepEqual(b.read('modelReader.records()[0]'),record);b.window.__before=b.read('window.CaderactDimensionGeometry.derive(modelReader.records()[0],modelReader.dimensionStyle(),modelReader.units())');b.window.__file=b.run('window.CaderactPersistence.serializeDocument(modelReader.snapshot())');b.run('window.__loaded=window.CaderactPersistence.loadStore(window.__file)');assert.deepEqual(b.read('window.__loaded.reader.records()[0]'),record);b.window.__loadedRecord=b.run('window.__loaded.reader.records()[0]');assert.deepEqual(b.read('window.CaderactDimensionGeometry.derive(window.__loadedRecord,modelReader.dimensionStyle(),modelReader.units())'),b.read('window.__before'))});

test('Escape every phase is history-free while current layer and repeat remain authoritative',async()=>{for(const points of [[],['10,0'],['10,0','0,0'],['10,0','0,0','0,10']]){const b=await browser();b.launch('Angular');for(const point of points)typed(b,point);b.key('Escape');assert.equal(b.read('modelReader.records().length'),0);assert.equal(b.read('documentController.historyInfo.entryCount'),0)}const b=await browser();b.run("layerGateway.create('Dimensions',{makeCurrent:true});window.__layer=modelReader.snapshot().currentLayerId");const record=create(b);assert.equal(record.layerId,b.run('window.__layer'));assert.deepEqual({color:record.color,linetype:record.linetype,lineweight:record.lineweight},{color:null,linetype:null,lineweight:null});b.run('window.caderactCommandRouter.repeatLastCommand()');assert.equal(b.read('window.caderactCommandRouter.activeSession.phase'),'first-ray')});
