const test=require('node:test');
const assert=require('node:assert/strict');
const {browser}=require('../helpers/browser.cjs');
const near=(a,b)=>assert.ok(Math.abs(a-b)<1e-9,`${a} != ${b}`);
const state=b=>b.read('({revision:documentController.currentRevision,stateId:documentController.currentStateId,history:documentController.historyInfo,dirty:documentController.isDirty,records:modelReader.records()})');

test('ME3 exact Circle/Ellipse area and semantic area formatting',async()=>{const b=await browser(),circle=b.read('window.CaderactMeasurement.measureRecord(recordGateway.createCircle({x:0,y:0},10))'),ellipse=b.read('window.CaderactMeasurement.measureRecord(recordGateway.createEllipse({center:{x:0,y:0},majorAxis:{x:10,y:0},minorRadius:5}))');near(circle.area,100*Math.PI);near(circle.perimeter,20*Math.PI);near(ellipse.area,50*Math.PI);assert.equal(ellipse.perimeter,undefined);assert.equal(b.run(`window.CaderactMeasurement.formatObject(${JSON.stringify(circle)},'area','mm').formatted`),'314.159 mm²')});

test('closed Polyline shoelace preserves orientation and exact perimeter',async()=>{const b=await browser(),measure=points=>b.read(`window.CaderactMeasurement.measureRecord(recordGateway.createPolyline(${JSON.stringify(points)},true))`),ccw=measure([{x:0,y:0},{x:10,y:0},{x:10,y:5},{x:0,y:5}]),cw=measure([{x:0,y:5},{x:10,y:5},{x:10,y:0},{x:0,y:0}]),triangle=measure([{x:0,y:0},{x:6,y:0},{x:0,y:4}]),concave=measure([{x:0,y:0},{x:4,y:0},{x:4,y:4},{x:2,y:2},{x:0,y:4}]),degenerate=measure([{x:0,y:0},{x:1,y:0},{x:2,y:0}]);assert.equal(ccw.area,50);assert.equal(ccw.signedArea,50);assert.equal(cw.area,50);assert.equal(cw.signedArea,-50);assert.equal(ccw.perimeter,30);assert.equal(triangle.area,12);assert.equal(concave.area,12);assert.equal(degenerate.area,0)});

test('open and self-intersecting Polylines expose no area while perimeter remains valid',async()=>{const b=await browser(),m=points=>b.read(`window.CaderactMeasurement.measureRecord(recordGateway.createPolyline(${JSON.stringify(points)},true))`),open=b.read(`window.CaderactMeasurement.measureRecord(recordGateway.createPolyline([{x:0,y:0},{x:3,y:0},{x:3,y:4}],false))`),bow=m([{x:0,y:0},{x:4,y:4},{x:0,y:4},{x:4,y:0}]),repeat=m([{x:0,y:0},{x:4,y:0},{x:4,y:4},{x:0,y:4},{x:4,y:0}]),overlap=m([{x:0,y:0},{x:4,y:0},{x:4,y:2},{x:1,y:0},{x:3,y:0}]);assert.equal(open.area,undefined);assert.equal(open.perimeter,undefined);for(const result of [bow,repeat,overlap]){assert.equal(result.selfIntersecting,true);assert.equal(result.area,undefined);assert.ok(Number.isFinite(result.perimeter))}});

test('Area and Perimeter commands complete valid preselection and reject invalid boundaries retryably',async()=>{for(const [factory,command,field,expected] of [[`recordGateway.createCircle({x:0,y:0},2)`,'Area','area',4*Math.PI],[`recordGateway.createEllipse({center:{x:0,y:0},majorAxis:{x:3,y:0},minorRadius:2})`,'Area','area',6*Math.PI],[`recordGateway.createPolyline([{x:0,y:0},{x:4,y:0},{x:4,y:3}],true)`,'PERIM','perimeter',12]]){const b=await browser();b.run(`window.__record=${factory};recordGateway.createAll([window.__record]);window.caderactSelection.selectOnly(window.__record.id)`);const before=state(b);b.launch(command);near(b.read(`window.caderactCommandRouter.lastResult.measurement.${field}`),expected);assert.deepEqual(state(b),before)}const b=await browser();b.run(`window.__open=recordGateway.createPolyline([{x:0,y:0},{x:4,y:0},{x:4,y:3}],false);window.__ellipse=recordGateway.createEllipse({center:{x:20,y:0},majorAxis:{x:3,y:0},minorRadius:2});recordGateway.createAll([window.__open,window.__ellipse])`);b.launch('Area');b.point(410,300);assert.equal(b.read('window.caderactCommandRouter.activeCommand'),'Area');assert.match(b.read('window.caderactCommandRouter.lastResult.message'),/closed/);b.key('Escape');b.launch('Perimeter');b.point(515,300);assert.equal(b.read('window.caderactCommandRouter.activeCommand'),'Perimeter');assert.match(b.read('window.caderactCommandRouter.lastResult.message'),/Ellipse perimeter/)});

test('Area explicit picking allows locked visible records and excludes hidden records',async()=>{const locked=await browser();locked.run(`layerGateway.create('Locked');window.__layer=modelReader.layers().find(x=>x.name==='Locked');window.__record=recordGateway.createCircle({x:0,y:0},3);recordGateway.createAll([window.__record]);recordGateway.assignLayer([window.__record.id],window.__layer.id);layerGateway.setLocked(window.__layer.id,true)`);const before=state(locked);locked.launch('Area');locked.point(415,300);near(locked.read('window.caderactCommandRouter.lastResult.measurement.area'),9*Math.PI);assert.deepEqual(state(locked),before);const hidden=await browser();hidden.run(`layerGateway.create('Hidden');window.__layer=modelReader.layers().find(x=>x.name==='Hidden');window.__record=recordGateway.createCircle({x:0,y:0},3);recordGateway.createAll([window.__record]);recordGateway.assignLayer([window.__record.id],window.__layer.id);layerGateway.setVisibility(window.__layer.id,false)`);hidden.launch('Area');hidden.point(415,300);assert.equal(hidden.read('window.caderactCommandRouter.activeCommand'),'Area');assert.equal(hidden.read('window.caderactCommandRouter.lastResult.kind'),'target-miss')});
