'use strict';
const {test}=require('node:test');const assert=require('node:assert/strict');const {browser}=require('../helpers/browser.cjs');
function seed(b){b.run('window.__source=recordGateway.createLine({x:0,y:0},{x:2,y:0});recordGateway.createAll([window.__source]);selection.selectOnly(window.__source.id)')}
function option(b,id,value){b.run(`window.caderactCommandRouter.activateOption(${JSON.stringify(id)})`);b.run(`window.caderactCommandRouter.submitActiveInput(${JSON.stringify(String(value))})`)}
const ordered=items=>items.slice().sort((a,c)=>JSON.stringify(a).localeCompare(JSON.stringify(c)));
test('RectangularArray previews and commits independent fresh copies in one history step',async()=>{const b=await browser();seed(b);const original=b.read('modelReader.records()[0]'),before=b.read('documentController.historyInfo.entryCount');b.launch('AR');option(b,'rows',2);option(b,'columns',2);option(b,'rowSpacing',-5);option(b,'columnSpacing',10);const preview=b.read('window.caderactCommandRouter.activeSession.getMovePreview().records.map(r=>({start:r.start,end:r.end}))');b.key('Enter');const records=b.read('modelReader.records()');assert.equal(records.length,4);assert.equal(b.read('documentController.historyInfo.entryCount'),before+1);assert.deepEqual(ordered(records.filter(r=>r.id!==original.id).map(r=>({start:{x:r.start.x,y:r.start.y},end:{x:r.end.x,y:r.end.y}}))),ordered(preview.map(r=>({start:{x:r.start.x,y:r.start.y},end:{x:r.end.x,y:r.end.y}}))));assert.equal(new Set(records.map(r=>r.id)).size,4);b.run('window.caderactHistory.undo()');assert.deepEqual(b.read('modelReader.records()'),[original]);b.run('window.caderactHistory.redo()');assert.deepEqual(b.read('modelReader.records()'),records)});
test('PolarArray uses resolved center, excludes duplicate full-circle source, and preserves properties',async()=>{const b=await browser();seed(b);const sourceId=b.read('window.__source.id');b.launch('PolarArray');b.run('window.caderactCommandRouter.submitActiveInput("0,0")');option(b,'count',4);option(b,'angle',360);const preview=b.read('window.caderactCommandRouter.activeSession.getMovePreview().records');b.key('Enter');const records=b.read('modelReader.records()');assert.equal(records.length,4);assert.equal(preview.length,3);assert.deepEqual(ordered(records.filter(r=>r.id!==sourceId).map(r=>({start:{x:r.start.x,y:r.start.y},end:{x:r.end.x,y:r.end.y}}))),ordered(preview.map(r=>({start:{x:r.start.x,y:r.start.y},end:{x:r.end.x,y:r.end.y}}))))});
test('PathArray accepts a resolved base and editable Line path with exact fixed-orientation copies',async()=>{const b=await browser();b.resize(800,600);b.run('window.__source=recordGateway.createLine({x:0,y:0},{x:2,y:0});window.__path=recordGateway.createLine({x:0,y:10},{x:20,y:10});recordGateway.createAll([window.__source,window.__path]);selection.selectOnly(window.__source.id)');b.launch('PathArray');b.run('window.caderactCommandRouter.submitActiveInput("0,10")');b.point(450,250);assert.equal(b.read('window.caderactCommandRouter.activeSession.phase'),'ready');option(b,'count',3);option(b,'spacing',5);b.key('Enter');const copies=b.read('modelReader.records().filter(r=>r.id!==window.__source.id&&r.id!==window.__path.id)');assert.equal(copies.length,2);assert.deepEqual(copies.map(r=>[r.start.x,r.start.y,r.end.x,r.end.y]).sort((a,c)=>a[0]-c[0]),[[5,0,7,0],[10,0,12,0]])});
test('array invalid parameters and cancellation remain mutation-free and retryable',async()=>{const b=await browser();seed(b);const before=b.read('({records:modelReader.records(),history:documentController.historyInfo.entryCount})');b.launch('RectangularArray');option(b,'rows',1000);b.key('Enter');assert.equal(b.read('window.caderactCommandRouter.activeCommand'),'RectangularArray');assert.deepEqual(b.read('({records:modelReader.records(),history:documentController.historyInfo.entryCount})'),before);b.key('Escape');assert.deepEqual(b.read('({records:modelReader.records(),history:documentController.historyInfo.entryCount})'),before)});
test('arrays reject grouped selection instead of flattening group semantics',async()=>{const b=await browser();b.run('window.__a=recordGateway.createLine({x:0,y:0},{x:2,y:0});window.__b=recordGateway.createLine({x:0,y:2},{x:2,y:2});recordGateway.createAll([window.__a,window.__b]);groupGateway.createGroup([window.__a.id,window.__b.id]);selection.applyRecordIds([window.__a.id,window.__b.id])');const before=b.read('({document:modelReader.snapshot(),history:documentController.historyInfo.entryCount})');b.launch('AR');b.key('Enter');assert.equal(b.read('window.caderactCommandRouter.activeCommand'),'RectangularArray');assert.deepEqual(b.read('({document:modelReader.snapshot(),history:documentController.historyInfo.entryCount})'),before)});
test('array publication failure is atomic and keeps preview retryable',async()=>{const b=await browser();seed(b);b.launch('AR');const preview=b.read('window.caderactCommandRouter.activeSession.getMovePreview().records.length'),before=b.read('modelReader.records()');b.run('window.__blocking=documentController.beginTransaction()');b.key('Enter');assert.equal(b.read('window.caderactCommandRouter.activeCommand'),'RectangularArray');assert.deepEqual(b.read('modelReader.records()'),before);assert.equal(b.read('window.caderactCommandRouter.activeSession.getMovePreview().records.length'),preview);b.run('window.__blocking.rollback()');b.key('Enter');assert.equal(b.read('window.caderactCommandRouter.activeCommand'),null)});
