'use strict';
const {test}=require('node:test');const assert=require('node:assert/strict');const {browser}=require('../helpers/browser.cjs');
function typed(b,value){b.input.value=value;b.emit(b.input,'input');return b.key('Enter',b.input)}
function seed(b){return b.run(`(()=>{const records=[recordGateway.createLine({x:0,y:0},{x:10,y:0}),recordGateway.createCircle({x:15,y:0},2),recordGateway.createText({insertionPoint:{x:0,y:5},text:'Valve',height:2,rotation:0})];recordGateway.createAll(records);window.caderactSelection.applyRecordIds(records.map(record=>record.id));return records})()`)}
function createBlock(b,name='Fixture'){const sources=seed(b);b.launch('Block');typed(b,name);typed(b,'2,3');return {sources,definition:b.read('modelReader.blockDefinitions()[0]')}}

test('GB4 registers Block and Insert with conventional aliases',async()=>{const b=await browser();for(const token of ['Block','B'])assert.equal(b.read(`window.caderactCommandRegistry.resolve(${JSON.stringify(token)}).name`),'Block');for(const token of ['Insert','I'])assert.equal(b.read(`window.caderactCommandRegistry.resolve(${JSON.stringify(token)}).name`),'Insert')})

test('Block snapshots selected semantics with fresh identities and preserves sources/base point',async()=>{const b=await browser(),{sources,definition}=createBlock(b);assert.equal(definition.name,'Fixture');assert.deepEqual(definition.basePoint,{x:2,y:3});assert.equal(definition.recordOrder.length,3);assert.equal(JSON.stringify(b.read('modelReader.records()')),JSON.stringify(sources.sort((a,c)=>a.id.localeCompare(c.id))));assert.ok(definition.recordOrder.every(id=>!sources.some(source=>source.id===id)));const sourceFeatures=sources.flatMap(record=>[record.start?.featureId,record.end?.featureId,record.insertionPoint?.featureId].filter(Boolean));const memberFeatures=Object.values(definition.records).flatMap(record=>[record.start?.featureId,record.end?.featureId,record.insertionPoint?.featureId].filter(Boolean));assert.ok(memberFeatures.every(id=>!sourceFeatures.includes(id)))})

test('Block default names are deterministic and duplicate explicit names reject atomically',async()=>{const b=await browser();seed(b);b.launch('Block');b.key('Enter');typed(b,'0,0');assert.equal(b.read('modelReader.blockDefinitions()[0].name'),'Block 1');b.launch('Block');typed(b,'block 1');assert.equal(b.read('window.caderactCommandRouter.activeSession.phase'),'name');assert.equal(b.read('modelReader.blockDefinitions().length'),1)})

test('Block rejects grouped sources and cancellation is mutation-free',async()=>{const b=await browser(),records=seed(b);b.run(`groupGateway.createGroup(${JSON.stringify(records.map(record=>record.id))})`);const before=b.read('modelReader.snapshot()');b.launch('Block');typed(b,'Grouped');assert.equal(b.read('window.caderactCommandRouter.activeSession.phase'),'name');b.key('Escape');assert.deepEqual(b.read('modelReader.snapshot()'),before)})

test('Block creation is one exact Undo/Redo operation',async()=>{const b=await browser(),{definition}=createBlock(b);assert.equal(b.read('documentController.historyInfo.entryCount'),2);b.run('window.caderactHistory.undo()');assert.equal(b.read('modelReader.blockDefinitions().length'),0);b.run('window.caderactHistory.redo()');assert.deepEqual(b.read('modelReader.blockDefinitions()[0]'),definition)})

test('Insert publishes canonical scale/rotation with fresh identities and supports multiple instances',async()=>{const b=await browser(),{definition}=createBlock(b);b.launch('Insert');typed(b,'Fixture');typed(b,'20,30');typed(b,'2');typed(b,'450');let instance=b.read('modelReader.records().find(record=>record.type==="block-instance")');assert.equal(instance.definitionId,definition.id);assert.equal(instance.scale,2);assert.ok(Math.abs(instance.rotation-Math.PI/2)<1e-12);assert.deepEqual({x:instance.insertionPoint.x,y:instance.insertionPoint.y},{x:20,y:30});b.launch('I');typed(b,'fixture');typed(b,'40,30');b.key('Enter');b.key('Enter');const instances=b.read('modelReader.records().filter(record=>record.type==="block-instance")');assert.equal(instances.length,2);assert.notEqual(instances[0].id,instances[1].id);assert.notEqual(instances[0].insertionPoint.featureId,instances[1].insertionPoint.featureId)})

test('Insert rejects invalid scale/name and cancellation without mutation',async()=>{const b=await browser();createBlock(b);const before=b.read('modelReader.snapshot()');b.launch('Insert');typed(b,'Missing');assert.equal(b.read('window.caderactCommandRouter.activeSession.phase'),'definition');typed(b,'Fixture');typed(b,'0,0');for(const value of ['0','-1','Infinity']){typed(b,value);assert.equal(b.read('window.caderactCommandRouter.activeSession.phase'),'scale')}b.key('Escape');assert.deepEqual(b.read('modelReader.snapshot()'),before)})

test('Insert preview and committed display derive transformed semantic Line/Circle/Text without persistence expansion',async()=>{const b=await browser();createBlock(b);b.launch('Insert');typed(b,'Fixture');b.point(500,250,'pointermove');b.flush();let scene=b.renders.at(-1);assert.ok(scene.nextSegmentPreviewOverlay.segments.length>0);assert.ok(scene.propertyPreviewDrawGroups.some(group=>group.circleGroup.circles.length>0));assert.ok(scene.annotationOverlay.items.some(item=>item.preview&&item.role==='text'));b.point(500,250);b.key('Enter');b.key('Enter');b.flush();scene=b.renders.at(-1);assert.ok(scene.lineGroups.some(group=>group.segments.length>0));assert.ok(scene.circleOverlay.committed.length>0);assert.ok(scene.annotationOverlay.items.some(item=>!item.preview&&item.role==='text'));const json=b.run('window.CaderactPersistence.serializeDocument(modelReader.snapshot())');assert.equal(json.includes('preview-instance'),false);assert.equal(json.includes('semanticId'),false)})

test('Insert Undo/Redo and persistence preserve exact instance and definition',async()=>{const b=await browser(),{definition}=createBlock(b);b.launch('Insert');typed(b,'Fixture');typed(b,'10,20');b.key('Enter');b.key('Enter');const instance=b.read('modelReader.records().find(record=>record.type==="block-instance")');b.run('window.caderactHistory.undo()');assert.equal(b.read('modelReader.records().some(record=>record.type==="block-instance")'),false);b.run('window.caderactHistory.redo()');assert.deepEqual(b.read('modelReader.records().find(record=>record.type==="block-instance")'),instance);b.run('window.__restored=window.CaderactPersistence.deserializeDocument(window.CaderactPersistence.serializeDocument(modelReader.snapshot()))');assert.deepEqual(b.read('window.__restored.blockDefinitions[modelReader.blockDefinitions()[0].id]'),definition);assert.deepEqual(b.read('window.__restored.geometry.objects[modelReader.records().find(record=>record.type==="block-instance").id]'),instance)})

test('Block instances expose only direct Insertion Osnap while tracking and measurement remain excluded',async()=>{const b=await browser();createBlock(b);b.launch('Insert');typed(b,'Fixture');typed(b,'100,100');b.key('Enter');b.key('Enter');b.launch('Line');b.point(900,-200,'pointermove');assert.equal(b.read('activeSnapResult.kind'),'insertion');assert.equal(b.read('activeSnapResult.reference.recordId'),b.read('modelReader.records().find(record=>record.type==="block-instance").id'));b.advance(500);assert.equal(b.read('window.caderactViewport.getObjectSnapTrackingState().acquired'),null);b.key('Escape');assert.equal(b.read('window.CaderactMeasurement.measureRecord(modelReader.records().find(record=>record.type==="block-instance"))'),null)})
