'use strict';
const {test}=require('node:test');const assert=require('node:assert/strict');const {browser}=require('../helpers/browser.cjs');
function typed(b,value){b.input.value=value;b.emit(b.input,'input');return b.key('Enter',b.input)}
function seed(b){return JSON.parse(JSON.stringify(b.run(`(()=>{const records=[recordGateway.createLine({x:0,y:0},{x:4,y:0}),recordGateway.createText({insertionPoint:{x:0,y:2},text:'Edit',height:1,rotation:0}),recordGateway.createRegion([recordGateway.createCircle({x:8,y:0},2)]),recordGateway.createHatch([recordGateway.createCircle({x:14,y:0},2)],{kind:'named',name:'ANSI31',angle:.2,scale:1,origin:{x:0,y:0}}),recordGateway.createLinearDimension({mode:'aligned',firstPoint:{x:0,y:5},secondPoint:{x:4,y:5},dimensionLinePoint:{x:0,y:7}})];return window.caderactDocumentSession.blockDefinitionGateway.create({name:'Editable',records}).definition})()`)))}

test('GB6 registers BlockEdit and opens an isolated identity-preserving workspace',async()=>{const b=await browser(),definition=seed(b),selection=b.read('window.caderactSelection.selectedIds()');assert.equal(b.read('window.caderactCommandRegistry.resolve("BE").name'),'BlockEdit');b.launch('BlockEdit');typed(b,'Editable');assert.equal(b.read('window.caderactCommandRouter.activeSession.phase'),'edit');assert.deepEqual(b.read('window.caderactCommandRouter.activeSession.workspace.snapshot()'),definition);assert.deepEqual(b.read('modelReader.blockDefinition(window.caderactCommandRouter.activeSession.workspace.original.id)'),definition);assert.deepEqual(b.read('window.caderactSelection.selectedIds()'),selection)})

test('GB6 local Move Rotate Scale Mirror preserve IDs while Copy/Delete stay isolated',async()=>{const b=await browser(),definition=seed(b),id=definition.recordOrder[0];b.launch('BE');typed(b,'Editable');b.run(`window.__w=window.caderactCommandRouter.activeSession.workspace;window.__w.select([${JSON.stringify(id)}]);window.__w.move(2,3);window.__w.rotate({x:0,y:0},Math.PI/2);window.__w.scale({x:0,y:0},2);window.__w.mirror({x:0,y:0},{x:0,y:1});window.__copies=window.__w.copy(5,0)`);const working=b.read('window.__w.snapshot()');assert.ok(working.records[id]);assert.equal(working.recordOrder.length,definition.recordOrder.length+1);assert.notEqual(b.read('window.__copies[0]'),id);assert.notEqual(working.records[b.read('window.__copies[0]')].start.featureId,definition.records[id].start.featureId);assert.deepEqual(b.read('modelReader.blockDefinitions()[0]'),definition);b.run('window.__w.deleteSelected()');assert.equal(b.read('window.__w.snapshot().recordOrder.length'),definition.recordOrder.length);assert.deepEqual(b.read('modelReader.blockDefinitions()[0]'),definition)})

test('GB6 Apply is one history step and updates many direct and transitive instances without rewriting them',async()=>{const b=await browser(),definition=seed(b),id=definition.recordOrder[0];b.run(`window.__nested=recordGateway.createBlockInstance({definitionId:${JSON.stringify(definition.id)},insertionPoint:{x:0,y:0}});window.__container=window.caderactDocumentSession.blockDefinitionGateway.create({name:'Container',records:[window.__nested]}).definition;window.__instances=[recordGateway.createBlockInstance({definitionId:${JSON.stringify(definition.id)},insertionPoint:{x:20,y:0}}),recordGateway.createBlockInstance({definitionId:window.__container.id,insertionPoint:{x:40,y:0}})];recordGateway.createAll(window.__instances);window.__instancesBefore=JSON.parse(JSON.stringify(window.__instances)).sort((a,c)=>a.id.localeCompare(c.id));window.__history=documentController.historyInfo.entryCount`);b.launch('BlockEdit');typed(b,'Editable');b.run(`window.__w=window.caderactCommandRouter.activeSession.workspace;window.__w.select([${JSON.stringify(id)}]);window.__w.move(10,0)`);b.key('Enter');const edited=b.read(`modelReader.blockDefinition(${JSON.stringify(definition.id)})`);assert.equal(b.read('documentController.historyInfo.entryCount'),b.read('window.__history')+1);assert.deepEqual(b.read('modelReader.records()'),b.read('window.__instancesBefore'));assert.notDeepEqual(edited,definition);b.run('window.caderactHistory.undo()');assert.deepEqual(b.read(`modelReader.blockDefinition(${JSON.stringify(definition.id)})`),definition);b.run('window.caderactHistory.redo()');assert.deepEqual(b.read(`modelReader.blockDefinition(${JSON.stringify(definition.id)})`),edited)})

test('GB6 Text Dimension Region Hatch and nested instances use shared semantic transforms',async()=>{const b=await browser(),definition=seed(b);b.run(`window.__nested=recordGateway.createBlockInstance({definitionId:${JSON.stringify(definition.id)},insertionPoint:{x:2,y:2},rotation:.2,scale:2,mirrored:false});window.__holder=window.caderactDocumentSession.blockDefinitionGateway.create({name:'Holder',records:[window.__nested]}).definition`);b.launch('BlockEdit');typed(b,'Editable');b.run('window.__w=window.caderactCommandRouter.activeSession.workspace;window.__w.select(window.__w.snapshot().recordOrder);window.__w.rotate({x:0,y:0},.4);window.__w.scale({x:0,y:0},2);window.__w.mirror({x:0,y:0},{x:0,y:1})');const working=b.read('window.__w.snapshot()');assert.deepEqual(working.recordOrder,definition.recordOrder);assert.ok(Object.values(working.records).some(record=>record.type==='text'&&record.height===2));assert.ok(Object.values(working.records).some(record=>record.type==='dimension-linear'));assert.ok(Object.values(working.records).some(record=>record.type==='region'));assert.ok(Object.values(working.records).some(record=>record.type==='hatch'));b.flush();assert.ok(b.renders.at(-1).annotationOverlay.items.length>=2);b.key('Enter')})

test('GB6 Cancel and Escape discard all local edits without history or selection mutation',async()=>{for(const escape of [false,true]){const b=await browser(),definition=seed(b),id=definition.recordOrder[0];b.run('window.caderactSelection.clear();window.__beforeHistory=documentController.historyInfo.entryCount');b.launch('BlockEdit');typed(b,'Editable');b.run(`window.caderactCommandRouter.activeSession.workspace.select([${JSON.stringify(id)}]);window.caderactCommandRouter.activeSession.workspace.move(99,99)`);escape?b.key('Escape'):b.run('window.caderactCommandRouter.activeSession.cancel()');assert.deepEqual(b.read('modelReader.blockDefinitions()[0]'),definition);assert.equal(b.read('documentController.historyInfo.entryCount'),b.read('window.__beforeHistory'));assert.deepEqual(b.read('window.caderactSelection.selectedIds()'),[])}})

test('GB6 cyclic and invalid replacements fail atomically through the shared graph validator',async()=>{const b=await browser(),a=seed(b),lineId=a.recordOrder[0];b.run(`window.__back=recordGateway.createBlockInstance({definitionId:${JSON.stringify(a.id)},insertionPoint:{x:0,y:0}});window.__bdef=window.caderactDocumentSession.blockDefinitionGateway.create({name:'Back',records:[window.__back]}).definition;window.__before=JSON.parse(JSON.stringify(modelReader.snapshot()));window.__history=documentController.historyInfo.entryCount`);b.launch('BlockEdit');typed(b,'Editable');b.run(`window.__w=window.caderactCommandRouter.activeSession.workspace;window.__bad=recordGateway.createBlockInstance({definitionId:window.__bdef.id,insertionPoint:{x:0,y:0}});window.__w.replaceMember({...window.__bad,id:${JSON.stringify(lineId)}})`);const outcome=b.run('window.caderactCommandRouter.activeSession.workspace.apply()');assert.equal(outcome.status,'validation-failed');assert.deepEqual(b.read('modelReader.snapshot()'),b.read('window.__before'));assert.equal(b.read('documentController.historyInfo.entryCount'),b.read('window.__history'))})

test('GB6 applied definitions persist exactly and workspace state is never serialized',async()=>{const b=await browser(),definition=seed(b),id=definition.recordOrder[0];b.launch('BlockEdit');typed(b,'Editable');b.run(`window.caderactCommandRouter.activeSession.workspace.select([${JSON.stringify(id)}]);window.caderactCommandRouter.activeSession.workspace.move(3,4)`);b.key('Enter');const edited=b.read('modelReader.blockDefinitions()[0]');b.run('window.__payload=window.CaderactPersistence.serializeDocument(modelReader.snapshot());window.__loaded=window.CaderactPersistence.deserializeDocument(window.__payload)');assert.deepEqual(b.read(`window.__loaded.blockDefinitions[${JSON.stringify(definition.id)}]`),edited);assert.equal(b.run('window.__payload.includes("block-edit")||window.__payload.includes("selectedIds")'),false)})
