'use strict';
const {test}=require('node:test');const assert=require('node:assert/strict');const {browser}=require('../helpers/browser.cjs');
function seed(b,nested=false){b.run(`window.__members=[recordGateway.createLine({x:0,y:0},{x:4,y:0}),recordGateway.createCircle({x:6,y:0},2),recordGateway.createPolyline([{x:0,y:2},{x:2,y:4},{x:4,y:2}],true),recordGateway.createText({insertionPoint:{x:0,y:6},text:'GB7',height:1,rotation:0}),recordGateway.createLinearDimension({mode:'aligned',firstPoint:{x:0,y:0},secondPoint:{x:4,y:0},dimensionLinePoint:{x:0,y:1}})];window.__base=blockDefinitionGateway.create({name:'Base',records:window.__members}).definition;window.__definition=window.__base;${nested?`window.__child=recordGateway.createBlockInstance({definitionId:window.__base.id,insertionPoint:{x:3,y:2},rotation:.25,scale:2,mirrored:true});window.__definition=blockDefinitionGateway.create({name:'Nested',records:[window.__child]}).definition;`:''}window.__instance=recordGateway.createBlockInstance({definitionId:window.__definition.id,insertionPoint:{x:20,y:10},rotation:.5,scale:3,mirrored:false});recordGateway.createAll([window.__instance])`);return b.read('window.__instance')}

test('GB7 registers Explode and X',async()=>{const b=await browser();for(const name of ['Explode','X'])assert.equal(b.read(`window.caderactCommandRegistry.resolve(${JSON.stringify(name)}).name`),'Explode')});

test('Block Instance Copy uses normal Copy with fresh identities and exact Undo/Redo',async()=>{const b=await browser(),source=seed(b);b.run('window.caderactSelection.selectOnly(window.__instance.id)');b.launch('Copy');b.input.value='0,0';b.key('Enter',b.input);b.input.value='5,2';b.key('Enter',b.input);const copy=b.read('modelReader.records().find(r=>r.id!==window.__instance.id)');assert.notEqual(copy.id,source.id);assert.notEqual(copy.insertionPoint.featureId,source.insertionPoint.featureId);assert.equal(copy.definitionId,source.definitionId);assert.deepEqual({rotation:copy.rotation,scale:copy.scale,mirrored:copy.mirrored},{rotation:source.rotation,scale:source.scale,mirrored:source.mirrored});assert.deepEqual(b.read('modelReader.records().find(r=>r.id===window.__instance.id)'),source);b.run('window.caderactHistory.undo()');assert.equal(b.read(`modelReader.records().some(r=>r.id===${JSON.stringify(copy.id)})`),false);b.run('window.caderactHistory.redo()');assert.deepEqual(b.read(`modelReader.records().find(r=>r.id===${JSON.stringify(copy.id)})`),copy)});

test('shared Move Rotate Scale Mirror transforms preserve Block identity/reference semantics',async()=>{const b=await browser(),source=seed(b);b.run(`window.__moves=[window.CaderactGeometryTransform.translateRecord(window.__instance,2,3),window.CaderactGeometryTransform.rotateRecord(window.__instance,{x:0,y:0},.2),window.CaderactGeometryTransform.scaleRecord(window.__instance,{x:0,y:0},2),window.CaderactGeometryTransform.mirrorRecord(window.__instance,{x:0,y:0},{x:0,y:1})]`);for(const record of b.read('window.__moves')){assert.equal(record.id,source.id);assert.equal(record.insertionPoint.featureId,source.insertionPoint.featureId);assert.equal(record.definitionId,source.definitionId);assert.ok(record.scale>0)}});

test('recursive Explode emits transformed native semantics with fresh identities and exact history',async()=>{const b=await browser(),source=seed(b,true),definition=b.read('window.__definition'),memberIds=b.read('window.__members.flatMap(r=>[r.id,r.start?.featureId,r.end?.featureId,r.insertionPoint?.featureId,...(r.vertices||[]).map(v=>v.featureId)].filter(Boolean))');b.run('window.caderactSelection.selectOnly(window.__instance.id)');b.launch('Explode');b.key('Enter');const outputs=b.read('modelReader.records()'),selected=b.read('window.caderactSelection.selectedIds()');assert.deepEqual(outputs.map(r=>r.type).sort(),['circle','dimension-linear','line','polyline','text']);assert.equal(outputs.some(r=>r.type==='block-instance'),false);assert.ok(outputs.every(r=>!memberIds.includes(r.id)));assert.ok(outputs.flatMap(r=>[r.start?.featureId,r.end?.featureId,r.insertionPoint?.featureId,...(r.vertices||[]).map(v=>v.featureId)].filter(Boolean)).every(id=>!memberIds.includes(id)));assert.deepEqual(selected,outputs.map(r=>r.id).sort());assert.deepEqual(b.read('modelReader.blockDefinition(window.__definition.id)'),definition);b.run('window.caderactHistory.undo()');assert.deepEqual(b.read('modelReader.records()'),[source]);b.run('window.caderactHistory.redo()');assert.deepEqual(b.read('modelReader.records()'),outputs)});

test('Explode rejects locked, grouped, and mixed selections atomically',async()=>{for(const mode of ['locked','grouped','mixed']){const b=await browser();seed(b);if(mode==='locked')b.run(`layerGateway.create('Locked');window.__layer=modelReader.layers().find(layer=>layer.name==='Locked');recordGateway.assignLayer([window.__instance.id],window.__layer.id);window.__tx=documentController.beginTransaction();window.__tx.replaceIn('layers',window.__layer.id,{...window.__layer,locked:true});window.__tx.publish();window.caderactSelection.selectOnly(window.__instance.id)`);if(mode==='grouped')b.run(`window.__other=recordGateway.createLine({x:0,y:0},{x:1,y:0});recordGateway.createAll([window.__other]);groupGateway.createGroup([window.__instance.id,window.__other.id]);window.caderactSelection.selectOnly(window.__instance.id)`);if(mode==='mixed')b.run(`window.__other=recordGateway.createLine({x:0,y:0},{x:1,y:0});recordGateway.createAll([window.__other]);window.caderactSelection.applyRecordIds([window.__instance.id,window.__other.id])`);const before=b.read('modelReader.snapshot()');b.launch('Explode');b.key('Enter');assert.deepEqual(b.read('modelReader.snapshot()'),before);assert.equal(b.read('window.caderactCommandRouter.activeCommand'),'Explode')}});

test('Explode persistence stays semantic and native outputs regain native authorities',async()=>{const b=await browser();seed(b,true);b.run('window.__out=recordGateway.explodeBlockInstances([window.__instance.id]);window.__serialized=window.CaderactPersistence.serializeDocument(modelReader.snapshot());window.__loaded=window.CaderactPersistence.loadStore(window.__serialized)');assert.equal(b.read('window.__out.status'),'committed');assert.equal(b.run('window.__serialized.includes("semanticId")||window.__serialized.includes("instancePath")'),false);assert.deepEqual(b.read('window.__loaded.reader.snapshot()'),b.read('modelReader.snapshot()'));assert.ok(b.read('window.CaderactMeasurement.measureRecord(modelReader.records().find(r=>r.type==="line"))!==null'));assert.equal(b.read('modelReader.records().some(r=>r.type==="block-instance")'),false)});
