'use strict';
const {test}=require('node:test');const assert=require('node:assert/strict');const {browser}=require('../helpers/browser.cjs');
function typed(b,value){b.input.value=value;b.emit(b.input,'input');return b.key('Enter',b.input)}
function state(b){return b.read('({document:modelReader.snapshot(),revision:documentController.currentRevision,stateId:documentController.currentStateId,history:documentController.historyInfo.entryCount,dirty:documentController.isDirty})')}
const plain=value=>JSON.parse(JSON.stringify(value));
function seed(b){return plain(b.run(`(()=>{const records=[recordGateway.createLine({x:0,y:0},{x:10,y:0}),recordGateway.createCircle({x:20,y:5},4),recordGateway.createArc({center:{x:30,y:0},start:{x:34,y:0},end:{x:30,y:4},radius:4,sweep:Math.PI/2}),recordGateway.createEllipse({center:{x:40,y:0},majorAxis:{x:6,y:2},minorRadius:3}),recordGateway.createPolyline([{x:50,y:0},{x:55,y:5},{x:60,y:0}],true)];recordGateway.createAll(records);return records})()`))}
function featureIds(record){if(record.type==='line'||record.type==='arc')return[record.start.featureId,record.end.featureId];if(record.type==='polyline')return record.vertices.map(vertex=>vertex.featureId);return[]}

test('Copy uses non-conflicting CP alias while C remains Circle',async()=>{for(const command of ['Copy','CP']){const b=await browser();b.launch(command);assert.equal(b.read('window.caderactCommandRouter.activeCommand'),'Copy')}const circle=await browser();circle.launch('C');assert.equal(circle.read('window.caderactCommandRouter.activeCommand'),'Circle')});

test('Copy duplicates every native type atomically with fresh record and topology identities',async()=>{
  const b=await browser(),originals=seed(b),sourceIds=originals.map(record=>record.id);b.run(`window.caderactSelection.applyRecordIds(${JSON.stringify(sourceIds)})`);const before=state(b);b.launch('Copy');typed(b,'0,0');typed(b,'@5,-2');const copyIds=plain(b.read('window.caderactCommandRouter.lastResult.recordIds')),all=plain(b.read('modelReader.records()')),copies=copyIds.map(id=>all.find(record=>record.id===id));
  assert.equal(copies.length,originals.length);assert.ok(copyIds.every(id=>!sourceIds.includes(id)));assert.equal(b.read('documentController.currentRevision'),before.revision+1);assert.equal(b.read('documentController.historyInfo.entryCount'),before.history+1);assert.deepEqual(plain(b.read('window.caderactSelection.selectedIds()')),copyIds.slice().sort());
  for(const original of originals){const current=all.find(record=>record.id===original.id),copy=copies.find(record=>record.type===original.type);assert.deepEqual(current,original);assert.equal(copy.layerId,original.layerId);assert.equal(copy.type,original.type);for(const id of featureIds(copy))assert.equal(featureIds(original).includes(id),false)}
  const ellipseOriginal=originals.find(r=>r.type==='ellipse'),ellipseCopy=copies.find(r=>r.type==='ellipse');assert.deepEqual(ellipseCopy.majorAxis,ellipseOriginal.majorAxis);assert.equal(ellipseCopy.minorRadius,ellipseOriginal.minorRadius);const polyOriginal=originals.find(r=>r.type==='polyline'),polyCopy=copies.find(r=>r.type==='polyline');assert.equal(polyCopy.closed,true);assert.deepEqual(polyCopy.vertices.map(v=>({x:v.x,y:v.y})),polyOriginal.vertices.map(v=>({x:v.x+5,y:v.y-2})));
  b.run('window.caderactHistory.undo()');assert.deepEqual(plain(b.read('modelReader.records()')),originals.slice().sort((a,c)=>a.id.localeCompare(c.id)));b.run('window.caderactHistory.redo()');const redone=plain(b.read('modelReader.records()'));for(const copy of copies)assert.deepEqual(redone.find(record=>record.id===copy.id),copy)
});

test('Copy preview keeps authoritative source normal, shares feedback, and applies Shift Ortho',async()=>{
  const b=await browser(),record=plain(b.run('recordGateway.createLine({x:0,y:0},{x:10,y:0})'));b.run(`recordGateway.createAll(${JSON.stringify([record])});window.caderactSelection.selectOnly(${JSON.stringify(record.id)})`);b.launch('Copy');typed(b,'20,20');const before=state(b);b.point(401,299,'pointermove');b.flush();assert.equal(b.read('activeSnapResult.kind'),'endpoint');assert.deepEqual(b.read('activeSnapResult.point'),{x:0,y:0});assert.deepEqual(state(b),before);b.point(403,297,'pointermove',{shiftKey:true});b.flush();assert.equal(b.read('activeSnapResult.snapped'),false);assert.deepEqual(plain(b.renders.at(-1).transformOverlay.candidatePoint),{x:403,y:200});assert.deepEqual(state(b),before);b.key('Escape');b.flush();assert.equal(b.renders.at(-1).transformOverlay,null);assert.deepEqual(state(b),before)
});

test('Copy postselection reuses click confirmation and zero displacement creates nothing',async()=>{
  const b=await browser(),record=plain(b.run('recordGateway.createLine({x:-10,y:0},{x:10,y:0})'));b.run(`recordGateway.createAll(${JSON.stringify([record])})`);b.launch('Copy');assert.equal(b.read('window.caderactCommandRouter.activeSession.phase'),'selection');b.point(400,300);b.key('Enter');assert.equal(b.read('window.caderactCommandRouter.activeSession.phase'),'base');const before=state(b);typed(b,'0,0');typed(b,'0,0');assert.deepEqual(state(b),before);assert.equal(b.read('modelReader.records().length'),1);assert.equal(b.read('window.caderactCommandRouter.activeCommand'),null)
});

test('Copy transaction failure publishes no partial records and preserves coherent retry preview',async()=>{
  const b=await browser(),originals=seed(b),ids=originals.map(record=>record.id);b.run(`window.caderactSelection.applyRecordIds(${JSON.stringify(ids)})`);b.launch('CP');typed(b,'0,0');b.run('window.__blocking=documentController.beginTransaction()');typed(b,'5,5');b.flush();assert.equal(b.read('window.caderactCommandRouter.activeCommand'),'Copy');assert.equal(b.read('modelReader.records().length'),5);assert.notEqual(b.renders.at(-1).transformOverlay,null);assert.equal(b.renders.at(-1).nextSegmentPreviewOverlay.segments.length,16);b.run('window.__blocking.rollback()');typed(b,'5,5');b.flush();assert.equal(b.read('modelReader.records().length'),10);assert.equal(b.renders.at(-1).transformOverlay,null);assert.equal(b.read('window.caderactCommandRouter.activeCommand'),null)
});
