'use strict';
const {test}=require('node:test');const assert=require('node:assert/strict');const {browser}=require('../helpers/browser.cjs');
const plain=value=>JSON.parse(JSON.stringify(value));
function state(b){return b.read('({document:modelReader.snapshot(),revision:documentController.currentRevision,stateId:documentController.currentStateId,history:documentController.historyInfo.entryCount,dirty:documentController.isDirty})')}
function createLine(b,a,c){return plain(b.run(`recordGateway.createLine(${JSON.stringify(a)},${JSON.stringify(c)})`))}
function add(b,records){b.run(`recordGateway.createAll(${JSON.stringify(records)})`)}
function finish(b){b.key('Enter',b.document)}
function drag(b,start,end,props={}){b.point(...start,'pointerdown',props);b.point(...end,'pointermove',props);b.point(...end,'pointerup',props)}

test('Delete resolves all aliases and deletes a preselected Line in one transaction',async()=>{for(const command of ['Delete','DEL','E','ERASE']){const b=await browser();b.launch(command);assert.equal(b.read('window.caderactCommandRouter.activeCommand'),'Delete')}const b=await browser(),line=createLine(b,{x:0,y:0},{x:10,y:0});add(b,[line]);b.run(`window.caderactSelection.selectOnly(${JSON.stringify(line.id)})`);const before=state(b);b.launch('Delete');assert.equal(b.read('window.caderactCommandRouter.activeSession.isSelectionPhase'),true);finish(b);assert.equal(b.read('modelReader.records().length'),0);assert.equal(b.read('documentController.currentRevision'),before.revision+1);assert.equal(b.read('documentController.historyInfo.entryCount'),before.history+1);assert.deepEqual(b.read('window.caderactSelection.selectedIds()'),[]);b.run('window.caderactHistory.undo()');assert.deepEqual(plain(b.read('modelReader.records()')),[line]);b.run('window.caderactHistory.redo()');assert.equal(b.read('modelReader.records().length'),0)});

test('Delete postselection reuses click, Window, Crossing, and Ctrl/Meta selection semantics',async()=>{const b=await browser(),a=createLine(b,{x:-10,y:0},{x:10,y:0}),c=createLine(b,{x:20,y:0},{x:30,y:0}),cross=createLine(b,{x:-40,y:10},{x:40,y:10});add(b,[a,c,cross]);b.launch('Delete');b.point(400,300);assert.deepEqual(b.read('window.caderactSelection.selectedIds()'),[a.id]);b.point(525,300,'pointerdown',{ctrlKey:true});assert.deepEqual(new Set(b.read('window.caderactSelection.selectedIds()')),new Set([a.id,c.id]));b.point(525,300,'pointerdown',{metaKey:true});assert.deepEqual(b.read('window.caderactSelection.selectedIds()'),[a.id]);drag(b,[300,240],[500,360]);assert.deepEqual(b.read('window.caderactSelection.selectedIds()'),[a.id]);drag(b,[500,240],[300,360],{ctrlKey:true});const selected=b.read('window.caderactSelection.selectedIds()');assert.ok(selected.includes(cross.id));finish(b);assert.ok(selected.every(id=>!b.read(`modelReader.records().some(record=>record.id===${JSON.stringify(id)})`)));assert.deepEqual(b.read('window.caderactSelection.selectedIds()'),[])});

test('Delete removes native geometry and Rectangle/Polygon Line collections with exact Undo/Redo identity',async()=>{const b=await browser();const records=plain(b.run(`(()=>{const rectangle=[recordGateway.createLine({x:0,y:0},{x:5,y:0}),recordGateway.createLine({x:5,y:0},{x:5,y:5}),recordGateway.createLine({x:5,y:5},{x:0,y:5}),recordGateway.createLine({x:0,y:5},{x:0,y:0})];const polygon=[recordGateway.createLine({x:10,y:0},{x:15,y:5}),recordGateway.createLine({x:15,y:5},{x:20,y:0}),recordGateway.createLine({x:20,y:0},{x:10,y:0})];return [recordGateway.createCircle({x:30,y:0},4),recordGateway.createArc({center:{x:40,y:0},start:{x:44,y:0},end:{x:40,y:4},radius:4,sweep:Math.PI/2}),recordGateway.createEllipse({center:{x:50,y:0},majorAxis:{x:4,y:1},minorRadius:2}),recordGateway.createPolyline([{x:60,y:0},{x:65,y:5},{x:70,y:0}],true),...rectangle,...polygon]})()`));add(b,records);b.run(`window.caderactSelection.applyRecordIds(${JSON.stringify(records.map(record=>record.id))})`);const before=state(b);b.launch('Delete');finish(b);assert.equal(b.read('modelReader.records().length'),0);assert.equal(b.read('documentController.historyInfo.entryCount'),before.history+1);b.run('window.caderactHistory.undo()');assert.deepEqual(plain(b.read('modelReader.records()')),records.slice().sort((x,y)=>x.id.localeCompare(y.id)));b.run('window.caderactHistory.redo()');assert.equal(b.read('modelReader.records().length'),0)});

test('Delete empty selection and Escape are history-free, while failed publication remains retryable',async()=>{const b=await browser(),line=createLine(b,{x:0,y:0},{x:10,y:0});add(b,[line]);const before=state(b);b.launch('Delete');finish(b);assert.deepEqual(state(b),before);b.launch('Delete');b.point(400,300);b.key('Escape',b.document);assert.deepEqual(state(b),before);assert.deepEqual(b.read('window.caderactSelection.selectedIds()'),[line.id]);b.launch('Delete');b.run('window.__blocking=documentController.beginTransaction()');finish(b);assert.equal(b.read('window.caderactCommandRouter.activeCommand'),'Delete');assert.deepEqual(plain(b.read('modelReader.records()')),[line]);b.run('window.__blocking.rollback()');finish(b);assert.equal(b.read('window.caderactCommandRouter.activeCommand'),null);assert.equal(b.read('modelReader.records().length'),0)});

test('idle Delete key invokes Delete for a committed selection but never destroys command-bar text',async()=>{const b=await browser(),line=createLine(b,{x:0,y:0},{x:10,y:0});add(b,[line]);b.run(`window.caderactSelection.selectOnly(${JSON.stringify(line.id)})`);b.input.value='erase';const inputEvent=b.key('Delete',b.input);assert.equal(inputEvent.defaultPrevented,false);assert.equal(b.read('modelReader.records().length'),1);const event=b.key('Delete',b.canvas);assert.equal(event.defaultPrevented,true);assert.equal(b.read('modelReader.records().length'),0)});

test('idle Backspace deletes committed selections atomically with exact Undo/Redo while text fields retain editing',async()=>{const b=await browser(),first=createLine(b,{x:0,y:0},{x:10,y:0}),second=createLine(b,{x:20,y:0},{x:30,y:0});add(b,[first,second]);const before=state(b);const idle=b.key('Backspace',b.canvas);assert.equal(idle.defaultPrevented,false);assert.deepEqual(state(b),before);b.run(`window.caderactSelection.applyRecordIds(${JSON.stringify([first.id,second.id])})`);const event=b.key('Backspace',b.canvas);assert.equal(event.defaultPrevented,true);assert.equal(b.read('modelReader.records().length'),0);assert.equal(b.read('documentController.historyInfo.entryCount'),before.history+1);b.run('window.caderactHistory.undo()');assert.deepEqual(plain(b.read('modelReader.records()')),[first,second].sort((a,c)=>a.id.localeCompare(c.id)));b.run('window.caderactHistory.redo()');assert.equal(b.read('modelReader.records().length'),0);const text=await browser(),line=createLine(text,{x:0,y:0},{x:10,y:0});add(text,[line]);text.run(`window.caderactSelection.selectOnly(${JSON.stringify(line.id)})`);text.input.value='erase';const backspace=text.key('Backspace',text.input),deleteKey=text.key('Delete',text.input);assert.equal(backspace.defaultPrevented,false);assert.equal(deleteKey.defaultPrevented,false);assert.equal(text.read('modelReader.records().length'),1);text.launch('Line');const active=text.key('Backspace',text.canvas);assert.equal(active.defaultPrevented,false);assert.equal(text.read('window.caderactCommandRouter.activeCommand'),'Line')});
