'use strict';
const {test}=require('node:test');
const assert=require('node:assert/strict');
const {browser}=require('../helpers/browser.cjs');

function seed(b){b.run('window.__member=recordGateway.createLine({x:0,y:0},{x:10,y:0});window.__definition=blockDefinitionGateway.create({name:"Editable",records:[window.__member]}).definition;window.__instanceA=recordGateway.createBlockInstance({definitionId:window.__definition.id,insertionPoint:{x:20,y:0}});window.__instanceB=recordGateway.createBlockInstance({definitionId:window.__definition.id,insertionPoint:{x:40,y:0}});window.__modelLine=recordGateway.createLine({x:0,y:20},{x:10,y:20});recordGateway.createAll([window.__instanceA,window.__instanceB,window.__modelLine])');return b.read('window.__definition')}
const state=b=>b.read('({document:modelReader.snapshot(),history:documentController.historyInfo,dirty:documentController.isDirty})');

test('GBUX3 enters the one BlockEdit authority from Blocks panel and shows contextual identity',async()=>{const b=await browser();seed(b);b.run('window.__entry=window.caderactBlocks.edit(window.__definition.id)');assert.equal(b.read('window.__entry.status'),'input-accepted');assert.equal(b.read('window.caderactCommandRouter.activeCommand'),'BlockEdit');assert.equal(b.read('window.caderactCommandRouter.activeSession.phase'),'edit');assert.equal(b.blockEditContext.hidden,false);assert.equal(b.blockEditName.textContent,'Editable');assert.equal(b.read('window.caderactBlockEditContext.getState().definitionName'),'Editable')});

test('GBUX3 selected Block Instance Properties enters the same BlockEdit session',async()=>{const b=await browser();seed(b);b.run('window.caderactSelection.selectOnly(window.__instanceA.id);window.caderactPropertiesPanel.open()');const section=b.propertiesContent.children.find(node=>node.children[0]?.textContent==='Block Transform'),button=section.children.find(node=>node.children[0]?.textContent==='Block Editing').children[1];b.emit(button,'click');assert.equal(b.read('window.caderactCommandRouter.activeCommand'),'BlockEdit');assert.equal(b.read('window.caderactCommandRouter.activeSession.definition.id'),b.read('window.__definition.id'));assert.equal(b.blockEditContext.hidden,false)});

test('GBUX3 pointer selection is isolated to definition members and never changes model selection',async()=>{const b=await browser(),definition=seed(b);b.run('window.caderactSelection.selectOnly(window.__modelLine.id);window.caderactBlocks.edit(window.__definition.id)');const before=b.read('window.caderactSelection.selectedIds()');b.point(405,300);assert.deepEqual(b.read('window.caderactCommandRouter.activeSession.workspace.selectedIds'),[definition.recordOrder[0]]);assert.deepEqual(b.read('window.caderactSelection.selectedIds()'),before);b.point(405,280);assert.deepEqual(b.read('window.caderactCommandRouter.activeSession.workspace.selectedIds'),[]);assert.deepEqual(b.read('window.caderactSelection.selectedIds()'),before)});

test('GBUX3 Save Changes commits once, updates all instances, and Undo/Redo is exact',async()=>{const b=await browser(),original=seed(b),id=original.recordOrder[0],instances=b.read('[window.__instanceA,window.__instanceB]');const before=b.read('documentController.historyInfo.entryCount');b.run(`window.caderactBlocks.edit(window.__definition.id);window.__workspace=window.caderactCommandRouter.activeSession.workspace;window.__workspace.select([${JSON.stringify(id)}]);window.__workspace.move(5,2)`);b.emit(b.blockEditSave,'click');const edited=b.read('modelReader.blockDefinition(window.__definition.id)');assert.notDeepEqual(edited,original);assert.equal(b.read('documentController.historyInfo.entryCount'),before+1);assert.deepEqual(b.read('modelReader.records().filter(record=>record.type==="block-instance")'),instances.sort((a,c)=>a.id.localeCompare(c.id)));assert.equal(b.blockEditContext.hidden,true);b.run('documentController.undo()');assert.deepEqual(b.read('modelReader.blockDefinition(window.__definition.id)'),original);b.run('documentController.redo()');assert.deepEqual(b.read('modelReader.blockDefinition(window.__definition.id)'),edited)});

test('GBUX3 Discard and Escape restore exactly with no history while local copy/delete remain isolated',async()=>{for(const mode of ['discard','escape']){const b=await browser(),original=seed(b),id=original.recordOrder[0];b.run(`window.caderactBlocks.edit(window.__definition.id);window.__workspace=window.caderactCommandRouter.activeSession.workspace;window.__workspace.select([${JSON.stringify(id)}]);window.__workspace.copy(3,0);window.__workspace.deleteSelected()`);const before=state(b);mode==='discard'?b.emit(b.blockEditDiscard,'click'):b.key('Escape');assert.deepEqual(b.read('modelReader.blockDefinition(window.__definition.id)'),original);assert.deepEqual(state(b),before);assert.equal(b.blockEditContext.hidden,true);assert.equal(b.read('window.caderactCommandRouter.activeCommand'),null)}});

test('GBUX3 local member add/delete and nested transforms save without touching model-space records',async()=>{const b=await browser(),original=seed(b),modelBefore=b.read('modelReader.records()');b.run('window.__leafMember=recordGateway.createCircle({x:0,y:0},2);window.__leaf=blockDefinitionGateway.create({name:"Leaf",records:[window.__leafMember]}).definition;window.__nested=recordGateway.createBlockInstance({definitionId:window.__leaf.id,insertionPoint:{x:2,y:2}});window.__withNested=blockDefinitionGateway.create({name:"Nested",records:[window.__nested]}).definition;window.caderactBlocks.edit(window.__definition.id);window.__w=window.caderactCommandRouter.activeSession.workspace;window.__w.select([window.__definition.recordOrder[0]]);window.__added=window.__w.copy(2,0);window.caderactCommandRouter.activateOption("apply")');assert.equal(b.read('modelReader.blockDefinition(window.__definition.id).recordOrder.length'),original.recordOrder.length+1);assert.deepEqual(b.read('modelReader.records()'),modelBefore);b.run('window.caderactBlocks.edit(window.__withNested.id);window.__nw=window.caderactCommandRouter.activeSession.workspace;window.__nw.select([window.__nested.id]);window.__nw.move(3,4);window.caderactCommandRouter.activateOption("apply");window.__json=window.CaderactPersistence.serializeDocument(modelReader.snapshot());window.__loaded=window.CaderactPersistence.loadStore(window.__json)');assert.equal(b.read('window.__loaded.reader.blockDefinition(window.__withNested.id).records[window.__nested.id].definitionId'),b.read('window.__leaf.id'));assert.deepEqual(b.read('modelReader.records()'),modelBefore)});
