'use strict';
const {test}=require('node:test');
const assert=require('node:assert/strict');
const {browser}=require('../helpers/browser.cjs');

function definition(b,name='Fixture'){b.run(`window.__member=recordGateway.createLine({x:0,y:0},{x:4,y:0});window.__definition=blockDefinitionGateway.create({name:${JSON.stringify(name)},basePoint:{x:1,y:2},records:[window.__member]}).definition`);return b.read('window.__definition')}
const state=b=>b.read('({revision:documentController.currentRevision,history:documentController.historyInfo,dirty:documentController.isDirty})');

test('GBUX2 lists Block Definitions with model-space instance counts and compact inspection',async()=>{const b=await browser(),defined=definition(b);b.run('window.__one=recordGateway.createBlockInstance({definitionId:window.__definition.id,insertionPoint:{x:10,y:10}});window.__two=recordGateway.createBlockInstance({definitionId:window.__definition.id,insertionPoint:{x:20,y:10}});recordGateway.createAll([window.__one,window.__two])');assert.equal(b.blocksList.children.length,1);const row=b.blocksList.children[0];assert.equal(row.children[1].textContent,'Fixture');assert.equal(row.children[2].textContent,'2');b.emit(row.children[1],'click');assert.equal(b.blocksList.children.length,2);assert.match(b.blocksList.children[1].textContent,/Definition · 1 member · Base 1, 2/);assert.equal(defined.name,'Fixture')});

test('GBUX2 Create delegates selection, naming, and resolved base point to the existing Block command',async()=>{const b=await browser();b.run('window.__source=recordGateway.createCircle({x:0,y:0},3);recordGateway.createAll([window.__source]);window.caderactSelection.selectOnly(window.__source.id)');const before=b.read('documentController.historyInfo.entryCount');b.emit(b.blockCreateButton,'click');assert.equal(b.read('window.caderactCommandRouter.activeCommand'),'Block');assert.equal(b.read('window.caderactCommandRouter.activeSession.phase'),'name');b.run('window.caderactCommandRouter.submitActiveInput("Panel Block");window.caderactCommandRouter.submitActiveInput("5,6")');const created=b.read('modelReader.blockDefinitions()[0]');assert.equal(created.name,'Panel Block');assert.deepEqual(created.basePoint,{x:5,y:6});assert.equal(b.read('modelReader.records()[0].id'),b.read('window.__source.id'));assert.equal(b.read('documentController.historyInfo.entryCount'),before+1)});

test('GBUX2 Insert launches and seeds the existing Insert session',async()=>{const b=await browser();definition(b);b.run('window.__started=window.caderactBlocks.insert(window.__definition.id)');assert.equal(b.read('window.__started.status'),'input-accepted');assert.equal(b.read('window.caderactCommandRouter.activeCommand'),'Insert');assert.equal(b.read('window.caderactCommandRouter.activeSession.phase'),'insertion');assert.equal(b.read('window.caderactCommandRouter.activeSession.definition.id'),b.read('window.__definition.id'));b.run('window.caderactCommandRouter.submitActiveInput("12,14");window.caderactCommandRouter.finishActive();window.caderactCommandRouter.finishActive()');assert.equal(b.read('modelReader.records().filter(record=>record.type==="block-instance").length'),1)});

test('GBUX2 inline rename preserves definition and instance identities while cancellation is mutation-free',async()=>{const b=await browser(),defined=definition(b);b.run('window.__instance=recordGateway.createBlockInstance({definitionId:window.__definition.id,insertionPoint:{x:8,y:9}});recordGateway.createAll([window.__instance])');let row=b.blocksList.children[0];b.emit(row.children[1],'dblclick');let input=b.blocksList.children[0].children[1];input.value='Renamed';b.key('Enter',input);assert.equal(b.read('modelReader.blockDefinitions()[0].name'),'Renamed');assert.equal(b.read('modelReader.blockDefinitions()[0].id'),defined.id);assert.equal(b.read('modelReader.records().find(record=>record.type==="block-instance").definitionId'),defined.id);row=b.blocksList.children[0];b.emit(row.children[1],'dblclick');input=b.blocksList.children[0].children[1];const before=state(b);input.value='Discarded';b.key('Escape',input);assert.equal(b.read('modelReader.blockDefinitions()[0].name'),'Renamed');assert.deepEqual(state(b),before);b.run('window.caderactBlocks.beginRename(window.__definition.id)');b.emit(b.document,'pointerdown',{target:b.canvas});assert.equal(b.read('modelReader.blockDefinitions()[0].name'),'Renamed')});

test('GBUX2 Select Instances uses SelectionManager and does not mutate document state',async()=>{const b=await browser();definition(b);b.run('window.__instances=[recordGateway.createBlockInstance({definitionId:window.__definition.id,insertionPoint:{x:2,y:2}}),recordGateway.createBlockInstance({definitionId:window.__definition.id,insertionPoint:{x:4,y:4}})];recordGateway.createAll(window.__instances);documentController.markStateSaved(documentController.captureStateToken());window.caderactSelection.clear()');const before=state(b);b.run('window.__selected=window.caderactBlocks.selectInstances(window.__definition.id)');assert.deepEqual(b.read('window.caderactSelection.selectedIds()'),b.read('window.__instances.map(record=>record.id).sort()'));assert.equal(b.read('window.__selected.status'),'selection-replaced');assert.deepEqual(state(b),before)});

test('GBUX2 delete refuses live definitions and purge removes only unreachable definition graphs atomically',async()=>{const b=await browser();definition(b,'Leaf');b.run('window.__nested=recordGateway.createBlockInstance({definitionId:window.__definition.id,insertionPoint:{x:0,y:0}});window.__parent=blockDefinitionGateway.create({name:"Parent",records:[window.__nested]}).definition;window.__unusedMember=recordGateway.createCircle({x:0,y:0},1);window.__unused=blockDefinitionGateway.create({name:"Unused",records:[window.__unusedMember]}).definition;window.__placed=recordGateway.createBlockInstance({definitionId:window.__parent.id,insertionPoint:{x:20,y:20}});recordGateway.createAll([window.__placed]);window.__refused=window.caderactBlocks.remove(window.__definition.id)');assert.equal(b.read('window.__refused.status'),'definition-in-use');const before=b.read('documentController.historyInfo.entryCount');b.run('window.__purged=window.caderactBlocks.purge()');assert.equal(b.read('window.__purged.status'),'committed');assert.deepEqual(b.read('window.__purged.definitionIds'),[b.read('window.__unused.id')]);assert.deepEqual(b.read('modelReader.blockDefinitions().map(value=>value.name).sort()'),['Leaf','Parent']);assert.equal(b.read('documentController.historyInfo.entryCount'),before+1);b.run('documentController.undo()');assert.deepEqual(b.read('modelReader.blockDefinitions().map(value=>value.name).sort()'),['Leaf','Parent','Unused']);b.run('documentController.redo()');assert.deepEqual(b.read('modelReader.blockDefinitions().map(value=>value.name).sort()'),['Leaf','Parent'])});

test('GBUX2 deletes unused safely, round-trips renamed metadata, and popup flips inside viewport',async()=>{const b=await browser();definition(b);const id=b.read('window.__definition.id'),row=b.blocksList.children[0],more=row.children[3];more.getBoundingClientRect=()=>({left:970,right:994,top:740,bottom:764});b.window.innerWidth=1000;b.window.innerHeight=768;b.window.caderactBlockActionsMenu.offsetWidth=204;b.window.caderactBlockActionsMenu.offsetHeight=172;b.emit(more,'click');assert.equal(b.window.caderactBlockActionsMenu.dataset.placement,'above');assert.ok(parseFloat(b.window.caderactBlockActionsMenu.style.left)<=788);b.run('window.caderactBlocks.rename(window.__definition.id,"Saved Block");window.__json=window.CaderactPersistence.serializeDocument(modelReader.snapshot());window.__loaded=window.CaderactPersistence.loadStore(window.__json)');assert.deepEqual(b.read('window.__loaded.reader.blockDefinition(window.__definition.id)'),b.read('modelReader.blockDefinition(window.__definition.id)'));b.run('window.__removed=window.caderactBlocks.remove(window.__definition.id)');assert.equal(b.read('window.__removed.status'),'committed');assert.equal(b.read('modelReader.blockDefinition('+JSON.stringify(id)+')'),null)});
