'use strict';
const {test}=require('node:test');
const assert=require('node:assert/strict');
const {browser}=require('../helpers/browser.cjs');

function seed(b,count=4){b.run(`window.__records=Array.from({length:${count}},(_,index)=>recordGateway.createLine({x:index,y:0},{x:index,y:2}));recordGateway.createAll(window.__records)`);return b.read('window.__records')}
const state=b=>b.read('({revision:documentController.currentRevision,history:documentController.historyInfo,dirty:documentController.isDirty})');

test('GBUX1 creates a native Group from selection and renders compact membership',async()=>{const b=await browser(),records=seed(b),before=state(b);b.run('window.caderactSelection.applyRecordIds([window.__records[0].id,window.__records[1].id])');b.emit(b.groupCreateButton,'click');const group=b.read('modelReader.groups()[0]');assert.deepEqual(group.memberIds,[records[0].id,records[1].id].sort());assert.equal(b.groupsList.children.length,1);assert.equal(b.groupsList.children[0].children[0].textContent,'Group 1');assert.equal(b.groupsList.children[0].children[1].textContent,'2');assert.equal(state(b).history.entryCount,before.history.entryCount+1);b.run('documentController.undo()');assert.equal(b.read('modelReader.groups().length'),0);b.run('documentController.redo()');assert.deepEqual(b.read('modelReader.groups()[0]'),group)});

test('GBUX1 inline rename commits on Enter and Escape/outside cancel without mutation',async()=>{const b=await browser();seed(b);b.run('window.__group=groupGateway.createGroup([window.__records[0].id,window.__records[1].id]).group');let row=b.groupsList.children[0];b.emit(row.children[0],'dblclick');let input=b.groupsList.children[0].children[0];input.value='Frame';b.key('Enter',input);assert.equal(b.read('modelReader.groups()[0].name'),'Frame');row=b.groupsList.children[0];b.emit(row.children[0],'dblclick');input=b.groupsList.children[0].children[0];const before=state(b);input.value='Discarded';b.key('Escape',input);assert.equal(b.read('modelReader.groups()[0].name'),'Frame');assert.deepEqual(state(b),before);b.run('window.caderactGroups.beginRename(window.__group.id)');input=b.groupsList.children[0].children[0];input.value='Outside';b.emit(b.document,'pointerdown',{target:b.canvas});assert.equal(b.read('modelReader.groups()[0].name'),'Frame')});

test('GBUX1 add/remove membership is atomic, prevents duplicate ownership, and dissolves below two members',async()=>{const b=await browser(),records=seed(b,5);b.run('window.__a=groupGateway.createGroup([window.__records[0].id,window.__records[1].id],{name:"A"}).group;window.__b=groupGateway.createGroup([window.__records[3].id,window.__records[4].id],{name:"B"}).group;window.caderactSelection.applyRecordIds([window.__records[3].id]);window.__duplicate=window.caderactGroups.addSelection(window.__a.id)');assert.equal(b.read('window.__duplicate.status'),'already-grouped');const before=b.read('documentController.historyInfo.entryCount');b.run('window.caderactSelection.applyRecordIds([window.__records[2].id]);window.__add=window.caderactGroups.addSelection(window.__a.id)');assert.equal(b.read('window.__add.status'),'committed');assert.deepEqual(b.read('modelReader.group(window.__a.id).memberIds'),[records[0].id,records[1].id,records[2].id].sort());assert.equal(b.read('documentController.historyInfo.entryCount'),before+1);b.run('window.caderactGroups.removeSelection(window.__a.id)');assert.equal(b.read('modelReader.group(window.__a.id).memberIds.length'),2);b.run('window.caderactSelection.applyRecordIds([window.__records[0].id]);window.__remove=window.caderactGroups.removeSelection(window.__a.id)');assert.equal(b.read('window.__remove.dissolved'),true);assert.equal(b.read('modelReader.group(window.__a.id)'),null);b.run('documentController.undo()');assert.equal(b.read('modelReader.group(window.__a.id).memberIds.length'),2)});

test('GBUX1 Select Group uses SelectionManager without history or dirty mutation',async()=>{const b=await browser();seed(b);b.run('window.__group=groupGateway.createGroup([window.__records[0].id,window.__records[1].id]).group;documentController.markStateSaved(documentController.captureStateToken());window.caderactSelection.clear()');const before=state(b);b.run('window.__selected=window.caderactGroups.selectGroup(window.__group.id)');assert.deepEqual(b.read('window.caderactSelection.selectedTargets()'),[b.read('({kind:"group",id:window.__group.id,recordIds:window.__group.memberIds})')]);assert.deepEqual(state(b),before);assert.equal(b.read('window.__selected.status'),'selection-replaced')});

test('GBUX1 accepts model Block Instances, never definition members, and persists exact edited metadata',async()=>{const b=await browser();b.run('window.__member=recordGateway.createLine({x:0,y:0},{x:1,y:0});window.__definition=blockDefinitionGateway.create({name:"Part",records:[window.__member]}).definition;window.__instance=recordGateway.createBlockInstance({definitionId:window.__definition.id,insertionPoint:{x:5,y:5}});window.__line=recordGateway.createLine({x:10,y:0},{x:12,y:0});recordGateway.createAll([window.__instance,window.__line]);window.__group=groupGateway.createGroup([window.__instance.id,window.__line.id]).group;groupGateway.rename(window.__group.id,"Assembly");window.__serialized=window.CaderactPersistence.serializeDocument(modelReader.snapshot());window.__loaded=window.CaderactPersistence.loadStore(window.__serialized);window.__invalid=groupGateway.addMembers(window.__group.id,[window.__member.id])');assert.equal(b.read('window.__invalid.status'),'missing-member');assert.deepEqual(b.read('window.__loaded.reader.groups()'),b.read('modelReader.groups()'));assert.equal(b.read('window.__loaded.reader.groupForRecord(window.__instance.id).name'),'Assembly')});

test('GBUX1 popup stays fixed, flips/clamps, and dock tabs remain keyboard navigable',async()=>{const b=await browser();seed(b);b.run('window.__group=groupGateway.createGroup([window.__records[0].id,window.__records[1].id]).group');const more=b.groupsList.children[0].children[2];more.getBoundingClientRect=()=>({left:970,right:994,top:740,bottom:764});b.window.innerWidth=1000;b.window.innerHeight=768;b.window.caderactGroupActionsMenu.offsetWidth=196;b.window.caderactGroupActionsMenu.offsetHeight=144;b.emit(more,'click');assert.equal(b.window.caderactGroupActionsMenu.hidden,false);assert.equal(b.window.caderactGroupActionsMenu.dataset.placement,'above');assert.ok(parseFloat(b.window.caderactGroupActionsMenu.style.left)<=796);b.emit(b.groupsTab,'click');assert.equal(b.groupsView.hidden,false);b.key('ArrowRight',b.groupsTab);assert.equal(b.blocksView.hidden,false);b.key('ArrowRight',b.blocksTab);assert.equal(b.propertiesView.hidden,false);b.key('ArrowRight',b.propertiesTab);assert.equal(b.layersView.hidden,false)});
