'use strict';
const {test}=require('node:test');const assert=require('node:assert/strict');const {browser}=require('../helpers/browser.cjs');
function typed(b,value){b.input.value=value;b.emit(b.input,'input');b.key('Enter',b.input)}
function select(b,ids){b.run(`selection.applyRecordIds(${JSON.stringify(ids)})`)}
const plain=records=>records.map(record=>record.type==='line'?{type:'line',start:{x:record.start.x,y:record.start.y},end:{x:record.end.x,y:record.end.y}}:{type:'polyline',closed:record.closed,vertices:record.vertices.map(v=>({x:v.x,y:v.y}))}).sort((a,b)=>JSON.stringify(a).localeCompare(JSON.stringify(b)));

test('Join and J publish connected Lines atomically with exact Undo/Redo identity',async()=>{for(const command of ['Join','J']){const b=await browser();b.run(`window.__a=recordGateway.createLine({x:0,y:0},{x:5,y:0});window.__b=recordGateway.createLine({x:10,y:0},{x:5,y:0});recordGateway.createAll([window.__a,window.__b])`);const ids=b.read('[window.__a.id,window.__b.id]'),original=b.read('modelReader.records()'),before=b.read('documentController.historyInfo.entryCount');select(b,ids);b.launch(command);b.key('Enter');assert.equal(b.read('window.caderactCommandRouter.activeCommand'),null);const result=b.read('modelReader.records()');assert.equal(result.length,1);assert.deepEqual(plain(result),[{type:'line',start:{x:0,y:0},end:{x:10,y:0}}]);assert.equal(b.read('documentController.historyInfo.entryCount'),before+1);b.run('window.caderactHistory.undo()');assert.deepEqual(b.read('modelReader.records()'),original);b.run('window.caderactHistory.redo()');assert.deepEqual(b.read('modelReader.records()'),result)}});
test('Join creates a native Polyline for compatible Polyline/Line chains',async()=>{const b=await browser();b.run(`window.__p=recordGateway.createPolyline([{x:0,y:0},{x:3,y:2},{x:5,y:0}],false);window.__l=recordGateway.createLine({x:5,y:0},{x:10,y:0});recordGateway.createAll([window.__p,window.__l])`);select(b,b.read('[window.__p.id,window.__l.id]'));b.launch('Join');b.key('Enter');const result=b.read('modelReader.records()[0]');assert.equal(result.type,'polyline');assert.deepEqual(result.vertices.map(v=>({x:v.x,y:v.y})),[{x:0,y:0},{x:3,y:2},{x:5,y:0},{x:10,y:0}])});
test('Join failures and locked/hidden selection remain active and mutation-free',async()=>{for(const mode of ['gap','angle']){const b=await browser();b.run(`window.__a=recordGateway.createLine({x:0,y:0},{x:5,y:0});window.__b=recordGateway.createLine(${mode==='gap'?'{x:6,y:0},{x:10,y:0}':'{x:5,y:0},{x:5,y:5}'});recordGateway.createAll([window.__a,window.__b])`);select(b,b.read('[window.__a.id,window.__b.id]'));const before=b.read('({records:modelReader.records(),history:documentController.historyInfo.entryCount})');b.launch('Join');b.key('Enter');assert.equal(b.read('window.caderactCommandRouter.activeCommand'),'Join');assert.deepEqual(b.read('({records:modelReader.records(),history:documentController.historyInfo.entryCount})'),before);b.key('Escape')}const locked=await browser();locked.run(`layerGateway.create('Locked');window.__layer=modelReader.layers().find(x=>x.name==='Locked');window.__a=recordGateway.createLine({x:0,y:0},{x:5,y:0});window.__b=recordGateway.createLine({x:5,y:0},{x:10,y:0});recordGateway.createAll([window.__a,window.__b]);recordGateway.assignLayer([window.__b.id],window.__layer.id);layerGateway.setLocked(window.__layer.id,true)`);select(locked,locked.read('[window.__a.id,window.__b.id]'));const before=locked.read('modelReader.records()');locked.launch('Join');locked.key('Enter');assert.deepEqual(locked.read('modelReader.records()'),before);assert.equal(locked.read('window.caderactCommandRouter.activeCommand'),'Join')});

test('Split uses resolved point input, previews exact geometry, and commits one undoable transaction',async()=>{const b=await browser();b.resize(800,600);b.run('window.__line=recordGateway.createLine({x:-10,y:0},{x:10,y:0});recordGateway.createAll([window.__line])');const original=b.read('modelReader.records()'),before=b.read('documentController.historyInfo.entryCount');b.launch('Split');b.point(440,300);assert.equal(b.read('window.caderactCommandRouter.activeSession.phase'),'point');b.point(400,300,'pointermove');b.flush();const preview=b.read('window.caderactCommandRouter.activeSession.getMovePreview().records');assert.equal(b.read('documentController.historyInfo.entryCount'),before);b.point(400,300);const result=b.read('modelReader.records()');assert.deepEqual(plain(result),plain(preview));assert.equal(result.length,2);assert.equal(b.read('documentController.historyInfo.entryCount'),before+1);b.run('window.caderactHistory.undo()');assert.deepEqual(b.read('modelReader.records()'),original);b.run('window.caderactHistory.redo()');assert.deepEqual(b.read('modelReader.records()'),result)});
test('Split supports open Polyline and rejects endpoint/off-entity points without mutation',async()=>{const b=await browser();b.resize(800,600);b.run('window.__p=recordGateway.createPolyline([{x:-10,y:0},{x:0,y:0},{x:0,y:10}],false);recordGateway.createAll([window.__p])');b.launch('SPL');b.point(370,300);typed(b,'-5,0');const result=b.read('modelReader.records()');assert.equal(result.length,2);assert.equal(result.every(record=>record.type==='polyline'),true);for(const candidate of ['-10,0','-5,1']){const invalid=await browser();invalid.resize(800,600);invalid.run('window.__l=recordGateway.createLine({x:-10,y:0},{x:10,y:0});recordGateway.createAll([window.__l])');const before=invalid.read('({records:modelReader.records(),history:documentController.historyInfo.entryCount})');invalid.launch('Split');invalid.point(440,300);typed(invalid,candidate);assert.equal(invalid.read('window.caderactCommandRouter.activeCommand'),'Split');assert.deepEqual(invalid.read('({records:modelReader.records(),history:documentController.historyInfo.entryCount})'),before);invalid.key('Escape')}});
test('Break removes the interval between two resolved interior points atomically',async()=>{const b=await browser();b.resize(800,600);b.run('window.__l=recordGateway.createLine({x:-10,y:0},{x:10,y:0});recordGateway.createAll([window.__l])');const original=b.read('modelReader.records()');b.launch('Break');b.point(440,300);typed(b,'-3,0');assert.equal(b.read('window.caderactCommandRouter.activeSession.phase'),'second-point');typed(b,'4,0');const result=b.read('modelReader.records()');assert.deepEqual(plain(result),[{type:'line',start:{x:-10,y:0},end:{x:-3,y:0}},{type:'line',start:{x:4,y:0},end:{x:10,y:0}}]);b.run('window.caderactHistory.undo()');assert.deepEqual(b.read('modelReader.records()'),original);b.run('window.caderactHistory.redo()');assert.deepEqual(b.read('modelReader.records()'),result)});
test('Split and Break cancellation clear transient state without mutation',async()=>{for(const command of ['Split','Break']){const b=await browser();b.resize(800,600);b.run('recordGateway.createAll([recordGateway.createLine({x:-10,y:0},{x:10,y:0})])');const before=b.read('({records:modelReader.records(),history:documentController.historyInfo.entryCount})');b.launch(command);b.point(440,300);if(command==='Break')typed(b,'-2,0');b.point(410,300,'pointermove');b.flush();b.key('Escape');assert.deepEqual(b.read('({records:modelReader.records(),history:documentController.historyInfo.entryCount})'),before)}});
