'use strict';
const test=require('node:test');const assert=require('node:assert/strict');const {browser}=require('../helpers/browser.cjs');
function typed(b,value){b.input.value=value;b.emit(b.input,'input');return b.key('Enter',b.input)}

test('Linear registry aliases are conflict-free and repeatable',async()=>{const b=await browser();for(const name of ['Linear','DIMLINEAR','DLI'])assert.equal(b.read(`window.caderactCommandRegistry.resolve(${JSON.stringify(name)}).name`),'Linear');assert.equal(b.read(`window.caderactCommandRegistry.resolve('Linear').repeatable`),true)});

test('P1 P2 P3 workflow commits one horizontal native dimension',async()=>{const b=await browser();b.launch('Linear');assert.match(b.run('window.caderactCommandRouter.activeSession.prompt'),/first extension/i);typed(b,'0,0');assert.match(b.run('window.caderactCommandRouter.activeSession.prompt'),/second extension/i);typed(b,'10,4');assert.match(b.run('window.caderactCommandRouter.activeSession.prompt'),/dimension line/i);typed(b,'5,10');const record=b.read('modelReader.records()[0]');assert.equal(record.type,'dimension-linear');assert.equal(record.mode,'horizontal');assert.deepEqual([record.firstPoint.x,record.firstPoint.y,record.secondPoint.x,record.secondPoint.y,record.dimensionLinePoint.x,record.dimensionLinePoint.y],[0,0,10,4,5,10]);assert.equal(record.textOverride,null)});

test('placement switches deterministically between horizontal and vertical',async()=>{const b=await browser();assert.equal(b.run(`window.CaderactLinearDimensionDraftSession.orientation({x:0,y:0},{x:10,y:4},{x:5,y:10})`),'horizontal');assert.equal(b.run(`window.CaderactLinearDimensionDraftSession.orientation({x:0,y:0},{x:10,y:4},{x:20,y:2})`),'vertical');assert.equal(b.run(`window.CaderactLinearDimensionDraftSession.orientation({x:0,y:0},{x:10,y:4},{x:5,y:2})`),'horizontal');assert.equal(b.run(`window.CaderactLinearDimensionDraftSession.orientation({x:10,y:4},{x:0,y:0},{x:20,y:2})`),'vertical')});

test('live preview uses shared D1 geometry and matches committed presentation',async()=>{const b=await browser();b.resize(800,600);b.flush();b.launch('Linear');typed(b,'0,0');typed(b,'10,4');b.point(425,250,'pointermove');b.flush();const preview=b.renders.at(-1);assert.equal(preview.annotationOverlay.items.length,1);assert.equal(preview.triangleGroups[0].triangles.length,2);const transient=b.read('window.caderactCommandRouter.activeSession.getDimensionPreview()');b.point(425,250);const committed=b.read('modelReader.records()[0]');b.window.__a=transient;b.window.__b=committed;assert.deepEqual(b.read(`({...window.CaderactDimensionGeometry.derive(window.__a,modelReader.dimensionStyle(),modelReader.units()),grips:undefined})`),b.read(`({...window.CaderactDimensionGeometry.derive(window.__b,modelReader.dimensionStyle(),modelReader.units()),grips:undefined})`))});

test('coincident extension points reject and preserve second-point phase',async()=>{const b=await browser();b.launch('Linear');typed(b,'2,2');typed(b,'2,2');assert.equal(b.read('window.caderactCommandRouter.activeSession.phase'),'second');assert.equal(b.read('modelReader.records().length'),0);assert.equal(b.read('documentController.historyInfo.entryCount'),0);typed(b,'8,2');typed(b,'4,6');assert.equal(b.read('modelReader.records().length'),1)});

test('typed relative points work and pointer motion remains history-free',async()=>{const b=await browser();b.resize(800,600);b.flush();b.launch('DLI');typed(b,'1,2');typed(b,'@5,3');b.point(450,220,'pointermove');b.flush();assert.equal(b.read('documentController.historyInfo.entryCount'),0);typed(b,'@2,4');const record=b.read('modelReader.records()[0]');assert.deepEqual([record.secondPoint.x,record.secondPoint.y,record.dimensionLinePoint.x,record.dimensionLinePoint.y],[6,5,8,9])});

test('commit is one history step and persistence restores exact identities',async()=>{const b=await browser();b.launch('Linear');typed(b,'10,0');typed(b,'0,6');typed(b,'-4,3');const exact=b.read('modelReader.records()[0]');assert.equal(exact.mode,'vertical');assert.equal(b.read('documentController.historyInfo.entryCount'),1);b.run('documentController.undo()');assert.equal(b.read('modelReader.records().length'),0);b.run('documentController.redo()');assert.deepEqual(b.read('modelReader.records()[0]'),exact);const file=b.run('window.CaderactPersistence.serializeDocument(modelReader.snapshot())');assert.equal(JSON.parse(file).fileVersion,3);b.window.__file=file;b.run('window.__loaded=window.CaderactPersistence.loadStore(window.__file)');assert.deepEqual(b.read('window.__loaded.reader.records()[0]'),exact)});

test('Escape cancels every phase and repeat starts with fresh state',async()=>{for(const points of [[],['0,0'],['0,0','5,0']]){const b=await browser();b.launch('Linear');for(const point of points)typed(b,point);b.key('Escape');assert.equal(b.read('modelReader.records().length'),0);assert.equal(b.read('documentController.historyInfo.entryCount'),0)}const b=await browser();b.launch('Linear');typed(b,'0,0');typed(b,'5,0');typed(b,'2,4');b.run('window.caderactCommandRouter.repeatLastCommand()');assert.equal(b.read('window.caderactCommandRouter.activeSession.phase'),'first')});

test('Grid and ordinary object snaps feed the existing authoritative point path',async()=>{const b=await browser();b.resize(800,600);b.flush();b.run(`recordGateway.createAll([recordGateway.createLine({x:0,y:0},{x:10,y:0})]);window.caderactViewport.setGridSnapEnabled(false)`);b.launch('Linear');b.point(400,300,'pointermove');b.point(400,300);assert.deepEqual(b.read('window.caderactCommandRouter.activeSession.draft.acceptedPoints()[0]'),{x:0,y:0});b.point(450,300,'pointermove');b.point(450,300);assert.deepEqual(b.read('window.caderactCommandRouter.activeSession.draft.acceptedPoints()[1]'),{x:10,y:0})});

test('commit uses the authoritative current usable layer and ByLayer properties',async()=>{const b=await browser();b.run(`layerGateway.create('Dimensions',{makeCurrent:true});window.__layer=modelReader.snapshot().currentLayerId`);b.launch('Linear');typed(b,'0,0');typed(b,'10,0');typed(b,'5,5');const record=b.read('modelReader.records()[0]');assert.equal(record.layerId,b.run('window.__layer'));assert.deepEqual({color:record.color,linetype:record.linetype,lineweight:record.lineweight},{color:null,linetype:null,lineweight:null})});
