const test=require('node:test');const assert=require('node:assert/strict');const{browser}=require('../helpers/browser.cjs');
const typed=(b,v)=>{b.input.value=v;b.emit(b.input,'input');b.key('Enter',b.input)};
const documentState=b=>b.read('({records:modelReader.records(),revision:documentController.currentRevision,stateId:documentController.currentStateId,dirty:documentController.isDirty,history:documentController.historyInfo})');

test('ME1 pure point measurement uses normalized CAD angles and safe zero semantics',async()=>{const b=await browser();const measure=(a,z)=>b.read(`window.CaderactMeasurement.pointToPoint(${JSON.stringify(a)},${JSON.stringify(z)})`);assert.deepEqual(measure({x:0,y:0},{x:3,y:4}),{start:{x:0,y:0},end:{x:3,y:4},deltaX:3,deltaY:4,distance:5,angleRadians:Math.atan2(4,3),angleDegrees:Math.atan2(4,3)*180/Math.PI});for(const [point,angle] of [[{x:1,y:0},0],[{x:0,y:1},90],[{x:-1,y:0},180],[{x:0,y:-1},270],[{x:-1,y:-1},225]])assert.equal(measure({x:0,y:0},point).angleDegrees,angle);assert.deepEqual(measure({x:2,y:2},{x:2,y:2}),{start:{x:2,y:2},end:{x:2,y:2},deltaX:0,deltaY:0,distance:0,angleRadians:null,angleDegrees:null});assert.equal(measure({x:1e-100,y:0},{x:1e100,y:1e100}).distance,Math.hypot(1e100-1e-100,1e100))});
test('Distance DI and DIST share a two-point read-only workflow and formatted result',async()=>{for(const alias of ['Distance','DI','DIST']){const b=await browser(),before=documentState(b);b.launch(alias);assert.equal(b.read('window.caderactCommandRouter.activeCommand'),'Distance');typed(b,'0,0');assert.equal(b.read('window.caderactCommandRouter.activeSession.phase'),'second');typed(b,'3,4');const result=b.read('window.caderactCommandRouter.lastResult');assert.equal(result.measurement.distance,5);assert.equal(result.measurement.deltaX,3);assert.equal(result.measurement.deltaY,4);assert.ok(result.formattedMeasurement.summary.includes('Distance = 5.000 mm'));assert.deepEqual(documentState(b),before)}});
test('Distance pointer acquisition reuses Endpoint and produces transient scene/HUD feedback',async()=>{const b=await browser();b.run(`recordGateway.createAll([recordGateway.createLine({x:0,y:0},{x:3,y:4})])`);const before=documentState(b);b.launch('Distance');b.point(400,300);b.point(413,282,'pointermove');b.flush();assert.equal(b.read('activeSnapResult.kind'),'endpoint');assert.deepEqual(b.read('window.caderactCommandRouter.activeSession.candidatePoint'),{x:3,y:4});assert.deepEqual(b.read('window.caderactViewport.getDynamicInputState().fields').map(x=>x.value),['5','53.13°']);const overlay=b.renders.at(-1).measurementOverlay;assert.equal(overlay.distance,5);assert.ok(overlay.segments.length);b.point(413,282);assert.equal(b.read('window.caderactCommandRouter.lastResult.measurement.distance'),5);b.flush();assert.equal(b.renders.at(-1).measurementOverlay,null);assert.deepEqual(documentState(b),before)});
test('Distance measures the final Grid and Ortho candidates rather than the raw pointer',async()=>{const grid=await browser();grid.emit(grid.gridSnapButton,'click');grid.launch('Distance');grid.point(407,293);grid.point(463,252,'pointermove');assert.deepEqual(grid.read('window.caderactCommandRouter.activeSession.candidatePoint'),{x:10,y:10});grid.point(463,252);assert.deepEqual(grid.read('window.caderactCommandRouter.lastResult.measurement.end'),{x:10,y:10});const ortho=await browser();ortho.emit(ortho.orthoButton,'click');ortho.launch('Distance');typed(ortho,'0,0');ortho.point(450,270,'pointermove');assert.deepEqual(ortho.read('window.caderactCommandRouter.activeSession.candidatePoint'),{x:10,y:0});assert.equal(ortho.read('window.caderactViewport.getDynamicInputState().fields[1].value'),'0.00°')});
test('zero Distance returns an em dash angle and completion is retained in command history',async()=>{const b=await browser();b.launch('Distance');typed(b,'2,2');typed(b,'2,2');const result=b.read('window.caderactCommandRouter.lastResult');assert.equal(result.measurement.angleDegrees,null);assert.equal(result.formattedMeasurement.angle,'—');assert.ok(b.commandHistory.children.at(-1).textContent.includes('Angle = —'))});
test('Distance Escape lifecycle and repeat clear transient state without document mutation',async()=>{const b=await browser(),before=documentState(b);b.launch('Distance');b.key('Escape');assert.equal(b.read('window.caderactCommandRouter.activeCommand'),null);b.launch('Distance');typed(b,'0,0');b.point(450,250,'pointermove');b.flush();assert.ok(b.renders.at(-1).measurementOverlay);b.key('Escape');b.flush();assert.equal(b.renders.at(-1).measurementOverlay,null);b.run('window.caderactCommandRouter.repeatLastCommand()');assert.equal(b.read('window.caderactCommandRouter.activeCommand'),'Distance');assert.deepEqual(documentState(b),before)});
