'use strict';
const {test}=require('node:test');const assert=require('node:assert/strict');const {browser,settle}=require('../helpers/browser.cjs');
function typed(b,value){b.input.value=value;b.emit(b.input,'input');return b.key('Enter',b.input)}
function state(b){return b.read('({document:modelReader.snapshot(),revision:documentController.currentRevision,stateId:documentController.currentStateId,history:documentController.historyInfo.entryCount,dirty:documentController.isDirty})')}
const plain=value=>JSON.parse(JSON.stringify(value));
function seed(b){return b.run(`(()=>{const records=[recordGateway.createLine({x:0,y:0},{x:10,y:0}),recordGateway.createCircle({x:20,y:5},4),recordGateway.createArc({center:{x:30,y:0},start:{x:34,y:0},end:{x:30,y:4},radius:4,sweep:Math.PI/2}),recordGateway.createEllipse({center:{x:40,y:0},majorAxis:{x:6,y:2},minorRadius:3}),recordGateway.createPolyline([{x:50,y:0},{x:55,y:5},{x:60,y:0}],true)];recordGateway.createAll(records);return records})()`)}

test('pure Move translation supports every native record while preserving semantic identity and vectors',async()=>{
  const b=await browser(),records=plain(seed(b));b.run('window.__translated=modelReader.records().map(record=>window.CaderactGeometryTransform.translateRecord(record,3,-7))');const moved=plain(b.read('window.__translated'));
  for(const record of records){const translated=moved.find(candidate=>candidate.id===record.id);assert.equal(translated.layerId,record.layerId);assert.equal(translated.type,record.type)}
  const byType=type=>moved.find(record=>record.type===type),original=type=>records.find(record=>record.type===type)
  assert.deepEqual(byType('line').start,{...original('line').start,x:3,y:-7});assert.deepEqual(byType('line').end,{...original('line').end,x:13,y:-7});assert.equal(byType('circle').radius,4);assert.deepEqual(byType('circle').center,{x:23,y:-2});assert.equal(byType('arc').radius,4);assert.equal(byType('arc').sweep,Math.PI/2);assert.deepEqual(byType('arc').start,{...original('arc').start,x:37,y:-7});assert.deepEqual(byType('ellipse').majorAxis,original('ellipse').majorAxis);assert.equal(byType('ellipse').minorRadius,3);assert.deepEqual(byType('polyline').vertices.map(v=>v.featureId),original('polyline').vertices.map(v=>v.featureId));assert.equal(byType('polyline').closed,true)
});

test('Move and M preselection translate all native records atomically and preserve selection through Undo/Redo',async()=>{
  for(const command of ['Move','M']){const b=await browser(),records=plain(seed(b)),ids=records.map(r=>r.id);b.run(`window.caderactSelection.applyRecordIds(${JSON.stringify(ids)})`);const before=state(b);b.launch(command);assert.equal(b.read('window.caderactCommandRouter.activeSession.phase'),'base');assert.equal(b.read('window.caderactFeedback.activePrompt'),'Move: Specify base point');typed(b,'0,0');typed(b,'@5,-2');const after=plain(b.read('modelReader.records()'));assert.equal(b.read('documentController.currentRevision'),before.revision+1);assert.equal(b.read('documentController.historyInfo.entryCount'),before.history+1);assert.deepEqual(plain(b.read('window.caderactSelection.selectedIds()')),ids.slice().sort());assert.deepEqual(after.map(r=>r.id),records.map(r=>r.id).sort());b.run('window.caderactHistory.undo()');assert.deepEqual(plain(b.read('modelReader.records()')),records.slice().sort((a,c)=>a.id.localeCompare(c.id)));b.run('window.caderactHistory.redo()');assert.deepEqual(plain(b.read('modelReader.records()')),after)}
});

test('Move postselection reuses click and Window selection before Enter confirms base-point phase',async()=>{
  const click=await browser();const record=plain(click.run('recordGateway.createLine({x:-10,y:0},{x:10,y:0})'));click.run(`recordGateway.createAll(${JSON.stringify([record])})`);click.launch('Move');assert.equal(click.read('window.caderactCommandRouter.activeSession.phase'),'selection');click.point(400,300);assert.deepEqual(plain(click.read('window.caderactSelection.selectedIds()')),[record.id]);click.key('Enter');assert.equal(click.read('window.caderactCommandRouter.activeSession.phase'),'base');typed(click,'0,0');typed(click,'5,0');assert.equal(click.read('modelReader.lines()[0].start.x'),-5)
  const box=await browser();const records=box.run(`(()=>{const r=[recordGateway.createLine({x:-10,y:0},{x:10,y:0}),recordGateway.createLine({x:50,y:50},{x:60,y:50})];recordGateway.createAll(r);return r})()`);box.launch('Move');box.point(340,270);box.point(460,330,'pointermove');box.point(460,330,'pointerup');assert.deepEqual(box.read('window.caderactSelection.selectedIds()'),[records[0].id]);assert.equal(box.read('window.caderactCommandRouter.activeSession.phase'),'selection');box.key('Enter');assert.equal(box.read('window.caderactCommandRouter.activeSession.phase'),'base')
});

test('Move postselection reuses Crossing selection and quick Space confirms it',async()=>{
  const b=await browser();const record=plain(b.run('recordGateway.createLine({x:-20,y:0},{x:20,y:0})'));b.run(`recordGateway.createAll(${JSON.stringify([record])})`);b.launch('Move');b.point(450,280);b.point(350,320,'pointermove');b.point(350,320,'pointerup');assert.deepEqual(plain(b.read('window.caderactSelection.selectedIds()')),[record.id]);assert.equal(b.read('window.caderactCommandRouter.activeSession.phase'),'selection');b.emit(b.canvas,'pointerenter');b.key(' ',b.input,{code:'Space'});b.emit(b.window,'keyup',{key:' ',code:'Space'});assert.equal(b.read('window.caderactCommandRouter.activeSession.phase'),'base');assert.equal(b.read('window.caderactFeedback.activePrompt'),'Move: Specify base point')
});

test('Move live preview shows source ghost and applies Shift Ortho without mutation',async()=>{
  const b=await browser();const selected=plain(b.run('recordGateway.createLine({x:0,y:0},{x:10,y:0})')),target=plain(b.run('recordGateway.createLine({x:20,y:20},{x:30,y:20})'));b.run(`recordGateway.createAll(${JSON.stringify([selected,target])})`);b.run(`window.caderactSelection.selectOnly(${JSON.stringify(selected.id)})`);b.launch('Move');typed(b,'0,0');const before=state(b);b.point(499,201,'pointermove');b.flush();assert.equal(b.read('activeSnapResult.kind'),'endpoint');assert.deepEqual(b.read('window.caderactCommandRouter.activeSession.candidatePoint'),{x:20,y:20});assert.deepEqual(state(b),before);b.point(497,203,'pointermove',{shiftKey:true});b.flush();const shifted=b.renders.at(-1);assert.deepEqual(plain(shifted.moveOverlay.basePoint),{x:400,y:300});assert.deepEqual(plain(shifted.moveOverlay.candidatePoint),{x:497,y:300});assert.deepEqual(Array.from(shifted.nextSegmentPreviewOverlay.segments),[497,300,547,300]);assert.deepEqual(state(b),before);b.key('Escape');b.flush();assert.deepEqual(state(b),before);assert.equal(b.renders.at(-1).moveOverlay,null)
});

test('Move source ghost represents every selected native object in renderer-neutral groups',async()=>{
  const b=await browser(),records=plain(seed(b)),ids=records.map(record=>record.id);b.run(`window.caderactSelection.applyRecordIds(${JSON.stringify(ids)})`);b.launch('Move');typed(b,'0,0');b.point(425,275,'pointermove',{shiftKey:true});b.flush();const overlay=b.renders.at(-1).moveOverlay;assert.equal(overlay.recordIds.length,5);assert.equal(overlay.source.segments.length,16);assert.equal(overlay.source.circles.length,1);assert.equal(overlay.source.arcs.length,1);assert.equal(overlay.source.ellipses.length,1);assert.equal(b.renders.at(-1).circleGroups[17].circles.length,1);assert.equal(b.renders.at(-1).arcGroups[17].arcs.length,1);assert.equal(b.renders.at(-1).ellipseGroups[17].ellipses.length,1)
});

test('Move zero displacement is history-free and transaction failure preserves retryable preview',async()=>{
  const zero=await browser();const zr=plain(zero.run('recordGateway.createLine({x:0,y:0},{x:10,y:0})'));zero.run(`recordGateway.createAll(${JSON.stringify([zr])})`);zero.run(`window.caderactSelection.selectOnly(${JSON.stringify(zr.id)})`);const before=state(zero);zero.launch('Move');typed(zero,'0,0');typed(zero,'0,0');zero.flush();assert.deepEqual(state(zero),before);assert.equal(zero.read('window.caderactCommandRouter.activeCommand'),null);assert.equal(zero.renders.at(-1).moveOverlay,null)
  const fail=await browser();const fr=plain(fail.run('recordGateway.createLine({x:0,y:0},{x:10,y:0})'));fail.run(`recordGateway.createAll(${JSON.stringify([fr])})`);fail.run(`window.caderactSelection.selectOnly(${JSON.stringify(fr.id)})`);fail.launch('Move');typed(fail,'0,0');fail.run('window.__blocking=documentController.beginTransaction()');typed(fail,'5,5');fail.flush();assert.equal(fail.read('window.caderactCommandRouter.activeCommand'),'Move');assert.deepEqual(plain(fail.read('modelReader.lines()[0]')),fr);assert.deepEqual(fail.read('window.caderactCommandRouter.activeSession.candidatePoint'),{x:5,y:5});assert.notEqual(fail.renders.at(-1).moveOverlay,null);fail.run('window.__blocking.rollback()');typed(fail,'5,5');fail.flush();assert.equal(fail.read('window.caderactCommandRouter.activeCommand'),null);assert.equal(fail.renders.at(-1).moveOverlay,null);assert.deepEqual(plain(fail.read('modelReader.lines()[0].start')),{...fr.start,x:5,y:5})
});

test('Move postselection keeps empty selection active and Escape preserves ordinary selection/document',async()=>{
  const b=await browser(),before=state(b);b.launch('Move');b.key('Enter');assert.equal(b.read('window.caderactCommandRouter.activeSession.phase'),'selection');assert.deepEqual(state(b),before);b.key('Escape');assert.equal(b.read('window.caderactCommandRouter.activeCommand'),null);assert.deepEqual(state(b),before)
});
