'use strict';
const test=require('node:test');const assert=require('node:assert/strict');const {browser}=require('../helpers/browser.cjs');
function typed(b,value){b.input.value=value;b.emit(b.input,'input');return b.key('Enter',b.input)}
function radial(b){return b.read("modelReader.records().find(record=>record.type==='dimension-radial')")}
function preselect(b,factory){b.run(`window.__source=${factory};recordGateway.createAll([window.__source]);window.caderactSelection.selectOnly(window.__source.id)`)}
function near(a,c,t=1e-9){assert.ok(Math.abs(a-c)<=t,`${a} != ${c}`)}

test('DimRadius and DimDiameter canonical names and short aliases are conflict-free',async()=>{const b=await browser();for(const [expected,names] of [['DimRadius',['DimRadius','DIMRADIUS','DRA']],['DimDiameter',['DimDiameter','DIMDIAMETER','DDI']]])for(const name of names)assert.equal(b.read(`window.caderactCommandRegistry.resolve(${JSON.stringify(name)}).name`),expected);assert.equal(b.read("window.caderactCommandRegistry.resolve('DRA').repeatable"),true)});

test('single Circle preselection enters placement and commits Radius or Diameter',async()=>{for(const [command,mode,value] of [['DimRadius','radius',5],['DimDiameter','diameter',10]]){const b=await browser();preselect(b,'recordGateway.createCircle({x:0,y:0},5)');b.launch(command);assert.equal(b.read('window.caderactCommandRouter.activeSession.phase'),'placement');assert.match(b.run('window.caderactCommandRouter.activeSession.prompt'),/dimension location/i);typed(b,'10,8');const record=radial(b);assert.equal(record.mode,mode);assert.deepEqual([record.centerPoint.x,record.centerPoint.y,record.dimensionPoint.x,record.dimensionPoint.y,record.leaderPoint.x,record.leaderPoint.y],[0,0,5,0,10,8]);assert.equal(b.run("window.CaderactDimensionGeometry.measure(modelReader.records().find(record=>record.type==='dimension-radial')).value"),value)}});

test('explicit Circle pick projects pick position exactly and leaves selection unchanged',async()=>{const b=await browser();b.resize(800,600);b.flush();b.run('window.__source=recordGateway.createCircle({x:0,y:0},5);recordGateway.createAll([window.__source])');b.launch('DRA');assert.equal(b.read('window.caderactCommandRouter.activeSession.phase'),'select');b.point(425,300);assert.equal(b.read('window.caderactCommandRouter.activeSession.phase'),'placement');assert.deepEqual(b.read('window.caderactCommandRouter.activeSession.sourceSnapshot.dimensionPoint'),{x:5,y:0});assert.deepEqual(b.read('window.caderactSelection.selectedIds()'),[]);typed(b,'10,5');assert.equal(radial(b).mode,'radius')});

test('Arc picks clamp to the finite stored sweep and reversed sweeps remain valid',async()=>{for(const sweep of [Math.PI/2,-Math.PI/2]){const b=await browser();b.resize(800,600);b.flush();b.run(`window.__source=recordGateway.createArc({center:{x:0,y:0},radius:5,start:{x:5,y:0},end:{x:0,y:${sweep>0?5:-5}},sweep:${sweep}});recordGateway.createAll([window.__source])`);b.launch('DimRadius');b.point(424,sweep>0?292:308);const point=b.read('window.caderactCommandRouter.activeSession.sourceSnapshot.dimensionPoint');b.window.__p=point;assert.equal(b.run('window.CaderactArcGeometry.angleOnSweep(Math.atan2(window.__p.y,window.__p.x),0,window.__source.sweep)'),true);typed(b,'8,0');near(Math.hypot(radial(b).dimensionPoint.x,radial(b).dimensionPoint.y),5)}});

test('Arc preselection fallback uses stored start and Arc Diameter uses implied full circle',async()=>{for(const [command,mode,arrows] of [['DimRadius','radius',1],['DimDiameter','diameter',2]]){const b=await browser();preselect(b,'recordGateway.createArc({center:{x:0,y:0},radius:4,start:{x:0,y:4},end:{x:-4,y:0},sweep:Math.PI/2})');b.launch(command);assert.deepEqual(b.read('window.caderactCommandRouter.activeSession.sourceSnapshot.dimensionPoint'),{x:0,y:4});typed(b,'6,6');const record=radial(b),presentation=b.read("window.CaderactDimensionGeometry.derive(modelReader.records().find(record=>record.type==='dimension-radial'),modelReader.dimensionStyle(),modelReader.units())");assert.equal(record.mode,mode);assert.equal(presentation.triangles.length,arrows);if(mode==='diameter')assert.deepEqual(presentation.lines[0],[{x:0,y:-4},{x:0,y:4}])}});

test('multiple or unsupported preselection falls back to retryable explicit picking',async()=>{const multiple=await browser();multiple.run('window.__records=[recordGateway.createCircle({x:0,y:0},5),recordGateway.createCircle({x:20,y:0},3)];recordGateway.createAll(window.__records);window.caderactSelection.applyRecordIds(window.__records.map(record=>record.id))');multiple.launch('DRA');assert.equal(multiple.read('window.caderactCommandRouter.activeSession.phase'),'select');for(const factory of ['recordGateway.createLine({x:0,y:0},{x:10,y:0})','recordGateway.createPolyline([{x:0,y:0},{x:10,y:0}],false)','recordGateway.createEllipse({center:{x:0,y:0},majorAxis:{x:5,y:0},minorRadius:2})']){const b=await browser();b.resize(800,600);b.flush();b.run(`recordGateway.createAll([${factory}])`);b.launch('DimDiameter');b.point(425,300);assert.equal(b.read('window.caderactCommandRouter.lastResult.reason'),'unsupported-object');assert.equal(b.read('window.caderactCommandRouter.activeSession.phase'),'select');assert.equal(b.read('documentController.historyInfo.entryCount'),1)}});

test('visible locked sources are accepted while hidden sources are unavailable',async()=>{const locked=await browser();locked.resize(800,600);locked.flush();locked.run("layerGateway.create('Locked');window.__layer=modelReader.layers().find(layer=>layer.name==='Locked');window.__source=recordGateway.createCircle({x:0,y:0},5);recordGateway.createAll([window.__source]);recordGateway.assignLayer([window.__source.id],window.__layer.id);layerGateway.setLocked(window.__layer.id,true)");locked.launch('DRA');locked.point(425,300);assert.equal(locked.read('window.caderactCommandRouter.activeSession.phase'),'placement');const hidden=await browser();hidden.resize(800,600);hidden.flush();hidden.run("layerGateway.create('Hidden');window.__layer=modelReader.layers().find(layer=>layer.name==='Hidden');window.__source=recordGateway.createCircle({x:0,y:0},5);recordGateway.createAll([window.__source]);recordGateway.assignLayer([window.__source.id],window.__layer.id);layerGateway.setVisibility(window.__layer.id,false)");hidden.launch('DRA');hidden.point(425,300);assert.equal(hidden.read('window.caderactCommandRouter.lastResult.kind'),'target-miss');assert.equal(hidden.read('window.caderactCommandRouter.activeSession.phase'),'select')});

test('captured snapshot survives source changes and dimension uses current layer ByLayer properties',async()=>{const b=await browser();preselect(b,'recordGateway.createCircle({x:0,y:0},5)');b.launch('DRA');b.run("recordGateway.removeAll([window.__source.id]);layerGateway.create('Dimensions',{makeCurrent:true});window.__layer=modelReader.snapshot().currentLayerId");typed(b,'9,3');const record=radial(b);assert.deepEqual([record.centerPoint.x,record.dimensionPoint.x],[0,5]);assert.equal(record.layerId,b.run('window.__layer'));assert.deepEqual({color:record.color,linetype:record.linetype,lineweight:record.lineweight},{color:null,linetype:null,lineweight:null});assert.equal(Object.hasOwn(record,'sourceRecordId'),false)});

test('pure radial geometry formats prefixes and remains finite around all placements',async()=>{for(const [mode,prefix,arrows] of [['radius','R',1],['diameter','Ø',2]])for(const leader of [{x:10,y:0},{x:-10,y:0},{x:0,y:10},{x:0,y:-10},{x:8,y:8},{x:1e-7,y:1e-7}]){const b=await browser();b.window.__r={type:'dimension-radial',mode,centerPoint:{x:0,y:0,featureId:'c'},dimensionPoint:{x:1e-6,y:0,featureId:'d'},leaderPoint:{...leader,featureId:'l'},textOverride:null};const p=b.read('window.CaderactDimensionGeometry.derive(window.__r,modelReader.dimensionStyle(),modelReader.units())');assert.equal(p.supported,true);assert.equal(p.triangles.length,arrows);assert.ok(p.text.value.startsWith(prefix));for(const line of p.lines)for(const point of line)assert.equal(Number.isFinite(point.x)&&Number.isFinite(point.y),true);assert.deepEqual(p.grips.map(grip=>grip.featureId),['c','d','l'])}});

test('preview equals committed presentation and placement uses shared resolved snapping',async()=>{const b=await browser();b.resize(800,600);b.flush();b.run('window.__source=recordGateway.createCircle({x:0,y:0},5);window.__line=recordGateway.createLine({x:10,y:10},{x:12,y:10});recordGateway.createAll([window.__source,window.__line]);window.caderactSelection.selectOnly(window.__source.id);window.caderactViewport.setGridSnapEnabled(false);window.caderactViewport.setObjectSnapTrackingEnabled(false)');b.launch('DRA');b.point(450,250,'pointermove');b.flush();const preview=b.read('window.caderactCommandRouter.activeSession.getDimensionPreview()');assert.equal(b.renders.at(-1).annotationOverlay.items.some(item=>item.preview),true);b.point(450,250);const record=radial(b);assert.deepEqual([record.leaderPoint.x,record.leaderPoint.y],[10,10]);b.window.__a=preview;b.window.__b=record;const a=b.read('window.CaderactDimensionGeometry.derive(window.__a,modelReader.dimensionStyle(),modelReader.units())'),c=b.read('window.CaderactDimensionGeometry.derive(window.__b,modelReader.dimensionStyle(),modelReader.units())');assert.deepEqual({...a,grips:undefined},{...c,grips:undefined})});

test('Radius and Diameter each publish one exact history record and persist through v2',async()=>{for(const command of ['DRA','DDI']){const b=await browser();preselect(b,'recordGateway.createCircle({x:0,y:0},5)');const before=b.read('documentController.historyInfo.entryCount');b.launch(command);typed(b,'9,4');const exact=radial(b);assert.equal(b.read('documentController.historyInfo.entryCount'),before+1);b.run('documentController.undo()');assert.equal(b.read("modelReader.records().some(record=>record.type==='dimension-radial')"),false);b.run('documentController.redo()');assert.deepEqual(radial(b),exact);b.window.__file=b.run('window.CaderactPersistence.serializeDocument(modelReader.snapshot())');b.run('window.__loaded=window.CaderactPersistence.loadStore(window.__file)');assert.deepEqual(b.read("window.__loaded.reader.records().find(record=>record.type==='dimension-radial')"),exact)}});

test('failed radial publication is atomic and preserves the captured snapshot for retry',async()=>{const b=await browser();preselect(b,'recordGateway.createCircle({x:0,y:0},5)');b.launch('DRA');const snapshot=b.read('window.caderactCommandRouter.activeSession.sourceSnapshot');b.run('window.__blocker=documentController.beginTransaction()');typed(b,'9,4');assert.equal(b.read('window.caderactCommandRouter.lastResult.reason'),'commit-failed');assert.deepEqual(b.read('window.caderactCommandRouter.activeSession.sourceSnapshot'),snapshot);assert.equal(b.read("modelReader.records().some(record=>record.type==='dimension-radial')"),false);b.run('window.__blocker.rollback()');typed(b,'9,4');assert.equal(radial(b).mode,'radius')});

test('Escape object-pick and placement phases are history-free and repeat starts clean',async()=>{const first=await browser(),before=first.read('documentController.historyInfo.entryCount');first.launch('DRA');first.key('Escape');assert.equal(first.read('documentController.historyInfo.entryCount'),before);const second=await browser();preselect(second,'recordGateway.createCircle({x:0,y:0},5)');second.launch('DRA');second.key('Escape');assert.equal(second.read("modelReader.records().some(record=>record.type==='dimension-radial')"),false);second.launch('DRA');typed(second,'8,3');second.run('window.caderactCommandRouter.repeatLastCommand()');assert.equal(second.read('window.caderactCommandRouter.activeSession.phase'),'placement')});
