'use strict';
const test=require('node:test');
const assert=require('node:assert/strict');
const {browser}=require('../helpers/browser.cjs');

function createRectangle(b,x1=0,y1=0,x2=4,y2=3){b.run(`window.__sources=[recordGateway.createLine({x:${x2},y:${y1}},{x:${x2},y:${y2}}),recordGateway.createLine({x:${x1},y:${y2}},{x:${x1},y:${y1}}),recordGateway.createLine({x:${x1},y:${y1}},{x:${x2},y:${y1}}),recordGateway.createLine({x:${x2},y:${y2}},{x:${x1},y:${y2}})];recordGateway.createAll(window.__sources)`)}

test('R3 selected unordered sources publish one Region atomically and retain sources',async()=>{const b=await browser();createRectangle(b);const before=b.read('modelReader.records()');b.run('selection.applyRecordIds(window.__sources.map(x=>x.id))');b.launch('Region');b.key('Enter');assert.equal(b.read('window.caderactCommandRouter.lastResult.status'),'command-completed');assert.equal(b.read('modelReader.records().filter(x=>x.type==="region").length'),1);assert.deepEqual(b.read('modelReader.records().filter(x=>x.type==="line")'),before);assert.equal(b.read('documentController.historyInfo.entryCount'),2);b.run('documentController.undo()');assert.deepEqual(b.read('modelReader.records()'),before);b.run('documentController.redo()');assert.equal(b.read('modelReader.records().filter(x=>x.type==="region").length'),1)});

test('R3 multiple disjoint selected faces publish together in one transaction',async()=>{const b=await browser();createRectangle(b,0,0,2,2);b.run('window.__more=[recordGateway.createLine({x:10,y:0},{x:12,y:0}),recordGateway.createLine({x:12,y:0},{x:12,y:2}),recordGateway.createLine({x:12,y:2},{x:10,y:2}),recordGateway.createLine({x:10,y:2},{x:10,y:0})];recordGateway.createAll(window.__more);selection.applyRecordIds([...window.__sources,...window.__more].map(x=>x.id))');const depth=b.read('documentController.historyInfo.entryCount');b.launch('Region');b.key('Enter');assert.equal(b.read('modelReader.records().filter(x=>x.type==="region").length'),2);assert.equal(b.read('documentController.historyInfo.entryCount'),depth+1);b.run('documentController.undo()');assert.equal(b.read('modelReader.records().filter(x=>x.type==="region").length'),0)});

test('R3 Point mode uses visible locked-compatible sources and authoritative world point',async()=>{const b=await browser();createRectangle(b);b.launch('Region');b.run('window.caderactCommandRouter.activeSession.handleOption("point")');const result=b.read('window.caderactCommandRouter.activeSession.handlePointerDown({x:2,y:1})');assert.equal(result.status,'command-completed');assert.equal(b.read('modelReader.records().filter(x=>x.type==="region").length'),1)});

test('R3 Point failure and Escape leave sources and history unchanged',async()=>{const b=await browser();createRectangle(b);const before=b.read('({records:modelReader.records(),history:documentController.historyInfo.entryCount})');b.launch('Region');b.run('window.caderactCommandRouter.activeSession.handleOption("point")');const failed=b.read('window.caderactCommandRouter.activeSession.handlePointerDown({x:20,y:20})');assert.equal(failed.reason,'no-enclosing-boundary');b.key('Escape');assert.deepEqual(b.read('({records:modelReader.records(),history:documentController.historyInfo.entryCount})'),before)});

test('R3 Point mode excludes hidden geometry and accepts visible locked geometry read-only',async()=>{const hidden=await browser();createRectangle(hidden);hidden.run("window.__default=modelReader.snapshot().defaultLayerId;layerGateway.create('Work',{makeCurrent:true});layerGateway.setVisibility(window.__default,false)");hidden.launch('Region');hidden.run('window.caderactCommandRouter.activeSession.handleOption("point")');let result=hidden.read('window.caderactCommandRouter.activeSession.handlePointerDown({x:2,y:1})');assert.equal(result.reason,'no-eligible-geometry');assert.equal(hidden.read('modelReader.records().filter(x=>x.type==="region").length'),0);const locked=await browser();createRectangle(locked);locked.run("window.__default=modelReader.snapshot().defaultLayerId;layerGateway.create('Work',{makeCurrent:true});layerGateway.setLocked(window.__default,true)");locked.launch('Region');locked.run('window.caderactCommandRouter.activeSession.handleOption("point")');result=locked.read('window.caderactCommandRouter.activeSession.handlePointerDown({x:2,y:1})');assert.equal(result.status,'command-completed');assert.equal(locked.read('modelReader.records().filter(x=>x.type==="region").length'),1)});
