'use strict';
const {test}=require('node:test');const assert=require('node:assert/strict');const {browser}=require('../helpers/browser.cjs');
function typed(b,value){b.input.value=value;b.emit(b.input,'input');return b.key('Enter',b.input)}
function state(b){return b.read('({document:modelReader.snapshot(),revision:documentController.currentRevision,stateId:documentController.currentStateId,history:documentController.historyInfo.entryCount,dirty:documentController.isDirty})')}
const plain=value=>JSON.parse(JSON.stringify(value)),near=(actual,expected)=>assert.ok(Math.abs(actual-expected)<1e-9,`${actual} != ${expected}`)
function seed(b){return plain(b.run(`(()=>{const records=[recordGateway.createLine({x:10,y:0},{x:20,y:0}),recordGateway.createCircle({x:20,y:5},4),recordGateway.createArc({center:{x:30,y:0},start:{x:34,y:0},end:{x:30,y:4},radius:4,sweep:Math.PI/2}),recordGateway.createEllipse({center:{x:40,y:0},majorAxis:{x:6,y:2},minorRadius:3}),recordGateway.createPolyline([{x:50,y:0},{x:55,y:5},{x:60,y:0}],true)];recordGateway.createAll(records);return records})()`))}

test('Rotate and RO resolve deterministically and the pure helper preserves every native identity',async()=>{for(const command of ['Rotate','RO']){const b=await browser();b.launch(command);assert.equal(b.read('window.caderactCommandRouter.activeCommand'),'Rotate')}const b=await browser(),records=seed(b);b.run('window.__rotated=modelReader.records().map(record=>window.CaderactGeometryTransform.rotateRecord(record,{x:0,y:0},Math.PI/2))');const rotated=plain(b.read('window.__rotated'));for(const source of records){const result=rotated.find(record=>record.id===source.id);assert.equal(result.layerId,source.layerId);assert.deepEqual(result.type,source.type)}const line=rotated.find(r=>r.type==='line'),sourceLine=records.find(r=>r.type==='line');near(line.start.x,0);near(line.start.y,10);assert.equal(line.start.featureId,sourceLine.start.featureId);const ellipse=rotated.find(r=>r.type==='ellipse');near(ellipse.majorAxis.x,-2);near(ellipse.majorAxis.y,6);assert.equal(ellipse.minorRadius,3);const poly=rotated.find(r=>r.type==='polyline');assert.deepEqual(poly.vertices.map(v=>v.featureId),records.find(r=>r.type==='polyline').vertices.map(v=>v.featureId));assert.equal(poly.closed,true)});

test('Rotate preselection applies one shared angle atomically and Undo/Redo preserve exact identities',async()=>{const b=await browser(),originals=seed(b),ids=originals.map(record=>record.id);b.run(`window.caderactSelection.applyRecordIds(${JSON.stringify(ids)})`);const before=state(b);b.launch('RO');assert.equal(b.read('window.caderactFeedback.activePrompt'),'Rotate: Specify center point');typed(b,'0,0');typed(b,'10,0');typed(b,'0,10');const rotated=plain(b.read('modelReader.records()'));assert.equal(b.read('documentController.currentRevision'),before.revision+1);assert.equal(b.read('documentController.historyInfo.entryCount'),before.history+1);assert.deepEqual(plain(b.read('window.caderactSelection.selectedIds()')),ids.slice().sort());for(const original of originals){const result=rotated.find(record=>record.id===original.id);assert.deepEqual(result.id,original.id);if(original.start?.featureId)assert.equal(result.start.featureId,original.start.featureId);if(original.vertices)assert.deepEqual(result.vertices.map(v=>v.featureId),original.vertices.map(v=>v.featureId))}b.run('window.caderactHistory.undo()');assert.deepEqual(plain(b.read('modelReader.records()')),originals.slice().sort((a,c)=>a.id.localeCompare(c.id)));b.run('window.caderactHistory.redo()');assert.deepEqual(plain(b.read('modelReader.records()')),rotated)});

test('Rotate preview retains its existing snap behavior when Shift is held',async()=>{const b=await browser(),selected=plain(b.run('recordGateway.createLine({x:10,y:0},{x:20,y:0})')),target=plain(b.run('recordGateway.createLine({x:0,y:10},{x:0,y:20})'));b.run(`recordGateway.createAll(${JSON.stringify([selected,target])});window.caderactSelection.selectOnly(${JSON.stringify(selected.id)})`);b.launch('Rotate');typed(b,'0,0');typed(b,'10,0');const before=state(b);b.point(401,249,'pointermove');b.flush();assert.equal(b.read('activeSnapResult.kind'),'endpoint');b.point(403,247,'pointermove',{shiftKey:true});b.flush();assert.equal(b.read('activeSnapResult.kind'),'endpoint');assert.deepEqual(state(b),before);b.key('Escape');b.flush();assert.equal(b.renders.at(-1).transformOverlay,null);assert.deepEqual(state(b),before)});

test('Rotate postselection reuses click confirmation and rejects degenerate reference/target without mutation',async()=>{const b=await browser(),record=plain(b.run('recordGateway.createLine({x:-10,y:0},{x:10,y:0})'));b.run(`recordGateway.createAll(${JSON.stringify([record])})`);b.launch('Rotate');b.point(400,300);b.key('Enter');assert.equal(b.read('window.caderactCommandRouter.activeSession.phase'),'center');const before=state(b);typed(b,'0,0');typed(b,'0,0');assert.equal(b.read('window.caderactCommandRouter.activeSession.phase'),'reference');assert.deepEqual(state(b),before);typed(b,'10,0');typed(b,'0,0');assert.equal(b.read('window.caderactCommandRouter.activeSession.phase'),'target');assert.deepEqual(state(b),before);typed(b,'10,0');assert.equal(b.read('window.caderactCommandRouter.activeCommand'),null);assert.deepEqual(state(b),before)});

test('Rotate transaction failure is atomic and preserves a coherent retry preview',async()=>{const b=await browser(),records=seed(b),ids=records.map(r=>r.id);b.run(`window.caderactSelection.applyRecordIds(${JSON.stringify(ids)})`);b.launch('RO');typed(b,'0,0');typed(b,'10,0');b.run('window.__blocking=documentController.beginTransaction()');typed(b,'0,10');b.flush();assert.equal(b.read('window.caderactCommandRouter.activeCommand'),'Rotate');assert.deepEqual(plain(b.read('modelReader.records()')),records.slice().sort((a,c)=>a.id.localeCompare(c.id)));assert.notEqual(b.renders.at(-1).transformOverlay,null);b.run('window.__blocking.rollback()');typed(b,'0,10');b.flush();assert.equal(b.read('window.caderactCommandRouter.activeCommand'),null);assert.equal(b.renders.at(-1).transformOverlay,null);assert.equal(b.read('modelReader.records().length'),5)});

test('Rotate Copy option defaults to No and creates fresh selected copies without mutating originals',async()=>{const b=await browser(),source=plain(b.run('recordGateway.createArc({center:{x:10,y:0},start:{x:14,y:0},end:{x:10,y:4},radius:4,sweep:Math.PI/2})'));b.run(`recordGateway.createAll([${JSON.stringify(source)}]);window.caderactSelection.selectOnly(${JSON.stringify(source.id)})`);const before=state(b);b.launch('Rotate');assert.equal(b.read('window.caderactCommandRouter.activeSession.options[0].value'),'No');b.run('window.caderactCommandRouter.activateOption("copy")');typed(b,'0,0');typed(b,'10,0');b.point(400,250,'pointermove');b.flush();const preview=b.renders.at(-1);assert.equal(preview.transformOverlay.copyMode,true);assert.equal(preview.transformOverlay.preserveSourceVisible,true);assert.equal(preview.transformOverlay.source.segments.length,0);assert.deepEqual(state(b),before);typed(b,'0,10');const records=plain(b.read('modelReader.records()'));assert.equal(records.length,2);const original=records.find(record=>record.id===source.id),copy=records.find(record=>record.id!==source.id);assert.deepEqual(original,source);assert.notEqual(copy.id,source.id);assert.notEqual(copy.start.featureId,source.start.featureId);assert.equal(copy.sweep,source.sweep);assert.deepEqual(plain(b.read('window.caderactSelection.selectedIds()')),[copy.id]);assert.equal(b.read('documentController.historyInfo.entryCount'),before.history+1);b.run('window.caderactHistory.undo()');assert.deepEqual(plain(b.read('modelReader.records()')),[source]);b.run('window.caderactHistory.redo()');assert.deepEqual(plain(b.read('modelReader.records()')).find(record=>record.id===copy.id),copy)});

test('Rotate Copy=Yes keeps zero angles history-free and retries failed publication without partial copies',async()=>{const b=await browser(),source=plain(b.run('recordGateway.createLine({x:0,y:0},{x:10,y:0})'));b.run(`recordGateway.createAll([${JSON.stringify(source)}]);window.caderactSelection.selectOnly(${JSON.stringify(source.id)})`);const before=state(b);b.launch('Rotate');b.run('window.caderactCommandRouter.activateOption("copy")');typed(b,'0,0');typed(b,'10,0');typed(b,'20,0');assert.deepEqual(state(b),before);b.launch('Rotate');b.run('window.caderactCommandRouter.activateOption("copy")');typed(b,'0,0');typed(b,'10,0');b.run('window.__blocking=documentController.beginTransaction()');typed(b,'0,10');assert.equal(b.read('window.caderactCommandRouter.activeCommand'),'Rotate');assert.deepEqual(plain(b.read('modelReader.records()')),[source]);b.run('window.__blocking.rollback()');typed(b,'0,10');assert.equal(b.read('modelReader.records().length'),2);assert.deepEqual(plain(b.read('modelReader.records()')).find(record=>record.id===source.id),source)});
