'use strict';
const {test}=require('node:test');const assert=require('node:assert/strict');const {browser}=require('../helpers/browser.cjs');
function typed(b,value){b.input.value=value;b.emit(b.input,'input');return b.key('Enter',b.input)}
const plain=value=>JSON.parse(JSON.stringify(value)),near=(actual,expected)=>assert.ok(Math.abs(actual-expected)<1e-9,`${actual} != ${expected}`)
function state(b){return b.read('({document:modelReader.snapshot(),revision:documentController.currentRevision,stateId:documentController.currentStateId,history:documentController.historyInfo.entryCount,dirty:documentController.isDirty})')}
function seed(b){return plain(b.run(`(()=>{const records=[recordGateway.createLine({x:10,y:0},{x:20,y:0}),recordGateway.createCircle({x:20,y:5},4),recordGateway.createArc({center:{x:30,y:0},start:{x:34,y:0},end:{x:30,y:4},radius:4,sweep:Math.PI/2}),recordGateway.createEllipse({center:{x:40,y:0},majorAxis:{x:6,y:2},minorRadius:3}),recordGateway.createPolyline([{x:50,y:0},{x:55,y:5},{x:60,y:0}],true)];recordGateway.createAll(records);return records})()`))}

test('Scale and SC resolve deterministically and pure helpers preserve native identity and semantics',async()=>{for(const command of ['Scale','SC']){const b=await browser();b.launch(command);assert.equal(b.read('window.caderactCommandRouter.activeCommand'),'Scale')}const b=await browser(),records=seed(b);b.run('window.__scaled=modelReader.records().map(record=>window.CaderactGeometryTransform.scaleRecord(record,{x:10,y:0},2))');const scaled=plain(b.read('window.__scaled'));for(const source of records){const result=scaled.find(record=>record.id===source.id);assert.equal(result.id,source.id);assert.equal(result.layerId,source.layerId);assert.equal(result.type,source.type)}const line=scaled.find(r=>r.type==='line'),sourceLine=records.find(r=>r.type==='line');assert.deepEqual(line.start,{...sourceLine.start,x:10,y:0});assert.deepEqual(line.end,{...sourceLine.end,x:30,y:0});const circle=scaled.find(r=>r.type==='circle');assert.deepEqual(circle.center,{x:30,y:10});assert.equal(circle.radius,8);const arc=scaled.find(r=>r.type==='arc'),sourceArc=records.find(r=>r.type==='arc');assert.deepEqual(arc.center,{x:50,y:0});assert.equal(arc.radius,8);assert.equal(arc.sweep,sourceArc.sweep);assert.equal(arc.start.featureId,sourceArc.start.featureId);const ellipse=scaled.find(r=>r.type==='ellipse');assert.deepEqual(ellipse.center,{x:70,y:0});assert.deepEqual(ellipse.majorAxis,{x:12,y:4});assert.equal(ellipse.minorRadius,6);const poly=scaled.find(r=>r.type==='polyline'),sourcePoly=records.find(r=>r.type==='polyline');assert.deepEqual(poly.vertices.map(v=>v.featureId),sourcePoly.vertices.map(v=>v.featureId));assert.equal(poly.closed,true);assert.throws(()=>b.run('window.CaderactGeometryTransform.scalePoint({x:1,y:1},{x:0,y:0},0)'))});

test('Scale preselection applies one shared factor atomically and Undo/Redo preserve exact identities',async()=>{const b=await browser(),originals=seed(b),ids=originals.map(r=>r.id);b.run(`window.caderactSelection.applyRecordIds(${JSON.stringify(ids)})`);const before=state(b);b.launch('SC');typed(b,'0,0');typed(b,'10,0');typed(b,'20,0');const scaled=plain(b.read('modelReader.records()'));assert.equal(b.read('documentController.currentRevision'),before.revision+1);assert.equal(b.read('documentController.historyInfo.entryCount'),before.history+1);assert.deepEqual(plain(b.read('window.caderactSelection.selectedIds()')),ids.slice().sort());for(const original of originals){const result=scaled.find(r=>r.id===original.id);assert.equal(result.id,original.id);if(original.start?.featureId)assert.equal(result.start.featureId,original.start.featureId);if(original.vertices)assert.deepEqual(result.vertices.map(v=>v.featureId),original.vertices.map(v=>v.featureId))}b.run('window.caderactHistory.undo()');assert.deepEqual(plain(b.read('modelReader.records()')),originals.slice().sort((a,c)=>a.id.localeCompare(c.id)));b.run('window.caderactHistory.redo()');assert.deepEqual(plain(b.read('modelReader.records()')),scaled)});

test('Scale postselection and relative input reuse Modify selection and D1 point routing',async()=>{const b=await browser(),record=plain(b.run('recordGateway.createLine({x:0,y:0},{x:10,y:0})'));b.run(`recordGateway.createAll([${JSON.stringify(record)}])`);b.launch('Scale');b.point(425,300);b.key('Enter');assert.equal(b.read('window.caderactCommandRouter.activeSession.phase'),'base');typed(b,'0,0');typed(b,'@10,0');typed(b,'@10,0');assert.equal(b.read('window.caderactCommandRouter.activeCommand'),null);assert.deepEqual(plain(b.read('modelReader.records()[0].end')),{...record.end,x:20,y:0})});

test('Scale preview uses fixed source ghost, shared markers/guides, snapping and Shift from one candidate',async()=>{const b=await browser(),selected=plain(b.run('recordGateway.createLine({x:10,y:0},{x:20,y:0})')),target=plain(b.run('recordGateway.createLine({x:0,y:20},{x:0,y:30})'));b.run(`recordGateway.createAll(${JSON.stringify([selected,target])});window.caderactSelection.selectOnly(${JSON.stringify(selected.id)})`);b.launch('Scale');typed(b,'0,0');b.flush();let overlay=b.renders.at(-1).transformOverlay;assert.deepEqual(plain(overlay.markers.center.point),{x:400,y:300});assert.equal(overlay.source.segments.length,0);typed(b,'10,0');b.flush();const before=state(b);b.point(401,201,'pointermove');b.flush();assert.equal(b.read('activeSnapResult.kind'),'endpoint');let scene=b.renders.at(-1);overlay=scene.transformOverlay;assert.equal(overlay.mode,'scale');assert.deepEqual(plain(overlay.markers.center.point),{x:400,y:300});assert.deepEqual(plain(overlay.markers.reference.point),{x:450,y:300});assert.deepEqual(plain(overlay.markers.target.point),{x:400,y:200});assert.deepEqual(Array.from(overlay.guideSegments),[400,300,450,300,400,300,400,200]);assert.deepEqual(Array.from(overlay.source.segments),[450,300,500,300]);assert.deepEqual(Array.from(scene.nextSegmentPreviewOverlay.segments),[500,300,600,300]);assert.deepEqual(state(b),before);b.point(503,297,'pointermove',{shiftKey:true});b.flush();assert.equal(b.read('activeSnapResult.snapped'),false);scene=b.renders.at(-1);overlay=scene.transformOverlay;assert.deepEqual(plain(overlay.markers.target.point),{x:503,y:297});near(overlay.factor,Math.hypot(103,-3)/50);assert.deepEqual(state(b),before);b.key('Escape');b.flush();assert.equal(b.renders.at(-1).transformOverlay,null);assert.deepEqual(state(b),before)});

test('Scale rejects zero reference/zero factor and unit factor is history-free',async()=>{const b=await browser(),record=plain(b.run('recordGateway.createLine({x:0,y:0},{x:10,y:0})'));b.run(`recordGateway.createAll([${JSON.stringify(record)}]);window.caderactSelection.selectOnly(${JSON.stringify(record.id)})`);const before=state(b);b.launch('Scale');typed(b,'0,0');typed(b,'0,0');assert.equal(b.read('window.caderactCommandRouter.activeSession.phase'),'reference');assert.deepEqual(state(b),before);typed(b,'10,0');typed(b,'0,0');assert.equal(b.read('window.caderactCommandRouter.activeSession.phase'),'target');assert.deepEqual(state(b),before);typed(b,'10,0');assert.equal(b.read('window.caderactCommandRouter.activeCommand'),null);assert.deepEqual(state(b),before)});

test('Scale rejects finite factors that produce non-finite geometry without publication',async()=>{const b=await browser(),record=plain(b.run('recordGateway.createLine({x:1e308,y:0},{x:1e308,y:1})'));b.run(`recordGateway.createAll([${JSON.stringify(record)}]);window.caderactSelection.selectOnly(${JSON.stringify(record.id)})`);const before=state(b);b.launch('Scale');typed(b,'0,0');typed(b,'10,0');typed(b,'20,0');assert.equal(b.read('window.caderactCommandRouter.activeCommand'),'Scale');assert.deepEqual(state(b),before);assert.equal(b.read('window.caderactCommandRouter.activeSession.getMovePreview().sourceRecords.length'),1);assert.equal(b.read('window.caderactCommandRouter.activeSession.getMovePreview().records.length'),0)});

test('Scale transaction failure is atomic and preserves coherent retry feedback',async()=>{const b=await browser(),records=seed(b),ids=records.map(r=>r.id);b.run(`window.caderactSelection.applyRecordIds(${JSON.stringify(ids)})`);b.launch('Scale');typed(b,'0,0');typed(b,'10,0');b.run('window.__blocking=documentController.beginTransaction()');typed(b,'20,0');b.flush();assert.equal(b.read('window.caderactCommandRouter.activeCommand'),'Scale');assert.deepEqual(plain(b.read('modelReader.records()')),records.slice().sort((a,c)=>a.id.localeCompare(c.id)));assert.notEqual(b.renders.at(-1).transformOverlay,null);b.run('window.__blocking.rollback()');typed(b,'20,0');b.flush();assert.equal(b.read('window.caderactCommandRouter.activeCommand'),null);assert.equal(b.renders.at(-1).transformOverlay,null);assert.equal(b.read('modelReader.records().length'),5)});
