'use strict'
const {test}=require('node:test'),assert=require('node:assert/strict'),{browser,Element}=require('../helpers/browser.cjs')

test('UX10 editable fields isolate Enter Escape printable input and global shortcuts from an active command',async()=>{const b=await browser();b.launch('Line');const textarea=new Element('textarea');textarea.parent=b.document;textarea.owner=b.document;textarea.focus();for(const key of ['x','Enter','Escape'])b.key(key,textarea);assert.equal(b.read('window.caderactCommandRouter.activeCommand'),'Line');assert.equal(b.read('window.caderactCommandRouter.activeSession.draft.acceptedPoints().length'),0);b.key('Escape',b.canvas);assert.equal(b.read('window.caderactCommandRouter.activeCommand'),null)})

test('UX10 Preferences owns Escape and Enter before an underlying command',async()=>{const b=await browser();b.launch('Line');b.emit(b.settingsTrigger,'click');assert.equal(b.settingsPanel.hidden,false);b.key('Enter',b.settingsClose);assert.equal(b.read('window.caderactCommandRouter.activeCommand'),'Line');b.key('Escape',b.settingsClose);assert.equal(b.settingsPanel.hidden,true);assert.equal(b.read('window.caderactCommandRouter.activeCommand'),'Line');assert.equal(b.document.activeElement,b.settingsTrigger)})

test('UX10 an open File menu closes before command cancellation or selection cycling',async()=>{const b=await browser();b.resize(800,600);b.run(`window.__a=recordGateway.createLine({x:0,y:0},{x:4,y:0});window.__b=recordGateway.createLine({x:0,y:0},{x:4,y:0});recordGateway.createAll([window.__a,window.__b])`);b.point(405,300);assert.ok(b.read('window.caderactViewport.getSelectionCycleState()'));b.emit(b.fileMenuTrigger,'click');assert.equal(b.fileMenuDropdown.hidden,false);b.key('Escape',b.canvas);assert.equal(b.fileMenuDropdown.hidden,true);assert.ok(b.read('window.caderactViewport.getSelectionCycleState()'));b.key('Escape',b.canvas);assert.equal(b.read('window.caderactViewport.getSelectionCycleState()'),null)})

test('UX10 selection cycling never captures keys from an editable field',async()=>{const b=await browser();b.resize(800,600);b.run(`window.__a=recordGateway.createLine({x:0,y:0},{x:4,y:0});window.__b=recordGateway.createLine({x:0,y:0},{x:4,y:0});recordGateway.createAll([window.__a,window.__b])`);b.point(405,300);const before=b.read('window.caderactViewport.getSelectionCycleState()');const input=new Element('input');input.parent=b.document;input.owner=b.document;input.focus();b.key('Tab',input,{shiftKey:true});b.key('Enter',input);b.key('Escape',input);assert.deepEqual(b.read('window.caderactViewport.getSelectionCycleState()'),before)})

test('UX10 registered command names and aliases are normalized collision-free and case-insensitive',async()=>{const b=await browser();const audit=b.read(`(()=>{const seen=new Map(),collisions=[];for(const command of window.caderactCommandRegistry.commands())for(const token of [command.name,...command.aliases]){const key=token.replace(/[\s_-]+/g,'').toUpperCase(),prior=seen.get(key);if(prior&&prior!==command.name)collisions.push([key,prior,command.name]);else seen.set(key,command.name)}return{collisions,commands:window.caderactCommandRegistry.commands().map(command=>command.name)}})()`);assert.deepEqual(audit.collisions,[]);for(const name of ['Line','Polyline','Move','Copy','Rotate','Trim','Extend','Fillet','Chamfer','Text','Linear','Leader','MLeader','Block','Insert','BlockEdit','PreviousSelection','SelectLast','InvertSelection'])assert.ok(audit.commands.includes(name),name);assert.equal(b.read('window.caderactCommandRegistry.resolve("sElInVeRt").name'),'InvertSelection')})
