'use strict';
const test=require('node:test');
const assert=require('node:assert/strict');
const {browser}=require('../helpers/browser.cjs');

function seed(b){b.run(`layerGateway.create('Walls');layerGateway.create('Notes');window.__walls=modelReader.layers().find(layer=>layer.name==='Walls');window.__notes=modelReader.layers().find(layer=>layer.name==='Notes');layerGateway.setCurrent(window.__walls.id);window.__wall=recordGateway.createLine({x:-20,y:0},{x:20,y:0});recordGateway.createAll([window.__wall]);layerGateway.setCurrent(window.__notes.id);window.__note=recordGateway.createLine({x:-20,y:20},{x:20,y:20});recordGateway.createAll([window.__note])`)}
const state=b=>b.read('({revision:documentController.currentRevision,stateId:documentController.currentStateId,history:documentController.historyInfo,dirty:documentController.isDirty,document:modelReader.snapshot()})');
const row=(b,id)=>b.layersList.children.find(child=>child.dataset.layerId===id);
function menuAction(b,id,label){b.emit(row(b,id).children[5],'click');return b.window.caderactLayerActionsMenu.children.find(child=>child.children[1]?.textContent===label)}

test('UX9A rows expose current visibility lock color and compact professional actions',async()=>{const b=await browser();seed(b);const id=b.read('window.__walls.id'),item=row(b,id);assert.equal(item.children[0].getAttribute('aria-pressed'),'false');assert.equal(item.children[1].getAttribute('aria-pressed'),'true');assert.equal(item.children[2].getAttribute('aria-pressed'),'false');assert.equal(item.children[3].children[0].style.backgroundColor,b.read('window.__walls.color'));assert.equal(item.children[4].textContent,'Walls');assert.match(item.children[5].getAttribute('aria-label'),/Actions/);assert.match(menuAction(b,id,'Select Layer Objects').getAttribute('aria-label'),/Select Layer Objects/)});

test('UX9A layer color is atomic and ByLayer updates without overwriting explicit color',async()=>{const b=await browser();seed(b);b.run('recordGateway.setProperties([window.__note.id],{color:"#ff00ff"})');const id=b.read('window.__notes.id'),before=b.read('documentController.historyInfo.entryCount'),swatch=row(b,id).children[3];b.emit(swatch,'click');const pop=b.window.caderactColorPopover;pop.hex.value='#123456';b.emit(pop.hex,'input');b.emit(pop.apply,'click');assert.equal(b.read('modelReader.layer(window.__notes.id).color'),'#123456');assert.equal(b.read('modelReader.records().find(record=>record.id===window.__note.id).color'),'#ff00ff');assert.equal(b.read('documentController.historyInfo.entryCount'),before+1);b.run('window.caderactHistory.undo()');assert.notEqual(b.read('modelReader.layer(window.__notes.id).color'),'#123456');b.run('window.caderactHistory.redo()');assert.equal(b.read('modelReader.layer(window.__notes.id).color'),'#123456')});

test('UX9A Select Layer Objects reuses SEL1 and never mutates document history or dirty state',async()=>{const b=await browser();seed(b);const before=state(b),id=b.read('window.__walls.id');b.emit(menuAction(b,id,'Select Layer Objects'),'click');assert.deepEqual(b.read('window.caderactSelection.selectedIds()'),[b.read('window.__wall.id')]);assert.deepEqual(state(b),before)});

test('UX9A Move Selection to Layer is one exact transaction and preserves properties and identity',async()=>{const b=await browser();seed(b);b.run('recordGateway.setProperties([window.__wall.id],{color:"#abcdef",linetype:"dashed",lineweight:.35});window.caderactSelection.selectOnly(window.__wall.id)');const before=b.read('modelReader.records().find(record=>record.id===window.__wall.id)'),history=b.read('documentController.historyInfo.entryCount'),target=b.read('window.__notes.id');b.emit(menuAction(b,target,'Move Selection to Layer'),'click');const moved=b.read('modelReader.records().find(record=>record.id===window.__wall.id)');assert.deepEqual({...moved,layerId:before.layerId},before);assert.equal(moved.layerId,target);assert.equal(b.read('documentController.historyInfo.entryCount'),history+1);b.run('window.caderactHistory.undo()');assert.deepEqual(b.read('modelReader.records().find(record=>record.id===window.__wall.id)'),before);b.run('window.caderactHistory.redo()');assert.deepEqual(b.read('modelReader.records().find(record=>record.id===window.__wall.id)'),moved)});

test('UX9A isolate is ephemeral, filters rendering selection and snap, and Unisolate restores workspace visibility',async()=>{const b=await browser();seed(b);b.resize(800,600);b.flush();const before=state(b),id=b.read('window.__walls.id');b.emit(menuAction(b,id,'Isolate'),'click');assert.deepEqual(b.read('window.caderactViewport.getLayerIsolationState()'),{active:true,layerId:id});assert.equal(b.layerUnisolateButton.hidden,false);assert.deepEqual(state(b),before);b.run('window.caderactViewport.selectAllCommittedGeometry()');assert.deepEqual(b.read('window.caderactSelection.selectedIds()'),[b.read('window.__wall.id')]);b.launch('Line');b.point(400,200,'pointermove');assert.notEqual(b.read('activeSnapResult?.reference?.recordId||null'),b.read('window.__note.id'));b.key('Escape');b.emit(b.layerUnisolateButton,'click');assert.deepEqual(b.read('window.caderactViewport.getLayerIsolationState()'),{active:false,layerId:null});assert.deepEqual(state(b),before);b.run('window.caderactViewport.selectAllCommittedGeometry()');assert.deepEqual(new Set(b.read('window.caderactSelection.selectedIds()')),new Set(b.read('[window.__wall.id,window.__note.id]')));b.run('window.caderactLayers.isolate(window.__walls.id);window.caderactDocumentSession.replaceStore(window.CaderactDocument.createStore(),{reason:"ux9a-replacement"})');assert.deepEqual(b.read('window.caderactViewport.getLayerIsolationState()'),{active:false,layerId:null})});

test('UX9A grouped model records move together while Block Definition members remain untouched',async()=>{const b=await browser();b.run(`layerGateway.create('Target');window.__target=modelReader.layers().find(layer=>layer.name==='Target');window.__a=recordGateway.createLine({x:0,y:0},{x:4,y:0});window.__b=recordGateway.createCircle({x:8,y:0},2);recordGateway.createAll([window.__a,window.__b]);groupGateway.createGroup([window.__a.id,window.__b.id]);window.__member=recordGateway.createLine({x:0,y:0},{x:1,y:0});window.__definition=blockDefinitionGateway.create({name:'LayerBlock',records:[window.__member]}).definition;window.__instance=recordGateway.createBlockInstance({definitionId:window.__definition.id,insertionPoint:{x:20,y:0}});recordGateway.createAll([window.__instance]);window.caderactSelection.selectOnly(window.__a.id)`);const originalMember=b.read('modelReader.blockDefinitions()[0].records[window.__member.id]'),target=b.read('window.__target.id'),history=b.read('documentController.historyInfo.entryCount');b.emit(menuAction(b,target,'Move Selection to Layer'),'click');assert.equal(b.read('modelReader.records().filter(record=>record.id===window.__a.id||record.id===window.__b.id).every(record=>record.layerId===window.__target.id)'),true);assert.deepEqual(b.read('modelReader.blockDefinitions()[0].records[window.__member.id]'),originalMember);assert.equal(b.read('documentController.historyInfo.entryCount'),history+1)});

test('UX9A layer color and ownership persist and retain DXF layer mapping',async()=>{const b=await browser();seed(b);b.run('layerGateway.setColor(window.__walls.id,"#2468ac")');const serialized=b.run('window.CaderactPersistence.serializeDocument(modelReader.snapshot())');b.window.__file=serialized;b.run('window.__loaded=window.CaderactPersistence.loadStore(window.__file);window.__dxf=window.CaderactDxfExport.exportDocument(modelReader.snapshot());window.__imported=window.CaderactDxfImport.createStore(window.__dxf.text)');assert.equal(b.read('window.__loaded.reader.layers().find(layer=>layer.name==="Walls").color'),'#2468ac');assert.equal(b.read('window.__loaded.reader.records().find(record=>record.id===window.__wall.id).layerId'),b.read('window.__walls.id'));assert.equal(b.read('window.__imported.store.reader.layers().find(layer=>layer.name==="Walls").color'),'#2468ac')});
