'use strict';
const test=require('node:test');
const assert=require('node:assert/strict');
const {browser}=require('../helpers/browser.cjs');
const row=(b,id)=>b.layersList.children.find(item=>item.dataset.layerId===id);
function layers(b){b.run("layerGateway.create('A');layerGateway.create('B');layerGateway.create('C')");return b.read("Object.fromEntries(modelReader.layers().map(layer=>[layer.name,layer.id]))")}

test('UX9C-R document-owned layer order preserves identity/current and survives Undo Redo and save/load',async()=>{const b=await browser(),ids=layers(b);b.run(`layerGateway.setCurrent(${JSON.stringify(ids.B)})`);const before=b.read('modelReader.layers().map(layer=>layer.id)'),revision=b.read('documentController.currentRevision');assert.equal(b.run(`layerGateway.reorder(${JSON.stringify(ids.C)},1).status`),'committed');assert.deepEqual(b.read('modelReader.layers().map(layer=>layer.id)'),[before[0],ids.C,ids.A,ids.B]);assert.equal(b.read('modelReader.snapshot().currentLayerId'),ids.B);assert.equal(b.read('documentController.currentRevision'),revision+1);b.run('documentController.undo()');assert.deepEqual(b.read('modelReader.layers().map(layer=>layer.id)'),before);b.run('documentController.redo()');const ordered=b.read('modelReader.layers().map(layer=>layer.id)');const serialized=b.run('window.CaderactPersistence.serializeDocument(modelReader.snapshot())');b.window.__saved=serialized;b.run('window.__loaded=window.CaderactPersistence.loadStore(window.__saved)');assert.deepEqual(b.read('window.__loaded.reader.layers().map(layer=>layer.id)'),ordered);assert.equal(b.read('window.__loaded.reader.snapshot().currentLayerId'),ids.B)});

test('UX9C-R row drag reorders upward/downward after threshold and Escape cancels preview',async()=>{const b=await browser(),ids=layers(b);function bounds(){b.layersList.children.forEach((item,index)=>item.getBoundingClientRect=()=>({left:0,right:260,top:index*32,bottom:index*32+32,width:260,height:32}));b.layersList.getBoundingClientRect=()=>({left:0,right:260,top:0,bottom:128,width:260,height:128})}bounds();let source=row(b,ids.C).children[4];b.emit(source,'pointerdown',{clientX:100,clientY:112,pointerId:7});b.emit(source,'pointermove',{clientX:100,clientY:40,pointerId:7});b.emit(source,'pointerup',{clientX:100,clientY:40,pointerId:7});assert.deepEqual(b.read('modelReader.layers().map(layer=>layer.name)'),['Default','C','A','B']);bounds();source=row(b,ids.C).children[4];const before=b.read('modelReader.snapshot().layerOrder');b.emit(source,'pointerdown',{clientX:100,clientY:48,pointerId:8});b.emit(source,'pointermove',{clientX:100,clientY:110,pointerId:8});b.key('Escape');b.emit(source,'pointerup',{clientX:100,clientY:110,pointerId:8});assert.deepEqual(b.read('modelReader.snapshot().layerOrder'),before)});

test('UX9C-R double click renames, Escape/outside action cancel, and invalid input stays editable',async()=>{const b=await browser(),ids=layers(b),name=()=>row(b,ids.A).children[4];b.emit(name(),'dblclick');let editor=name();assert.equal(editor.tag,'input');editor.value='Renamed';b.key('Enter',editor);assert.equal(b.read(`modelReader.layer(${JSON.stringify(ids.A)}).name`),'Renamed');const history=b.read('documentController.historyInfo.entryCount');b.emit(name(),'dblclick');editor=name();editor.value='Partial';b.emit(row(b,ids.B).children[4],'click');assert.equal(b.read(`modelReader.layer(${JSON.stringify(ids.A)}).name`),'Renamed');assert.equal(b.read('documentController.historyInfo.entryCount'),history+1);b.emit(name(),'dblclick');editor=name();editor.value='';b.key('Enter',editor);assert.equal(name().tag,'input');b.key('Escape',name());assert.equal(b.read(`modelReader.layer(${JSON.stringify(ids.A)}).name`),'Renamed')});

test('UX9C-R menu is a fixed overlay, flips above, clamps, and never changes list order',async()=>{const b=await browser(),ids=layers(b),item=row(b,ids.C),anchor=item.children[5],menu=b.window.caderactLayerActionsMenu,before=b.read('modelReader.snapshot().layerOrder');anchor.getBoundingClientRect=()=>({left:940,right:980,top:730,bottom:758});menu.offsetWidth=196;menu.offsetHeight=172;b.emit(anchor,'click');assert.equal(menu.hidden,false);assert.equal(menu.dataset.placement,'above');assert.ok(parseFloat(menu.style.left)<=820);assert.ok(parseFloat(menu.style.top)>=8);assert.deepEqual(b.read('modelReader.snapshot().layerOrder'),before);assert.equal(b.layersList.children.length,4)});

test('UX9C-R HSV surface and hue stage arbitrary color until one Apply',async()=>{const b=await browser(),id=b.read('modelReader.snapshot().defaultLayerId'),swatch=row(b,id).children[3],picker=b.window.caderactColorPopover,history=b.read('documentController.historyInfo.entryCount');picker.sv.getBoundingClientRect=()=>({left:0,top:0,width:200,height:100});picker.hue.getBoundingClientRect=()=>({left:0,top:0,width:18,height:360});b.emit(swatch,'click');b.emit(picker.hue,'pointerdown',{clientX:9,clientY:120});b.emit(picker.hue,'pointerup',{clientX:9,clientY:120});b.emit(picker.sv,'pointerdown',{clientX:150,clientY:25});b.emit(picker.sv,'pointerup',{clientX:150,clientY:25});const staged=picker.getState();assert.equal(staged.open,true);assert.match(staged.value,/^#[0-9a-f]{6}$/);assert.equal(b.read('documentController.historyInfo.entryCount'),history);assert.notEqual(b.read(`modelReader.layer(${JSON.stringify(id)}).color`),staged.value);b.emit(picker.apply,'click');assert.equal(b.read(`modelReader.layer(${JSON.stringify(id)}).color`),staged.value);assert.equal(b.read('documentController.historyInfo.entryCount'),history+1)});

test('UX9C-R Hex and RGB synchronize HSV while Cancel remains mutation-free',async()=>{const b=await browser(),id=b.read('modelReader.snapshot().defaultLayerId'),picker=b.window.caderactColorPopover,swatch=row(b,id).children[3],before=b.read('documentController.historyInfo.entryCount');b.emit(swatch,'click');picker.hex.value='#00ff00';b.emit(picker.hex,'input');assert.ok(Math.abs(picker.getState().hsv[0]-120)<.01);picker.channels[0].value='0';picker.channels[1].value='0';picker.channels[2].value='255';b.emit(picker.channels[2],'input');assert.ok(Math.abs(picker.getState().hsv[0]-240)<.01);b.emit(picker.cancel,'click');assert.equal(b.read('documentController.historyInfo.entryCount'),before)});

test('UX9C-R4 shared color primary action has visible centered Apply label',async()=>{const b=await browser(),picker=b.window.caderactColorPopover;assert.equal(picker.apply.textContent,'Apply');assert.equal(picker.apply.getAttribute('aria-label'),'Apply color');const css=require('node:fs').readFileSync(require('node:path').join(__dirname,'../../src/css/editor-page.css'),'utf8');assert.match(css,/\.color-popover-actions button\{[^}]*display:inline-flex[^}]*align-items:center[^}]*justify-content:center/s);assert.match(css,/\.color-popover-actions \.color-apply\{color:var\(--text-on-accent\);background:var\(--accent\)/)});

test('UX9C-R production dock drag leaves resize authority to observer and persists only final width',async()=>{const b=await browser(),canvas=b.canvas,initialSizes=b.sizes.length,initialRenders=b.renders.length,initialStored=b.read('window.caderactUserPreferences.value.rightDockWidth');b.emit(b.rightDockResize,'pointerdown',{clientX:700,pointerId:9});b.emit(b.rightDockResize,'pointermove',{clientX:680,pointerId:9});b.emit(b.rightDockResize,'pointermove',{clientX:660,pointerId:9});b.flush();assert.equal(b.sizes.length,initialSizes);assert.equal(b.canvas,canvas);assert.equal(b.read('window.caderactUserPreferences.value.rightDockWidth'),initialStored);b.resize(760,600);assert.equal(b.sizes.length,initialSizes+1);assert.ok(b.renders.length>initialRenders);assert.equal(b.renders.at(-1).width,760);assert.equal(b.canvas,canvas);b.emit(b.rightDockResize,'pointerup',{clientX:660,pointerId:9});assert.equal(b.read('window.caderactUserPreferences.value.rightDockWidth'),328)});

test('UX9C-R row controls and compact rename styling preserve fixed layout',async()=>{const b=await browser(),ids=layers(b),before=b.read('modelReader.snapshot().layerOrder'),item=row(b,ids.A);for(const index of [0,1,2,3,5]){if(index===3){b.emit(item.children[index],'click');b.emit(b.window.caderactColorPopover.cancel,'click')}else if(index===5){b.emit(item.children[index],'click');b.key('Escape')}else b.emit(item.children[index],'click')}assert.deepEqual(b.read('modelReader.snapshot().layerOrder'),before);const css=require('node:fs').readFileSync(require('node:path').join(__dirname,'../../src/css/editor-page.css'),'utf8');assert.match(css,/grid-template-columns:20px 24px 24px 24px minmax\(0,1fr\) 24px/);assert.match(css,/\.layers-list\s*\{[^}]*overflow-x:hidden/s);assert.match(css,/\.layer-actions-menu\{position:fixed/s);assert.match(css,/\.right-dock-resize\{[^}]*cursor:col-resize/s);assert.match(css,/\.layers-panel \.right-dock-resize[^\{]*\{cursor:col-resize\}/);assert.match(css,/\.layer-actions-menu\{[^}]*background:#fff[^}]*border:1px solid var\(--border-default\)[^}]*box-shadow:var\(--shadow-popup\)/s);assert.match(css,/\.layer-actions-menu \.layer-menu-action\{[^}]*background:transparent[^}]*border:0[^}]*font:inherit/s);assert.match(css,/\.layer-name-input\s*\{[^}]*height:24px[^}]*border:1px solid var\(--accent\)[^}]*outline:none[^}]*background:transparent[^}]*box-shadow:none/s);assert.match(css,/\.layer-name-input:focus-visible\s*\{[^}]*outline:none[^}]*box-shadow:none/s)});
