'use strict';
const test=require('node:test');const assert=require('node:assert/strict');const {browser}=require('../helpers/browser.cjs');
function styledLine(b,patch={}){return b.read(`(()=>{const record=recordGateway.createLine({x:0,y:0},{x:20,y:0});recordGateway.createAll([record]);recordGateway.setProperties([record.id],${JSON.stringify(patch)});return record.id})()`)}
function groupFor(b,id,preview=false){b.flush();return b.renders.at(-1)[preview?'propertyPreviewDrawGroups':'propertyDrawGroups'].find(group=>Array.from(group.recordIds).includes(id))}

test('ViewportScene resolves ByLayer color and updates it live when the layer changes',async()=>{const b=await browser(),id=styledLine(b);assert.equal(groupFor(b,id),undefined);const layerId=b.read('modelReader.snapshot().currentLayerId');b.run(`window.__tx=documentController.beginTransaction();window.__layer=window.__tx.readIn('layers',${JSON.stringify(layerId)});window.__tx.replaceIn('layers',${JSON.stringify(layerId)},{...window.__layer,color:'#123456'});window.__tx.publish()`);assert.equal(groupFor(b,id).style.color,'#123456')});

test('explicit object style wins over layer style and resetting restores ByLayer',async()=>{const b=await browser(),id=styledLine(b,{color:'#ff0000',linetype:'dashed',lineweight:.7}),layerId=b.read('modelReader.snapshot().currentLayerId');b.run(`window.__tx=documentController.beginTransaction();window.__layer=window.__tx.readIn('layers',${JSON.stringify(layerId)});window.__tx.replaceIn('layers',${JSON.stringify(layerId)},{...window.__layer,color:'#0000ff',linetype:'dotted',lineweight:.13});window.__tx.publish()`);let group=groupFor(b,id);assert.deepEqual(JSON.parse(JSON.stringify(group.style)),{color:'#ff0000',linetype:'dashed',lineweight:.7,lineWidth:2.8});b.run(`recordGateway.setProperties([${JSON.stringify(id)}],{color:null,linetype:null,lineweight:null})`);group=groupFor(b,id);assert.deepEqual(JSON.parse(JSON.stringify(group.style)),{color:'#0000ff',linetype:'dotted',lineweight:.13,lineWidth:.75})});

test('every semantic linetype maps to one deterministic renderer-neutral dash pattern',async()=>{const expected={continuous:[],dashed:[8,4],dotted:[1,3],'dash-dot':[8,3,1,3]};for(const [linetype,pattern] of Object.entries(expected)){const b=await browser(),id=styledLine(b,{color:'#112233',linetype});const group=groupFor(b,id);assert.equal(group.style.linetype,linetype);assert.deepEqual(Array.from(group.lineGroup.dashPattern),pattern)}});

test('all supported lineweights map to bounded deterministic CSS-pixel widths',async()=>{const expected=new Map([[.13,.75],[.18,.75],[.25,1],[.35,1.4],[.5,2],[.7,2.8],[1,4]]);for(const [lineweight,width] of expected){const b=await browser(),id=styledLine(b,{color:'#112233',lineweight});const group=groupFor(b,id);assert.equal(group.style.lineWidth,width);assert.ok(Number.isFinite(group.lineGroup.lineWidth)&&group.lineGroup.lineWidth>=.75&&group.lineGroup.lineWidth<=4)}});

test('style batches cover Lines, Polylines, Circles, Arcs, and Ellipses with shared resolved data',async()=>{const b=await browser();const ids=b.read(`(()=>{const records=[recordGateway.createLine({x:0,y:0},{x:10,y:0}),recordGateway.createPolyline([{x:0,y:5},{x:10,y:5}],false),recordGateway.createCircle({x:20,y:0},4),recordGateway.createArc({center:{x:30,y:0},radius:4,start:{x:34,y:0},end:{x:30,y:4},sweep:Math.PI/2}),recordGateway.createEllipse({center:{x:40,y:0},majorAxis:{x:5,y:0},minorRadius:2})];recordGateway.createAll(records);recordGateway.setProperties(records.map(record=>record.id),{color:'#abcdef',linetype:'dash-dot',lineweight:.5});return records.map(record=>record.id)})()`);b.flush();const group=b.renders.at(-1).propertyDrawGroups.find(candidate=>candidate.style.color==='#abcdef');assert.deepEqual(Array.from(group.recordIds).sort(),ids.sort());assert.ok(group.lineGroup.segments.length>=8);assert.equal(group.circleGroup.circles.length,1);assert.equal(group.arcGroup.arcs.length,1);assert.equal(group.ellipseGroup.ellipses.length,1)});

test('selection stays as an overlay, locked records retain style, and hidden records are excluded',async()=>{const b=await browser(),id=styledLine(b,{color:'#ff0000'}),layerId=b.read('modelReader.snapshot().currentLayerId');b.run(`window.caderactSelection.selectOnly(${JSON.stringify(id)})`);b.flush();let scene=b.renders.at(-1);assert.equal(scene.propertyDrawGroups.some(group=>group.style.color==='#ff0000'),true);assert.equal(scene.selectionOverlay.segments.length,4);assert.equal(b.read(`modelReader.records()[0].color`),'#ff0000');b.run(`layerGateway.create('Other');layerGateway.setCurrent(modelReader.layers().find(layer=>layer.name==='Other').id);layerGateway.setLocked(${JSON.stringify(layerId)},true)`);assert.equal(groupFor(b,id).style.color,'#ff0000');b.run(`layerGateway.setLocked(${JSON.stringify(layerId)},false);layerGateway.setVisibility(${JSON.stringify(layerId)},false)`);b.flush();scene=b.renders.at(-1);assert.equal(scene.propertyDrawGroups.some(group=>Array.from(group.recordIds).includes(id)),false)});

test('property rendering follows edit, Undo, Redo, and persistence without stale style state',async()=>{const b=await browser(),id=styledLine(b);b.run(`recordGateway.setProperties([${JSON.stringify(id)}],{color:'#aabbcc',linetype:'dashed',lineweight:.5})`);assert.equal(groupFor(b,id).style.color,'#aabbcc');b.run('documentController.undo()');assert.equal(groupFor(b,id),undefined);b.run('documentController.redo()');assert.equal(groupFor(b,id).style.linetype,'dashed');const serialized=b.run('window.CaderactPersistence.serializeDocument(modelReader.snapshot())');b.run(`window.__loaded=window.CaderactPersistence.loadStore(${JSON.stringify(serialized)})`);assert.deepEqual(b.read('window.CaderactObjectProperties.recordProperties(window.__loaded.reader.records()[0])'),{color:'#aabbcc',linetype:'dashed',lineweight:.5})});

test('transform, Copy/Mirror-style, Offset, Trim, and Extend previews carry source appearance batches',async()=>{const b=await browser(),id=styledLine(b,{color:'#ee44aa',linetype:'dotted',lineweight:.35});b.run(`window.caderactSelection.selectOnly(${JSON.stringify(id)})`);b.launch('Move');b.input.value='0,0';b.emit(b.input,'input');b.key('Enter',b.input);b.point(450,250,'pointermove');let group=groupFor(b,id,true);assert.equal(group.style.color,'#ee44aa');assert.deepEqual(Array.from(group.lineGroup.dashPattern),[1,3]);assert.equal(group.lineGroup.lineWidth,1.4);assert.equal(b.read(`modelReader.records().find(record=>record.id===${JSON.stringify(id)}).color`),'#ee44aa')});

test('Canvas2D applies and resets resolved dash and width without leaking state',async()=>{const b=await browser({realRenderer:true}),calls=[];const context={setTransform(){},fillRect(){},beginPath(){},moveTo(){},lineTo(){},stroke(){calls.push(['stroke',this.strokeStyle,this.lineWidth])},setLineDash(value){calls.push(['dash',...value])}};const canvas={getContext:()=>context};const styled={color:'#ff0000',colorData:[1,0,0,1],lineWidth:2,dashPattern:[8,4],segments:new Float32Array([0,0,10,0])},plain={color:'#00ff00',colorData:[0,1,0,1],lineWidth:1,dashPattern:[],segments:new Float32Array([0,2,10,2])},scene={width:20,height:20,deviceScale:1,backgroundColor:'#000',drawGroups:[{lineGroup:styled},{lineGroup:plain}]};new b.window.CaderactCanvas2DRenderer(canvas).render(scene);assert.deepEqual(calls,[['dash',8,4],['stroke','#ff0000',2],['dash'],['stroke','#00ff00',1],['dash']]);assert.equal(context.lineWidth,1)});

test('shared CPU stroke preparation gives WebGPU deterministic dash and width parity inputs',async()=>{const b=await browser();const source=new Float32Array([0,0,20,0]);assert.deepEqual(Array.from(b.window.CaderactStrokeStyle.dashSegments(source,[8,4])),[0,0,8,0,12,0,20,0]);assert.equal(b.window.CaderactStrokeStyle.expandSegments(source,2).length,8);assert.equal(b.window.CaderactStrokeStyle.expandSegments(source,4).length,16)});

test('WebGPU consumes the same resolved color, dash, and width as CPU-prepared line batches',async()=>{const b=await browser();b.context.GPUBufferUsage={UNIFORM:1,COPY_DST:2,VERTEX:4};b.load('src/js/rendering/Renderer.js');b.load('src/js/rendering/WebGPURenderer.js');let drawn=0,uploaded=null;const pass={setPipeline(){},setBindGroup(){},setVertexBuffer(){},draw(count){drawn=count},end(){}},device={lost:new Promise(()=>{}),createBuffer:()=>({destroy(){}}),createShaderModule:()=>({}),createRenderPipeline:()=>({getBindGroupLayout:()=>({})}),createBindGroup:()=>({}),createCommandEncoder:()=>({beginRenderPass:()=>pass,finish:()=>({})}),queue:{writeBuffer(buffer,offset,data){if(data.length>4)uploaded=Array.from(data)},submit(){}}},context={configure(){},getCurrentTexture:()=>({createView:()=>({})})},lineGroup={color:'#336699',colorData:[.2,.4,.6,1],lineWidth:2,dashPattern:[8,4],segments:new Float32Array([0,0,20,0])},scene={width:20,height:20,backgroundColorData:[0,0,0,1],drawGroups:[{lineGroup}]};new b.window.CaderactWebGPURenderer({}, {}, device, context, 'test',()=>{}).render(scene);assert.equal(drawn,8);assert.ok(uploaded);for(let index=2;index<uploaded.length;index+=6)for(const [offset,value] of [.2,.4,.6,1].entries())assert.ok(Math.abs(uploaded[index+offset]-value)<1e-6)});
