'use strict';
const { test }=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs');const vm=require('node:vm');
function tracking(){let next=0,timers=new Map();const context=vm.createContext({window:{},setTimeout:(fn)=>{const id=++next;timers.set(id,fn);return id},clearTimeout:id=>timers.delete(id)});vm.runInContext(fs.readFileSync('src/js/editor/ObjectSnapTracking.js','utf8'),context);return {t:context.window.CaderactObjectSnapTracking.create({setTimer:context.setTimeout,clearTimer:context.clearTimeout}),fire:()=>{for(const fn of timers.values())fn();timers.clear()}}}
const snap=(kind,x=1,y=2)=>({snapped:true,kind,point:{x,y},reference:{recordId:'r',featureId:'f'}});
test('eligible semantic snaps acquire after dwell while Grid and Nearest do not',()=>{const x=tracking();for(const kind of ['endpoint','vertex','midpoint','center','quadrant','intersection']){x.t.clear();x.t.observeSnap(snap(kind));x.fire();assert.equal(x.t.getState().acquired.kind,kind)}x.t.clear();x.t.observeSnap(snap('grid'));x.fire();assert.equal(x.t.getState().acquired,null);x.t.observeSnap(snap('nearest'));x.fire();assert.equal(x.t.getState().acquired,null)});
test('candidate changes and ineligible snaps cancel dwell; acquisition survives moving away',()=>{const x=tracking();x.t.observeSnap(snap('endpoint',1));x.t.observeSnap(snap('endpoint',2));x.fire();assert.equal(x.t.getState().acquired.point.x,2);x.t.observeSnap({snapped:false,point:{x:0,y:0}});x.t.clearHover();assert.equal(x.t.getState().acquired.point.x,2)});
test('projects H/V guides in CSS space with horizontal deterministic ties and clears fully',()=>{const x=tracking();x.t.observeSnap(snap('endpoint',10,20));x.fire();const map=(x,y)=>({x,y});x.t.project({x:30,y:23},map);assert.deepEqual(JSON.parse(JSON.stringify(x.t.getState().candidate)),{x:30,y:20});assert.equal(x.t.getState().guide,'horizontal');x.t.project({x:13,y:50},map);assert.deepEqual(JSON.parse(JSON.stringify(x.t.getState().candidate)),{x:10,y:50});assert.equal(x.t.getState().guide,'vertical');x.t.project({x:30,y:40},map);assert.equal(x.t.getState().guide,null);x.t.clear();const state=JSON.parse(JSON.stringify(x.t.getState()));assert.equal(state.acquired,null);assert.deepEqual(state.acquiredPoints,[]);assert.equal(state.guide,null);assert.equal(state.candidate,null)});
test('retains four distinct points, ignores near duplicates, and evicts oldest',()=>{const x=tracking();for(let index=0;index<5;index++){x.t.observeSnap(snap('endpoint',index*10,0));x.fire()}assert.deepEqual(Array.from(x.t.getState().acquiredPoints,value=>value.point.x),[10,20,30,40]);x.t.observeSnap(snap('midpoint',40+1e-11,0));x.fire();assert.equal(x.t.getState().acquiredPoints.length,4);assert.deepEqual(Array.from(x.t.getState().acquiredPoints,value=>value.acquisitionOrder),[2,3,4,5])});
test('constructs bounded H/V intersections and prefers them over a single guide',()=>{const x=tracking(),map=(x,y)=>({x,y});x.t.observeSnap(snap('endpoint',10,20));x.fire();x.t.observeSnap(snap('endpoint',40,60));x.fire();x.t.project({x:12,y:58},map);assert.deepEqual(JSON.parse(JSON.stringify(x.t.getState().candidate)),{x:10,y:60});assert.equal(x.t.getState().candidateKind,'intersection');assert.deepEqual(Array.from(x.t.getState().activeGuides,value=>value.kind),['vertical','horizontal']);x.t.project({x:39,y:21},map);assert.deepEqual(JSON.parse(JSON.stringify(x.t.getState().candidate)),{x:40,y:20})});
test('tracks configured Polar rays separately and supports a bounded Polar/HV intersection',()=>{const x=tracking(),map=(x,y)=>({x,y});x.t.observeSnap(snap('endpoint',0,0));x.fire();x.t.project({x:10,y:9},map,{polarEnabled:true,polarIncrementDegrees:45,polarToleranceDegrees:10});assert.ok(Math.abs(x.t.getState().candidate.x-x.t.getState().candidate.y)<1e-9);assert.equal(x.t.getState().activeGuides[0].kind,'polar');x.t.project({x:10,y:9},map,{polarEnabled:false});assert.equal(x.t.getState().candidate,null);x.t.observeSnap(snap('endpoint',20,10));x.fire();x.t.project({x:10.5,y:10.5},map,{polarEnabled:true,polarIncrementDegrees:45,polarToleranceDegrees:10});assert.ok(Math.abs(x.t.getState().candidate.x-10)<1e-9);assert.equal(x.t.getState().candidate.y,10);assert.equal(x.t.getState().candidateKind,'intersection');assert.deepEqual(Array.from(x.t.getState().activeGuides,value=>value.kind),['polar','horizontal'])});
